### ISSUE TITLE
Python API imageNew() of Display

### ISSUE THREAD

**Issue by ibjeong** [cyberbotics/webots#1020]
I think I found a bug in `Display.newImage()`.

In `resources/languages/python/controller.i`, `imageNew()` is defined as follows:
```
%rename (__internalImageNew) imageNew(int width, int height, const void *data, int format) const;
...
%extend webots::Display {
  %pythoncode %{
    def imageNew(self, data, format, width=None, height=None):
      if isinstance(data, list):
        return self.__internalImageNew(len(data), len(data[0]), data, format)
      elif width is None or height is None:
        raise TypeError('imageNew : width and height must be given if data is not a list')
      else:
        return self.__internalImageNew(width, height, data, format)
    def drawPolygon(self, x, y):
      self.__internalDrawPolygon(x, y, min(len(x), len(y)))
    def fillPolygon(self, x, y):
      self.__internalFillPolygon(x, y, min(len(x), len(y)))
  %}
}
```

I guess it's intended to support easy access to the image like `image[x][y][ch]` as `Camera.getImageArray()`, but `Displey.imageNew()` passes the given data directly to the `const void *data` parameter, which expects a row-major data.

It should rearrange the given data to column-major before passing the data to C's `imageNew()`.

**Comment by omichel** [comment]
Thank you for reporting that bug. I believe I fixed it in #1033. Can you check it and confirm?
