### ISSUE TITLE
Cppcheck 1.89 Update

### ISSUE THREAD

**Issue by DavidMansolino** [cyberbotics/webots#1028]
**Describe the Bug**
Cppcheck 1.89 is giving many new issues, it is now available on mac OS on Travis, but we should update on Linux too:
  - [x] Fix/remove errors: https://travis-ci.com/cyberbotics/webots/jobs/248075574#L909
  - [x] Update on Linux too.

**Comment by stefaniapedrazzi** [comment]
I fixed the errors in #1031.
But I'm not sure what should be done to update the cppcheck version on Linux for Travis.

**Comment by DavidMansolino** [comment]
I will check this part.

**Comment by stefaniapedrazzi** [comment]
Thank you
