### ISSUE TITLE
Extend TexturedBackground PROTO

### ISSUE THREAD

**Issue by DavidMansolino** [cyberbotics/webots#1061]
As a follow-up of #880 we should improve the `TexturedBackground` PROTO:
  - [ ] Add a skycolor field (set to black by default).
  - [ ] Add a bolean field to define if we want to see the background (color part) or not.
  - [ ] Eventually add a bolean field to define if we want to see the reflections or not.
  - [ ] Other?

**Comment by fabienrohrer** [comment]
Fixed in #1082
