### ISSUE TITLE
Quality Assurance R2020a

### ISSUE THREAD

**Issue by DavidMansolino** [cyberbotics/webots#1164]
Tests:
### Installation
  * [x] Windows
  * [x] macOS
  * Ubuntu 16.04
    * [ ] Snap
    * [x] Tarball
    * [x] Debian
  * Ubuntu 18.04
    * [x] Snap
    * [x] Tarball
    * [x] Debian
### Simulation reset
  * [ ] Windows
  * [ ] macOS
  * Ubuntu 16.04
    * [ ] Snap
  * Ubuntu 18.04
    * [x] Snap
### Creation of a small project
  * [x] Windows
  * [x] macOS
  * Ubuntu 18.04
    * [x] Snap
### VRML import/export
  * [x] Windows
  * [x] macOS
  * Ubuntu 18.04
    * [x] Snap
### Make a movie
  * [x] Windows
  * [x] macOS
  * Ubuntu 16.04
    * [ ] Snap
    * [x] Tarball
    * [x] Debian
  * Ubuntu 18.04
    * [x] Snap
    * [x] Tarball
    * [x] Debian
### Delete objects in the Scene Tree
  * [x] Windows
  * [x] macOS
  * Ubuntu 18.04
    * [x] Snap
### Copy a robot in the Scene Tree
  * [x] Windows
  * [x] macOS
  * Ubuntu 18.04
    * [x] Snap
### Java controllers
  * [x] Windows
  * [x] macOS
  * Ubuntu 16.04
    * [ ] Snap
    * [x] Tarball
    * [x] Debian
  * Ubuntu 18.04
    * [x] Snap
    * [x] Tarball
    * [x] Debian
### Python controllers
  * [x] Windows
  * [x] macOS
  * Ubuntu 16.04
    * [ ] Snap
    * [x] Tarball
    * [x] Debian
  * Ubuntu 18.04
    * [x] Snap
    * [x] Tarball
    * [x] Debian
### Robot window
  * [x] Windows
  * [x] macOS
  * Ubuntu 16.04
    * [ ] Snap
    * [x] Tarball
    * [x] Debian
  * Ubuntu 18.04
    * [x] Snap
    * [x] Tarball
    * [x] Debian
### Devices worlds
  * [x] Windows
  * [x] macOS
  * Ubuntu 18.04
    * [x] Snap
### Support of UTF-8 characters
  * [x] Windows
### Visual Studio wizard
  * [x] Windows
### Matlab controllers
  * [ ] Windows
  * [ ] macOS
  * Ubuntu 18.04
    * [ ] Snap
### Mouse interactions
  * [x] Windows
  * [x] macOS
  * Ubuntu 18.04
    * [x] Snap
### e-puck - remote control
  * [ ] Windows
  * [ ] macOS
  * Ubuntu 18.04
    * [ ] Snap
### Binary compilation
  * [x] Windows
  * [x] macOS
  * Ubuntu 16.04
    * [ ] Snap
    * [x] Tarball
    * [x] Debian
  * Ubuntu 18.04
    * [x] Snap
    * [x] Tarball
    * [x] Debian
### DARwIn-OP
  * [ ] Windows
  * [ ] macOS
  * Ubuntu 18.04
    * [ ] Snap
### Make HTML5 animation
  * [x] Windows
  * [x] macOS
  * Ubuntu 18.04
    * [x] Snap
### Streaming Server
  * Ubuntu 18.04
    * [x] Snap
### Extern controllers
  * [ ] Windows
  * [ ] macOS
  * Ubuntu 18.04
    * [x] Snap
### Offline documentation
  * [x] Windows
  * [x] macOS
  * Ubuntu 18.04
    * [x] Snap
### SUMO interface
  * [x] Windows
  * [x] macOS
  * Ubuntu 18.04
    * [x] Snap
### OSM importer and SUMO exporter:
  * [ ] macOS
  * Ubuntu 18.04
    * [x] Snap
### Backward compatibility
  * [ ] Windows
  * [ ] macOS
  * Ubuntu 18.04
    * [ ] Snap
### ROS controllers
  * Ubuntu 18.04
    * [x] Snap
### Guided Tour
  * [x] Windows
  * [x] macOS
  * Ubuntu 16.04
    * [ ] Snap
    * [x] Tarball
    * [x] Debian
  * Ubuntu 18.04
    * [x] Snap
    * [x] Tarball
    * [x] Debian

| Test | Description
|---|---|
| Installation  | Install Webots from the provided package, following the installation instruction from the Webots user guide. |
|   | Check that when pressing the simulation reset while the simulation is running you have the same behavior at the second iteration.Check this for the 10-15 first worlds of the guided tour. |
| Creation of a small project | From scratch and using only the Webots GUI (wizards (including VisualStudio on windows), scene tree, new, and so on), create a world |
| VRML import/export  | Check that the VRML import/export menu is working. |
| Make a movie  | Make a movie using the menu: Files > Make Movie ... </br>Test at least a normal screen resolution and the full screen resolution (1920x1080 Full HD). |
| Delete objects in the Scene Tree  | 1. Open a complex world </br>2. Select the last object in the Scene Tree </br>3. Hit the [Delete] button until the Scene Tree is empty (besides the 3 top nodes) </br>4. Revert and repeat the operation starting from the 4th node. </br>The test succeeds if Webots does not crash. |
| Copy a robot in the Scene Tree  | 1. Open a world that contains a robot</br>2. Select the robot</br>3. Hit the [Copy] button</br>4. Hit the [Paste After] button</br>5. At this point there should be 2 robots close to one another</br>6. Separate the 2 robots using the mouse (if needed)</br>7. Save the .wbt</br>8. Push [Revert]</br>9. Push [Run]</br></br>The test succeeds if both robots have the same appearance and behavior, etc. |
| Java controllers  | 1. Open the world: projects/languages/java/worlds/examples.wbt</br>2. Hit [Run]</br></br>The test succeeds if all 3 robots move, the camera images change and there is no error message.</br></br>3. Modify Help message (Driver.java at line 88)</br>4. Hit the [Save] button</br>5. Accept the relocation of the project proposed by Webots, in that order hit: [Yes], [OK], [Open], [OK].</br>6. Hit the [Build] button</br>7. When Webots proposes to 'Revert', hit [Yes].</br>8. Hit [Run]</br></br>The compilation test succeeds if the help message printed in the console contains the last modifications. |
| Python controllers  | 1. Open the world: projects/languages/python/worlds/examples.wbt</br>2. Hit [Run]</br></br>The test succeeds if all 3 robots move, the camera images change and there is no error message.</br></br>All the Python versions officially supported by the OS should be tested. |
| Robot window  | The generic robot window opens itself correctly, even if the simulation is stopped or at step 0 (by double clicking on the robot, or by selecting the corresponding item in the Robot menu)</br></br>Note: The e-puck, the Thymio II and the DARwIn-OP have a custom robot window.</br> |
| Devices worlds  | Run all the examples in the 'projects/samples/devices/worlds' directory and check that they all work as expected. |
| Support of UTF-8 characters  | Test that a user having UTF-8 characters in his account name can:</br>- launch Webots</br>- launch controllers</br>- Compile controllers |
| Visual Studio wizard  | Test that the VisualStudio wizard works. |
| Matlab controllers  | 1. Open the world: projects/languages/matlab/worlds/e-puck_matlab.wbt</br>2. Hit [Run]</br></br>The test succeeds if:</br>a) the e-puck robot moves</br>b) the camera and display viewports show moving images</br>c) a Matlab Window with 4 subwindows appears and all subwindows show moving graphics | 
| Mouse interactions  | Using the mouse and the keyboard, ensure that one can move the camera (translate, rotate, zoom), the objects (xz translation, lift), and apply forces/torques.</br></br>A right click in the 3D scene opens the context menu.</br></br>A double click on a robot opens the robot window. |
| e-puck - remote control  | Try to remote control an e-puck2 robot over Bluetooth |
| Binary compilation  | Test that controllers / physics plugins / controller plugins (remote control / robot windows) / libraries (qt_utils) can be cleaned and compiled smoothly. On Windows, please make sure to test by opening Webots from the icon. |
| DARwIn-OP  | to test:</br>-> the simulations do the expected thing</br>-> controllers can be modified</br>-> you can remote-control and remote-compile the real robot</br>-> same with Robotis OP2 |
| Make HTML5 animation  | Can create an animation (File / Make HTML5 animation) and play it into a web browser. |
| Streaming Server  | 1. start with the streaming server: webots --stream</br></br>2. open the web page located in resources/web/streaming_viewer/index.html and connect to Webots (using the default parameters).</br></br>3. the 3D view of Webots should display properly on the web page. It should be possible to change the viewpoint and select objects. |
| Extern controllers  | Open a simulation with a robot. Set the controller of the robot to <extern> and launch the controller from the command line. The test succeeds if the robot behaves the same as with the normal controller. |
| Offline documentation  | Check that the offline documentation is working from 'Help / offline documentation / ...' and from the context menu. |
| SUMO interface  | Open the 'projects/vehicle/highway' world:</br></br>  1.Start the simulation and check that SUMO is correctly started in GUI mode.</br>  2. Check that the version of SUMO (top of the SUMO GUI window) is the one specified in the Changelog.</br>  3. Check in Webots that other vehicles are appearing and moving.</br>  4. Check that the main vehicle is visible in SUMO as a green triangle (you may need to zoom). |
| OSM importer and SUMO exporter  | 1. Install the python dependencies as explained in https://www.cyberbotics.com/doc/automobile/openstreetmap-importer#dependencies</br></br>2. Convert the OSM file:</br></br>mkdir -p $HOME/my_project/resources/osm_files</br>mkdir -p $HOME/my_project/resources/OSM_importer</br>cp $WEBOTS_HOME/projects/vehicles/importer_demo.sh $HOME/my_project/importer_demo.sh</br>cp $WEBOTS_HOME/resources/osm_importer/config.ini $HOME/my_project/resources/OSM_importer/config.ini</br>cp $WEBOTS_HOME/projects/vehicles/resources/osm_files/village.osm $HOME/my_project/resources/osm_files/village.osm</br>cd $HOME/my_project</br>chmod u+x ./importer_demo.sh</br>./importer_demo.sh village</br></br>3. Open the generated world file and check the result is similar to the one distributed in Webots (project/vehicles/village).</br> 4. In pause mode, add the SumoInterface node and set it's 'useNetconvert' field to FALSE.</br> 5. Run the simulation and check that you can see vehicles appearing and correctly aligned on the roads. |
| Backward compatibility  | Open few worlds of the previous Webots version, and check they can be open with the rightful warnings if required. This test should particularly focus on the modifications of the tested release breaking the backward compatibility. |
| ROS controllers  | Test the distributed ROS simulations located in projects/languages/ros. The instructions are available at https://www.cyberbotics.com/doc/guide/tutorial-8-using-ros |
| Guided Tour | Check that all the worlds of the guided tour behave as expected. |

**Comment by DavidMansolino** [comment]
Here is a first draft of the table (I only restored what was in our previous quality assurance test without any update or correction).
Maybe we can but this in an issue template so that we can keep it up to date and review it what do you think?

**Comment by fabienrohrer** [comment]
This seems good to me as-is.

**Comment by stefaniapedrazzi** [comment]
Maybe I would create a wiki page with the template.
I'm not sure we need an issue for this.

**Comment by stefaniapedrazzi** [comment]
For the linux tests I would make this:

* all the test for the snap package
* debian and tarball
  - Installation
  - guided tour
  - java/python/cpp controllers
  - movies
  - robot windows
 -  binary compilation

**Comment by DavidMansolino** [comment]
I updated the list taking this and the platform seetings from the previous QA into account.

**Comment by stefaniapedrazzi** [comment]
Thank you

**Comment by stefaniapedrazzi** [comment]
We forgot that on Linux we have to test both on Ubuntu 16.04 and Ubuntu 18.04.
I can update the table and add different check boxes for the two versions of Ubuntu.

**Comment by stefaniapedrazzi** [comment]
I was wondering if it wasn't better to create a column for each platform.
What do you think?

| Test    | Description | Windows | macOS  | Ubuntu 16.04  | Ubuntu 18.04
|-|-|-|-|-|-
| Installation  | Install Webots from the provided package, following the installation instruction from the Webots user guide. | <ul><li>[ ] tested</li></ul> | <ul><li>[ ] tested</li></ul> | <ul><li>[ ] Snap</li><li>[ ] Tarball</li><li>[ ] Debian</li></ul> | <ul><li>[ ] Snap</li><li>[ ] Tarball</li><li>[ ] Debian</li></ul> |
| Simulation reset  | Check that when pressing the simulation reset while the simulation is running you have the same behavior at the second iteration.Check this for the 10-15 first worlds of the guided tour. | <ul><li>[ ] tested</li></ul> | <ul><li>[ ] tested</li></ul> |  | <ul><li>[ ] Snap</li></ul> |
| Creation of a small project | From scratch and using only the Webots GUI (wizards (including VisualStudio on windows), scene tree, new, and so on), create a world  | <ul><li>[ ] tested</li></ul> | <ul><li>[ ] tested</li></ul> |  | <ul><li>[ ] Snap</li></ul> |

| Test    | Description | Tested Platforms
|-|-|-
| Installation  | Install Webots from the provided package, following the installation instruction from the Webots user guide. | <ul><li>[ ] Windows</li><li>[ ] macOS</li><li>Ubuntu 16.04<ul><li>[ ] Snap</li><li>[ ] Tarball</li><li>[ ] Debian</li></ul><li>Ubuntu 18.04<ul><li>[ ] Snap</li><li>[ ] Tarball</li><li>[ ] Debian</li></ul></ul>
| Simulation reset  | Check that when pressing the simulation reset while the simulation is running you have the same behavior at the second iteration.Check this for the 10-15 first worlds of the guided tour. | <ul><li>[ ] Windows</li><li>[ ] macOS</li><li>Ubuntu 18.04<ul><li>[ ] Snap</li></li></ul></ul>
| Creation of a small project | From scratch and using only the Webots GUI (wizards (including VisualStudio on windows), scene tree, new, and so on), create a world | <ul><li>[ ] Windows</li><li>[ ] macOS</li><li>Ubuntu 18.04<ul><li>[ ] Snap</li></li></ul></ul>

**Comment by fabienrohrer** [comment]
My tests on `macOS` went very well.

**Comment by DavidMansolino** [comment]
On windows too for me

**Comment by fabienrohrer** [comment]
Tests on Ubuntu 16 (Debian and tarball) went well too.

**Comment by michou214** [comment]
I also try all the tests on my `Windows` computer. I found minor issues.
1) Tests not tested:
Support UTF-8 characters, Matlab controllers, e-puck remote control, Binary compilation, DARwIn-OP, Streaming server, Extern controllers, SUMO interface, OSM importer and SUMO exporter, ROS controllers

2) `projects/samples/devices/spherical_camera.wbt`: The camera view is not a sphere as you can see in the following screenshot but it's possible that it's due to my graphic card.
![spherical_camera](https://user-images.githubusercontent.com/36080014/70974639-83707000-20a8-11ea-9e99-df6e31195d3b.png)
**Configuration OpenGL:**
System: Windows 10 64-bit
OpenGL vendor : Intel
OpenGL renderer : Intel(R) HD Graphics 620
OpenGL version : 3.3.0 - Build 23.20.16.4973
Available GPU memory : N/A

3) `projects/samples/devices/nao_demo.wbt`: I will make a PR to correct the text displayed in the console that doesn't correspond to the movement realized by the Nao. Instead of making one step forward/backward, he makes more.

**Comment by DavidMansolino** [comment]
@michou214 thank you for the tests!
I tested on Windows on my computer and ``spherical_camera.wbt`` is working (so we probably have an issue with your GPU).
And about Matlab, I was suspecting that this was broken since a while, but it is good to have the confirmation.

**Comment by DavidMansolino** [comment]
Adding a ``.vcxproj.user`` file with this content fixes the problem: 
```
<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="Current" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|x64'">
    <LocalDebuggerEnvironment>PATH=%WEBOTS_HOME%/lib/controller;%PATH%</LocalDebuggerEnvironment>
    <DebuggerFlavor>WindowsLocalDebugger</DebuggerFlavor>
  </PropertyGroup>
</Project>
```
