### ISSUE TITLE
Is there any API can read objects‘s Ground Truth bounding box ？

### ISSUE THREAD

**Issue by Kailthen** [cyberbotics/webots#1165]
Hi there,
From LiDar sensor, one can read point cloud of other cars, can i read the 'real' position and bounding box values with any API ?

thanks

**Comment by fabienrohrer** [comment]
The solid position, orientation and boundingObject can be get directly using the supervisor API. Some objets fields are hidden by a PROTO interface.

Here is a typical example about how to get the translation, orientation and size of SOME objects (tables and chairs PROTOs):
https://gist.github.com/fabienrohrer/543c2a9751eefc6d352e6957e6e3dc90
The way to get the size may vary depending on the PROTO open fields.

Currently, there is no API to retrieve AABB or so. This would be useful.

I hope this answers your question (Next time, I think that [stackoverflow](https://stackoverflow.com/questions/tagged/webots) is more suitable than issue tracking for this kind of question ;-) ).
