### ISSUE TITLE
e-puck_line_demo floor texture is blurred

### ISSUE THREAD

**Issue by stefaniapedrazzi** [cyberbotics/webots#1183]
The floor texture of the e-puck_line_demo.wbt simulation is extremely blurred and doesn't look nice.
I think that previously the resolution was much bigger and the world was looking much nicer than this:

![Screenshot from 2019-12-12 10-46-00](https://user-images.githubusercontent.com/5910449/70701658-04a4bd00-1ccd-11ea-88d0-69f4fb6dbcb6.png)

Yes should improve it and probably restore a better image resolution.

**Comment by fabienrohrer** [comment]
This is because of the texture quality setting, probably set to "low" in your case. I think there is nothing to do with this.

**Comment by stefaniapedrazzi** [comment]
yes, you are right.
I forgot about it.
