### ISSUE TITLE
Consistency in PROTO field names for physics

### ISSUE THREAD

**Issue by stefaniapedrazzi** [cyberbotics/webots#1195]
It seems that most of the time the field name `enablePhysics` is used, but there are a couple of PROTO nodes that uses `physics` instead.
If possible it would be better to always use the same field name.

Here are the few sensors using `physics`:
* Robotis LDS-01
* SickLdMrs
* MultiSenseS21

Given that it is new, maybe it would be good to fix at least the Robotis LDS-01.

**Comment by DavidMansolino** [comment]
I am fixing the Robotis LDS-01 rigth now, and I think we can safetly change the other too @fabienrohrer  will this break anything for our friends using these sensors?

**Comment by fabienrohrer** [comment]
I don't see any issue to fix this now, thank you.

**Comment by DavidMansolino** [comment]
Fixed in #1196
