### ISSUE TITLE
External Controller for ML Cloud Training ?

### ISSUE THREAD

**Issue by MentalGear** [cyberbotics/webots#1236]
Is it possible to use Webots with the external mode to train robots controled by ML via the cloud (like google colab) ?

Cloud Training is an important asset for ML, and it would be great if Webots would provide some basics guides to ensure easy usage and/or, if not possible yet, implement functions that make external server training possible to assure it stays compatible & competitive with current developments in the field.

(As an aside, some basic guides on ML implementation with Webots would also be great. One excellent example of a great documentation with plenty of accessible guides and examples is the Unity ML project)

**Comment by omichel** [comment]
It is certainly possible to use Webots to train robots controlled by ML via the cloud. Using extern controllers is a possibility to achieve this. However, we do not provide any ready-made toolkit or tutorial for that. But we would be happy to see some volunteers developing such a toolkit or tutorial.

**Comment by MentalGear** [comment]
Thank you for your answer. Indeed, I found
- "Numerical Optimization Methods"
- "Interfacing Webots to Third Party Software with TCP/IP"
in the documentation (which is one of the most well written and presented sim app guide I have seen so far! 👍) though always appreciate a hint if there's more to know.
I will try to figure out the rest, and if I succeed, might post back here with a howto. :)

**Comment by DavidMansolino** [comment]
> if I succeed, might post back here with a howto. :)

This would be highly appreciated :wink:
