### ISSUE TITLE
Webots Crash on start up 2020a Win10

### ISSUE THREAD

**Issue by MyKoo** [cyberbotics/webots#1245]
Hi everyone!

When I launch Webots 2020a, it shows homescreen with tutorial and then I cannot click anything, then it shuts. I don't have any reports. 

Starting Webots with safemode didn't work for me.

 - Operating System: Win 10
 - Graphics Card: NVIDIA GeForce GTX1050m

**Comment by omichel** [comment]
Does Webots R2019b revision 1 work on your PC?

**Comment by MyKoo** [comment]
I tried it, and unfortunetaly it doesn't. Same happened when I downloaded R2019b.

**Comment by omichel** [comment]
That's odd. Are you sure your NVIDIA drivers are up-to-date?
Did you installed Webots locally (only for you) or for all users (in `C:\Program Files\Webots`)?

**Comment by MyKoo** [comment]
Now, they are. It didn't help.
It's installed only for me.

**Comment by omichel** [comment]
Can you try to uninstall Webots and re-install it for all users?

**Comment by MyKoo** [comment]
It works, thank you very much!
If I meet further problems I will reopen this issue.

**Comment by omichel** [comment]
Can you tell me what is your local username? Does it contain any non-ASCII character, like Asian characters?

**Comment by MyKoo** [comment]
ASCII characters only.

**Comment by omichel** [comment]
OK, thank you for the feedback... I have no more idea to investigate the issue... We tested local installations here and they work fine... So, I have no clue on what could be the cause of the problem...

**Comment by stefaniapedrazzi** [comment]
Did you have a previous Webots version installed on your system when installing Webots R2020a?

**Comment by MyKoo** [comment]
I had uninstalled 2019b rev.1 before launching 2020a.
At the beggining Webots haven't worked.
