### ISSUE TITLE
Setting sensor noise/resolution by code?

### ISSUE THREAD

**Issue by MentalGear** [cyberbotics/webots#1259]
I have been looking through the API for motor and position sensor, but can't find a function that allows to get or set noise & resultion values, as well as dir( positionSensor ).
Am I missing something, or is it only possible to set those values via the GUI ?
(OR is this a thing that can only be changed via the supervisor API ?)

**Comment by DavidMansolino** [comment]
You can't directly change these values from your controller using the position-sensor or motor API.

However, as a workaround, you can use the Supervisor API (https://cyberbotics.com/doc/reference/supervisor) to change the value of any field in the scene-tree (e.g. the noise and resolution fields).

Find here a very simple example changing the position field of a light: https://cyberbotics.com/doc/guide/samples-devices#supervisor-wbt
