### ISSUE TITLE
Quality Assurance R2020a-rev1

### ISSUE THREAD

**Issue by DavidMansolino** [cyberbotics/webots#1261]
Since this is a very small release the list of tests is very small.

Tests:
### Installation
  * [x] Windows
  * [x] macOS
  * Ubuntu 16.04
    * [x] Snap
    * [x] Tarball
    * [x] Debian
  * Ubuntu 18.04
    * [x] Snap
    * [x] Tarball
    * [x] Debian
### Make a movie
  * [x] Windows
  * [x] macOS
  * Ubuntu 16.04
    * [x] Snap
    * [x] Tarball
    * [x] Debian
  * Ubuntu 18.04
    * [x] Snap
    * [x] Tarball
    * [x] Debian
### Visual Studio wizard
  * [x] Windows
### Binary compilation
  * [x] Windows
  * [x] macOS
  * Ubuntu 16.04
    * [x] Snap
    * [x] Tarball
    * [x] Debian
  * Ubuntu 18.04
    * [x] Snap
    * [x] Tarball
    * [x] Debian
### Extern controllers
  * [x] Windows
  * [x] macOS
  * Ubuntu 18.04
    * [x] Snap
### SUMO interface
  * [x] Windows
  * [x] macOS
  * Ubuntu 18.04
    * [x] Snap
### Guided Tour
  * [x] Windows
  * [x] macOS
  * Ubuntu 16.04
    * [x] Snap
    * [x] Tarball
    * [x] Debian
  * Ubuntu 18.04
    * [x] Snap
    * [x] Tarball
    * [x] Debian

**Comment by omichel** [comment]
When opening `city.wbt` (guided tour), I am getting this error:
```
ERROR: 'C:/Users/Olivier/AppData/Local/Programs/Webots/projects/objects/traffic/protos/DirectionPanel.proto': error: Template engine error: luaL_dostring error : ...ta/Local/Programs/Webots/resources/lua/liluat/liluat.lua:520: attempt to perform arithmetic on local 'line_number' (a nil value).
```

**Comment by omichel** [comment]
`range_finder.wbt` attempts to save a `tiff` image and displays an error:
```
... Webots\projects\samples\devices\controllers\range_finder\range_finder.exe"
[range_finder] Error: wb_range_finder_save_image(): .tiff image not supported anymore, use .hdr instead.
```

**Comment by fabienrohrer** [comment]
The tests run smoothly on macOS. I have the same issue with the range finder, but not the one with city.wbt.

**Comment by DavidMansolino** [comment]
Same on Ubuntu 18.04, I am fixing the range-finder one

**Comment by DavidMansolino** [comment]
I think all the issues are now fixed, I will relaunch the creation of the packages.

**Comment by DavidMansolino** [comment]
Released.
