### ISSUE TITLE
sojourner.wbt doesn't look like Mars any more

### ISSUE THREAD

**Issue by omichel** [cyberbotics/webots#1269]
Because of recent changes in the textures / background, the ground color of sojourner.wbt is not red any more, but grey. It's a pity as it should refer to the red planet (Mars)...

**Comment by DavidMansolino** [comment]
I looked for nice looking HDR background images, but it's not so easy to find a good one, until now I only found those ones: https://www.canstockphoto.fr/search.php?related_image=54674898&related_mode=artist
Ideally, we should find similar ones (but free and a more permissive license).

**Comment by omichel** [comment]
Changing the color of the soil, rocks and fog can greatly improve the red planet appearance. I will make some try a post a screenshot here.

**Comment by omichel** [comment]
![sojourner](https://user-images.githubusercontent.com/1264964/72716573-bcea3e80-3b72-11ea-93c6-17cd1ce28bd5.png)
