### ISSUE TITLE
Improve exception safety with smart pointers

### ISSUE THREAD

**Issue by elfring** [cyberbotics/webots#1277]
Would you like to wrap any pointer data members with the class template “[std::unique_ptr](https://en.wikipedia.org/wiki/Smart_pointer#unique_ptr "Description for the usage of smart pointers")”?

Update candidates:
- [BotStudioWindow](https://github.com/cyberbotics/webots/blob/565b5aed95a2aadb73bccf2ad733d37893d5edfe/projects/robots/gctronic/e-puck/plugins/robot_windows/botstudio/core/BotStudioWindow.cpp#L46)
- [FrameBuffer](https://github.com/cyberbotics/webots/blob/69202baee3c0974f69f0e72d3412d19ed69feaad/projects/robots/robotis/darwin-op/libraries/robotis-op2/robotis/Framework/src/vision/Image.cpp#L39)
- [SwitchWidget](https://github.com/cyberbotics/webots/blob/565b5aed95a2aadb73bccf2ad733d37893d5edfe/projects/robots/gctronic/e-puck/plugins/robot_windows/botstudio/core/SwitchWidget.cpp#L34)

**Comment by DavidMansolino** [comment]
The use of `std::unique_ptr` might indeed be interesting in some specific case, however, we don't want to change the files you point for the following reasons:
  - **BotStudioWindow** and **SwitchWidget**: those files are part of a deprecated feature that is going to be removed soon.
  - **FrameBuffer** this file comes from another repository (kind of fork) and we, therefore, don't want to modify it to avoid forking from the original file.

However, if you see any other file where the use of a `std::unique_ptr` would be an advantage your contribution will be welcome.
