### ISSUE TITLE
Broken docs Links with Tab

### ISSUE THREAD

**Issue by DavidMansolino** [cyberbotics/webots#1296]
**Describe the Bug**
When entering a link to the doc with the tab-os or tab-language set, the page is not found and the index is displayed:
https://cyberbotics.com/doc/guide/running-extern-robot-controllers?tab-os=macos&tab-language=python

**Comment by DavidMansolino** [comment]
It seems there is an issue on the PHP side when parsing the url.
It seems that the `tabs` are not correctly parsed and are part of the `page`:
```
Setup: {"book":"guide","page":"running-extern-robot-controllers?tab-os=macos&amp;tab-language=python","tab":"","tabs":[],"anchor":"","branch":"hotifx-doc","repository":"cyberbotics","tag":"","url":"https://raw.githubusercontent.com/cyberbotics/webots/"}
```

Here is the problematic parsing:
https://github.com/cyberbotics/webots/blob/0d7f111588ab876434c39f995b8c1e5736088144/docs/doc.php#L28-L74

**Comment by stefaniapedrazzi** [comment]
maybe we should replace
```
"/&(tab-[^=?&]+)=([^?&#]+)/"
```
by 
```
/[&?](tab-[^=?&]+)=([^?&#]+)/"
```

**Comment by DavidMansolino** [comment]
Yes, that's probably the cause. Not sure what is the procedure to test changes on this file?

**Comment by stefaniapedrazzi** [comment]
I don't remember how much this functionality can be tested locally.
For sure it is possible to test part of it.
I can look at this if you want.

**Comment by DavidMansolino** [comment]
If you have an environment to test set-up why not.

**Comment by stefaniapedrazzi** [comment]
Ok.
Yes, I can easily test this using the local robotbenchmark setup.

**Comment by DavidMansolino** [comment]
Perfect, thanks a lot.
