### ISSUE TITLE
Webot ROS connection crashes when supervisor is on the robot and you call the service to get the translation of the node through the supervisor service

### ISSUE THREAD

**Issue by hkdeman** [cyberbotics/webots#1361]
**Describe the Bug**
I was trying to call the supervisor node using the ros service api through terminal. Each time I call a specific function like "/robot-name/node/get_velocity" (for example), the ros connection crashed on the webots GUI (it printed that in the console).

**Steps to Reproduce**
Add supervisor to a robot
Get velocity of the node of the robot using ROS service

**Expected behavior**
The GUI should print that the ROS connection is off. You need to reload the world to restart the connection.

**Screenshots**
![image](https://user-images.githubusercontent.com/25112802/74451580-c2882b00-4e77-11ea-9e9c-3c4cde867a45.png)

**System**
Description:    Ubuntu 18.04.3 LTS
Release:        18.04
Codename:       bionic

**Comment by DavidMansolino** [comment]
Can you please edit your post to add the description in the post instead of the title and if possible provide some code and stack.

**Comment by hkdeman** [comment]
> Can you please edit your post to add the description in the post instead of the title and if possible provide some code and stack.

Apologies! Changed!

**Comment by DavidMansolino** [comment]
Can you check what is the value of the `node` argument of this service that you are using?
