### ISSUE TITLE
Crash when double click on Camera Display

### ISSUE THREAD

**Issue by sudhirkelappan** [cyberbotics/webots#1372]
[backtrace_from_coredump.txt](https://github.com/cyberbotics/webots/files/4213672/backtrace_from_coredump.txt)
**Describe the Bug**
Webots crashes when I double click on Camera Display

**Steps to Reproduce**
1. webots --mode=pause /usr/local/webots/projects/vehicles/worlds/city.wbt
2. In the world view double click on the camera display overlay to open it in a separate window.
4. Webots coredumps.

**Expected behavior**

**Screenshots**

**System**
 - Operating System: Linux Ubuntu 16.04
 - Graphics Card: NVIDIA GeForce GTX 1060 6GB/PCIe/SSE2

**Additional context**
Happens on Speedometer display overlay as well.

**Comment by sudhirkelappan** [comment]
[backtrace_from_coredump.txt](https://github.com/cyberbotics/webots/files/4213669/backtrace_from_coredump.txt)

**Comment by DavidMansolino** [comment]
Probably linked to #302.

**Comment by stefaniapedrazzi** [comment]
Should be fixed in #2119.
