### ISSUE TITLE
Windows installer: loading errors when updating Webots version

### ISSUE THREAD

**Issue by stefaniapedrazzi** [cyberbotics/webots#1387]
**Describe the Bug**
If the user modifies manually the files in the installation folder (e.g. `C:/Program Files/Webots`), the uninstaller doesn't remove completely all the files.

If some files cannot be deleted, the error should be written the uninstaller logs in red.
This is probably not sufficient and if possible it would be better to prompt the error in a message box window or make it more visible so that users cannot miss it.

This is already the case for example when the uninstaller tries to remove a directory that doesn't exists.

**Users report**
We regularly have users reports about error after updating the Webots version.

For example a user reported that he modified the robots/sphero project by editing the world file and adding extra texture.
After updating to a newer version of Webots, there were errors loading the BB-8 PROTO node in a custom world.

**System**
 - Operating System: Windows 10

**Comment by omichel** [comment]
It is indeed possible to remove all the files, but do we really want to do that? See this [discussion](https://stackoverflow.com/questions/643547/how-to-configure-inno-setup-to-uninstall-everything).

**Comment by stefaniapedrazzi** [comment]
No, I don't think that removing all the files and deleting the users modifications without notifying him is better. And modifying the installation files is not a good practice that Webots should really support.

But I think that we should improve the notifications to the user, like forcing him to take some specific actions, instead of simply logging the errors because users don't read them and then reports issues and ask for help.
