### ISSUE TITLE
" DLL load failed" when using pycharm

### ISSUE THREAD

**Issue by Weiyi-Zhang258** [cyberbotics/webots#1399]
Hello, when I execute python scripts controllers in webots, it works well.
But when I follow the instructions about how to use pycharm on webots, it does not work.
I'm using win10.

Here are my pycharm settings:
![QQ图片20200222000225](https://user-images.githubusercontent.com/57039926/75050316-b7cc3680-5506-11ea-87e4-da36925bbab0.png)
![QQ图片20200222000229](https://user-images.githubusercontent.com/57039926/75050338-c1559e80-5506-11ea-9250-317f1a09da1e.png)

Here is the result:

![QQ图片20200221214044](https://user-images.githubusercontent.com/57039926/75039108-ea6c3400-54f2-11ea-9a1a-c13d4a656c33.png)

![QQ图片20200221214048](https://user-images.githubusercontent.com/57039926/75039112-ecce8e00-54f2-11ea-8181-04f99d9e9ec4.png)

**Comment by omichel** [comment]
Which version of Webots are you using? Did you try with a nightly build?

**Comment by omichel** [comment]
I believe I found the problem: you should add an extra PATH to your environment variables:
`PYTHONUNBUFFERED=1;PATH=G:\Program Files\Webots\lib\controller\;G:\Program Files\Webots\msys64\mingw64\bin`

Can you try that and confirm it works?

**Comment by Weiyi-Zhang258** [comment]
> I believe I found the problem: you should add an extra PATH to your environment variables:
> `PYTHONUNBUFFERED=1;PATH=G:\Program Files\Webots\lib\controller\;G:\Program Files\Webots\msys64\mingw64\bin`
> 
> Can you try that and confirm it works?

Yes!!! I have tried your solution and it works very well!!! Thank you very much for your detailed help!

**Comment by Weiyi-Zhang258** [comment]
> I believe I found the problem: you should add an extra PATH to your environment variables:
> `PYTHONUNBUFFERED=1;PATH=G:\Program Files\Webots\lib\controller\;G:\Program Files\Webots\msys64\mingw64\bin`
> 
> Can you try that and confirm it works?

Hi, there is another problem. After I succeeded in running the example code, I tried to control a robotis-op2 robot in pycharm. And I'm sure to add the extra path you mentioned, but it seems some more PATH needs to be added. Can you tell me what should I add?
![QQ图片20200222102157](https://user-images.githubusercontent.com/57039926/75084746-38b61d00-555d-11ea-95bd-c8ab8ab721b0.png)
![QQ图片20200222102107](https://user-images.githubusercontent.com/57039926/75084753-45d30c00-555d-11ea-821d-daaa801590f4.png)
![QQ图片20200222102128](https://user-images.githubusercontent.com/57039926/75084756-49ff2980-555d-11ea-99f0-d34502f35249.png)

**Comment by Weiyi-Zhang258** [comment]
> > I believe I found the problem: you should add an extra PATH to your environment variables:
> > `PYTHONUNBUFFERED=1;PATH=G:\Program Files\Webots\lib\controller\;G:\Program Files\Webots\msys64\mingw64\bin`
> > Can you try that and confirm it works?
> 
> Hi, there is another problem. After I succeeded in running the example code, I tried to control a robotis-op2 robot in pycharm. And I'm sure to add the extra path you mentioned, but it seems some more PATH needs to be added. Can you tell me what should I add?
> 
> The same error occurs at here:
> from managers import RobotisOp2GaitManager, RobotisOp2MotionManager
> 
> Traceback (most recent call last):
> File "D:/controllers/op2_controller2/op2_controller2.py", line 16, in
> from managers import RobotisOp2GaitManager, RobotisOp2MotionManager
> File "G:\Program Files\Webots\projects\robots\robotis\darwin-op\libraries\python37\managers.py", line 15, in
> import _managers
> ImportError: DLL load failed: 找不到指定的模块。
> 
> Here are my settings:
> PYTHONUNBUFFERED=1;PATH=G:\Program Files\Webots\lib\controller;G:\Program Files\Webots\msys64\mingw64\bin

I have found it:
G:\Program Files\Webots\projects\robots\robotis\darwin-op\libraries\robotis-op2

**Comment by LIU-yx97** [comment]
> I believe I found the problem: you should add an extra PATH to your environment variables:
> `PYTHONUNBUFFERED=1;PATH=G:\Program Files\Webots\lib\controller\;G:\Program Files\Webots\msys64\mingw64\bin`
> 
> Can you try that and confirm it works?

**Comment by LIU-yx97** [comment]
> > I believe I found the problem: you should add an extra PATH to your environment variables:
> > `PYTHONUNBUFFERED=1;PATH=G:\Program Files\Webots\lib\controller\;G:\Program Files\Webots\msys64\mingw64\bin`
> > Can you try that and confirm it works?
> 
> Yes!!! I have tried your solution and it works very well!!! Thank you very much for your detailed help!

I also met the same problem, and modified according to your way, but the problem still exists.
This is my Environment variables:
PYTHONUNBUFFERED=1;
PATH=E:\Program Files1\webots\Webots\lib\controller\;E:\Program Files1\webots\Webots\msys64\mingw64\bin\;E:\Program Files1\webots\Webots\msys64\mingw64\bin\cpp\;;
PYTHONPATH=E:\Program Files1\webots\Webots\lib\controller\python37
