### ISSUE TITLE
TrajectoryFollower ROS-Webots MoveIt Bug

### ISSUE THREAD

**Issue by Tim-Stoll** [cyberbotics/webots#1422]
**Describe the Bug**
I sending a Goal from Webots to MoveIT and MoveIT plans the and executes the trjaectorie. Through the TrajectoryFollower Action, the Trajectory gets executed in Webots. I wanted to get some feedback if i reached my goal. That should be given from the last else  in the update function.
def update(self):
        if self.robot and self.trajectory:
            print(1)
            now = self.robot.getTime()
            if (now - self.trajectory_t0) <= self.trajectory.points[-1].time_from_start.to_sec():  # Sending intermediate points
                self.last_point_sent = False
                setpoint = sample_trajectory(self.trajectory, now - self.trajectory_t0)
                for i in range(len(setpoint.positions)):
                    self.motors[i].setPosition(setpoint.positions[i])
                    # Velocity control is not used on the real robot and gives bad results in the simulation
                    # self.motors[i].setVelocity(math.fabs(setpoint.velocities[i]))
            elif not self.last_point_sent:  # All intermediate points sent, sending last point to make sure we reach the goal.
                print(2)
                self.last_point_sent = True
                last_point = self.trajectory.points[-1]
                state = self.jointStatePublisher.last_joint_states
                position_in_tol = within_tolerance(state.position, last_point.positions, self.joint_goal_tolerances)
                setpoint = sample_trajectory(self.trajectory, self.trajectory.points[-1].time_from_start.to_sec())
                for i in range(len(setpoint.positions)):
                    self.motors[i].setPosition(setpoint.positions[i])
                    # Velocity control is not used on the real robot and gives bad results in the simulation
                    # self.motors[i].setVelocity(math.fabs(setpoint.velocities[i]))
            else:  # Off the end
                print(3)
                if self.goal_handle:
                    last_point = self.traj.points[-1]
                    print(999)
                    state = self.jointStatePublisher.last_joint_states
                    position_in_tol = within_tolerance(state.position, last_point.positions, [0.1] * 6)
                    velocity_in_tol = within_tolerance(state.velocity, last_point.velocities, [0.05] * 6)
                    if position_in_tol and velocity_in_tol:
                        # The arm reached the goal (and isn't moving) => Succeeded
                        self.goal_handle.set_succeeded()
                        self.goal_handle = None 

**Expected behavior**
After my Goal is reached i expeccted that i could get this feedback. But it seems like the self.goal_handle.set_succeeded() never gets executed and through that i cant get feedback.

**System**
 - Operating System: [Linux Ubuntu 18.04]

**Comment by DavidMansolino** [comment]
This is now fixed in #1423, the patch will be available in the nightly from tomorrow.
