### ISSUE TITLE
Mandatory Python2.7 Dependency

### ISSUE THREAD

**Issue by DavidMansolino** [cyberbotics/webots#1470]
**Describe the Bug**
Python2.7 is supposed to be an optional dependency to compile Webots, however, the compilation fails if ti is not available due to this line:
https://github.com/cyberbotics/webots/blob/master/projects/robots/robotis/darwin-op/libraries/Makefile#L31

**Comment by remi-cyberbotics** [comment]
Which system does not ship python2.7 by default ? I mean we could solve the issue, but I would say very, very few systems come without it. It is almost all the time required by many programs and is installed system-wide. Maybe just Windows ?

**Comment by DavidMansolino** [comment]
Yes, Windows, and Ubuntu 20.04 too.

**Comment by remi-cyberbotics** [comment]
:eyes:
