### ISSUE TITLE
Crash when modifying textureAnimation from Robot in track.wbt

### ISSUE THREAD

**Issue by remi-cyberbotics** [cyberbotics/webots#1478]
Load Samples->Devices->Track.wbt

The field is located in:
DEF TRACKED_ROBOT->children-> DEF LEFT_TRACK->textureAnimation (-0.033)

Try to change it by any mean, webots crashes.

**Comment by DavidMansolino** [comment]
An assertion seems to be raised in debug mode:
```
nodes/WbTrack.cpp:343: void WbTrack::updateTextureAnimation(): Assertion `mShape && mShape->abstractAppearance()' failed.
```
