### ISSUE TITLE
Web interface: jQuery UI dialog cannot be moved and resized on iOS

### ISSUE THREAD

**Issue by stefaniapedrazzi** [cyberbotics/webots#1496]
**Describe the Bug**
jQuery UI dialogs cannot be moved or resized from a iOS device.
I tested on a iPad with two different browsers (Safari and Brave) running robotbenchmark.net.

**Steps to Reproduce**
1. Go to robotbenchmark.net and start a benchmark
2. Try to move or resize the info window
-> nothing happens

All the other actions works as expected.

This was working when the mobile interface has been developed.
So it should be due to some changes in iOS/browser.
On Android it works as expected and in Linux/Chrome simulating any iPhone/iPad device it works too.

**Comment by omichel** [comment]
Did you try to update to the latest version of jQuery?

**Comment by stefaniapedrazzi** [comment]
No, I didn't try but the touch events for jQuery UI are handled by the touch punch library that has not been updated since 5 years and we are alrady using the latest version (0.2.3)

**Comment by stefaniapedrazzi** [comment]
I tested on the newly release iOS 13.4, but I still get the same bug.

**Comment by stefaniapedrazzi** [comment]
To be checked again with the new wrenjs version.

**Comment by omichel** [comment]
We are not using jQueryUI any more.

**Comment by ThomasOliverKimble** [comment]
We just tested the new floating windows on iOS and they are some other issues that need to be dealt with: they are not even showing up in the first place. I will assign myself to this issue and try and tackle it today.

**Comment by ThomasOliverKimble** [comment]
The new floating windows have been tested and work well on iOS. Closing the issue!
