### ISSUE TITLE
Allow the Supervisor to lock/unlock connectors while the simulation is running

### ISSUE THREAD

**Issue by Acwok** [cyberbotics/webots#1513]
I have a scene with more than 36 robots and each of these robot have 6 connectors.  
I'd like to lock/unlock the connectors manually (not using the autoLock feature).
Adding a controller to each connector would slow down the simulation.

**I'd like to add a robot supervisor to the scene, with a controller attached to lock/unlock the connectors by changing their "isLocked" field.**

Currently, changing the "isLocked" field works but the value is not taking into consideration while the simulation is running (the connectors are not locked/unlocked).

Another solution would be to be able to cast a Node to a Connector. We could then use the Supervisor getFromDef() to get a pointer to the connector Node and cast it to a connector pointer to be able to use the lock()/unlock() functions of the Connector.

**Comment by DavidMansolino** [comment]
I quickly checked and it seems the field is correctly connected to an update function at runtime:
https://github.com/cyberbotics/webots/blob/bf600fa908cd2035d6b11f5a80f713f6a1349a67/src/webots/nodes/WbConnector.cpp#L124
But the update function does not actually perform any locking it just perform field checks:
https://github.com/cyberbotics/webots/blob/bf600fa908cd2035d6b11f5a80f713f6a1349a67/src/webots/nodes/WbConnector.cpp#L147

If the simulation is running, this update function should call the ``lock()``/``unlock()``functions.
