### ISSUE TITLE
Wrong Supervisor Field State when another Supervisor import nodes

### ISSUE THREAD

**Issue by DavidMansolino** [cyberbotics/webots#1519]
**Describe the Bug**
When a supervisor controller imports a node in the scene tree, the number of children of the parent field (``wb_supervisor_field_get_count``) is correctly updated in the supervisor controller.
But if another supervisor controller is using this field, then the number of children is not updated in its reference of the field.

**Comment by stefaniapedrazzi** [comment]
I can reproduce the same bug if I add a node or item manually from the scene tree.

There is currently no message that can be used to notify the supervisor API that the field count changed so a proper fix can only be implemented in R2021.

If this is a problematic issue that we need to fix in R2020 rev1, it should be possible to temporary request again the whole field to Webots and update the count if it the field already existed in the libController list.
