### ISSUE TITLE
Exception during the ROS launch

### ISSUE THREAD

**Issue by stevemartinov** [cyberbotics/webots#1531]
**Describe the Bug**
Whenever I try to run some ROS examples, I get this error:

```
Traceback (most recent call last):
  File "/home/a/catkin_ws/src/webots_ros/src/webots_launcher.py", line 40, in <module>
    subprocess.call(command)
  File "/usr/lib/python2.7/subprocess.py", line 172, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
=============================================
```

**Steps to Reproduce**
1. Install ROS melodic on 18.04 and try to run an example:
`roslaunch webots_ros keyboard_teleop.launch`

**System**
 - Operating System: [Ubuntu 18.04]
 - Graphics Card: [NVIDIA GeForce RTX 2080 11 GB]

**Comment by DavidMansolino** [comment]
Thank you for this bug report, we have indeed some issues with the latest version of ROS melodic, we are currently looking at it.

Did you install the webots_ros package from source or from APT?
Have you set the ``WEBOTS_HOME`` environment variable?
