### ISSUE TITLE
Online Documentation Referring to Development Version

### ISSUE THREAD

**Issue by telramund** [cyberbotics/webots#1536]
**Describe the Bug**

The Parquetry appearance PROTO seems not to have a "type" parameter defined, contrary to the documentation:
https://www.cyberbotics.com/doc/guide/appearances#parquetry

**Steps to Reproduce**

Create a world file with the following content:

```
#VRML_SIM R2020a utf8
WorldInfo { }
TexturedBackground { }
TexturedBackgroundLight { }
Floor {
  size 50 50
  appearance Parquetry { type "light strip" }
}
```

Observe "Skipped unknown 'type' parameter in Parquetry PROTO." error message and that floor appearance matches "dark strip", not "light strip". Change type to "dark strip", note that the appearance has not changed.

**System**
 - Operating System: Gentoo Linix
 - Graphics Card: NVIDIA 940MX

**Comment by DavidMansolino** [comment]
You are completely right, it seems their is a bug with our online documentation, the documentation of the next release of Webots is online and not of the current one, please find the correct version of the documentation here:

https://www.cyberbotics.com/doc/guide/appearances?version=R2020a-rev1

**Comment by omichel** [comment]
This is because changes for Webots R2020a revision 2 were committed on the master branch and got automatically published as the default online documentation. We should have a created a branch for revision 2 instead. We will take are of this from Webots R2020b revision 1.
