### ISSUE TITLE
Any more specific explanation or tutorials about the DistanceSensor?

### ISSUE THREAD

**Issue by Dest1nation** [cyberbotics/webots#1537]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by DavidMansolino** [comment]
Here is the main documentation about distance sensors: https://cyberbotics.com/doc/reference/distancesensor
You will also find some more information about the distance-sensors of the e-puck for example here: https://en.wikibooks.org/wiki/Cyberbotics%27_Robot_Curriculum/Novice_programming_Exercises#The_IR_Sensors_[Novice]
