### ISSUE TITLE
Can't import a VRML-file to webots

### ISSUE THREAD

**Issue by ipa-rwu** [cyberbotics/webots#1575]
I import a VRML file(.wrl) to webots (FILE>Import VRML97) 
First I try the VRML file from ```webots/resources/nodes/```, e.g. Sphere.wrl. Then I got error: ``error: Expected field name or '}', found 'vrmlField'``.
Then I try the module my colleague created. Then I got ``error: Skipped unknown 'Separator' node or PROTO``
Does anyone have a solution?

_Originally posted by @ipa-rwu in https://github.com/cyberbotics/webots/issues/303#issuecomment-617105691_

**Comment by DavidMansolino** [comment]
Please do not duplicate issues (#303)
