### ISSUE TITLE
Inverted direction when moving robot with SHIFT key in hoap2_sumo.wbt

### ISSUE THREAD

**Issue by stefaniapedrazzi** [cyberbotics/webots#158]
**Describe the Bug**
In ``hoap2_sumo.wbt`` world, when moving the robot with SHIFT+mouse left button and drag, the robot is moved in the wrong direction w.r.t to the mouse movement: left instead of right and front instead of back.
For all the other robots and world the behavior is correct.

**Steps to Reproduce**
1. Go to 'hoap2_sumo.wbt'
2. move the Hoap2 robot with SHIFT+mouse left click+mouse drag

**Expected behavior**
The robot should be moved in the same direction as the mouse pointer.

**System**
 - Operating System: Linux Ubuntu 18.04
 - Graphics Card: NVIDIA GeForce GT 740

Note that there is also some strange behavior moving the robot in `robotis_op3_motion_player.wbt` with SHIFT+mouse, but this could be due to the size of the world.

**Comment by fabienrohrer** [comment]
I cannot reproduce this bug on macOS or on my Ubuntu18.04 virtual machine.

**Comment by DavidMansolino** [comment]
I can reproduce it on Ubuntu 16.04 native machine but not systematically most of the time it is working fine.

**Comment by stefaniapedrazzi** [comment]
I can reproduce this systematically. But it depends on the view and on where I click with the mouse to start the rotation.
