### ISSUE TITLE
Contradiction in the Motor documentation

### ISSUE THREAD

**Issue by Acwok** [cyberbotics/webots#1582]
**Documentation page(s) concerned**
https://github.com/cyberbotics/webots/blob/master/docs/reference/motor.md#force-and-torque-control

**What is the problem with the current documentation?**
There is a contradiction between the description and the table.  
The description says that the PID is used when doing velocity control:
> The position (resp. velocity) control described above are performed by the Webots PID-controller

while the table says the opposite:

> 
| &nbsp;                                                                         | position control                                 | velocity control                                 | force or torque control                      |
| ------------------------------------------------------------------------------ | ------------------------------------------------ | ------------------------------------------------ | -------------------------------------------- |
| uses PID-controller                                                            | yes                                              | no                                               | no                                           |

**Comment by DavidMansolino** [comment]
You're right, the first sentence is wrong only the position control is done using the Webots PID, the parenthesis part should be removed.
