### ISSUE TITLE
Can you provide a simulation example of Robot path planning algorithm in MATLAB?

### ISSUE THREAD

**Issue by sxbug** [cyberbotics/webots#1596]
Hi
I found that NO document for example of KUKA . Can you pleased provide an example of robot arm path planning based on MATLAB? I think such an example has certain representativeness. Thank you

sxbug

**Comment by omichel** [comment]
Unfortunately, developing such a documentation is not in our priorities at the moment. However, you are welcome to contribute such a documentation. We would be happy to review your contribution.
