### ISSUE TITLE
Non-HDR backgrounds are deprecated. Please select one of the following 'TexturedBackground.texture'

### ISSUE THREAD

**Issue by LeoJhonSong** [cyberbotics/webots#1600]
Hi, I am using webots 2020b from the Webots Nightly Build (24-4-2020) on Ubuntu18.04.

The problem I met id that every time I load the world I got this in the console:
![image](https://user-images.githubusercontent.com/37630203/80445833-cdffd400-8947-11ea-951b-db546eff9152.png)

The `TexturedBackground` I use is **noon_sunny_empty** and the `TexturedBackgroundLight` is also **noon_sunny_empty**.

I really want to use this one as I try to simulate a noon beachside :joy:

I saw there were pull requests trying to make these background become HDR ones, is this **noon_sunny_empty** a forgotten one? :joy:

**Comment by DavidMansolino** [comment]
For some background (such as noon_sunny_empty) it is not possible to convert them to HDR (HDR need more information than regular background, and this information can't be created if not available).

If you really want to use this background you can either:
  - ignore the warning.
  - convert the node to base node (right click on the node 'Convert to Base Node(s)' to remove the warning.

**Comment by LeoJhonSong** [comment]
thanks！
