### ISSUE TITLE
Unable to start Webots

### ISSUE THREAD

**Issue by Jajafarov** [cyberbotics/webots#1601]
**Describe the Bug**
I get a segmentation fault when trying to start Webots. 

**Steps to Reproduce**
1. Install Webots R2020a rev1 using snap.
2. Launch Webots.

**Expected behavior**
Webots should launch.

**System**
 - Operating System: Arch Linux
 - Graphics Card: NVIDIA GeForce RTX 2070 Super 8 GB

**Additional context**
This is the specific error I get.
```
Fontconfig`` warning: FcPattern object weight does not accept value [40 210)
/snap/webots/14/usr/share/webots/webots: line 86: 260171 Segmentation fault      (core dumped) "$webots_home/bin/webots-bin" "$@"
```

**Comment by DavidMansolino** [comment]
Did you try starting Webots with the safe mode enabled (https://cyberbotics.com/doc/guide/starting-webots#safe-mode)?

**Comment by omichel** [comment]
Can you try this [fix](https://forum.snapcraft.io/t/snapped-app-not-loading-fonts-on-fedora-and-arch/12484/35) and report whether it helps?
```
sudo rm /var/cache/fontconfig/*
rm ~/.cache/fontconfig/*
fc-cache -r
```

**Comment by Jajafarov** [comment]
Starting in safe mode does not help. The fontconfig cache fix didn't work either although it changed from `[40 210)` to `[0 205)` if that means anything.

**Comment by Jajafarov** [comment]
Strange, clearing the cache without running `fc-cache -r` seems to work.

**Comment by omichel** [comment]
Can you confirm what you did exactly? Simply:
```
sudo rm /var/cache/fontconfig/*
rm ~/.cache/fontconfig/*
```
And that worked?

**Comment by Jajafarov** [comment]
> Can you confirm what you did exactly? Simply:
> 
> ```
> sudo rm /var/cache/fontconfig/*
> rm ~/.cache/fontconfig/*
> ```
> 
> And that worked?

Yes, I ran exactly this and it is now working.
