### ISSUE TITLE
The spot web component has broken pistons

### ISSUE THREAD

**Issue by omichel** [cyberbotics/webots#1606]
Moving the piston motors seems to break the [Spot robot](https://cyberbotics.com/doc/guide/spot) in the user guide.

**Comment by DavidMansolino** [comment]
That's not coming from the robot model as I can confirm the rotation of the piston is correct in Webots.
And it seems the spot is not the only robot concerned, moving the ``wheel1_joint`` motor of the robotino gives also very strange result: https://cyberbotics.com/doc/guide/robotino3

**Comment by DavidMansolino** [comment]
Same with the new P-Rob3, some solids are rotating around the wrong axis: https://cyberbotics.com/doc/guide/p-rob3?version=feature-prob3
