### ISSUE TITLE
Mutli-job compilation of webots.min.js is raising warnings on macOS

### ISSUE THREAD

**Issue by DavidMansolino** [cyberbotics/webots#1623]
**Describe the Bug**
When compiling with the `-jX` option, the compilation of webots.min.js is raising this warning:
```
# compressing webots.lib.js
make[3]: warning: jobserver unavailable: using -j1.  Add `+' to parent make rule.
# compressing webots.min.js
```

**Comment by omichel** [comment]
I cannot reproduce this problem on Windows, but I found and am fixing another problem with this Makefile.

**Comment by DavidMansolino** [comment]
It seems indeed macOS specific as I can't reproduce it on Ubuntu too.
