### ISSUE TITLE
Resetting the simulation doesn't reset the LIDAR sensor correctly

### ISSUE THREAD

**Issue by Jajafarov** [cyberbotics/webots#1624]
**Describe the Bug**
Resetting the simulation doesn't reset the LIDAR sensor correctly, you have to reset the world completely for it to correctly reset. Only resetting the simulation leads to the scan having an incorrect rotation. The "shape" of the scan is correct, only the angle works incorrectly. This can both be seen using the point cloud rendering and by printing the values in the console.

**Steps to Reproduce**
1. Start up the LIDAR example with LIDAR point cloud rendering enabled.
2. Run the example for a few seconds.
3. Reset the simulation and run it again for a few seconds.
4. Pause the simulation and see the point cloud incorrectly angled.

**Expected behavior**
The LIDAR scan should be oriented in the same direction in the second simulation as the first.

**Screenshots**
![image](https://user-images.githubusercontent.com/9387120/81015379-e5b2ed00-8e5e-11ea-9be1-084ac606d2be.png)

**System**
 - Operating System: Arch Linux
 - Graphics Card: NVIDIA GeForce RTX 2070 Super 8 GB

**Comment by DavidMansolino** [comment]
Thank you for the bug report, I can indeed reproduce this issue. We will fix this for the next release of Webots.
