### ISSUE TITLE
Velodyne 32E and 64E only has 1125 points per layer instead of 4500

### ISSUE THREAD

**Issue by jrcblue** [cyberbotics/webots#1628]
We add two kinds of lidars, Velodyne 32E and 64E to the car. Then, we get the point cloud and the horizontal resolution. We found there are only 1125 points per layer instead of 4500. (The document says it should be 4500).
Thanks.

**Comment by DavidMansolino** [comment]
Thank you for the bug report, I can indeed reproduce the problem with those two lidars only (the other models don't seem affected by the bug).

**Comment by DavidMansolino** [comment]
This is now fixed and will be included in the nightly build from tomorrow: https://github.com/cyberbotics/webots/releases
