### ISSUE TITLE
Invalid MATLAB Controller Function Prototypes for Arrays

### ISSUE THREAD

**Issue by lukicdarkoo** [cyberbotics/webots#1642]
**Documentation page(s) concerned**
- https://cyberbotics.com/doc/guide/controller-programming?tab-language=matlab#reading-sensors
- https://cyberbotics.com/doc/reference/accelerometer?tab-language=matlab#accelerometer-functions
- https://cyberbotics.com/doc/reference/compass?tab-language=matlab#compass-functions
- ...

**What is the problem with the current documentation?**
As discussed [here](https://github.com/cyberbotics/webots/pull/1632#discussion_r422013099) examples such as:
```
[x y z] = wb_accelerometer_get_values(acc)
```
are not valid in MATLAB and can be misleading for the users.

**Describe how you would fix it**
Those examples should be replaced with
```
x_y_z_array = wb_accelerometer_get_values(acc)
```

**Comment by gokulp01** [comment]
@omichel @lukicdarkoo I think #1664 solves the issue :)

**Comment by omichel** [comment]
@lukicdarkoo: can we close this issue?

**Comment by lukicdarkoo** [comment]
Yes!
