### ISSUE TITLE
Errors in Windows Package Creation

### ISSUE THREAD

**Issue by DavidMansolino** [cyberbotics/webots#1650]
**Describe the Bug**
The creation of the Windows package is generating error and warning messages:
```
# /mingw64/bin/libzstd.dll is already included
# processing ffmpeg dependencies (DLLs)
# building distribution source
# creating webots.iss version R2020a revision 2: done
# creating webots_setup.exe (takes long)
Error on line 21437 in C:\projects\webots-master\src\packaging\webots.iss: Source file "C:\msys64\\mingw64\bin\libicuuc65.dll" does not exist.
Compile aborted.
```

https://ci.appveyor.com/project/omichel/webots-master/builds/32774904#L5582

**Comment by omichel** [comment]
Yes, this is because libicu was upgraded to version 66. I will take care of fixing this.

**Comment by omichel** [comment]
The package now builds without any error or warning: https://ci.appveyor.com/project/omichel/webots-9ufow
