### ISSUE TITLE
wrong length of horizontal  tab in webots console

### ISSUE THREAD

**Issue by LeoJhonSong** [cyberbotics/webots#1660]
~~**System**: Ubuntu1804~~
**System**: Windows 10
**Version**: 2020b

Hi, I was trying to use '\t' to prettier my output, but I surprisingly found that a horizontal tab in webots console is **11** but not **8** spaces. Is that what supposed to be?
![image](https://user-images.githubusercontent.com/37630203/81862301-1819c400-959c-11ea-8912-c6cda86a3932.png)

**Comment by DavidMansolino** [comment]
You're right, I tested on macOS it is not equal to 8 spaces either, but rather 7. This probably depends on the font used.

**Comment by omichel** [comment]
Indeed. This value is expressed in pixels and the default value is 80 pixels. See https://doc.qt.io/qt-5/qplaintextedit.html#tabStopDistance-prop
I write a small test controller program on Windows:
```C
  char *s = "12345678901234567890";
  char buffer[256];
  printf("              %s%s%s%s%s%s\n", s, s, s, s, s, s);
  for (int i = 0; i < 20; i++) {
    int a[4];
    for (j = 0; j < sizeof(a) / sizeof(int); j++)
      a[j] = rand() % 10;
    sprintf(buffer, "%.2d:\t%%.%ds\t%%.%ds\t%%.%ds\t%%.%ds\n", i + 1, a[0], a[1], a[2], a[3]);
    // puts(buffer);
    printf(buffer, s, s, s, s);
  }
```
And I get this:
![tabs](https://user-images.githubusercontent.com/1264964/81955610-97de7780-960a-11ea-9d60-d306e4fa1046.png)
So, I would say the behavior is normal.
Maybe we can add a preferences item for changing this 80 pixels value?

**Comment by LeoJhonSong** [comment]
I'm sorry that I have to correct my information:

> ![image](https://user-images.githubusercontent.com/37630203/81862301-1819c400-959c-11ea-8912-c6cda86a3932.png)

This output above was obtained on **Windows 10**, not Ubuntu1804. So same tab length as what @omichel got. 
Webots console works pretty well on my Ubuntu1804 :smile:

**Comment by omichel** [comment]
OK, so I guess we can close this issue.
Feel free to re-open it if you believe there is a problem.

**Comment by LeoJhonSong** [comment]
Thank you. BTW are we going to add a preferences item for changing the horizontal tab length?

**Comment by omichel** [comment]
If you need it, please go ahead and implement it, I will be happy to review your PR about it.
