### ISSUE TITLE
associate controller file in arbitrary path

### ISSUE THREAD

**Issue by LeoJhonSong** [cyberbotics/webots#1676]
It seems so far we could only modify the **controller** field of a robot node to associate the robot with a controller file under `project_root/controller/`. I wonder if we could associate the robot with a controller file under arbitrary path? I have tried that if we run the robot with **\<extern\>**, the path of the controller file does not matter, so I think this could be not so difficult.

**Comment by DavidMansolino** [comment]
It should be feasible to associate controller of your current project, but the controller directory should be named controller**s** (e.g. `project_root/controllers/`) and not controller.
Unfortunately, using arbitrary path is supported only with extern controller for now.
But we have plan to improve this (see #1638).
