### ISSUE TITLE
cannot use get_id under CameraRecognitionObject when using Python

### ISSUE THREAD

**Issue by fiveriddle** [cyberbotics/webots#1687]
**Describe the Bug**
When i want use the get_id of  CameraRecognitionObject when using Python, it occurs the error that the get_id are not in the list, i wonder how could i take the id or the position out?
<img width="336" alt="屏幕快照 2020-05-22 上午10 02 15" src="https://user-images.githubusercontent.com/65746681/82623719-63bf1400-9c13-11ea-95ca-1b94784478ca.png">

**Screenshots**

**System**
 - Operating System: macOS Mojave

**Comment by omichel** [comment]
You should write:
```python
    if data.get_id() == 1813:
```

**Comment by fiveriddle** [comment]
> You should write:
> 
> ```python
>     if data.get_id() == 1813:
> ```
it  still occur the error
[recog] Traceback (most recent call last):
[recog]   File "recog.py", line 43, in <module>
[recog]     if data.get_id() == 1803:
[recog] AttributeError: 'list' object has no attribute 'get_id'

**Comment by omichel** [comment]
Can you please post your complete controller source code?

**Comment by fiveriddle** [comment]
> Can you please post your complete controller source code?
from so far it is like
from controller import Robot
from controller import Camera
from controller import CameraRecognitionObject


TIME_STEP = 64

robot = Robot()
camera1=Camera('camera1')
camera1.enable(TIME_STEP)
camera1.recognitionEnable(TIME_STEP)
wheels = []
data=[]
wheelsNames = ['wheel1', 'wheel2', 'wheel3', 'wheel4']
for i in range(4):
    wheels.append(robot.getMotor(wheelsNames[i]))
    wheels[i].setPosition(float('inf'))
    wheels[i].setVelocity(0.0)

while robot.step(timestep) != -1:
    leftSpeed = 0.0
    rightSpeed = 0.0
    cameraData = camera1.getImage()
    number = camera1.getRecognitionNumberOfObjects() 
    data = camera1.getRecognitionObjects()   
    for i in range(number):
        if data.get_id() == 1803:
            leftSpeed = 6.0
            rightSpeed = 6.0
            if((data.get_position())> -3):
                leftSpeed = 0.0
                rightSpeed = 0.0

**Comment by omichel** [comment]
Can you try this:
```python
[...]
    data = camera1.getRecognitionObjects()   
    for d in data:
        if d.get_id() == 1803:
[...]
```

**Comment by fiveriddle** [comment]
> Can you try this:
> 
> ```python
> [...]
>     data = camera1.getRecognitionObjects()   
>     for d in data:
>         if d.get_id() == 1803:
> [...]
> ```



> Can you try this:
> 
> ```python
> [...]
>     data = camera1.getRecognitionObjects()   
>     for d in data:
>         if d.get_id() == 1803:
> [...]
> ```

My aim is to scan all the objects in the image to check whether there exist the ideal id(which we have test and record before). Once confirmed, I want to get the z, x or y position of the object. ( for the next step). However, when I take use of python, I do not understand how to call database.
1.  Do I need to use the CameraRecognitionObject API? 
Such as directly use
CameraRecognitionObject.get_id() 
or use 
data = camera1.getRecognitionObjects()
and use data.get_id()
2. how to call the position, do i need to built another 3 length array like 
position =[3]
position=data[i].get_position()
and take use of position[2] to use the z-position?
and how could i know the objects' id 
is the class more like 
data[i].get_position[k](in C language)?
how to write it in python?
Thanks a lot.

**Comment by omichel** [comment]
Yes, `getRecognitionObjects()` returns an array of `CameraRecognitionObject` which you can access using either the `[]`operator or the `for object in objects` construct which I originally suggested.
