### ISSUE TITLE
Broken Controller Arguments

### ISSUE THREAD

**Issue by DavidMansolino** [cyberbotics/webots#1712]
**Describe the Bug**
The controller arguments are broken (at least in python).

**Steps to Reproduce**
1. Open and run the pedestrian world.

**Screenshots**
The starting command line looks wrong:
```
INFO: pedestrian: Starting controller: python!-u+pedestrian.py+--trajectory="0+3,+0+-3"+--speed=2.5
```

The controllers fails:
```
[pedestrian] Usage: pedestrian.py [options]
[pedestrian] 
[pedestrian] pedestrian.py: error: no such option: -3
WARNING: 'pedestrian' controller exited with status: 2.
[pedestrian] Usage: pedestrian.py [options]
```

This has probably been introduced in #1709.

**Comment by DavidMansolino** [comment]
In this case, the following argument `--trajectory="0 3, 0 -3" --speed=2.5` gives these arguments in the controller (printed with `print(sys.argv)`):
```
[pedestrian] ['pedestrian.py', '--trajectory="0', '3,', '0', '-3"', '--speed=2.5']
```

**Comment by DavidMansolino** [comment]
I confirm it was working fine before #1709.

**Comment by omichel** [comment]
I believe we have a design problem here. `Robot.controllerArgs` should be a MFString instead of a SFString. I will consider fixing this on the develop branch later. I will now fix the bug with a somehow dirty patch, so that it behaves as before.
