### ISSUE TITLE
Add search functionality to documentation

### ISSUE THREAD

**Issue by ljden** [cyberbotics/webots#1714]
It would be good to have search functionality added to the online [webots documentation](https://cyberbotics.com/doc/guide/) to boost functionality and usability

**Comment by omichel** [comment]
Are regular search engines (https://google.com, https://duckduckgo.com) not sufficient for this?

**Comment by ljden** [comment]
From a usability standpoint I would say no, they are not sufficient

**Comment by gokulp01** [comment]
@omichel @DavidMansolino @ljden I think #1726 solves the issue. If there is anything else I can do, I'd be more than happy to do so :)

**Comment by DavidMansolino** [comment]
Yes this solves the issue perfectly!
