### ISSUE TITLE
Both Java examples return null-pointer exception when running at line 15

### ISSUE THREAD

**Issue by MichaelFrancis123** [cyberbotics/webots#1787]
**Documentation page(s) concerned**
https://cyberbotics.com/doc/guide/supervisor-programming?tab-language=java

The Java examples do build, but when running the simulation there is a null-pointer exception on line 15. This line is:
    final Field trans_field = robot_node.getField("translation");

I would like an example code which I can run on a robot object.

**Comment by MichaelFrancis123** [comment]
I have noticed that I have this issue with other languages too, which makes me seem to think it hasn't to do with the language, but with my robot settings. Of course I have remembered to set the supervisor option to TRUE.

**Comment by omichel** [comment]
The problem is probably because your Robot node doesn't have a DEF name equal to "MY_ROBOT". Please check the scene tree and ensure your Robot has a correct DEF name.
