### ISSUE TITLE
Broken IndexedLineSet Appearance

### ISSUE THREAD

**Issue by DavidMansolino** [cyberbotics/webots#1794]
**Describe the Bug**
The appearance of the indexedLineSet node is not working, it is always black:
![image](https://user-images.githubusercontent.com/2461619/84898976-5842f980-b0a8-11ea-9295-e261fed12184.png)
Here is how it should looks like (image of the doc):
![geometric_primitives](https://user-images.githubusercontent.com/2461619/84899034-6e50ba00-b0a8-11ea-81b6-d80c6d7832a7.png)

**Comment by omichel** [comment]
I suppose this regression was introduced when we generalized the PBRAppearance.
This example uses PBRApperance for the IndexedLineSet which doesn't really makes sense.
If we replace the PBRAppearance with an Appearance node with the ambiantIntensity set to 1, the color of the IndexedLineSet appears to be correct.

**Comment by DavidMansolino** [comment]
It seems you are right, I checked and it seems it never worked with PBRAppearance.
But we should in any case either fix this either deny the use of PBRAppearance in the appearance field of Shape node using an indexedLineSet.
