### ISSUE TITLE
run multiple instances in parallel

### ISSUE THREAD

**Issue by culurciello** [cyberbotics/webots#1797]
Hi, great work here! We are using this for a reinforcement learning project.
It would help us immensely if we could run multiple instances of the simulator in parallel. Is this possible?

**Comment by omichel** [comment]
Yes, this is possible.

**Comment by culurciello** [comment]
Thanks so much! Would you kindly let us know what is the best suggested way to do so? Is this it: https://cyberbotics.com/doc/guide/web-simulation? Thanks again

**Comment by omichel** [comment]
A simple script can be used to launch several instances of Webots in parallel.
