### ISSUE TITLE
crossroads proto: missing recognition color

### ISSUE THREAD

**Issue by jdeantoni** [cyberbotics/webots#1810]
In order to allow camera object recognition of crossroads, it is required to have a "recognition color". This is actually missing in the current cross road Proto. 

This is really helpful to develop controller for autonomous vehicles.

_Appear on webots R2020a revision 1_

**Comment by DavidMansolino** [comment]
Good point, feel free to add it yourself:
https://github.com/cyberbotics/webots/edit/master/projects/objects/road/protos/Crossroad.proto
