### ISSUE TITLE
Add a Mechanical Loop Example

### ISSUE THREAD

**Issue by DavidMansolino** [cyberbotics/webots#1818]
On this page we should write an extremely simple example of mechanical loop:
https://cyberbotics.com/doc/reference/solidreference

**Comment by DavidMansolino** [comment]
Feel free to make a pull-request to fix this issue :wink:

**Comment by gaurivn** [comment]
Sure, thank you

**Comment by gaurivn** [comment]
@DavidMansolino , can you please specify the location, should I add in the README, or in which doc should I add mechanical loop example

**Comment by DavidMansolino** [comment]
In the documentation page I pointed.
But if you are not familiar with Webots and its doc, it is probably better letting this issue to someone else.

**Comment by gaurivn** [comment]
Okay I got it, thank you, will send a PR soon.
