### ISSUE TITLE
Debugging symbols are removed on compile

### ISSUE THREAD

**Issue by ljden** [cyberbotics/webots#1819]
**Describe the Bug**
Debugging symbols are stripped at linking when following the Webots guide for [Using the GNU Debugger with a Controller](https://cyberbotics.com/doc/guide/debugging-c-cpp-controllers?tab-os=linux&tab-language=c++#using-the-gnu-debugger-with-a-controller)

**Steps to Reproduce**
1. Create dummy controller
2. Open Makefile in controller directory and add line `CFLAGS = -g`
3. Save and compile with `make`
4. run `gdb dummy_controller`
5. gdb outputs:

> GNU gdb (Ubuntu 8.1-0ubuntu3.2) 8.1.0.20180409-git
...
Reading symbols from ./dummy_controller...(no debugging symbols found)...done.

**Expected behavior**
Debugging symbols should not be stripped so they can be loaded by gdb

Output when compiled correctly:
>GNU gdb (Ubuntu 8.1-0ubuntu3.2) 8.1.0.20180409-git
...
Reading symbols from ./dummy_controller...done.

**System**
 - Operating System: Ubuntu 18.04
 - Graphics Card: N/A

**Additional context**
Compiling with `make debug` does not strip the debugging symbols

The offending lines are related to the `release` goal: https://github.com/cyberbotics/webots/blob/03742b638505d796a0e87a38c3a1d9d94ad303a6/resources/Makefile.include#L268-L275

If this is still the desired behaviour, then the documentation (linked above) should be updated to recommend compiling with `make debug` and the suggestion of adding `CFLAGS = -g` to the Makefile should be removed

Edit: linked correct portion of code

**Comment by omichel** [comment]
This is the desired behavior.
You are right, the documentation is not up-to-date to this.
Feel free to propose some fix for the documentation.

**Comment by ljden** [comment]
@omichel Is there a way to choose the make target with the "build" button in the Webots app? I can compile with `make debug` from the command line, but I can't see anything obvious in the app to do the same

**Comment by omichel** [comment]
No, you are right, this is only possible from the command line.

**Comment by DavidMansolino** [comment]
The lines your are referring in `webots/src/webots/Makefile` are for compiling Webots executable and not for compiling controllers.

**Comment by ljden** [comment]
Ah you're right! They are (nearly) the same in the [`Makefile.include` file](https://github.com/cyberbotics/webots/blob/03742b638505d796a0e87a38c3a1d9d94ad303a6/resources/Makefile.include#L268-L275) hence my confusion

**Comment by ljden** [comment]
@omichel I've edited the documentation in a fork and am making a PR, should that go into master?

**Comment by omichel** [comment]
Yes.
