### ISSUE TITLE
Improve description of spot robot world

### ISSUE THREAD

**Issue by stefaniapedrazzi** [cyberbotics/webots#1848]
The Spot simulation is part of the Guided Tour, but the description and title doesn't match the other worlds in the Guided Tour.

Tasks:
1. Improve description in `WorldInfo.info` (currently simply "Spot Robot")
2. Adjust `WorldInfo.title` to be coherent with others (just keep the robot name, remove '.' at the end of the sentence, etc.)

Maybe it would also be simply enough to switch the  `WorldInfo.info` and `WorldInfo.title` values.

**Comment by DavidMansolino** [comment]
Fixed in #1913
