### ISSUE TITLE
touch sensor didn't work in webots_ros (complete_test example) and how to add touch sensor for gripper?

### ISSUE THREAD

**Issue by ipa-rwu** [cyberbotics/webots#1849]
Hello,

I want to add a touchsensor at the endpoint of gripper. But it doesn't work.
So I tried the example complete_test in webots_ros package. Basiclly, what I did is:

- start the world: complete_test.wbt
- put a object next to touch sensor
- call touchsensor service: `rosservice call /my_robot/touch_sensor/enable "value: 1"`
- Monitoring touchsensor topic: `rostopic echo /my_robot/touch_sensor/value`

I also tried:
- `roslaunch webots_ros complete_test.launch `
- and monitoring touchsensor topic: `rostopic echo /my_robot/touch_sensor/value`

I checked the document [https://cyberbotics.com/doc/reference/touchsensor?tab-language=c++#collision-detection](url)
I am wondering if if is because of "boundingObject" in touchsensor is null. As you can see this screenshot
![Screenshot from 2020-06-29 23-24-35](https://user-images.githubusercontent.com/54799760/86057639-d667ae80-ba5f-11ea-809d-21998c233103.png)

What I tried on gripper is:
![Screenshot from 2020-06-29 23-45-14](https://user-images.githubusercontent.com/54799760/86059224-9d7d0900-ba62-11ea-985d-bd24ea631b90.png)
But then it seems gripper can't work properly. 
![Screenshot from 2020-06-29 23-46-08](https://user-images.githubusercontent.com/54799760/86059288-bbe30480-ba62-11ea-96fd-1ad6c106ff30.png)

Thanks in advance.

**Comment by omichel** [comment]
Can you please upload a ZIP including your world file and proto file so that I can try to reproduce the problem?

**Comment by ad-daniel** [comment]
I'm closing this for now, feel free to reopen it if you have additional issues.
