### ISSUE TITLE
connector_detach test sometimes failing

### ISSUE THREAD

**Issue by DavidMansolino** [cyberbotics/webots#1859]
**Describe the Bug**
The following test is sometimes giving False negative:
```
FAILURE with connector_detach: Connectors should not be detached when applying a force < 2.1 N.
```

**Comment by DavidMansolino** [comment]
One more here: https://travis-ci.com/github/cyberbotics/webots/jobs/357446537#L8711

**Comment by DavidMansolino** [comment]
One more here: https://travis-ci.com/github/cyberbotics/webots/jobs/360665942#L8711

**Comment by BenjaminDeleze** [comment]
I think this test does not exist anymore and the `connector` test works in a stable way.
