### ISSUE TITLE
Assertion Failure on Windows Release

### ISSUE THREAD

**Issue by DavidMansolino** [cyberbotics/webots#1891]
**Describe the Bug**
It is not the first time (#1881) that a user is reporting an assertion failure with a release version of Webots on Windows.
In release mode, no assertion failure should be raised.

This is not good, not only because we raise assertions for the end-user, but also because it means that the assertions are evaluated even in release mode (which impacts the performance).

**Comment by omichel** [comment]
Fixed in #1934.
