### ISSUE TITLE
Fix "controllerArgs" tyep in test suite worlds 

### ISSUE THREAD

**Issue by stefaniapedrazzi** [cyberbotics/webots#1906]
The `Robot.controllerArgs` field has been changed from SFString to MFString.
All the occurrences have been updated but the test worlds.

In the test worlds, the "controllerArgs" is usually used to passed the controller name, but this is probably no longer necessary.
So we could take the opportunity to check if the "controllerArgs" are still needed and remove it.

**Comment by omichel** [comment]
Note that putting the brackets around a MFString list of a single element is optional. Therefore all the test worlds are syntactically correct with respect to `Robot.controllerArgs`.
