### ISSUE TITLE
Pop Alert Window Buttons Can't Respond

### ISSUE THREAD

**Issue by AlbusSong** [cyberbotics/webots#1944]
These buttons are unable to respond to user's click actions.

<img width="420" alt="Screen Shot 2020-07-20 at 5 51 06 PM" src="https://user-images.githubusercontent.com/47345588/87951891-d59bc880-cab1-11ea-85a9-0177c66b6a60.png">

**Comment by DavidMansolino** [comment]
Do you experience this only with these buttons or all of them?

**Comment by DavidMansolino** [comment]
I can indeed reproduce this with all the pop-up windows.

**Comment by omichel** [comment]
It seem to be a [known bug](https://bugreports.qt.io/browse/QTBUG-84879).

**Comment by AlbusSong** [comment]
Oh, would have to wait a bit long. 
So what should I do to avoid this bug?
Or you will do something to fix it before August 20th?

**Comment by omichel** [comment]
Yes, we will fix it in the next couple of days (probably with Qt 5.14.2), so that you can use a nightly build that corrects the problem.

**Comment by DavidMansolino** [comment]
Here is the update PR #1736, I propose to simply rollback this PR while waiting for Qt 5.15.1

**Comment by AlbusSong** [comment]
OK, so fast.
So what I shall do now is just to wait for the merging of the **pr** on **master** branch, right?

**Comment by omichel** [comment]
On the **develop** branch, yes. Then, you will be able to download the next R2020b nightly build which will include the patch.
