### ISSUE TITLE
Segfault when reloading world without stopping animation recording

### ISSUE THREAD

**Issue by JennyLynnFletcher** [cyberbotics/webots#1956]
Webots crashes with a segfault when reloading world while recording animation

**Steps to Reproduce**
1. File -> Make HTML Animation **or** call to `supervisor.animationStartRecording()`
2. Click reload world button before clicking File -> Stop HTML Animation or `supervisor.animationStopRecording()`

**System**
 - Operating System: Linux EndeavourOS
 - Graphics Card: NVIDIA GeForce GTX 1660 SUPER

(Has also been encountered on other systems which I don't have details of)

**Comment by omichel** [comment]
Thank you for this bug report. I can indeed reproduce the crash on Windows as well.
