### ISSUE TITLE
Worlds throwing errors

### ISSUE THREAD

**Issue by stefaniapedrazzi** [cyberbotics/webots#1966]
I started to test all the distributed worlds (same order as in the Open Sample World dialog). Here are the ones that throw errors:
* [x] inverse_kinematics.wbt:
```
INFO: inverse_kinematics: Starting controller: python3 -u inverse_kinematics.py
INFO: valve_turner: Starting controller: python3 -u valve_turner.py 15.7079632679
INFO: valve_turner: Starting controller: python3 -u valve_turner.py 15.7079632679
Draw a circle on the paper sheet...
Traceback (most recent call last):
  File "inverse_kinematics.py", line 96, in <module>
    ikResults = armChain.inverse_kinematics([x, y, z])
  File "/usr/local/lib/python3.6/dist-packages/ikpy/chain.py", line 102, in inverse_kinematics
    raise ValueError("Your target must be a 4x4 transformation matrix")
ValueError: Your target must be a 4x4 transformation matrix
WARNING: 'inverse_kinematics' controller exited with status: 1.
```

* [x] e-puck_kinematic.wbt: this warning is displayed at each controller loop step
```
WARNING: E-puck (PROTO) > DEF EPUCK_ACCELEROMETER Accelerometer: Parent of Accelerometer node has no physics: measurements may be wrong.
```

* [x] ipr_collaboration.wbt: it blocks when picking the second box

* [x] altino.wbt: runs extremely slow (only 0.5x on my desktop PC)

* [x] highway_overtake.wbt:
```
Error: wb_supervisor_field_set_sf_vec3f() called on a read-only PROTO internal field.
```

*  [ ] motor.wbt: prints this error a couple of times
```
WARNING: The current physics step could not be computed correctly. Your world may be too complex. If this problem persists, try simplifying your bounding object(s), reducing the number of joints, or reducing WorldInfo.basicTimeStep.
```

* [x] curriculum novice and beginner worlds: cannot open botstudio:
```
Error: libqt_utils.so: cannot open shared object file: No such file or directory (dynamic library)
Error: robot window initialization failed
Error: Cannot load the "/home/stefi/webots/projects/robots/gctronic/e-puck/plugins/robot_windows/botstudio/libbotstudio.so" robot window library.
```

* [x] highway_driving.wbt (same issue as highway_overtake.wbt):
The problem comes from WbSupervisorUtilities, where it is not correctly detected that the robot node is visible from the scene tree.
```
Traceback (most recent call last):
  File "sensors_visualization.py", line 38, in <module>
    for i in range(childrenField.getCount()):
AttributeError: 'NoneType' object has no attribute 'getCount'
WARNING: 'sensors_visualization' controller exited with status: 1.
```

**Comment by DavidMansolino** [comment]
About ``inverse_kinematics``, which version of the `ikpy` module are you using?
You are probably not using the latest one (see #1782)

**Comment by stefaniapedrazzi** [comment]
Yes, probably I don't have the latest version. But it should not only be checked if ikpy is installed but also that the version is the expected one.

**Comment by stefaniapedrazzi** [comment]
I just completed opening and running all the worlds.

My ikpy version is 2.3.2.

**Comment by stefaniapedrazzi** [comment]
I will start fixing the problem with the internal proto flag for Supervisor *self* node.

**Comment by stefaniapedrazzi** [comment]
`motor.wbt` seems quite unstable.
I tried to change the masses of the solids and I could reduce the number of ODE errors printed, but as soon as the top face of the cylinder touches the face of the box and error remains.
