### ISSUE TITLE
`laser_pointer.wbt` red spots not displayed in the main view

### ISSUE THREAD

**Issue by stefaniapedrazzi** [cyberbotics/webots#1969]
The red spots of the `laser` DistanceSensor are displayed in the camera but not in the 3D view

![laser_pointer](https://user-images.githubusercontent.com/5910449/88260360-8083d080-ccc4-11ea-8f05-0f4d8037de6e.png)

I tested on Ubuntu 18.04 (development system and VM)

**Comment by DavidMansolino** [comment]
Same on macOS.

**Comment by omichel** [comment]
Same on Windows.
