### ISSUE TITLE
New consoles are wrongly added on movie creation

### ISSUE THREAD

**Issue by stefaniapedrazzi** [cyberbotics/webots#1972]
When creating a movie (just after clicking the stop recording button and choosing the file name), additional consoles are open.

Steps to reproduce:
1. open for example `languages/python/worlds/example.wbt`
2. start the simulation and record a movie
3. stop simulation and stop recording
4. choose file name
-> some new consoles appears

If you have just one opened console, then one new one appears (total 2).
If you have two open consoles, then two new consoles appear (total 4).

**Comment by DavidMansolino** [comment]
Duplicated with #1970
