### ISSUE TITLE
highway_driving controller error

### ISSUE THREAD

**Issue by DavidMansolino** [cyberbotics/webots#1977]
**Describe the Bug**
The highway_driving supervisor controller is raising many times this error:
`Error: wb_supervisor_field_set_sf_vec3f() called on a read-only PROTO internal field.`

The first issue is this one:
`Error: wb_supervisor_field_import_mf_node_from_string() called on a read-only PROTO internal field.`

However, this field is visible in the scene-tree.

**Comment by stefaniapedrazzi** [comment]
Also reported here #1966

**Comment by stefaniapedrazzi** [comment]
`highway_overtake` is throwing the same error.
