### ISSUE TITLE
Small note about VirtualBox and OpenGL

### ISSUE THREAD

**Issue by lukicdarkoo** [cyberbotics/webots#1982]
**Documentation page(s) concerned**
https://www.cyberbotics.com/doc/guide/general-bugs

**Describe how you would fix it**
It is good that OpenGL support in VirtualBox is mentioned. However, I would prefer a few more details. A small note that VirtualBox with `Enable 3D Acceleration` acceleration will provide OpenGL 2.2 support that is not sufficient for Webots to work would be handy. Users should disable `Enable 3D Acceleration` option.

**Comment by omichel** [comment]
@lukicdarkoo: could you make a proposal (PR) for such a note?

**Comment by lukicdarkoo** [comment]
Sure!
