### ISSUE TITLE
E-puck robot window produces an error message on Enable All

### ISSUE THREAD

**Issue by lukicdarkoo** [cyberbotics/webots#1983]
**Steps to Reproduce**
1. Add e-puck proto to the world
2. Double click on the robot
3. Click "Enable All"
4. See error in console: `Error: wb_distance_sensor_enable(): invalid device tag.`

**Expected behavior**
It should work without errors

**Screenshots**
![image](https://user-images.githubusercontent.com/2135826/88284445-b6897a80-cced-11ea-829f-a87f66886520.png)

**System**
 - Operating System: Linux Ubuntu 20.04
 - Graphics Card: Intel UHD Graphics 620

**Comment by DavidMansolino** [comment]
I can indeed reproduce this when the version is set to `1`.

**Comment by omichel** [comment]
I assume this should have been closed by #1989.
