### ISSUE TITLE
Multiple issues with LiDAR

### ISSUE THREAD

**Issue by lukicdarkoo** [cyberbotics/webots#1985]
**Describe the Bug**
HokuyoUtm30lx sensor shows wrong readings.

**Steps to Reproduce**
1. Run `webots /snap/webots/x1/usr/share/webots/projects/samples/devices/worlds/hokuyo.wbt`
2. Check the screenshots for incorrect behaviours

**Screenshots**
Default
![image](https://user-images.githubusercontent.com/2135826/88286631-572d6980-ccf1-11ea-9a88-f2833c410222.png)
Default, no changes in the world.

`minRange`
![image](https://user-images.githubusercontent.com/2135826/88287842-2fd79c00-ccf3-11ea-8496-dc5207f16ba3.png)
If we assume that the blue circle is `minRange` something is not correct according to the display in the up-left corner.

`noise` 
![image](https://user-images.githubusercontent.com/2135826/88289191-294a2400-ccf5-11ea-9ac6-efd550943a23.png)
Noise is set to 0.005 meaning that the standard deviation is 15cm. Distances shown on the display, that represent the distance to the green box, are sometimes huge.
This is most likely related to #1784 

**System**
 - Operating System: Linux Ubuntu 20.04
-  Graphics Card: Intel UHD Graphics 620

**Comment by DavidMansolino** [comment]
> Default, no changes in the world, laser rays are not visible even though Show Lidar Rays Paths is on. There are some lines, but no rays (although I am not sure what I am supposed to see). Also, no point cloud when Show Lidar Point Cloud. According to the documentation, I think I should see rays and points: https://cyberbotics.com/doc/guide/the-user-interface

You don't see the point-cloud even if enabled in the optional rendering because the point-cloud mode the lidar is not enabled. To test point-cloud optional rendering, check the devices/lidar simulation.

**Comment by lukicdarkoo** [comment]
@DavidMansolino Sorry, this is my bad, I will edit the issue.
