### ISSUE TITLE
Issue with webots_ros::node_get_orientation for identity orientation between object and world

### ISSUE THREAD

**Issue by s-trinh** [cyberbotics/webots#1986]
Please find attached a Webots world and the ROS code to get the pose of an object using the `webots_ros` supervisor functionality.

When the orientation of the cube is equal to the world coordinates system, the returned orientation using `webots_ros::node_get_orientation` gives a wrong orientation.

The orientation should be identity while it gives:
```
  -1    0    0
   0    1    0
   0    0   -1
   0    0    0
```

The received quaternion is `geometry_msgs::Quaternion (w, x, y, z): 0 0 1 0` while it should be `1 0 0 0`.

As soon as you change slightly the orientation of the object, the returned orientation is correct. If you set the orientation to `1 0 0 0` in quaternion, the received orientation is wrong again.

Observed with Webots R2020b.

I have also added a video that shows the issue.

[Orientation_issue.zip](https://github.com/cyberbotics/webots/files/4967392/Orientation_issue.zip)

**Comment by DavidMansolino** [comment]
You're right, it seems there is some issues on the conversion from matrix to quaternion here:
https://github.com/cyberbotics/webots/blob/develop/projects/default/controllers/ros/RosMathUtils.cpp#L17
