### ISSUE TITLE
Get a NodeRef from a DeviceTag.

### ISSUE THREAD

**Issue by DavidMansolino** [cyberbotics/webots#1992]
It would be useful (requested by several users) to be able to get the node ref of a device, with a function like this:
```C
WbNodeRef wb_supervisor_node_get_from_tag(WbDeviceTag tag)
```

**Comment by omichel** [comment]
I assume you mean:
```C
WbNodeRef wb_supervisor_node_get_from_tag(WbDeviceTag tag)
```

**Comment by Simon-Steinmann** [comment]
Please implement this! Exactly what I need.

**Comment by DavidMansolino** [comment]
We will, just after the release of Webots R2020b that we are currently finalizing.
