### ISSUE TITLE
New solid falls down from the table.

### ISSUE THREAD

**Issue by xxchenchen** [cyberbotics/webots#1995]
**Describe the Bug**
My new solid falls down from the table.
[ Moreover I cant hold them by robot hand. It is not solid. Hand moves into the box.]

**Steps to Reproduce**
1. Go to 'add solid.' 
2. Move into the children 'your solids.' (Solid from new 3d models)
3. Select bounding object is a box
4- Select physic physic
5. error: My new solid falls down from the table. Moreover it is invisible not solid. Robot does not grasp it.

**Expected behavior**
It is expected that it is on the table not under. Moreover robot grasp it.

**Screenshots**

**System**
Windows and Ubunutu
webots 2020a and 2002b
Nvdia

![1](https://user-images.githubusercontent.com/48223944/88474798-b1693d00-cf32-11ea-8bf7-e6131bcaed0a.jpeg)
![2](https://user-images.githubusercontent.com/48223944/88474799-b29a6a00-cf32-11ea-8d1c-7ebb4e98b59f.jpeg)
![3](https://user-images.githubusercontent.com/48223944/88474800-b3330080-cf32-11ea-9282-24fa8b1c014e.jpeg)
![4](https://user-images.githubusercontent.com/48223944/88474801-b3cb9700-cf32-11ea-9505-d34f5cabc136.jpeg)

**Comment by DavidMansolino** [comment]
From the error message in your 3rd screenshot, it seems the 'kutu' Solid node misses a bounding object, which seems to be contradictory with what is visible in the last screenshot, is it the same simulation?

**Comment by xxchenchen** [comment]
That is same simulation. Thanks

**Comment by xxchenchen** [comment]
![clean_world](https://user-images.githubusercontent.com/48223944/88517056-eb9c1280-cff6-11ea-9a92-4acc2cb0da46.jpeg)
That is clean world. That inlcludes just one kutu solid.

**Comment by xxchenchen** [comment]
![clean_1](https://user-images.githubusercontent.com/48223944/88517484-9280ae80-cff7-11ea-92b9-a7183f9fa4d5.jpeg)

**Comment by DavidMansolino** [comment]
Can you please share the world file?

**Comment by xxchenchen** [comment]
I sent it.

**Comment by DavidMansolino** [comment]
There are several problem in your world file:
  - If you define the mass you have to set the density to -1.
  - Your bounding object is clearly too WAY too small 0.001 * 0.001 => 0.001 mm for the side of the box.

**Comment by xxchenchen** [comment]
![webots2](https://user-images.githubusercontent.com/48223944/88547013-d2f72100-d025-11ea-8de1-fe47caef5a5f.jpeg)

**Comment by xxchenchen** [comment]
density=-1 mass=0.5 boudnary size 0.15 0.15 0.04

I obtained errror. Why?

**Comment by xxchenchen** [comment]
![image](https://user-images.githubusercontent.com/48223944/88593050-a19f4500-d067-11ea-9d3b-534d84948689.png)
There is no error. However, the box falls down.
