### ISSUE TITLE
Mirroring Lidar output

### ISSUE THREAD

**Issue by SherlockSheep** [cyberbotics/webots#2027]
When I used webots with ROS, I got mirroring Lidar output when I viewed the scan topic in rviz, as can be seen at 6:12 in [video](https://www.youtube.com/watch?v=xRvFJDuhx3Y).

To make sure that the problem is not specific-sensor-related, I tried HokuyoUtm30lx and Sick LMS291,  and I met the same problem. I wonder why this happens and how I can fix it.

**Comment by DavidMansolino** [comment]
You're right, the scan seems to be inversed, we will fix this for the next version of Webots that will be released soon.

**Comment by DavidMansolino** [comment]
The problem is actually due to the fact that the Webots and RVIZ coordinate systems are not equivalent.
The Webots X-axis becomes -Y in RVIZ.
The Webots Y-axis becomes Z in RVIZ.
The Webots Z-axis becomes -X in RVIZ.

**Comment by SherlockSheep** [comment]
For velodyne VLP-16, I could tell :
> The Webots X-axis becomes -Y in RVIZ.
> The Webots Y-axis becomes Z in RVIZ.
> The Webots Z-axis becomes -X in RVIZ.

But for those single-line Lidars, the coordinate systems seemed to be weird.

**Comment by SherlockSheep** [comment]
@DavidMansolino Thanks for replying. 
For velodyne VLP-16, I could tell :
> The Webots X-axis becomes -Y in RVIZ.
> The Webots Y-axis becomes Z in RVIZ.
> The Webots Z-axis becomes -X in RVIZ.

But for those single-line Lidars, the coordinate systems seemed to be weird.

**Comment by DavidMansolino** [comment]
The coordinate system should be the same for the multi-lines and single-line lidars.
What difference do you see between them?

**Comment by SherlockSheep** [comment]
Sorry my bad, I should post my screenshots.

This is how I placed Velodyne VLP-16:
![VLP16_POS](https://user-images.githubusercontent.com/26016629/88799258-c49d3680-d1d8-11ea-8ce1-d1f22c769e8f.png)

This is how I placed HokuyoUtm30lx:
![Hokuyo_POS](https://user-images.githubusercontent.com/26016629/88799351-ee565d80-d1d8-11ea-97b9-36ce7a949018.png)

And I got these in rviz:
![output](https://user-images.githubusercontent.com/26016629/88799400-0201c400-d1d9-11ea-8de1-7abee1302c12.png)

**Comment by SherlockSheep** [comment]
In the third picture,:
z axis points toward the screen for the HokuyoUtm30lx rviz visualization.
z axis points outward the screen for the VLP-16 rviz visualization.
