### ISSUE TITLE
Fpv camera won't reload

### ISSUE THREAD

**Issue by ST33LDI9ITAL** [cyberbotics/webots#2049]
I saved world state after closing the fpv camera in the mavic demo by clicking the X in corner and then it wouldn't reload after reloading world. Couldn't find a way to manually get it to open on sim screen again.

**Comment by DavidMansolino** [comment]
You can re-open it from the overlay menu: https://cyberbotics.com/doc/guide/the-user-interface#overlays-menu

**Comment by ST33LDI9ITAL** [comment]
Just saw in discord. Thanks,  thought I went all through menus but guess I skipped over it somehow.
