### ISSUE TITLE
Cleanup 'src' and 'scripts' directories

### ISSUE THREAD

**Issue by DavidMansolino** [cyberbotics/webots#2065]
**Describe the Bug**
Both directories contain scripts.
We should move all the scripts in the 'scripts' directory:
  - src/bin => scripts/new_version
  - src/install_scripts => scripts/install
  - src/packaging => scripts/packaging. (for this last one it is more arguable)

**Comment by omichel** [comment]
While at it, I would move `src/lib/Controller` to `src/controller`
