### ISSUE TITLE
Segmentation error when changing the type of the floor

### ISSUE THREAD

**Issue by agayev169** [cyberbotics/webots#2085]
I was following the official [tutorials](https://cyberbotics.com/doc/guide/tutorial-2-modification-of-the-environment) and after creating a floor, I tried to change its type. When changing the type of the floor to any other value different from the default (chequered) I always get the following error:
```/usr/local/bin/webots: line 88:  5916 Segmentation fault      (core dumped) "$webots_home/bin/webots-bin" "$@"```

My OS is Ubuntu 18.04, no graphics card.

**Comment by stefaniapedrazzi** [comment]
Which version of Webots are you using?

We fixed many related issues in the latest Webots R2020b.
If you are using a previous version, could you please check if you get the same errors on Webots R2020b?

**Comment by agayev169** [comment]
I am using Webots R2020b.

**Comment by stefaniapedrazzi** [comment]
I will properly fix the issue as soon as possible.

But probably the changes in #2084 should already prevent this issue to arise in case of the Floor PROTO.

**Comment by agayev169** [comment]
I read PROTO files both for Floor and RectangleArena. As far as I understood, the variable ```floorTextureUrl```, whose problem is described in #2084 is the same as ```texture``` in Floor PROTO file. However, the same code pattern is used in the Floor.PROTO file [here](https://github.com/cyberbotics/webots/blob/323d9231584325b0da9106c2bea2f91a90199df7/projects/objects/floors/protos/Floor.proto#L29-L32).

**Comment by agayev169** [comment]
FYI: I tried to modify the world file where I changed the type value of a Floor object and it worked. I thought it may help during debugging.

**Comment by stefaniapedrazzi** [comment]
Yes, it should be sufficient to remove the deprecated fields warning in the PROTO file to let it work.

This will workaround the issue in this particular case. I found the source of the issue but may take some time to correctly fix it and test it.
