### ISSUE TITLE
Add ODE 'rho' Parameter to ContactProperties

### ISSUE THREAD

**Issue by Simon-Steinmann** [cyberbotics/webots#2086]
Adding the rho parameters (see link) to the ContactProperties will enable common simulation scenarios like wheel slippage and sliding objects
http://ode.org/wiki/index.php?title=Manual#Contact

**Comment by omichel** [comment]
@ad-daniel: I am closing this issue as I believe it was fixed in #3771. Feel free to re-open if needed.
