### ISSUE TITLE
The problem of buliding omni wheel robot

### ISSUE THREAD

**Issue by huiduan-25** [cyberbotics/webots#2090]
I try to build an omnidirectional robot  with 6 omni wheels. After assembly, there is only one rotational motor shown on the graph, I have no idea what part is wrong. Could you please help me?

Thank you

**Comment by huiduan-25** [comment]
![image](https://user-images.githubusercontent.com/69326215/89584029-43c2e800-d833-11ea-801c-86580ed34428.png)

**Comment by DavidMansolino** [comment]
Did you set different names for each motor or did you leave the default one?

**Comment by huiduan-25** [comment]
> Did you set different names for each motor or did you leave the default one?

Hi，David
Each motor has the individual name from Wheel1 to Wheel6. But also，I am confused about why the name on the graph is rotational motor 0.

**Comment by DavidMansolino** [comment]
Can you share the world file here?

**Comment by huiduan-25** [comment]
Dear Mr. David

Hope this email finds you well.

I have attached the world file here. I appreciate your kind help.

Best wishes

huiduan-25
________________________________
发件人: David Mansolino <notifications@github.com>
发送时间: 2020年8月7日 08:50
收件人: cyberbotics/webots <webots@noreply.github.com>
抄送: huiduan-25 <xiaofeixiaaxy@outlook.com>; Author <author@noreply.github.com>
主题: Re: [cyberbotics/webots] The problem of buliding omni wheel robot (#2090)


Can you share the world file here?

―

**Comment by huiduan-25** [comment]
[try 9.zip](https://github.com/cyberbotics/webots/files/5040276/try.9.zip)
Hi, I am not sure if the file from the outlook is available. I attach the file here as well.

Thank you

**Comment by huiduan-25** [comment]
Dear Mr. David

I just attach the zip file in the email.

best wishes

hudiaun-25

________________________________
发件人: David Mansolino <notifications@github.com>
发送时间: 2020年8月7日 08:50
收件人: cyberbotics/webots <webots@noreply.github.com>
抄送: huiduan-25 <xiaofeixiaaxy@outlook.com>; Author <author@noreply.github.com>
主题: Re: [cyberbotics/webots] The problem of buliding omni wheel robot (#2090)


Can you share the world file here?

―

**Comment by DavidMansolino** [comment]
You set the DEF name but not the actual name, you have to define the ``name`` field of the ``RotationalMotor`` nodes.

**Comment by huiduan-25** [comment]
Dear Mr. David

That is really helpful！The problem has been solved！I can see full 6 graphs now. But I am not sure what the meaning of the 0 represents in the picture.
[cid:dc8a8a6c-e1cf-4977-950a-e244db92a275]
Once the world is run, the robot starts to the rotation movement, to make the robot move forward, should I apply the controller to the robot.  Is that possible I can refer the controller code of omniwheel from Github.

Appreciate again for your help.

Best wishes

huiduan-25

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: David Mansolino <notifications@github.com>
发送时间: Friday, August 7, 2020 10:32:29 AM
收件人: cyberbotics/webots <webots@noreply.github.com>
抄送: huiduan-25 <xiaofeixiaaxy@outlook.com>; Author <author@noreply.github.com>
主题: Re: [cyberbotics/webots] The problem of buliding omni wheel robot (#2090)


You set the DEF name but not the actual name, you have to define the name field of the RotationalMotor nodes.

―

**Comment by DavidMansolino** [comment]
0 is the current target position.

About controlling the robot, I would strongly recommend following the tutorials, in particular this one: https://www.cyberbotics.com/doc/guide/tutorial-4-more-about-controllers

**Comment by huiduan-25** [comment]
That is great! Thank you for your help!

huiduan-25
________________________________
发件人: David Mansolino <notifications@github.com>
发送时间: 2020年8月7日 10:49
收件人: cyberbotics/webots <webots@noreply.github.com>
抄送: huiduan-25 <xiaofeixiaaxy@outlook.com>; Author <author@noreply.github.com>
主题: Re: [cyberbotics/webots] The problem of buliding omni wheel robot (#2090)


0 is the current target position.

About controlling the robot, I would strongly recommend following the tutorials, in particular this one: https://www.cyberbotics.com/doc/guide/tutorial-4-more-about-controllers

―
