### ISSUE TITLE
MJPEG streaming not working with local streaming viewer

### ISSUE THREAD

**Issue by omichel** [cyberbotics/webots#2093]
When starting Webots in stream mode and connecting with the local streaming viewer, the X3D mode works fine, but the MJPEG one doesn't:
```
ERROR: Streaming server: Unsupported message: mjpeg: 1215x728.
```

**Comment by stefaniapedrazzi** [comment]
Do you mean using the `resources/web/streaming_viewer/index.html`?

It works fine for me on Linux in a branch based to a prior master branch.
So it the issue be introduced in #2077?

**Comment by omichel** [comment]
> Do you mean using the resources/web/streaming_viewer/index.html?

Yes.

> It works fine for me on Linux in a branch based to a prior master branch.
> Has the issue been introduced in #2077?

OK, thank you for the test. I will check.

**Comment by omichel** [comment]
It works actually on the master branch as well.
The reported error message appears only if you forget to specify `mode=mjpeg` when starting Webots with the `--stream` option, which is fine. I will maybe try to improve it a little bit, so that it's clear how to fix it.
