### ISSUE TITLE
Why helicoidalRoadSegment node has two roadBorderWidth field ?

### ISSUE THREAD

**Issue by qingliuql** [cyberbotics/webots#2097]
**Describe the Bug**

   When I add a helicoidalRoadSegment node in my world, I find that two roadBorderWidth field exist in the first line and following line. So, when I set one of the two field, the borderwidth changes exactly. But, when I save the world and Reload world, the helicoidalRoadSegment roadBorderWidth changes back to the default value.

**Steps to Reproduce**

1. Open a world,
2. Click to add new proto node helicoidalRoadSegment,
3. set the value of roadBorderWidth (one of them or two) in the field, 
4. save and reload world,
5. roadBorderWidth changes back to the default value and see the error:
#Duplicated definition of field roadBorderWidth in the instance of PROTO HelicoidalRoadSegment.

**Expected behavior**
I hope I can set the roadBorderWidth value and save it in the world. Reload world, roadBorderWidth value doesn't change, Thank you!

**Screenshots**
![screen](https://user-images.githubusercontent.com/69410316/89724716-442cd000-da39-11ea-9634-62c318b2ddac.png)

**System**
 - Operating System: Windows 10
 - Graphics Card: NVIDIA GeForce GTX950M,

**Comment by DavidMansolino** [comment]
Thank you for this bug report, this is a bug, I just fixed it in #2099.
The fix will be available in the nightly build from tomorrow:
https://github.com/cyberbotics/webots/releases
