### ISSUE TITLE
Python ImportError: dynamic module does not define module export function

### ISSUE THREAD

**Issue by JasonLrh** [cyberbotics/webots#2098]
On Mac 10.15.6, Webots 2020B, brew python@3.8.5
>Traceback (most recent call last):
  File "walk.py", line 2, in <module>
    from controller import Robot,Camera
  File "/Applications/Webots.app/lib/controller/python38/controller.py", line 31, in <module>
    import _controller
ImportError: dynamic module does not define module export function (PyInit__controller)
WARNING: 'walk' controller exited with status: 1.  

and the env of mine is 
>$ echo $WEBOTS_HOME 
/Applications/Webots.app

When I use 2020a, I can go to the `Applications/Webots.app/lib/controller/python` to rebuild the lib. but in 2020b, this directory is no longer exist. How can I correctly import controller module?

ps: the front of my code is below
~~~python
#!/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/bin/python3.8
import os
import sys

for i in sys.path:
    print(i)
import cv2 as cv

libraryPath = os.path.join(os.environ.get("WEBOTS_HOME"), 'projects', 'robots', 'robotis', 'darwin-op', 'libraries',
                           'python37')
libraryPath = libraryPath.replace('/', os.sep)
sys.path.append(libraryPath)
from managers import RobotisOp2GaitManager, RobotisOp2MotionManager
from controller import Robot,Camera
~~~

**Comment by DavidMansolino** [comment]
> When I use 2020a, I can go to the Applications/Webots.app/lib/controller/python to rebuild the lib. but in 2020b, this directory is no longer exist. How can I correctly import controller module?

You should simply add the python version at the end of the path.

**Comment by JasonLrh** [comment]
> You should simply add the python version at the end of the path.  

but I can use python3(python3.8) directly in the Terminal. Does it means I've added the python in the PATH

**Comment by DavidMansolino** [comment]
Yes, however on mac terminal PATH and Application PATH might differ, are you starting Webots from the terminal or from the icon?
In any case on macOS it is strongly recommended to set the full path to the python executable in the Webots preferences:
https://cyberbotics.com/doc/guide/preferences#general

**Comment by JasonLrh** [comment]
> Yes, however on mac terminal PATH and Application PATH might differ, are you starting Webots from the terminal or from the icon?
> In any case on macOS it is strongly recommended to set the full path to the python executable in the Webots preferences:
> https://cyberbotics.com/doc/guide/preferences#general

I add the acture python path in the head of PATH. Nothing changed. I've solved those problem in 2020a by rebuild them in `${WEBOTS_HOME}/lib/controller/python` but this directory disappear in 2020b.

The `_controller.so ` and `_vehicle.so ` do need to re-build for a slight platform changed. I've tried to re-build the `Webots` app but after generating there isn't a directory `${Webots_build_dir}/lib/controller/python*`

**Comment by DavidMansolino** [comment]
I just checked with a fresh installation of R2020b and I have the ``/lib/controller/python*`` folders, if you don't have them, maybe you should try re-installing the application:
![image](https://user-images.githubusercontent.com/2461619/89758565-6a5d7900-dae8-11ea-8008-ea4f0c00c278.png)

**Comment by JasonLrh** [comment]
> I just checked with a fresh installation of R2020b and I have the `/lib/controller/python*` folders, if you don't have them, maybe you should try re-installing the application:
> ![image](https://user-images.githubusercontent.com/2461619/89758565-6a5d7900-dae8-11ea-8008-ea4f0c00c278.png)

yes. my folder is same. I also have `python[num][num]`, but what I need is a source directory `python`

**Comment by DavidMansolino** [comment]
The sources are in `webots/resources/languages/python` (for the standard Webots Python API, but you will find similar path for extension (e.g. vehicle, darwin-op, etc.)).

**Comment by JasonLrh** [comment]
OK,I build all Webots source, and it works well now. Thanks.

**Comment by JasonLrh** [comment]
Done
