### ISSUE TITLE
rostopic echo /......./...../recognition_objects doesnt work: no message

### ISSUE THREAD

**Issue by SherlockSheep** [cyberbotics/webots#2114]
Hi. First I met the problem the same as [#1637](https://github.com/cyberbotics/webots/issues/1637) with webots 2020a, then I upgraded webots to 2020b.
This time when I try to echo /..../...../recognition_objects, the datatype/md5sum error's gone, but there's no message at all. Other topics works fine.
This is my screenshot, what i got by rostopic hz /..../...../recognition_objects.
![no_recog_info](https://user-images.githubusercontent.com/26016629/89995052-92510600-dcbb-11ea-9719-19db145ea558.png)

**Comment by SherlockSheep** [comment]
![pub_exist](https://user-images.githubusercontent.com/26016629/89997161-5a978d80-dcbe-11ea-90b6-50d1267cdd24.png)
Publisher exists.
And bounding boxes in webots' camera overlay looks fine.
Guys please help me.

**Comment by DavidMansolino** [comment]
I can indeed confirm the issue, we will have a look at it.

**Comment by DavidMansolino** [comment]
As a temporary workaround I just found that the `../camera/recognition_objects` topic is published if you subscribe to the `../camera/image` topis too.

**Comment by SherlockSheep** [comment]
@DavidMansolino You are right, it works.
Thank you very much!!  : )
