### ISSUE TITLE
Github Schedulded Action Runs only on master

### ISSUE THREAD

**Issue by DavidMansolino** [cyberbotics/webots#2126]
**Describe the Bug**
This condition here: https://github.com/cyberbotics/webots/blob/master/.github/workflows/test_suite.yml#L7, triggers build only on the master branch and therefore nightlies are created only from the master branch.

**Comment by DavidMansolino** [comment]
This doesn't seem to be supported now by Github Actions: https://github.community/t/scheduled-builds-of-non-default-branch/16306/15

**Comment by stefaniapedrazzi** [comment]
I think we can close this issue given that we already applied a workaround to created the nightlies also for the develop branch.
