### ISSUE TITLE
how do you display a point in space in GUI?

### ISSUE THREAD

**Issue by culurciello** [cyberbotics/webots#2136]
Hi, I need to mark a point in space in the GUI to debug. How can I do that?
Thanks a lot@
E

**Comment by DavidMansolino** [comment]
A simple solution is to add a Transform with a Shape with a Sphere as geometry.
Please use our Discord channel for such kind of questions: https://discord.com/invite/nTWbN9m

**Comment by culurciello** [comment]
thansk a lot
