### ISSUE TITLE
Noise becomes fixed patterned.

### ISSUE THREAD

**Issue by SherlockSheep** [cyberbotics/webots#2139]
Set noise field of Camera node to any positive value, for example 0.2, and start simulation. At the beginning image noise works fine, which is random noise in 3 channels: 
![freeze_noise0](https://user-images.githubusercontent.com/26016629/91001271-d61e0680-e5fd-11ea-90b8-52263c0da8e1.png)

But minutes later(simulation time), the image noise becomes fixed patterned, and is only black-and-white:
![freeze_noise1](https://user-images.githubusercontent.com/26016629/91001452-4dec3100-e5fe-11ea-9402-f819f69adef2.png)

Lidar noise suffers from the same issue.

This issue exists on both 2020a-rev1 and 2020b-rev1-nightly-build. I tested with ubuntu 16.04 and ROS kinetic.

**Comment by DavidMansolino** [comment]
I just tried and for me, it seems to work fine (after 1hour of simulation time):

![pioneer3at](https://user-images.githubusercontent.com/2461619/91012247-107ba980-e5e6-11ea-8342-54a58659ab77.png)

What is your GPU? Can you give us the output of the 'webots --sysinfo' command?

**Comment by SherlockSheep** [comment]
$ webots --sysinfo
System: Linux 4.15.0-107-generic x86_64
Processor: Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz
Number of cores: 8
OpenGL vendor: NVIDIA Corporation
OpenGL renderer: GeForce RTX 2080/PCIe/SSE2
OpenGL version: 4.6.0 NVIDIA 440.100

**Comment by SherlockSheep** [comment]
By the way, I'm trying to make a transparent wall to test my sonar application, which should be seen by Lidar. I made a `Solid` with Box `Shape`, and I set `appearance PBRAppearance` > `transparency` to 1. But the wall was still detected by Lidar. How could I accomplish my purpose?

**Comment by DavidMansolino** [comment]
Your configuration looks perfect. Can you identify an exact time or action that makes the noise looks like this?

To make the wall completely transparent, you should completely remove the Shape node.

**Comment by SherlockSheep** [comment]
Thank you! I shall post a screen recording video later.

**Comment by SherlockSheep** [comment]
@DavidMansolino 
Hi, I've post a video on youtube:
https://youtu.be/Yhu3B104F0M

**Comment by DavidMansolino** [comment]
Thank you for the video, I tried many times and unfortunately was not able to reproduce the issue.
Can you please try with a nightly build of Webots R2020b-rev1: https://github.com/cyberbotics/webots/releases

**Comment by SherlockSheep** [comment]
I tested Webots Nightly Build (25-8-2020) with the computer mentioned above (Ubuntu16.04+ROS Kinetic), the issue existed.
Then I tested with another computer (Ubuntu18.04+ROS Melodic), and the issue also existed.
This is the configuration of the second computer:
```
System: Linux 5.4.0-42-generic x86_64
Processor: AMD Ryzen 5 3600 6-Core Processor
Number of cores: 12
OpenGL vendor: NVIDIA Corporation
OpenGL renderer: GeForce RTX 2060/PCIe/SSE2
OpenGL version: 4.6.0 NVIDIA 440.100
```
Could it be relevant to OpenGL version?

**Comment by DavidMansolino** [comment]
Just to make sure I tried with the exact same OpenGL version:
```
System: Linux 5.4.0-42-generic x86_64
Processor: Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz
Number of cores: 4
OpenGL vendor: NVIDIA Corporation
OpenGL renderer: GeForce 940MX/PCIe/SSE2
OpenGL version: 4.6.0 NVIDIA 440.100
```

But I  still can't reproduce the problem, I don't have a lot more ideas to understand where does the problem come from. Do both of your computers use the same GPU?

**Comment by SherlockSheep** [comment]
No they are not the same. One of them is RTX 2080, the other one is RTX 2060.

**Comment by SherlockSheep** [comment]
@DavidMansolino 
Hi David, it seems that this issue is related to the GPU we are using.
My colleague helped trying on another computer, which has GTX 1080 and the OpenGL version is also 4.6.0. The noise worked perfectly fine.
So RTX 20 series are (maybe) to blame.

**Comment by DavidMansolino** [comment]
Hi @SherlockSheep, ok that's good that you were able to test with another kind of GPU, it seems to make sense now.
Unfortunately, I don't have any RTX 20.. GPU available to test right now, but if I am not wrong my colleague @stefaniapedrazzi has one and will be able to test this next week.

**Comment by SherlockSheep** [comment]
Thank you for your patient response. I have another question to ask: must Webots run with graphical interface? We want to use Webots on our server for CI testing. If Webots could run without graphical interface, there would be no bother installing one.

**Comment by DavidMansolino** [comment]
> I have another question to ask: must Webots run with graphical interface? We want to use Webots on our server for CI testing. If Webots could run without graphical interface, there would be no bother installing one.

It's a bit tricky, but yes, Webots can run without graphical interface, we use CI too and run Webots inside, we use a virtual framebuffer (XVFB) to run it.
We run it on Github Actions for example: https://github.com/cyberbotics/webots/blob/master/.github/workflows/test_suite_linux.yml#L63-L90
We also have an example using Travis if needed.

**Comment by DavidMansolino** [comment]
Note that we also plan to create a Github Action that will automatically install Webots in your Github Action environment to ease the use of Webots in GitHub Action, would this be useful for you?

**Comment by SherlockSheep** [comment]
Thank you! That's exactly what we need! : )

**Comment by stefaniapedrazzi** [comment]
I can reproduce the issues on my linux system with an RTX 2060 GPU.

Even at the beginning the noise is sometimes a fixed black and white pattern instead of random RGB (every 10/30 simulation steps). But when running the simulation the fixed pattern appears always more frequently.

**Comment by stefaniapedrazzi** [comment]
I suspect the issue comes from some floating point over-/under-flow handled differently in RTX GPUs and used to compute the pseudo random values.

What changed in RTX NVidia Turing GPUs is that they also support half floating point precision to speed up computations.
I'm now testing to find a way to fix it.

**Comment by stefaniapedrazzi** [comment]
Here is a post presenting a modified noise implementation that doesn't use the `sin` function and works correctly on my system.
http://byteblacksmith.com/improvements-to-the-canonical-one-liner-glsl-rand-for-opengl-es-2-0/

**Comment by DavidMansolino** [comment]
That looks good, I just tested on my computer (GTX 970) and works fine too.

**Comment by SherlockSheep** [comment]
Thank you @stefaniapedrazzi : )
