### ISSUE TITLE
Can i integrate my android application with webots simulator created?

### ISSUE THREAD

**Issue by IAmVyshak** [cyberbotics/webots#2147]
Hi Team

I have just started with webots and i am planning to simulate a robot cleaner (domestic robot) using webots. I have an android application that is used to pair with the physical robot and control the functionality. 

My question, can i use this webot simulator to connect/integrate with my android application so that i can perform the functionalities on the simulated robot from the android application.

**Comment by DavidMansolino** [comment]
If you plan to run Webots on a desktop computer and use your android application to communicate with the controller of the simulated robot, yes, this is for sure feasible.

**Comment by omichel** [comment]
For this kind of questions, please use our Discord channel, not GitHub.
