### ISSUE TITLE
Update ROS tutorial to mention ROS noetic

### ISSUE THREAD

**Issue by stefaniapedrazzi** [cyberbotics/webots#2165]
**Documentation page(s) concerned**
https://www.cyberbotics.com/doc/guide/tutorial-8-using-ros

**What is the problem with the current documentation?**
Currently the documentation specifies that only ROS `melodic` and `kinetic` are supported.

For example, on Ubuntu 20.04 / ROS noetic and python 3, the instruction to install `rosdep` is:
```
sudo apt-get install python3-rosdep
```

**Comment by omichel** [comment]
Fixed in #2178.
