### ISSUE TITLE
Python command in OSM importer demo

### ISSUE THREAD

**Issue by stefaniapedrazzi** [cyberbotics/webots#2173]
By default 'python' command doesn't seem to be defined on Ubuntu 20.04.
Alias doesn't work on bash scripts.
It would be good to use the PYTHON_COMMAND variable in the `importer_demo.sh` script so that the python command can be easily set by the user without modifying the file.

For example similarly to 
https://github.com/cyberbotics/webots/blob/b7ebc72b20f68693fd1339ef30bbf5817874fe60/projects/default/controllers/ros/Makefile#L38-L41

**Comment by DavidMansolino** [comment]
Maybe we can even use python3 command?
This script is now not compatible with python2 anymore (#2150).

**Comment by stefaniapedrazzi** [comment]
Yes, this will be much easier and will solve the issue I had.
