### ISSUE TITLE
Animation play/stop button not available on Safari/macOS.

### ISSUE THREAD

**Issue by DavidMansolino** [cyberbotics/webots#2175]
**Describe the Bug**
When opening an exported animation on macOS (safari), the play, stop and navbar are not visible.

**Comment by lukicdarkoo** [comment]
I have just tested on macOS Big Sur (11.0.1) and Webots R2020b rev1 and it seems to be working:
![image](https://user-images.githubusercontent.com/2135826/101379301-6a159480-38b4-11eb-945c-7c618b8f1920.png)

**Comment by omichel** [comment]
So, can we we close this issue?

**Comment by lukicdarkoo** [comment]
Yes
