### ISSUE TITLE
Mismatch between local simulation and recorded html animation

### ISSUE THREAD

**Issue by yuchen93** [cyberbotics/webots#2234]
**Describe the Bug**
Recorded html5 animation is different from the simulation. Object position lags behind moving gripper.

**Steps to Reproduce**
I created a html5 recording of a simulation but the animation is different from the local simulation. 

**Expected behavior**
In local simulation, everything looks normal. However, in the animation replay, when the gripper moves objects, the object's position lags behind the gripper's position. 

**Screenshots**
![1](https://user-images.githubusercontent.com/14132226/92978545-b425e000-f455-11ea-993b-1f91334f51f4.png)
![2](https://user-images.githubusercontent.com/14132226/92978547-b5efa380-f455-11ea-9f6b-f0d6ec616787.png)
![3](https://user-images.githubusercontent.com/14132226/92978550-b7b96700-f455-11ea-9c85-26b3e9c2aba6.png)

**System**
 - Operating System: Linux Ubuntu 20.04
 - Graphics Card: NVIDIA GeForce RTX 2080 11 GB

**Additional context**
I do have a lot of objects in the environment, that might be the issue since I had no problem with a different environment with less objects. I'd like to know if there is an easy fix (possibly from the html end) for this particular environment. 

Thanks

**Comment by stefaniapedrazzi** [comment]
Do you get this issue after jumping to a specific time during the animation replay or also when just starting the animation without moving manually the time slider?

Could you please share your simulation and your generated animation files (html, json, and x3d files)?

**Comment by yuchen93** [comment]
I get this without jumping time, you can see the html replay here: https://www.cs.utexas.edu/~yuchen93/trash-sorting-sim/html/trash_sorting_arena.html

Attached the project files here as well. You can find the created html, json and x3d in there. I removed the texture files to reduce file size. 

Thanks a lot for looking into this!

[belt_sorting_sim.zip](https://github.com/cyberbotics/webots/files/5257156/belt_sorting_sim.zip)

**Comment by yuchen93** [comment]
I tried to dynamically load the objects to reduce the number of total moving object but the resulting animation now does not even have the dynamically loaded objects.
![no_objects](https://user-images.githubusercontent.com/14132226/93929390-688af600-fce1-11ea-8956-361269090229.png)

**Comment by stefaniapedrazzi** [comment]
> I tried to dynamically load the objects to reduce the number of total moving object but the resulting animation now does not even have the dynamically loaded objects.

Adding objects dynamically is not supported in HTML animation mode.
Another option is to initially locate the object somewhere else on the floor but not on the conveyor belt (this is slowing down the simulation and increasing the size of the animation JSON file) and move objects on the conveyor belt only when needed.

I can reproduce the issue with your world and I'm now inspecting it.

**Comment by stefaniapedrazzi** [comment]
It is not the position of the objects (cans bottles) that is wrong, but the links of the UR robot that are no longer correctly aligned when the robotics arm moves.
This occurs with this particular controller but seems to work fine with the default `ure_can_grasper` controller.

**Comment by yuchen93** [comment]
OK! I'll look into fixing my controller. This issue does not show up in the local simulation though, why is that the case?

**Comment by stefaniapedrazzi** [comment]
There is clearly a bug somewhere when exporting the solid position. I'm still working on it.

**Comment by stefaniapedrazzi** [comment]
This bug should be fixed in #2266.
The patch will be included in the nightly build of Webots R2020b rev 2 starting from tomorrow (https://github.com/cyberbotics/webots/tags)
