### ISSUE TITLE
Inertia import and visualization requirements, and improve the simulation speed.

### ISSUE THREAD

**Issue by zapplelove** [cyberbotics/webots#2247]
### Feature request
+ I think the inertia of the robot has a big impact on the dynamics, but I have a complex simulate situation that I need the self-collision to get the force in which the touch sensor is in the robot, so I can't use the shape of the solid as the boudingObject(This will collide with the sensor and produce incorrect results. ). I need to use numerical values to give the inertia of the robot's member, but I don't know if that's right value. So I need a feature like Gazebo to see the inertia of the link.
+ Integrating `urdf2webots` functions into software and regenerate urdf file or sdf file.
+ The icon for Centroid visualization is too small.
+ When I simulate using the self-collision option, it is too slow.

**Comment by omichel** [comment]
> So I need a feature like Gazebo to see the inertia of the link.

Can you post a screenshot of what you mean here?

> The icon for Centroid visualization is too small.

Do you mean the cross displayed when activating `View / Optional Rendering / Show Center of Mass` is too thin?

**Comment by zapplelove** [comment]
> Can you post a screenshot of what you mean here?

In the Gazebo, you can use the `View/Center of Mass` and `inertias` to see if you set the right value. Here are some screenshots of my robot in the Gazebo:

> 
![image](https://user-images.githubusercontent.com/18183148/93578678-32433300-f9d0-11ea-8bf8-00243c36164d.png)
+ the original view of the robot foot link.
![image](https://user-images.githubusercontent.com/18183148/93578916-759da180-f9d0-11ea-8c36-4d42f3c5ec24.png)
+ the view of the foot link with its inertia.
![image](https://user-images.githubusercontent.com/18183148/93578988-877f4480-f9d0-11ea-9e8e-f9fb685239f6.png)
+ the view of the foot link with its center of mass.
> Do you mean the cross displayed when activating `View / Optional Rendering / Show Center of Mass` is too thin?

yes, it is.

**Comment by omichel** [comment]
Simply clicking on your robot (selecting it) should display the bounding objects used to compute the inertia:
![humanoid_marathon](https://user-images.githubusercontent.com/1264964/93581869-fee9af80-f9a1-11ea-8b1a-9edb1e0cf78c.png)

**Comment by zapplelove** [comment]
> Simply clicking on your robot (selecting it) should display the bounding objects used to compute the inertia:
> ![humanoid_marathon](https://user-images.githubusercontent.com/1264964/93581869-fee9af80-f9a1-11ea-8b1a-9edb1e0cf78c.png)

Yes, I know this. But if I give the inertia instead of `boundingObject`, it would display nothing in webots

**Comment by omichel** [comment]
> Yes, I know this. But if I give the inertia instead of boundingObject, it would display nothing in webots

I am not sure if it is possible to compute a inertia volume from an inertia matrix... Are you sure Gazebo uses only the inertia matrix to display these magenta boxes?

**Comment by zapplelove** [comment]
> I am not sure if it is possible to compute a inertia volume from an inertia matrix... Are you sure Gazebo uses only the inertia matrix to display these magenta boxes?

I think it is. Because if I modify the value in the `<inertial><inertia>` label, the box will change, but in webots, I need to change `boundingObject`, actually, sometimes, I don't want the collision in the body but just the inertia.

**Comment by omichel** [comment]
> I think it is. Because if I modify the value in the <inertial><inertia> label, the box will change

That looks weird... Are you sure this inertia tag doesn't contain any bounding object, just the inertia matrix? And are you sure the magenta box is only computed from the inertia matrix?

**Comment by zapplelove** [comment]
> > I think it is. Because if I modify the value in the  label, the box will change
> 
> That looks weird... Are you sure this inertia tag doesn't contain any bounding object, just the inertia matrix? And are you sure the magenta box is only computed from the inertia matrix?

The urdf2webots project has solved this problem, and It can use `inertia` label in the urdf file to import `inertiaMatrix` directly into webots, although it's not visualizable.

**Comment by zapplelove** [comment]
I still have a problem. If I have a force sensor in a link like this:
![image](https://user-images.githubusercontent.com/18183148/93694838-1e6c0e00-fb43-11ea-9d03-49b3fba7bee3.png)
How to add a `touchsenor` to get the right value of it? Or any solution to this?

**Comment by zapplelove** [comment]
> I still have a problem. If I have a force sensor in a link like this:
> ![image](https://user-images.githubusercontent.com/18183148/93694838-1e6c0e00-fb43-11ea-9d03-49b3fba7bee3.png)
> How to add a `touchsenor` to get the right value of it? Or any solution to this?

There is a `positionsensor` of the joint, why not a `forcesensor` of it?

**Comment by zapplelove** [comment]
> ![image](https://user-images.githubusercontent.com/18183148/93694838-1e6c0e00-fb43-11ea-9d03-49b3fba7bee3.png)

I try this method:
+ set the `boundingObject` of a `Group` of `Cylinder`s with different `Translation`s
+ add a `SliderJoint` and set `minStop/maxStop`'s value of 0.001;
+ add a `endPoint Solid`;
+ add a `TouchSensor` and set the `boundingObject` of a `Cylinder` with a `Translation`;
after these steps, a collision can occur between the touchsensor and the link. Then set the selfCollision to be true of the robot, but this breaks the joint, So this is not the right solution to this situation.

**Comment by stefaniapedrazzi** [comment]
Maybe what you are looking for is the `Motor` force/torque feedback measurements that you can get from the Motor API:
https://www.cyberbotics.com/doc/reference/motor#wb_motor_enable_force_feedback

I you also want to add the force sensor shape on the model, then you could add it simply as part of the `endPoint Solid` node.

**Comment by omichel** [comment]
> Thanks. I will have a try. And another question, I use one same controller to control the models created by webots and Adams separately, but the simulation results of them are quite different. Which result should I trust?

That's difficult to say without an in depth study of your Adams and Webots models. Are you sure that both models are the same? If so, the main difference probably comes from the fact that Webots and Adams don't use the same physics engine.

**Comment by zapplelove** [comment]
> That's difficult to say without an in depth study of your Adams and Webots models. Are you sure that both models are the same? If so, the main difference probably comes from the fact that Webots and Adams don't use the same physics engine.

I'm sure about that, they use the same models and the same control program. I agree about the different physics engines cause different results.

**Comment by zapplelove** [comment]
> Maybe what you are looking for is the `Motor` force/torque feedback measurements that you can get from the Motor API:
> https://www.cyberbotics.com/doc/reference/motor#wb_motor_enable_force_feedback
> 
> I you also want to add the force sensor shape on the model, then you could add it simply as part of the `endPoint Solid` node.

I have used this method. Here are the results:
+ When I set the motor position, the force feedback the right value.
+ When I set the motor force, the force feedback is very close to zero.
Actually, in the real world, a force sensor in the body link will feedback a correct force value both position control and force control.

**Comment by omichel** [comment]
As explained in the documentation you are referring to, the force feedback does not measure the force (resp. torque) specified with the wb_motor_set_force (resp. wb_motor_set_torque) function. Therefore you have to add it manually to get the total force applying there in order to compare to the motor position control case.

**Comment by BenjaminDeleze** [comment]
I'm closing this for now, feel free to reopen it if you have additional issues.
