### ISSUE TITLE
Simulation running without step() calls

### ISSUE THREAD

**Issue by Simon-Steinmann** [cyberbotics/webots#2253]
**Describe the Bug**
When having an <extern> controller, and webots is waiting for it to connect, the simulation is running, even though no robot.step() calls are being made. This is especially apparent when being in "run" mode, which uses all available resources. In my opinion, the simulation should only get calculated, when there is actual simulation steps

**Steps to Reproduce**
1. Start a world containing a robot with <extern> controller
2. Set webots to 'run' mode
3. See/hear computer max out one cor
4. Set webots to 'realtime' or pause, see/hear core usage drop

**Comment by stefaniapedrazzi** [comment]
This issue occurs only with extern controllers and not with controllers started by Webots.

**Comment by Simon-Steinmann** [comment]
That is correct, but it is very bothersome, when working with extern controllers, especially for Reinforcement Learning, where running it at max speed is the default. So anytime you have webots open, and adjust your code, your system is running at maximum boost, wasting power, being noisy etc.

**Comment by stefaniapedrazzi** [comment]
Yes, sure.
I just added some details that will complete the issue description and will help understanding it.
