### ISSUE TITLE
Ubuntu 16.04: issues with nodejs during compilation

### ISSUE THREAD

**Issue by stefaniapedrazzi** [cyberbotics/webots#2254]
When compiling Webots `resources/web/wwi` on Ubuntu 16.04 docker image following the instruction on the wiki page (https://github.com/cyberbotics/webots/wiki/Docker#create-your-own-image) the compilation fails because of nodejs issues.

On Ubuntu 18.04 docker image it works correctly.

We should fix it or explicitly mention that only Ubuntu 18.04 and Ubuntu 16.04 are supported.

**Comment by DavidMansolino** [comment]
What is the exact issue when compiling on Ubuntu 16.04? For me it compiles fine on native Ubuntu 16.04 (and should therefore be possible to compile on Docker).
In any case, I think these instructions (https://github.com/cyberbotics/webots/wiki/Docker#create-your-own-image) should be updated to use the new scripts (maybe we have to add a few dependencies in it): https://github.com/cyberbotics/webots/blob/master/scripts/install/linux_optional_compilation_dependencies.sh
This will avoid duplication and make the creation of the development environment simpler.

**Comment by stefaniapedrazzi** [comment]
These are the errors:
![image](https://user-images.githubusercontent.com/5910449/93767448-54c78d00-fc18-11ea-9a2e-942a766edf1d.png)


nodejs is not properly set with the given instructions.

**Comment by stefaniapedrazzi** [comment]
I will adjust the installation scripts so that they can be reused also in the docker image.
