### ISSUE TITLE
Creating objects dynamically in the supervisor controller

### ISSUE THREAD

**Issue by yuchen93** [cyberbotics/webots#2259]
**Is your feature request related to a problem? Please describe.**
I am trying to find a way to dynamically add/remove objects to the simulation, ideally in the supervisor node. 
I am not sure if this function already exists or not but I haven't found a straight-forward example of how to accomplish this.  I only found an example in the SUMO interface where new car models are generated and added as traffic but I cannot figure out how it is accomplished.

**Describe the solution you'd like**
It would be great if there is an API call to create/load objects in the supervisor node.

**Comment by DavidMansolino** [comment]
You can find one example here: 
https://www.cyberbotics.com/doc/guide/samples-devices#supervisor-wbt
And here is the source code:
https://github.com/cyberbotics/webots/blob/master/projects/samples/devices/controllers/sample_supervisor/sample_supervisor.c
