### ISSUE TITLE
Webots crashes when ContactProperties.softCFM is 0

### ISSUE THREAD

**Issue by omichel** [cyberbotics/webots#2288]
**Steps to Reproduce**

- open the projects/samples/howto/worlds/cylinder_stack.wbt example.
- pause and revert the simulation.
- set the WorldInfo.ContactProperties.softCFM to 0.
- run the simulation.
- Webots crashes.

**Comment by Simon-Steinmann** [comment]
Can confirm this crash. Also, it should be possible to set CFM to 0. This is the default in most simulations. As I agree on it being on by default, and it makes the simulation much more stable, there could be instances, where the user wants no error correction applied.

**Comment by omichel** [comment]
Webots crashes [here](https://github.com/cyberbotics/webots/blob/master/src/webots/nodes/WbSolid.cpp#L1999) as the position returned by `dBodyCopyPosition` or `dBodyGetRelPointPos` returns `{ nan, nan, nan }`.

**Comment by omichel** [comment]
We already have a constraint on `WorldInfo.CFM` that should be strictly positive. I believe we should apply the same constraint to `ContactProperties.softCFM` otherwise, it causes singularities causing instabilities and generating nan values for object positions in ODE, which seems to be non-trivial to fix.

**Comment by omichel** [comment]
Fixed in #2487.
