### ISSUE TITLE
_controller is not found when using PyCharm as in documentation

### ISSUE THREAD

**Issue by wbadry** [cyberbotics/webots#2294]
**Describe the Bug**
The [PyCharm](https://cyberbotics.com/doc/guide/using-your-ide?tab-language=python#pycharm) import reports an error finding `_controller`
**Steps to Reproduce**
1. Add the following to `the environment variables`

| Environment Variable 	| Location                                        	                        |
|----------------------	|-------------------------------------------------	        |
| WEBOTS_HOME          	| C:\Program Files\Webots                         	                |
| PYTHONPATH           	| C:\Program Files\Webots\lib\controller\python37 	|
| PYTHONIOENCODING  | UTF-8                                           	                                |
| Path                 	        | C:\Program Files\Webots\lib\controller          	        |
| Path                 	        | C:\Program Files\Webots\msys64\mingw64\bin      	|
| Path                 	        | C:\Program Files\Webots\msys64\mingw64\bin\cpp  	|

![2020-10-03_22-03-02](https://user-images.githubusercontent.com/5664750/95000819-6a4b9800-05c4-11eb-8a72-20a65088a677.png)
![2020-10-03_22-03-53](https://user-images.githubusercontent.com/5664750/95000825-6e77b580-05c4-11eb-830a-5a8b1cd05813.png)

2. Follow [tutorial 1](https://www.cyberbotics.com/doc/guide/tutorial-1-your-first-simulation-in-webots?tab-language=python) on webots.
3. Open the `epuck_go_forward` folder in `PyCharm IDE`
![2020-10-03_22-08-02](https://user-images.githubusercontent.com/5664750/95000874-f3fb6580-05c4-11eb-8933-195a7ef5dfae.png)

4. Follow the configuration of `PyCharm` as in [webots tutorial](https://cyberbotics.com/doc/guide/using-your-ide?tab-language=python#pycharm).
![2020-10-03_22-13-25](https://user-images.githubusercontent.com/5664750/95000990-15a91c80-05c6-11eb-8be3-bc07549d937c.png)

5. Set controller to `extern` and run it.
![2020-10-03_22-17-31](https://user-images.githubusercontent.com/5664750/95001012-4ab56f00-05c6-11eb-939f-2d618d71e396.png)

6. Run PyCharm script from `PyCharm` . Even if project name is not set in environment variables, it should run the first extern controller as in documentation.

7. The script fails to find `_controller` 
![2020-10-03_22-15-52](https://user-images.githubusercontent.com/5664750/95001035-851f0c00-05c6-11eb-8cc2-d1965d26492a.png)

**Expected behavior**
The robot should start as in tutorial. It runs well as internal webots controller.

**System**
 - Operating System: Windows 10 x64
 - Graphics Card: NVIDIA Geforce 1050 Ti

**Comment by omichel** [comment]
It seems, you should also add `C:\Program Files\Webots\lib\controller\python37` to your system *Path* environment variable:
![image](https://user-images.githubusercontent.com/1264964/95093696-579ea380-0729-11eb-9a47-43d2857aa753.png)
Can you confirm it works also for you like that? If so, I will fix the documentation accordingly.

**Comment by wbadry** [comment]
Thanks @omichel 
I added it although it might be already added as PYTHONPATH variable as in [here](https://stackoverflow.com/questions/50278029/how-to-import-a-pyd-file-as-a-python-module)

![2020-10-05_17-08-12](https://user-images.githubusercontent.com/5664750/95097248-8dde2200-072d-11eb-99c7-a656899c9dec.png)

![2020-10-05_18-18-03](https://user-images.githubusercontent.com/5664750/95105320-452b6680-0737-11eb-93bb-b4499d4f2fa1.png)

My motivation is to take advantage of PyCharm for autocompletion of all functions and code refactoring on PyCharm. I tried to look for the issue. I don'r know if  `_controller.pyd` is used on webots text editor or something else. But it seems that even if the path is added to PYTHONPATH, path and project structure, it is not found by the compiler.

**Comment by omichel** [comment]
`_controller.pyd` is located in `C:\Program Files\Webots\lib\controller\python37\`. Therefore adding it to the global `PATH` environment variable should solved the problem. It worked for me. Did you restart PyCharm after modifying the `PATH` system variable?

**Comment by wbadry** [comment]
Thank you @omichel . I believe the problem is in `_controller.pyd` since the folder is seen by PyCharm. The auto-completion detected `controller.py` classes and methods which is located as you know in the same folder as `_controller.pyd`

![2020-10-06_14-42-42](https://user-images.githubusercontent.com/5664750/95203548-34382f00-07e3-11eb-8534-f1c886c96807.png)

![2020-10-06_14-46-34](https://user-images.githubusercontent.com/5664750/95203574-3a2e1000-07e3-11eb-9c98-409d55220e05.png)

**Comment by omichel** [comment]
Since it works on my computer after adding `C:\Program Files\Webots\lib\controller\python37\` to my *Path* environment variable, I believe it was needed to be able to load `_controller.pyd` which is basically a DLL whose path should be in the *Path* environment variable to be found.

**Comment by wbadry** [comment]
Do you use `Python 3.7` or calling it from `Python 3.8` on your machine?

**Comment by omichel** [comment]
`Python 3.7` from https://python.org

**Comment by omichel** [comment]
I found that this extra path can alternatively be set directly in PyCharm _Settings_ (from the _File_ menu):
![image](https://user-images.githubusercontent.com/1264964/95211989-841bf380-07ed-11eb-9869-c4faf9aa5dd2.png)
(in my case, Webots R2020b revision 1 was installed in the `D:` drive).

**Comment by wbadry** [comment]
Thanks again @omichel 

I am confident that the issue is with `_controller.pyd` and `_vehicle.pyd` not the path at all.

I created this very naive project:

- **test.py** : for just importing packages
- **helloworld.pyd** : cython dummy with hello Waleed print compiled into pyd
- **_controller.pyd** and **_vehicle.pyd** copied from webots direcotry

![2020-10-06_16-17-54](https://user-images.githubusercontent.com/5664750/95214361-1f15cd00-07f0-11eb-8829-c60fbae5bf42.png)

![2020-10-06_16-19-05](https://user-images.githubusercontent.com/5664750/95214377-2210bd80-07f0-11eb-98d5-a1b86589f861.png)

Without the need to add it to the path since I import it directly from code, it is not found meaning it is compiled with a different version possible a higher version that makes it unrecognized. That's why I asked if you are calling them from a project with `3.8` interpreter not `3.7`

![2020-10-06_16-25-17](https://user-images.githubusercontent.com/5664750/95214835-99465180-07f0-11eb-9270-6722fb4a5351.png)

Thanks, @omichel  for updating the issue with possible solutions.

Here is the project if you would like to quickly run it. Just check if the interpreter is set `3.7`
[test_pyd.zip](https://github.com/cyberbotics/webots/files/5334497/test_pyd.zip)

**Comment by omichel** [comment]
I found yet another cleaner option. Do not set any environment variables in the system preferences, but only in PyCharm: from the _Run_ menu, select _Edit Configurations..._ and click on the icon on the right hand side of the _Environment variables:_ field. Then modify the `Path` in the _[x] Include system environment variables_ section as follow:

![image](https://user-images.githubusercontent.com/1264964/95215211-0659e700-07f1-11eb-92f1-a41de9c63a2d.png)

**Comment by wbadry** [comment]
Hi @omichel 
I also tried [this step](https://intellij-support.jetbrains.com/hc/en-us/community/posts/360009758419-failed-to-load-pyd-package) which has the advantage of making the namespace come to PyCharm instead of being dimmed

![2020-10-06_16-41-36](https://user-images.githubusercontent.com/5664750/95216875-ddd2ec80-07f2-11eb-8e7f-edc07c263723.png)


I would really appreciate it Oliver if you get a chance to try the project I sent you with Python 3.7 compiler at your side to check if it works or not. If the import failed, then _controller and _vehicle need to be compiled with a 3.7 version.

**Comment by omichel** [comment]
I could manage to run your project. Here is the modified version. Be sure to add `C:\Program Files\Webots\lib\controller\python37` in the PyCharm settings as shown here:
![image](https://user-images.githubusercontent.com/1264964/95218145-440c3f00-07f4-11eb-93e2-8402c3cda722.png)
[test_pyd.zip](https://github.com/cyberbotics/webots/files/5334654/test_pyd.zip)

**Comment by wbadry** [comment]
You are absolutely a magician Oliver 👍 

I cleaned up everything and this is the way that it made it work with no redundancy:

1. Just like you mentioned, adding `C:\Program Files\Webots\lib\controller\python37` in **project structure**. This is to allow `auto-completion` to work, but the code would compile even without it.
2. This is your **magic touch that made everything went to work**. The `Path` must be added by copying and pasting it and not relying on the system environment 

![2020-10-06_17-55-29](https://user-images.githubusercontent.com/5664750/95226600-6f475c00-07fd-11eb-8fd7-f3ee8bc1a306.png)

It is possibly a bug in PyCharm. Even identical Path added as in documents won't make it be visible unless it is added like this in environment variables:

`PYTHONUNBUFFERED=1;Path=C:\WINDOWS\system32\\;C:\WINDOWS\\;C:\Program Files\Webots\msys64\mingw64\bin\\;C:\Program Files\Webots\msys64\mingw64\bin\cpp\\;C:\Program Files\Webots\lib\controller\\;C:\Program Files\Webots\lib\controller\python37`

So, your way worked. Well done Oliver and hope to get the docs updated with this. Very awesome work.
