### ISSUE TITLE
RobotNode Reset

### ISSUE THREAD

**Issue by MentalGear** [cyberbotics/webots#2299]
Feature request: a function to reset all parameters of the current (robot) node. Useful for ml training instead of reseting the whole world.

**Comment by DavidMansolino** [comment]
Would a Supervisor function such as something like `wb_supervisor_node_reset` suit your needs?

**Comment by omichel** [comment]
I am closing this stalled issue since we didn't received an answer from @MentalGear. Feel free to re-open if needed.
