### ISSUE TITLE
Webots Thymio simulator and thymio2_aseba controller: Not possible  to connect to a tcp port 33333 on Ubuntu 20.04

### ISSUE THREAD

**Issue by AutreTechLab** [cyberbotics/webots#2336]
**Describe the Bug**
Webots Thymio simulator and thymio2_aseba controller: Not possible  to connect to a tcp port 33333. 

We upgraded to Ubuntu 20.04 because we started experimenting with ROS 2 Foxy Fitzroy and want to use Webots as simulator. I understand that this requires the installation of the old Aseba Studio package. (`Connect Aseba Studio or VPL for Thymio II to this controller through TCP/IP.`; `Use the Thymio II robot window to access some special events (tap, clap, etc.).`).<br>
We have checked http://wiki.thymio.org/en:linuxinstall, but there is currently no mention of the Ubuntu 20.04 distribution. Ubuntu 20.04 comes with QT5 instead of QT5, and that is probably the reason why the old package aseba_1.6.1_amd64.deb cannot be installed anymore. Furthermore, we switched to the new Thymio Suite 2.0, which is easier to use and under active development.

**Steps to Reproduce**
1. Configure Thymio2 in Webots and start simulation
`INFO: thymio2_aseba: Starting controller: /usr/local/webots/projects/robots/mobsya/thymio/controllers/thymio2_aseba/thymio2_aseba port=33333
Thymio II Aseba server`
- `Connect Aseba Studio or VPL for Thymio II to this controller through TCP/IP.`
- `Use the Thymio II robot window to access some special events (tap, clap, etc.).`
- `Change the server port using the Thymio2::controllerArgs field.`
`In order to have an accurate simulation, it is recommended to set WorldInfo::basicTimeStep to 10.` <br>
`Server started on port 33333...`
2. Run Thymio Suite 2 (older tools like Aseba studio are no longer available on Ubuntu 20.04)
- `flatpak install flathub org.mobsya.ThymioSuite`
- `flatpak run org.mobsya.ThymioSuite`

**Expected behavior**
- Thymio suite 2.0 show show the presence and connect to the Webot simulator on port 33333

**System**
 - Operating System: Ubuntu 20.04

**Additional context**
- An issue was logged in  Mobsya /aseba: suite 2 rc5: connect to a tcp port #742
- here is the reply:   
   - mbonani commented on Jun 2
   - The Webot simulator cannot be connect to the Thymio Suite like it connects before, probably it is possible that web bots show its presence like our simulator using zeroconf/bonjour

**Comment by ygoumaz** [comment]
#5289 gets rid of dashel and aseba.
