### ISSUE TITLE
Fix human animations in latest version of Webots

### ISSUE THREAD

**Issue by stefaniapedrazzi** [cyberbotics/webots#2343]
The simulation of animated human with `Skin` node is no longer correctly working in the latest version of Webots.

I just checked again and for example in Webots R2019b revision 1 and Webots R2020a revision 1 they are working correctly.

**Comment by stefaniapedrazzi** [comment]
It seems that the bone index changed and the ones used in the controller and retrieved from the BVH animation file don't match any longer the ones read by Webots from the FBX.

**Comment by stefaniapedrazzi** [comment]
The Webots internal bones order changed due the libassimp update.
Given that root bone index was hard coded in the `bvh_animation.c` controller, the wrong bone was moved.
Fixing the `bvh_animation.c` so that it retrieves the root bone index based on the name fixes the issue and the same controller works correctly both in Webots R2020b and Webots R2020a.

**Comment by omichel** [comment]
So why did you close this issue? Is `bvh_animation.c` already fixed?

**Comment by stefaniapedrazzi** [comment]
The human animation sample simulation and the `bvh_animation` controller is not available on this webots repo yet.
I will port it from the old repository when addressing #2345.
