### ISSUE TITLE
Release the Skin node

### ISSUE THREAD

**Issue by stefaniapedrazzi** [cyberbotics/webots#2345]
The `Skin` node is still experimental and it would be good to make it public and document it.
From the latest feedback I received, using FBX format for the human model (mesh and rigged skeleton) and BVH motion fine is the good way to go.

Previous work on documentation:
https://github.com/cyberbotics/webots-doc/pull/96
Remaining issues:
https://github.com/cyberbotics/webots-dev/issues/4063

**Comment by BenjaminDeleze** [comment]
I think it was fixed in #3566
