### ISSUE TITLE
Textured Parallelipiped checkboxes don't match cube mapping

### ISSUE THREAD

**Issue by Justin-Fisher** [cyberbotics/webots#2361]
Create a textured parallelipiped, select cube mapping, select the Webots-suggested cube_mapping.jpg as the texture to map.  The parallelipiped appears reasonably with the expected faces adjoining.  Now change the setting for _right_ to FALSE.

**Expected behavior:**  The blue side labelled RIGHT should be the side that disappears.  
**What actually happens:** the side labeled FRONT disappears instead.  (Similar problems affect several of the other checkboxes. 
 E.g. the side I wanted to remove was labelled BACK, but to remove it I actually had to set _left_ to FALSE.)

I'm not sure what to suggest to fix this mismatch, as any change you make may break backwards compatibility for some existing uses.  If you do change it, I guess I'd suggest changing which faces the checkboxes remove, rather than changing how the texture maps to the vertices, as it'd be annoying to have to use different cubemaps for these from what you use for textured boxes, and if the change does break backwards compatibility for someone, it's generally much easier to change a couple of boolean checkboxes than it is to make new texture maps.  Or maybe you should just clearly document the mismatch and live with it?

![image](https://user-images.githubusercontent.com/19636109/96538001-28298400-125d-11eb-91fb-88058266476c.png)

**Comment by omichel** [comment]
This bug is also reproducible with the TexturedBox PROTO as well.
