### ISSUE TITLE
Collision callback in physics plugin is not called if `boundingObject` is a `Group` node

### ISSUE THREAD

**Issue by lukicdarkoo** [cyberbotics/webots#2420]
**Describe the Bug**
Callback function `int webots_physics_collide(dGeomID g1, dGeomID g2)` in physics plugin is not called if `boundingObject` is a `Group` node.

**Steps to Reproduce**
1. Download [physics_callback_bug.zip](https://github.com/cyberbotics/webots/files/5465323/physics_callback_bug.zip)
2. Run `default.wbt`

**Expected behavior**
In the world, there are two same robots, but one has a `Group` node as a bounding object while the other only a `Shape` node. Therefore, the callback should be called for both of them which is not the case.

**System**
 - Operating System:  Windows 10
 - Graphics Card: NVIDIA GeForce RTX 2060

**Comment by omichel** [comment]
Fixed in #2505.
