### ISSUE TITLE
Python 3.9 support doesn't appear to be installed

### ISSUE THREAD

**Issue by PeterJCLaw** [cyberbotics/webots#2469]
**Describe the Bug**

Python 3.9 support is claimed in the docs for both macOS and linux, yet doesn't appear to be installed on either.

On Ubuntu:
```
find /usr/local/webots -name controller.py -type f
/usr/local/webots/lib/controller/python38/controller.py
/usr/local/webots/lib/controller/python27/controller.py
/usr/local/webots/lib/controller/python36/controller.py
/usr/local/webots/lib/controller/python35/controller.py
/usr/local/webots/lib/controller/python37/controller.py
```

**Expected behavior**

A Python 3.9 controller should be installed.

**System**
Operating System: Ubuntu 18.04.5

```
$ webots --version
Webots version: R2020b revision 1
```

**Comment by omichel** [comment]
You are right, the documentation is not up-to-date with the current released version. It actually reflects the nightly build of the master branch. Python 3.9 is indeed supported in Webots R2020b revision 2 which you can download as a nightly build. We will take care of avoiding this kind of problem in the future.
