### ISSUE TITLE
Robot windows slows performance after closed / reset

### ISSUE THREAD

**Issue by Simon-Steinmann** [cyberbotics/webots#2493]
**Describe the Bug**
Opening the robot window (double click on robot) slows the performance of Webots. Closing or resetting the simulation does not return to the same performance level as before. Only a world reload does.

**Steps to Reproduce**
1. Open a world with a robot
2. Run simulation in fast mode and take a note of the realtime factor (RF)
3. open the robot window (double click on robot) - RF should decrease
4. Close robot window - RF should go up but not as high as in step 2
5. Reset simulation (back-arrow or ctrl-shift-T) - RF still not as high as in step 2
6. Reload world. RF should now be the same as in step 2

**Expected behavior**
Closing the robot window should turn off all background tracking / monitoring and there should be no impact of performance anymore

**Feature Suggestions:**
- Give the user the option to adjust the polling rate of the robot window (in a multiple of timesteps). This could allow for less performance impact
- Give the user the option to enable / disable what they want to monitor / controll. An "disable all" and "enable all" option would be great too.

**Comment by stefaniapedrazzi** [comment]
Performance should be improved in #2655
