### ISSUE TITLE
web simulator cannot start controllers

### ISSUE THREAD

**Issue by yuchen93** [cyberbotics/webots#2495]
**Describe the Bug**
I am trying to run remote simulation on an AWS server. 
Remote streaming works great but whenever I start remote simulation with the simulation server script, I got the following errors:

[INFO   ]  Error: invalid whitelist path /usr/local/webots/lib/controller
[INFO   ]  Error: proc 68551 cannot sync with peer: unexpected EOF

and the simulation fails to start the controllers. From some quick search, this seems to be a firejail problem.

**Expected behavior**
I expected web simulation to run in similar fashion as web streaming (I actually do not need to be able to edit controller but just want to start a different web streaming for each different client). 

**System**
 - Operating System: Linux Ubuntu 18.04

**Additional Context**
I modified the simulation server script to use xvbf to run webots and skipped the project setup function since my web server and simulation server are the same.

Thanks

**Comment by omichel** [comment]
I you don't need, you should disable firejail be deleting [this line](https://github.com/cyberbotics/webots/blob/master/resources/web/server/simulation_server.py#L715) from your simulation server script.
