### ISSUE TITLE
Offline documentation doesn't work

### ISSUE THREAD

**Issue by lukicdarkoo** [cyberbotics/webots#2549]
**Steps to Reproduce**
1. Go to `Help > Offline Documentation > User Guide`

**Screenshots**
![image](https://user-images.githubusercontent.com/2135826/101771255-ee049200-3ae9-11eb-8a25-f58500cbdde8.png)

**System**
- Operating System: Ubuntu 20.04
- Webots: R2021a from snap

**Comment by omichel** [comment]
I cannot reproduce this bug on Windows.

**Comment by lukicdarkoo** [comment]
I had badly configured alias (my environment) for this and #2550, my bad
