### ISSUE TITLE
hokuyo.wbt makes Webots freezing on Ubuntu 18.04 VM

### ISSUE THREAD

**Issue by stefaniapedrazzi** [cyberbotics/webots#2563]
In my Ubuntu 18.04 VM, the `hokuyo.wbt` blocks at 32ms and Webots is completely freezed and I have to manually kill it.
I tested with the snap package but I will now check with other packages too.

**Comment by omichel** [comment]
I just tested on Windows again and it works fine.

**Comment by stefaniapedrazzi** [comment]
It also works fine on my native Ubuntu 18.04.

**Comment by omichel** [comment]
OK, so I remember that it is a known bug with some VM which don't support Lidars because of a bug in reading the OpenGL depth buffer. So, this is not a regression and I am afraid we cannot do much to fix it.

**Comment by lukicdarkoo** [comment]
Could it be related to?
https://github.com/cyberbotics/webots/pull/2509

**Comment by omichel** [comment]
Which VM are you using? VMware or Virtual Box?

**Comment by stefaniapedrazzi** [comment]
VirtualBox

**Comment by stefaniapedrazzi** [comment]
I just checked the mainstream snap package available from the snap stable repository and it works correctly.
So the issue seems only related to the latest changes introduced in R2021a.
By the way I confirm I have the same problem with the tarball installation too.

**Comment by omichel** [comment]
See #32 for the Lidar problem spotted on VMs and its resolution.

**Comment by stefaniapedrazzi** [comment]
I will check.
Just note that all the other Lidar simulations works fine.

**Comment by stefaniapedrazzi** [comment]
The issue seems

> Could it be related to?
> #2509

Yes, it seems that the problem is that the value is NaN and here we just filter out INF values:
https://github.com/cyberbotics/webots/blob/develop/projects/samples/devices/controllers/hokuyo/hokuyo.c#L69-L72

Just changing the check to ``f != INFINITY && !isnan(f)`` make it work on my system.
