### ISSUE TITLE
The Display external display view is stuck when Camera is attached

### ISSUE THREAD

**Issue by lukicdarkoo** [cyberbotics/webots#2585]
**Steps to Reproduce**
1. Download [display_bug.zip](https://github.com/cyberbotics/webots/files/5715191/display_bug.zip)
2. Start the simulation
3. Double click on the Display view
4. Move the robot, so the camera can see a different scene
5. You should notice that the view in the Display window got stuck

**Screenshots**
![image](https://user-images.githubusercontent.com/2135826/102606751-87a1f400-4127-11eb-99e7-f46c03b3739b.png)

**System**
 - Operating System:  Windows
 - Webots version: R2020a

It may be a regression.

**Comment by stefaniapedrazzi** [comment]
I could reproduce this also in R2019.
