### ISSUE TITLE
"LD_LIBRARY_PATH" may overwrite other library path

### ISSUE THREAD

**Issue by helloliver** [cyberbotics/webots#2586]
**Describe the Bug**

I built webots from source successfully, but my ROS cannot work!

```bash
/opt/ros/melodic/lib/rosout/rosout: error while loading shared libraries: libroscpp.so: cannot open shared object file: No such file or directory
process[rosout-1]: started with pid [13069]
```

And I found the problem was resulted from an environment variable. Details are following.

In the file "scripts/install/bashrc.linux":

```bash
export LD_LIBRARY_PATH=$WEBOTS_HOME/lib/webots  # Add the Webots libraries to the library path (useful when launching Webots directly without using the launcher).
```

Other LD_LIBRARY_PATH will be overwrited!!! You can reset the variable as:
```bash
export LD_LIBRARY_PATH=$WEBOTS_HOME/lib/webots:$LD_LIBRARY_PATH
```

That's all.

**Comment by omichel** [comment]
Thank for this bug report and proposed solution.
The patch is in #2587.
