### ISSUE TITLE
incorrect detection of GPU memory on iMac 2020

### ISSUE THREAD

**Issue by Bradford-Miller** [cyberbotics/webots#2588]
**Describe the Bug**
On starting WeBots 2021a for the first time, it generates a warning that my system is below minimum requirements having less than 2Gb of memory. However, "About this Mac" reports an AMD Radeon Pro 5500 XT 8 GB card. (iMac 20,1)

**Steps to Reproduce**
See above

**Expected behavior**
No error and a dawning realization that this is a sufficient graphics card to run Webots uninhibited.

**Screenshots**

**System**
 - Operating System: MacOS Catalina
 - Graphics Card: AMD Radeon Pro 5500 XT 8 GB

**Additional context**

**Comment by Bradford-Miller** [comment]
Sorry, that should have read Webots 2021a.

**Comment by omichel** [comment]
Could you please post a screenshot of the window you get when going to the "Help" menu, "OpenGL information..."?

**Comment by omichel** [comment]
The detection of available GPU RAM doesn't work well in case of AMD cards: it retrieves the currently available GPU RAM, e.g., the memory not currently in use, and not the total GPU RAM. Therefore, if some GPU RAM is already used by another process, Webots may believe that your amount of GPU RAM is way smaller than it actually is. 
It is not possible (or very complicated) to retrieve the total GPU RAM information on macOS in case of AMD GPU.

Given that hardware requirements below the Webots specification correspond now to pretty old machines, I would suggest that we drop these problematic tests in Webots, as they cause more trouble to people with recent hardware than they help people with outdated hardware.

**Comment by the-raspberry-pi-guy** [comment]
Just wanted to contribute that this is also a present and annoying issue when using Webots on my MacBook Pro 16 2019. I have a very high spec configuration, but presumably I am suffering from the same GPU AMD issues that you are discussing @omichel :

<img width="245" alt="image" src="https://user-images.githubusercontent.com/5570173/106381710-a34d1b00-63b2-11eb-84e5-c8cdb7e112ed.png">

I am trying to run on a 4K screen, when I snap the window to only half of the size of the display though I start to get some better performance (ie: a real time factor of 1 and not very much lag)

**Comment by omichel** [comment]
This should not affect the performance. 4K resolutions yield anyhow to a lower performance whatever your graphics card and operating system. But it also highly depend on the simulation. Which world file are you running to get such a bad performance? Is that a sample world included with Webots?
