### ISSUE TITLE
ICONS don't fit on the 4K screen

### ISSUE THREAD

**Issue by Cpy-bit** [cyberbotics/webots#2594]
ICONS don't fit on the 4K screen. They looks very small, and there is no options to resize it.

**Comment by omichel** [comment]
Can you please give us more information about your operating system and post a screenshot showing the problem?

**Comment by Cpy-bit** [comment]
My operating system : WIN 10
My Screen resolution: 3840*2160
![problem](https://user-images.githubusercontent.com/62270982/103173709-b93d5c80-4897-11eb-99b2-edecedaba197.png)

**Comment by lukicdarkoo** [comment]
I can reproduce this on my laptop. It is not related to the high resolution, but to the display scaling (go to `Display > Scale and layout` and set to any number greater than 100).

**Comment by omichel** [comment]
Another solution is to define the following environment variable in your system: `QT_ENABLE_HIGHDPI_SCALING=1`
