### ISSUE TITLE
DistanceSensor returns max value when facing certain TexturedBox faces

### ISSUE THREAD

**Issue by WillB97** [cyberbotics/webots#2605]
**Describe the Bug**
When using the sonar DistanceSensor with an environment constructed from TexturedBox elements certain areas appear to return the maximum value regardless of the distance from the wall. These areas appear to correspond to one of the triangles on each face.

**Steps to Reproduce**
1. Create a TexturedBox
2. Place a sonar DistanceSensor perpendicular to the created box
3. Move the DistanceSensor parallel to the box along its whole length

**Expected behavior**
The DistanceSensor should return a consistant value corresponding to the distance from the box.

**Screenshots**
![2020-12-23-142900_991x647_scrot](https://user-images.githubusercontent.com/10937272/103007424-506a8300-452b-11eb-96c1-5ee4a3ad5c2a.png)

**System**
 - Operating System: Windows 10 (also replicated on Manjaro Linux)
 - Graphics Card: NVIDIA GeForce GTX 1070 8 GB

**Comment by omichel** [comment]
Could you upload a super simple simulation showing this wrong behavior?
We need a world file with a super simple robot and a sonar and a very simple robot controller preferably in python that displays the wrong sensor readings.
This would help us tracking down the problem.

**Comment by WillB97** [comment]
Here's the stripped down version of our scenario. [TexturedBox-demo.zip](https://github.com/cyberbotics/webots/files/5735896/TexturedBox-demo.zip)
