### ISSUE TITLE
Wrong OpenGL version detected

### ISSUE THREAD

**Issue by Serafadam** [cyberbotics/webots#2612]
**Describe the Bug**
Hi, I've been trying to run a snap version of Webots on a fresh installation Linux with latest AMD drivers installed. Sadly the simulator won't start, or after a fresh snap installation will start with the welcoming screen, and after that it will quit with the message:

```
webots  

libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: radeonsi
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: radeonsi
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
FATAL: Webots requires OpenGL 3.3 while only OpenGL 1.4 can be initialized.
Please check your GPU abilities and install the latest graphics drivers.
Please do also check that your graphics hardware meets the requirements specified in the User Guide.
```

glxinfo tells me that I currently have OpenGL 4.6 installed:

```
glxinfo | grep OpenGL

OpenGL vendor string: Advanced Micro Devices, Inc.
OpenGL renderer string: AMD Radeon (TM) R9 390 Series
OpenGL core profile version string: 4.6.14756 Core Profile Context 20.45
OpenGL core profile shading language version string: 4.60
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL core profile extensions:
OpenGL version string: 4.6.14756 Compatibility Profile Context 20.45
OpenGL shading language version string: 4.60
OpenGL context flags: (none)
OpenGL profile mask: compatibility profile
OpenGL extensions:
OpenGL ES profile version string: 4.6.14756 Compatibility Profile Context 20.45
OpenGL ES profile shading language version string: 4.60
OpenGL ES profile extensions:
```

Without the drivers, Webots launch properly, but have graphic options limited.

**Steps to Reproduce**
1. Install pro drivers as in https://amdgpu-install.readthedocs.io/en/latest/install-installing.html#installing-the-pro-variant
2. glxinfo
3. Install Webots via Snap
4. Run Webots in terminal
5. See error

**Expected behavior**
Webots working properly

**System**
 - Operating System: Kubuntu 20.04
 - Graphics Card: AMD Radeon R9 390 8GB

**Comment by stefaniapedrazzi** [comment]
Do you get the same issue if you install Webots using the tarball package instead of the snap package?

Note that if you run `glxinfo` from a terminal then the environment could be different than the one on the snap container.

**Comment by stefaniapedrazzi** [comment]
Could be related to #2496.

**Comment by Serafadam** [comment]
Hi, sorry for the long delay,
I tested deb, as well as a tarball package.
The deb shows me the same errors as in snap, but the tarball works perfectly with all features enabled. Now I wonder what is the difference between them

**Comment by Serafadam** [comment]
Ok, it seems I found the issue, when running `amdgpu-pro` install some drivers are not installed, when using regular `amdgpu-install` apt works, tarball works, snap does not work.

**Comment by ic** [comment]
For the record, same problem with an AMD GPU Strix Halo (January 2025). Snap installation only detects MESA, not the HW. Installing with [APT the release found on GitHub](https://github.com/cyberbotics/webots/releases/download/R2025a/webots_2025a_amd64.deb) works fine, detecting and using the GPU.
