### ISSUE TITLE
Installation instructions refer to webots_2021a-rev1 instead of webots_2021a

### ISSUE THREAD

**Issue by brettle** [cyberbotics/webots#2616]
**Documentation page(s) concerned**
https://cyberbotics.com/doc/guide/installation-procedure

**What is the problem with the current documentation?**
It refers to a non-existent release.

**Describe how you would fix it**
Make it refer to the correct release. Looks like the release is a template variable, but I don't have time to track down where it's computed.

**Comment by omichel** [comment]
I believe we fixed it. Can you confirm?
Feel free to re-open this issue if you spot any problem.
