### ISSUE TITLE
Installation is failed using latest Homebrew in macOS

### ISSUE THREAD

**Issue by kawarimidoll** [cyberbotics/webots#2636]
**Documentation page(s) concerned**
https://cyberbotics.com/doc/guide/installation-procedure#from-the-homebrew-package

**What is the problem with the current documentation?**
The command `brew cask install` in this page doesn't work now because of update of Homebrew.

[Error: Calling brew cask install is disabled! · Discussion #340 · Homebrew/discussions](https://github.com/Homebrew/discussions/discussions/340#discussioncomment-232364)

> `brew cask <command>` was deprecated in favor of `brew <command> --cask` in Homebrew 2.6.0. Now that 2.7.0 has been released, they have been disabled.

**Describe how you would fix it**
Replace `brew cask install` with `brew install --cask` .

**Comment by omichel** [comment]
Fixed in #2638.
