### ISSUE TITLE
howto/physics simulation is broken

### ISSUE THREAD

**Issue by stefaniapedrazzi** [cyberbotics/webots#2643]
In the `howto/physics` simulation, the MyBot robot fails detecting obstacles and detect objects even when it should not.

The expected behavior is that the robot goes down just after the box stop intersecting the robot ray and messages in the console should only be written when the ray intersects a box.

I tested R2019a and it works.
At some point the color of the ray was also changing but in R2019a this already doesn't work we should inspect this as well and restore the behavior if possible or remove unneeded code.

**Comment by lukicdarkoo** [comment]
Reverting the `WbSimulationCluster.cpp` to R2020b fixes the issue...
