### ISSUE TITLE
Vehicle wheels sink in the ground

### ISSUE THREAD

**Issue by anastasiapan** [cyberbotics/webots#2645]
**Describe the Bug**
After I add a vehicle in the world the wheels seem to sink in the floor. I have a specific car in the screenshots but it happens for more vehicles that I have tried.

**Steps to Reproduce**
1. Create a project
2. Add a world -the world I used is a chessboard from the tutorial but bigger. I have pasted my wbt file in the additional context.
3. Add a car node
4. Start the simulation - wheels sink in

**Expected behavior**
Wheels should stay on the ground

**Screenshots**
![before_simulation](https://user-images.githubusercontent.com/43236029/104445438-66eb8380-5599-11eb-8ced-eb838cfc4806.jpg)
![after_simulation_start](https://user-images.githubusercontent.com/43236029/104445446-694ddd80-5599-11eb-96f0-427cba1d0ba9.jpg)

**System**
 - Operating System: [Windows 10]
 - Graphics Card: [Nvidia Geforce RTX 2060]

**Additional context**
#VRML_SIM R2021a utf8
WorldInfo {
  basicTimeStep 16
  coordinateSystem "NUE"
}
Viewpoint {
  orientation -0.46134774057218736 -0.8461962857136512 -0.26666478641425145 1.0474096902583303
  position -11.235150136910923 8.637307630756313 11.256040438097262
}
TexturedBackground {
}
TexturedBackgroundLight {
}
Floor {
}
DEF WALL_1 Solid {
  translation 5 0.05 0
  children [
    DEF WALL_SHAPE Shape {
      appearance PBRAppearance {
        baseColor 0.8 0.8 0.8
        roughness 1
        metalness 0
      }
      geometry Box {
        size 0.02 0.1 10
      }
    }
  ]
  name "solid(1)"
  boundingObject USE WALL_SHAPE
}
DEF WALL_2 Solid {
  translation -5 0.05 0
  children [
    USE WALL_SHAPE
  ]
  name "solid(2)"
  boundingObject USE WALL_SHAPE
}
DEF WALL_3 Solid {
  translation 0 0.05 -5
  rotation 0 1 0 1.5708
  children [
    USE WALL_SHAPE
  ]
  name "solid(3)"
  boundingObject USE WALL_SHAPE
}
DEF WALL_4 Solid {
  translation 0 0.05 5
  rotation 0 1 0 1.5708
  children [
    USE WALL_SHAPE
  ]
  name "solid(4)"
  boundingObject USE WALL_SHAPE
}

**Comment by omichel** [comment]
This is normal: see this [FAQ](https://cyberbotics.com/doc/guide/modeling#my-robot-sinks-into-the-ground-how-to-remove-this-effect) to fix it.
