### ISSUE TITLE
Lidar Point Cloud does not work

### ISSUE THREAD

**Issue by it14149** [cyberbotics/webots#2660]
**Describe the Bug**
The Lidar Cloud Point does not properly work during the simulation. It will start and stop showing the lidar points at "random" intervals. This happens in both the lidar.wbt sample and any new simulation I've tried.

**Steps to Reproduce**
1. Open the lidar.wbt sample from Help --> Webots Guided Tour --> Devices Tour --> lidar.wbt
2. Run the simulation

**Expected behavior**
The Lidar Cloud Point should not stop working. It should constantly show the lidar points.

**Video**
https://user-images.githubusercontent.com/12613442/104852089-5d4b7e00-5901-11eb-85e7-838dd85b9a8d.mp4

**System**
 - Operating System: Windows 10 Pro
 - Graphics Card: NVIDIA GeForce GTX 1050

**Additional context**
In the video provided it seems that the cloudpoint works at certain places (in the center of the map and momentarily near the bottom green object which implies it is not random.

**Comment by omichel** [comment]
I believe we can close this issue as it was fixed in #2666.
