### ISSUE TITLE
getLayerRangeImage() and getRangeImage() return the same list

### ISSUE THREAD

**Issue by martingochevski** [cyberbotics/webots#2672]
**Describe the Bug**
Both functions, when called from the Velodyne HDL-32E and presumably other Lidars, return the full range image, which is not correct according to the documentation on getLayerRangeImage().

**Steps to Reproduce**
1. Place Lidar on top of a car
2. Get the data from both functions
3. Compare their lengths

**Expected behavior**
Get only the data ranging from a * resolution to a * (2 * resolution - 1) when calling getLayerRangeImage(a).

**Screenshots**

**System**
 - Operating System: Windows 10 
 - Graphics Card: Nvidia GTX 1080Ti

**Additional context**

**Comment by stefaniapedrazzi** [comment]
C and C++ functions are correct: `getLayerRangeImage()` returns a pointer linking to the layer. This is part of the full image data, but it is up to the user to compute the size.

Python and Java functions are wrong and return the full image.
