### ISSUE TITLE
USE id not exported correcty when DEF is in a PROTO

### ISSUE THREAD

**Issue by BenjaminDeleze** [cyberbotics/webots#2685]
**Describe the Bug**
When you have a PROTO with a customizable field than can be set as DEF (like the appearance field in the solidPipe PROTO) and you add another node (outside the PROTO) with a USE toward this DEF, the DEF id inside the USE node is not correctly exported in x3d.

This bug seems to apply to appearance but also shape, geometries, etc

**Steps to Reproduce**
1. Open webots with "./webots --stream"
2. Open "floating_geometries.wbt"
3. Open the streaming viewer
4. See that the pool's floor is missing its appearance and  ```X3dLoader: no matching DEF node "n10" node.``` appears in the browser's console.

**Expected behavior**
It seems like two nodes are created for the appearance of the pool, one when parsing the PROTO file (id = 10) and one to actually display the pool.

The pool's floor USE referenced the id 10 whereas it should reference the id of the other node as it is the second one that is actually exported and not the one with id 10.

**Screenshots**
![Screenshot from 2021-01-29 11-28-26](https://user-images.githubusercontent.com/25938827/106264068-79b2b900-6225-11eb-816e-691ee2189519.png)

Simplified version of floating_geometries.wbt in webots

![Screenshot from 2021-01-29 11-29-00](https://user-images.githubusercontent.com/25938827/106264071-7a4b4f80-6225-11eb-9e03-b359db907383.png)

The rendering in the current web viewer

**Additional context**
This bug is not fixed by the new version of the web viewer as it seems directly related to webots and how it loads worlds.

**Comment by stefaniapedrazzi** [comment]
For nodes defined in PROTO parameters multiple instances are created:
* one instance for the PROTO parameter node
* one finalized instance for each use in the PROTO body  

In the X3D file PROTO parameters are not exported and only the internal finalized nodes are exported.
But reference DEF node links to a PROTO parameter node instead of linking to (any) of its finalized instances.
