### ISSUE TITLE
Something wrong about time stamp for ROS topic

### ISSUE THREAD

**Issue by JackyMao1999** [cyberbotics/webots#2686]
I'm using webots 2020b-rev1 now which I installed by .deb package. And I'm using ROS melodic + Ubuntu 18.04.
I have added the `-clock` and  `--use-sim-time` argument to the ros controller in webots.But I also notised that the time stemps are abnormal.

The /clock topic published by Webots like that:
![1](https://user-images.githubusercontent.com/48790075/106372139-b6a6b900-63a7-11eb-91a7-4b6431aec2d0.png)

When the sensors finished enabled ,I echo header of laser topic, and I got:
![2](https://user-images.githubusercontent.com/48790075/106372150-c45c3e80-63a7-11eb-9059-897ec4ed0c62.png)

I also echo another topic's header, I got:
![3](https://user-images.githubusercontent.com/48790075/106372193-52d0c000-63a8-11eb-8574-4608edc42698.png)

When I run cartographer and move_base together. And I set `use-sim-time=true` in cartographer's launch file，like that：
![4](https://user-images.githubusercontent.com/48790075/106372312-64ff2e00-63a9-11eb-96a2-931f7bceedc6.png)

The move_base wouldn't  run, because they have the different time stamp.
![5](https://user-images.githubusercontent.com/48790075/106372395-2027c700-63aa-11eb-8032-bb9dae8761f0.png)

Thanks for your reading.

**Comment by omichel** [comment]
Do you get the same problem with Webots R2021a?

**Comment by JackyMao1999** [comment]
> Do you get the same problem with Webots R2021a?

I'm sorry.I haven't tried it.

**Comment by JackyMao1999** [comment]
> Do you get the same problem with Webots R2021a?

I tried it with Webots R2021a, It has the same problems.

**Comment by lukicdarkoo** [comment]
Do you use an external controller or the `ros` controller?

**Comment by JackyMao1999** [comment]
> Do you use an external controller or the `ros` controller?

I use the ros controller，like this：

![-8b4b217fcce48f8.jpg](https://user-images.githubusercontent.com/48790075/106602401-e61c1800-6597-11eb-9172-c839c022f231.jpg)

**Comment by lukicdarkoo** [comment]
I can reproduce it, I am checking the problem

**Comment by lukicdarkoo** [comment]
The `controllerArgs` parameter should contain also `--use-sim-time`:
```
  controllerArgs [
    "--name=robot_name"
    "--use-sim-time"
    "--clock"
  ]
```

And somewhere in the launch file you should set the `/use_sim_time` parameter to `true`:
```
<param name="/use_sim_time" value="true" />
```

Please let me know if this works for you.

**Comment by JackyMao1999** [comment]
> The `controllerAr parameter should contain also `--use-sim-time`:
> ```vrml
> controllerArgs [
>   "--name=robot_name"
>   "--use-sim-time"
>   "--clock"
> ]
> ```
> 
> And somewhere in the launch file you should set the `/use_sim_time` parameter to `true`:
> ```xml
> <param name="/use_sim_time" value="true" />
> ```
> 
> Please let me know if this works for you.

I have tried this，but I still have this problem.

**Comment by lukicdarkoo** [comment]
That is strange because it works fine for me. I modified this example:
https://github.com/cyberbotics/webots_ros/blob/master/launch/pioneer3at.launch

By applying the changes I mentioned above I could see the lidar sensor using the simulation time. Do you use Webots R2021a?

**Comment by JackyMao1999** [comment]
> That is strange because it works fine for me. I modified this example:
> https://github.com/cyberbotics/webots_ros/blob/master/launch/pioneer3at.launch
> 
> By applying the changes I mentioned above I could see the lidar sensor using the simulation time. Can you try Webots R2021a?

oh,It works fine in Webots R2021a. I need to  change many code of the object to the new version.But thank you very much.
