### ISSUE TITLE
Improve the HTML5 animation export style 

### ISSUE THREAD

**Issue by lukicdarkoo** [cyberbotics/webots#2692]
Currently, the exported page has a lot of spacing around the actual animation. Maybe we could improve it a little to look like the RobotBenchmark simulation page, e.g.:
https://robotbenchmark.net/benchmark/inverted_pendulum/simulation.php

**Comment by stefaniapedrazzi** [comment]
@lukicdarkoo this should already be with the improvements in R2021b.
Could you please close this issue or assign a milestone?

**Comment by BenjaminDeleze** [comment]
This has been improved in #4423
