### ISSUE TITLE
Compilation errors for controllers using Qt on Windows

### ISSUE THREAD

**Issue by stefaniapedrazzi** [cyberbotics/webots#2717]
Recompiling controllers using Qt on Windows throws this error:
```
cannot find -lQt5Core
```
As a workaround it is possible to add the following line on the `Makefile`:
```
LIBRARIES += -L"$(WEBOTS_HOME)/msys64/mingw64/bin"
```
or
```
DYNAMIC_LIBRARIES += -L"$(WEBOTS_HOME)/msys64/mingw64/bin"
```

On macOS and linux, the path to the Qt library folder (`lib/webots`) is added as "DYNAMIC_LIBRARY".
On Windows, in the past, we had many issues due to conflicts with Qt and I don't know exactly what is the status now and if we should do the same as on the other OS.

Steps to reproduce (checked from an installed package and not development system):
1. Open "highway.wbt"
2. Change controller and select "racing_wheel"
3. Recompile "racing_wheel" controller (accept the relocation of the project)

**Comment by omichel** [comment]
I believe we should add this path only in the local Makefile of these specific controllers using Qt to avoid conflicts.
