### ISSUE TITLE
3d model texture path issue

### ISSUE THREAD

**Issue by mxf8bv** [cyberbotics/webots#2722]
When importing 3d models (e.g. .obj with .mtl files), textures are often not found.
On Windows it seems to work to have them in the same folder as the model only when the path is prefixed like this: ".\texturename.jpg" (but not "./texturename.jpg" in Unix style URIs, which again makes it less portable).

On Linux, I could not get relative paths to workat all and textures only seem load when absolute paths are given (which is obviously not portable).

Furthermore, the model geometry seems to be saved in a world file but textures are not, so that when models move in the file system, a gray untextured render remains.

Tested with Linux and Windows in Release R2021a but the same effect also occured in earlier releases.

**Comment by omichel** [comment]
Could you please post a simple example showing this problem: a ZIP file including a world file, a obj file and a texture?

**Comment by BenjaminDeleze** [comment]
I'm closing this for now, feel free to reopen it if you have additional issues.

**Comment by loicgirard** [comment]
Personnaly, I have this Boat.obj mesh, with its corresponding Boat.mtl . The mtl file points to .bmp files in the textures folder.

In WeBots I can only import the Boat.obj model using import 3D model or using 
`
geometry Mesh {
  
`
which appears white. So I don't understand how to add the .mtl so that the boat gets its textures. 

Here's the zip file.
[Fishing_Boat_obj.zip](https://github.com/cyberbotics/webots/files/8212987/Fishing_Boat_obj.zip)

**Comment by omichel** [comment]
The .mtl file is ignored by Webots indeed. Here is how to proceed:

1. You should convert your images to JPG format.
2. You should refer to these images in your [PBRAppearance](https://cyberbotics.com/doc/reference/pbrappearance) node.

See for example: [CorrugatedMetal.proto](https://github.com/cyberbotics/webots/blob/released/projects/appearances/protos/CorrugatedMetal.proto).

**Comment by omichel** [comment]
I believe the mapping is the following:
- occlusionMap: boat_ao.jpg
- normalMap: boat_normal.jpg
- baseColorMap: boat_diffuse.jpg
- roughnessMap: boat_gloss.jpg
- metalnessMap: boat_specular.jpg

**Comment by loicgirard** [comment]
I was also wondering how I could add the other textures, thanks! I was using Appearance to add boat_diffuse.jpg to the Mesh node, but the texture isn't matching, I explain:

In my case the textures aren't uniform and look like this: 

![image](https://user-images.githubusercontent.com/59942428/157456003-fd4ad99d-20e9-4f8d-ad50-e5a355f113d0.png)

When I add the boat_diffuse.jpg to the baseColorMap, I get the following result:

![image](https://user-images.githubusercontent.com/59942428/157455945-86f55630-1f71-4b5c-a951-0d4ffe6e458e.png)

I think I should change the position and orientation of the texture, I tried to move it with the TextureTransform node of the Appearance node, but I haven't found a match yet :/

**Comment by omichel** [comment]
Normally, the obj file should contain the texture mapping (texture coordinates). Can you open it successfully in a 3D modeling software like Blender?

**Comment by omichel** [comment]
I just tried and it works nicely in Webots for me:
![boat](https://user-images.githubusercontent.com/1264964/157472768-dc45ae0c-e273-4465-818b-536186a0f6cc.png)

**Comment by loicgirard** [comment]
Thanks omichel !

I am using 2021b, and I still have the texture not well put with your worlds.zip :( I guess it works only for >2022a-b

**Comment by omichel** [comment]
> I guess it works only on >2022a-b

Yes, I would recommend you to upgrade to Webots R2022a.
