### ISSUE TITLE
Pioneer P3AT model issue

### ISSUE THREAD

**Issue by mxf8bv** [cyberbotics/webots#2723]
Using the P3AT model, it rarely but repeatedly occurs that the wheels are attached off-center. Thus, when the robot drives it "wobbles" strongly. Reloading the removes the problem.

Tested in R2021a on Linux.

**Comment by lukicdarkoo** [comment]
Does it happen after the simulation reset or reload?

**Comment by mxf8bv** [comment]
I only remember it with certainty at one occasion: it happened after
loading and disappeared after reloading.

**Comment by BenjaminDeleze** [comment]
I'm closing this for now, feel free to reopen it if you have additional issues.
