### ISSUE TITLE
spherical Lidar/RangedFinder in Linux VMWare sometimes detects invisible 'walls' to left/right side

### ISSUE THREAD

**Issue by Thomas-Feldmeier** [cyberbotics/webots#2724]
![Lidar2](https://user-images.githubusercontent.com/73528085/107232851-35dc6280-6a22-11eb-82fb-3c66a88ecc5c.png)

In the picture you see the pointcloud of an lidar with max. range = 20m. To the left or right side of the lidar, it seems to detects a wall in exactly 1 meter distance. But there is no wall here. The measured data is wrong too (not only the pointcloud visualisation).

Spherical distances are measured by shooting several 'pictures' (Z-Buffer), one to the front, one to the left, one to the right. The front one is always correct, but the left or right one can be wrong. Most of the time left and right is wrong, but sometimes left or right or both are correct, this can change from one timeStep to another. 

Operation System: Linux Ubuntu 20.04 -> VMWare Workstation 16 Player (non-commercial or Pro) (virtual machine) -> Linux Ubuntu 20.04 (hardware acceleration on)

This bug does not happen if the same virtual machine (with linux) is started from the windows version of VMWare Workstation Player.
The bug does not happen if the hardware acceleration of the graphics card is turned off (in settings of the virtual machine in VMWare Workstation).

**Comment by omichel** [comment]
It is unfortunately a bug in VMWare Player. See comments in the [documentation](https://www.cyberbotics.com/doc/guide/general-bugs#virtualization) about it. I am afraid it has to be fixed on the WMWare side rather than in Webots.
