### ISSUE TITLE
Lidar point cloud is not shown if at least one ray exceeds maxRange

### ISSUE THREAD

**Issue by Thomas-Feldmeier** [cyberbotics/webots#2726]
If a lidar is in a small room, the point cloud of the lidar can be seen (if the option is turned on). But if the room is too big and some rays don't hit an obstacle unitl maxRange of that lidar, the point cloud is not show at all.

This bug is in Webots2021, but was not in Webots2020. In Webots 2020, if an ray exceeded the maxRange, the measured distance was some limited value, in Webots2021 this was changed to infinity, there is probably some infinity check missing in the lidar point cloud visualisation.

**Comment by omichel** [comment]
This bug was fixed [recently](https://github.com/cyberbotics/webots/pull/2666), if you download/install a nightly build, it shouldn't have the bug.
