### ISSUE TITLE
All of the 3D lidar sensor give back wrong Z-axis data by webots_ros

### ISSUE THREAD

**Issue by RENyunfan** [cyberbotics/webots#2730]
**Describe the Bug**

All of the 3D lidar sensors give back the wrong Z-axis data by webots_ros.

**Steps to Reproduce**
1. Create a new world and set some obstacles.
2. Creat a robot and add a 3d lidar sensor such as velodyneVLP-16.
3. Select the contoller as ros.
4. Use webots_ros to publish the point cloud.
5. Move the lidar to 1m (or 2m) above the ground.
6. See in rviz, the ground is -1.3 m ( -2.54m).

![image](https://user-images.githubusercontent.com/44119031/107491385-08301e80-6bc6-11eb-821f-20b9376b3f34.png)

![image](https://user-images.githubusercontent.com/44119031/107491870-b5a33200-6bc6-11eb-8768-4874f6b1ae43.png)

And I also test sick and VLP-64, the same thing happened, which is unreasonable.

I didn't write any code, the things just went wrong with ros service.

Any idea?

**Comment by RENyunfan** [comment]
I tested the point cloud in the x, y-axis, both of them are right, and I also have some z-axis sample:
```matlab

y = [-1.29139757156,-2.55461740494,-3.80381822586,-5.05427646637];
x = 1:4;
plot(x,-y,'*-')
```
and finally, find the scaler is close to 1.26-1.27.
![image](https://user-images.githubusercontent.com/44119031/107780675-f5624900-6d81-11eb-8fe4-0d121418782a.png)

Anyone can give some explanations?

**Comment by Simon-Steinmann** [comment]
@RENyunfan can you share your worldfile? That would make it much easier to troubleshoot.

**Comment by BenjaminDeleze** [comment]
I'm closing this for now, feel free to reopen it if you have additional issues.
