### ISSUE TITLE
Wrong joint data when setting up initial robot state

### ISSUE THREAD

**Issue by ipa-rwu** [cyberbotics/webots#2731]
**Describe the Bug**
I want to set up the initial UR5e state like this
![ur5e_in_cell](https://user-images.githubusercontent.com/54799760/107496609-d0a77f00-6b91-11eb-966e-c0f11c71629d.png)
Then I use ROS to control the robot. But I found all the joint data is 0

**Expected behavior**
I expect it should publish the current joint state.

**System**
 - Operating System: Linux Ubuntu 18.04

**Comment by lukicdarkoo** [comment]
Do you use the following package?
https://github.com/cyberbotics/webots/tree/114ef740e47613c8235022716d7cf0782e383f3a/projects/robots/universal_robots/resources/ros_package/ur_e_webots

**Comment by BenjaminDeleze** [comment]
I'm closing this for now, feel free to reopen it if you have additional issues.
