### ISSUE TITLE
Webots crashes when run the samples

### ISSUE THREAD

**Issue by tyc877** [cyberbotics/webots#2758]
**Describe the Bug**
Crashes happen when running the samples, the error code is 0xc0000279

**Steps to Reproduce**
1. Go to Webots
2. Click on samples
3. Run the samples

**Expected behavior**

**Screenshots**

**System**
 - Operating System: Windows 10 20H2
 - Graphics Card: NVIDIA GeForce GTX 1650Ti

**Additional context**

**Comment by lukicdarkoo** [comment]
You cannot run any sample on Windows?

**Comment by tyc877** [comment]
no, I cannot
0xc0000279 error happens

**Comment by tyc877** [comment]
The cpu is amd Ryzen7 4800H

**Comment by lukicdarkoo** [comment]
Can you turn off your antivirus software?

**Comment by tyc877** [comment]
There is no antivirus software except windows defender.

**Comment by tyc877** [comment]
And in the console, the messages are like "The process crashed some time after starting successfully" and "controller crashed".

**Comment by omichel** [comment]
OK, so it is not Webots that is crashing, but the controller program, right?

**Comment by tyc877** [comment]
you are right, it happens once I run the sample with the controller.

**Comment by tyc877** [comment]
May I know how to fix this problem?

**Comment by omichel** [comment]
It could be a DLL conflict: the controller which is launched by Webots loads a number of DLLs from Webots and from your system. If you have installed some third party software that put some DLL in the wrong way (like in the Windows system folder, which is bad), then, it may cause the Webots controllers program to crash. Did you install any special software on your PC?

**Comment by tyc877** [comment]
I installed Matlab, SolidWorks, and CoppeliaSim.
I guess I did not change any DLL files manually.
How can I check this DLLs problem and find which DLL is conflicted?

**Comment by omichel** [comment]
You can investigate with [dependency walker](https://www.dependencywalker.com/) on the binary file of a Webots controller that is crashing. It should list all the DLL used by the controller. They should be either Windows system DLL or Webots DLLs. If a a DLL is coming from another software, this is likely the culprit.

**Comment by tyc877** [comment]
Ok, I will try, thank you very much.

**Comment by omichel** [comment]
You should instruct dependency walker to search also in the Webots DLLs, i.e., in the `C:\Program Files\Webots\msys64\mingw64\bin\`, `C:\Program Files\Webots\msys64\mingw64\bin\cpp\` and `C:\Program Files\Webots\lib\controller\` folders.

**Comment by tyc877** [comment]
Ok, thank you very much.

**Comment by ad-daniel** [comment]
I'm closing this for now, feel free to reopen it if you have additional issues.

**Comment by tyc877** [comment]
Thank you very much!
