### ISSUE TITLE
4k UI upclaing or high DPI support

### ISSUE THREAD

**Issue by octorber123** [cyberbotics/webots#2773]
**Documentation page(s) concerned**
https://cyberbotics.com/doc/guide/general-faq

**What is the problem with the current documentation?**
Need a way to upscale the user interface for 4k or high dpi display. currently there is nothing in the documentation that has anything on the matter.

**Describe how you would fix it**
please write about how we can upscale the UI for webots so we can use it on High DPI monitors.

**Comment by omichel** [comment]
This was fixed [here](https://github.com/cyberbotics/webots/pull/2631).
