### ISSUE TITLE
Minor change in webots reference doc of Node chart 

### ISSUE THREAD

**Issue by bkpcoding** [cyberbotics/webots#2792]
**Documentation page(s) concerned**
https://cyberbotics.com/doc/reference/node-chart#inheritance

**What is the problem with the current documentation?**
I think that the documentation needs to state that the arrow head points to the derived node while the arrow tail starts with the base node. 
![Screenshot 2021-03-01 131815](https://user-images.githubusercontent.com/59369344/109467411-24223400-7a91-11eb-9406-1dd4cc5aab2f.png)

**Describe how you would fix it**
Again correct me if I am wrong. If the issue is fine then I think it's a good first issue for the new contributors.  They can just change the arrow head and tail part of the documentation by clicking the link above the documentation "Contribute on Github!".

**Comment by stefaniapedrazzi** [comment]
Yes, this is wrong and should be fixed as soon as possible.
But I would not wait for new contributors for such a minor change and I would fix it immediately.
If you won't do it yourself, we will do it.

**Comment by bkpcoding** [comment]
Oh okay, sure I will fix it immediately.

**Comment by stefaniapedrazzi** [comment]
Thank you!
