### ISSUE TITLE
What's the best default translation for a ball object?

### ISSUE THREAD

**Issue by omichel** [cyberbotics/webots#2828]
_Originally posted by @stefaniapedrazzi in https://github.com/cyberbotics/webots/pull/2783#discussion_r589554149_

> Usually the PROTO nodes we provide are by default added above the ground.
With this change the ball will be half below the ground.
Is this really wanted? Because version seems better and this is the only ball from the `objects/balls` section that is not located above the default ground position.

I am opening this issue to discuss this problem, before creating a PR to fix it.

If we want to fix it in a similar way as other ball proto, we should set a default value for the Y coordinate of the ball, equals to the radius of the ball. This has the following drawbacks:
- with ENU coordinate system, it simply doesn't work: we should set Z to the radius.
- if we change the size of the ball, we need to adjust the Y/Z value accordingly, which is not obvious in case of the FIFA ball because it's size (1-5) doesn't give directly the information on the radius.

The idea of setting the default translation value to 0 0 0 fixes the problem with ENU/NUE coordinate systems, but you will have to adjust the height of the ball so that it doesn't appear half in the ground.

Unlike other objects, a ball doesn't have a upside, so offsetting the center of the ball with its radius will not be good after the ball a rolled a little bit: its coordinates (translation field) will become confusing, given its center may be upside down or in between.

I could not find a good solution to this problem and I believe having 0 0 0 as the default position of a ball is something simple and understandable even though it requires to manually offset it from the ground when creating it out of the blue, which seems acceptable.

So, unless we find a better solution, I will fix all the balls we have in Webots to set them at 0 0 0 default position, like the RobocupSoccerBall and the FifaSoccerBall.

**Comment by Simon-Steinmann** [comment]
I think 0 0 0 is the most intuitive. Adding a new Object or solid, will place it at the origin of the parent. I think this consistency outweighs the "nice to have" feature of spawning an object at the "correct" height. If something like this would be added, I think it would require some LUA script to place it according to the coord-sys. And perhaps only, if it is a parent of root.

**Comment by omichel** [comment]
I believe this issue has been fully addressed in #2865.
