### ISSUE TITLE
Missing Lidar enpoint for libRemoteControl 

### ISSUE THREAD

**Issue by RTrioux** [cyberbotics/webots#2832]
Hi, I would like to use the remote control functions to print various real data from my robot.
I would also like to use display the lidar data on the scene. Unfortunately, the lidar endpoint in the 
"remote_control.h" seems to be missing. I can't see any "wrb_lidar_set_values..." functions.
Can you add an endpoint for that please ?

Thanks in advance for reading and considering this request :)

**Comment by omichel** [comment]
Unfortunately, this is not a priority on our roadmap. However, it shouldn't be difficult for you to implement it, if you take inspiration from what was done for the camera device. If you want to implement it yourself, we will be happy to review your contribution in a new Pull Request aiming at the develop branch. If you would like us to implement it for you, please contact sales@cyberbotics.com for an offer.
