### ISSUE TITLE
RoboCup Stadium is aligned "wrongly" and can not be rotated

### ISSUE THREAD

**Issue by jgueldenstein** [cyberbotics/webots#2848]
**Describe the Bug**
The RoboCup stadium is aligned with the y-axis pointing towards the goal. In the team communication protocol, it is defined that the x-axis points towards the goal (https://github.com/RoboCup-Humanoid-TC/RobocupProtocol/blob/1ab5585c33a83c2df9e2513995c60bc8860e67f5/robocup.proto#L39). That is why we would like to rotate it

The rotation of the field can not be changed for some reason, probably because it is autogenerated.

**Steps to Reproduce**
1. Open the RobocupSoccerField.proto field.
2. Enable "show coordinate system" (CTRL+F1)
3. Change the rotation field of the SoccerField node in the scene tree.

**Expected behavior**
x-axis points towards one of the goals or the world can be rotated.

**Screenshots**
![Screenshot from 2021-03-11 17-19-47](https://user-images.githubusercontent.com/31923619/110819099-26a13c80-828e-11eb-94fc-e04df709d7cc.png)
![Screenshot from 2021-03-11 17-20-24](https://user-images.githubusercontent.com/31923619/110819104-2739d300-828e-11eb-9591-7f7282ac5cdc.png)

**Comment by omichel** [comment]
Thank you for the feedback. We will fix this as soon as possible.

**Comment by omichel** [comment]
Fixed in #2851.

**Comment by jgueldenstein** [comment]
@omichel thank you for taking care of this so quickly
