### ISSUE TITLE
there is a bug :AttributeError: 'NoneType' object has no attribute 'setVelocity' when I copy the codes in the tutorial of official websites

### ISSUE THREAD

**Issue by LuranWang** [cyberbotics/webots#2853]
**Describe the Bug**

**Steps to Reproduce**

**Expected behavior**

**Screenshots**

**System**
 - Operating System: [e.g., Windows 10, Linux Ubuntu 18.04, macOS Mojave]
 - Graphics Card: [e.g., NVIDIA GeForce RTX 2080 11 GB, AMD Radeon RX 580 8GB, etc.]

**Additional context**

**Comment by omichel** [comment]
Too vague, useless.
