### ISSUE TITLE
Pedestrian crossing does not appear above a straight road

### ISSUE THREAD

**Issue by nelsondmmg** [cyberbotics/webots#2855]
**Describe the Bug**
Pedestrian crossing does not appear above a straight road

**Steps to Reproduce**
Adding the crossing by the add an object

**Expected behavior**
The crossing should be reproduced above the road

**Screenshots**
![pedStrips](https://user-images.githubusercontent.com/5951480/111165295-290dda00-859f-11eb-97ec-5f266132dbcb.png)

**System**
 - Webots R2021a revision 1
 - Operating System: Linux Ubuntu 20.04
 - Graphics Card: NVIDIA GeForce RTX 2060 mobile

**Comment by stefaniapedrazzi** [comment]
Note that this seems an issue due to the semi-transparent PNG image.
If the texture URL is changed to point to a JPG texture, then it works correctly and the texture is displayed in the scene.

**Comment by nelsondmmg** [comment]
The crossing was displayed correctly? Because I converted the crossing.png into a jpg and then changed the PROTO to point to the jpg version and this is the result:
![pedStrips2](https://user-images.githubusercontent.com/5951480/111167226-2ca26080-85a1-11eb-981c-31a5ce4639a3.png)

**Comment by stefaniapedrazzi** [comment]
I simply tested changing the texture and with JPG something was displayed but honestly didn't check if the JPG was displayed correctly.
So it could simply be that the texture mapping is wrong.

**Comment by stefaniapedrazzi** [comment]
The `PedestrianCrossing` PROTO has been broken by #2364.

**Comment by stefaniapedrazzi** [comment]
@nelsondmmg Thank you for reporting this issue.
The bug has been fixed in  #2857.
You can apply the changes to your local file or wait for the next nightly build of R2021a-rev1.
