### ISSUE TITLE
Control Webots installed on Windows using Linux Backend

### ISSUE THREAD

**Issue by veds12** [cyberbotics/webots#2896]
I am currently trying to get started with using Webots. Now, I prefer a Linux development environment but don't want to dual boot my machine either. So I use WSL for all my work. Unfortunately, WSL doesn't support any GUI. I tried using windows remote desktop as a gui and installed Webots on my WSL but the rendering seems to be very painful and slow. So I was wondering if there's any way that the graphical part of the simulator runs on windows while the controllers, etc. that I define (any backend in general) is running on WSL. If there's no way to do that currently, would be possible/feasible to add such a feature?

**Comment by omichel** [comment]
This is not possible and currently not in our roadmap, but if you want to contribute this feature, you are welcome.
