### ISSUE TITLE
Nao_demo_python

### ISSUE THREAD

**Issue by byr211568** [cyberbotics/webots#2933]
Error: wbu_motion_set_loop() called with NULL argument.
Error: wbu_motion_play() called with NULL 'motion' argument.
I'm sorry that i have some trouble,
i want to add something on the controller file calling "Nao_demo_python"
such as

 elif key == ord('1'):
                for i in range(3):
                    self.startMotion(self.forwards)

but it can't move for many times at one loop
what could i do?

**Comment by tarithj** [comment]
what are you trying to do?

**Comment by byr211568** [comment]
使nao机器人在一次键盘输入后从一点走到另一点




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Tarith ***@***.***&gt;; 
发送时间: 2021年4月2日(星期五) 凌晨0:16
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [cyberbotics/webots] Nao_demo_python (#2933)





 
what are you trying to do?

**Comment by ShuffleWire** [comment]
@omichel could we close this issue now ? it been 3 month ago...

**Comment by omichel** [comment]
Yes.
