### ISSUE TITLE
Incorrect lens distortion

### ISSUE THREAD

**Issue by jnoyola** [cyberbotics/webots#2934]
**Describe the Bug**
Lens distortion appears to incorrectly transform vertical lines. I only started experimenting with lens distortion today, so please correct me if I misunderstood, but based on the documentation and other resources I found, it appears incorrect.

**Steps to Reproduce**
1. Create a camera.
2. Add a lens.
3. Set the `radialCoefficients.x` to a positive value (e.g. 1).
4. Place an object in front of the camera and observe it near the left and the right of the image.

**Expected behavior**
Horizontal lines are bowed out from the center as expected.
Vertical lines on the right side of the image are bowed out from the center as expected.
Vertical lines on the left side of the image should also be bowed out from the center, but instead remain vertical.

![image](https://user-images.githubusercontent.com/4064932/113399010-5b1b8c00-9354-11eb-8bbe-5234d3abbbec.png)

**Screenshots**
When the object is near the right of the image, it appears as expected.
![image](https://user-images.githubusercontent.com/4064932/113389662-44216d80-9345-11eb-97d5-81fd61542a21.png)
When the object is near the left of the image, vertical lines remain vertical. Note the right side of the checkerboard in fact bows to the left.
![image](https://user-images.githubusercontent.com/4064932/113389872-9bbfd900-9345-11eb-8fe0-f12593f4a7d1.png)

**System**
 - Operating System: Windows 10
 - Graphics Card: NVIDIA GeForce RTX 2080 8 GB

**Additional context**
Not sure if it's related, but sources such as [this](https://www.sciencedirect.com/topics/engineering/lens-distortion) suggest that barrel distortion would have a negative K<sub>1</sub>, but that appears to create pincushion distortion in Webots.

**Comment by omichel** [comment]
Relates with #2295.
