### ISSUE TITLE
Webots urdf/proto resource

### ISSUE THREAD

**Issue by anastasiapan** [cyberbotics/webots#2948]
Hello
I recently saw a related post on ROS Discourse (https://discourse.ros.org/t/urdf-with-webots/19665) that you plan to migrate from PROTO to urdf. My question is about the features only available in PROTO. The reason I post here and not on Discourse is because I didn't want to derail the conversation there.

So the problem is that we use the [connector](https://cyberbotics.com/doc/reference/connector) and to make that work with urdf we found a solution but it is a bit "hacky" and it uses a gazebo feature:

```xml
<gazebo>
    <joint name="rod_joint" type="fixed">
      <pose>0.285 0 0 0 0 0</pose>
      <parent>base_front_rod</parent>
      <child>base_back_rod</child>
    </joint>
  </gazebo>

  <!-- GAZEBO control -->
  <gazebo>
    <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so">
      <robotNamespace>$(arg robot_namespace)</robotNamespace>
    </plugin>
  </gazebo>
```
PROTO:
```
 device [
	 RotationalMotor {
                  name "base_front_rod_joint"
                  maxVelocity 2.0
                  minPosition -0.35
                  maxPosition 0.35
                  maxTorque 40
                }
                PositionSensor {
                  name "base_front_rod_joint_sensor"
                }
              ]
              endPoint Solid {
                translation -0.005330 0.200000 0.044680
                rotation 0.000000 -1.000000 0.000000 3.378992
				children [
                  Connector {
                    translation 0.17271 0 0
                    name "connector_front_rod"
                    model "connector_rod"
                    isLocked TRUE
                    autoLock TRUE
                  }
				]
```
Would it be possible to simulate the connector in as similar way with urdf? I am asking now because I am trying to be a bit proactive and see if PROTO file utilities will be gone. I can provide with both urdf or proto if you want.

**Comment by lukicdarkoo** [comment]
We haven't decided on the architecture yet, but we plan to add a `<webots>` tag and put everything Webots specific inside:
https://github.com/cyberbotics/urdf2webots/issues/112

That means that Connectors, as well as other Webots specific devices, will be preserved.

We don't have plans on dropping the PROTO support, it will still be the native format.

**Comment by anastasiapan** [comment]
Thank you very much for your response! I just misunderstood the post on Discourse then.
