### ISSUE TITLE
New to webots, e-puck issue with jerky movement and laggy graphics on 3080

### ISSUE THREAD

**Issue by Evanj1034** [cyberbotics/webots#2975]
Hi all,

I am using the e-puck sample bot with the collision detection and pulling accelerometer data for further data analysis. I am using matlab for the code since my school gets paid A LOT of money to use them, and therefore cannot use Python like any other sensible person would (only joking a little bit ;). 

I can post my code, but would like to limit how much I post since this is a project for school, and I do not want classmates to find this and plagiarize.

https://user-images.githubusercontent.com/65079008/114878236-081eeb80-9dce-11eb-818d-019ac1878b85.mp4

**Comment by omichel** [comment]
That's not a Webots issue, bug or feature request. Please use our Discord channel or the GitHub Discussions if you need help.
