### ISSUE TITLE
Can't use right wheel motor on e-puck

### ISSUE THREAD

**Issue by GilangRama** [cyberbotics/webots#3004]
I can't use right wheel motor to turn right in webot, but when I use left wheel instead of right wheel It can turn right properly.

here's the code

#include <webots/robot.h>
#include <webots/motor.h>

#define TIME_STEP 64

int main(int argc, char **argv) {

  wb_robot_init();

  WbDeviceTag motorkanan=wb_robot_get_device("right wheel motor"); //cannot turn right

  wb_motor_set_position(motorkanan, INFINITY);

  while (wb_robot_step(TIME_STEP) != -1) {
  

  wb_robot_cleanup();

  return 0;
}

**Comment by omichel** [comment]
That not an issue, but a technical question. Please use GitHub Discussions or Discord instead to ask the community or subscribe to a Premier service plan to get official technical user support.
