### ISSUE TITLE
Reset from GUI still not working on certain cases

### ISSUE THREAD

**Issue by ad-daniel** [cyberbotics/webots#3051]
**Describe the Bug**
As it surfaced here #3036, some issues persist on the master branch regarding the reset.

How to reproduce:
1. Load the ` tests/protos/worlds/nested_parameter_transform_node.wbt ` world.
2. Run it and notice the PROTO node move.
3. Reset. The node doesn't return to the initial position.

It's unclear what about it makes it fail, the specific case is a heavily nested PROTO with multiple instances.

**Comment by ShuffleWire** [comment]
I have another case : 
Using situation described in https://github.com/cyberbotics/webots/issues/3163
Proceed until step 4 (create model and controller, and remove the JointParameters)
Run simulation, cylindre should move.
Pause the simulation.
Restart the simulation.
Cylinder don't go back to the original position.
BUT
Hit a few time the "Execute one simulation step" button, and the cylinder will eventually go back to position. Note that when it come back, it doesn't go at the position 0, but a bit more, like if the simulation have been actually running during those few step, and the cylinder "catch up" to the correct position only at this moment.
