### ISSUE TITLE
Add a previous / next button in documentation

### ISSUE THREAD

**Issue by ShuffleWire** [cyberbotics/webots#3075]
**Feature**
When I browse the documentation using the integrated viewer, I often wish to go back and forth between articles have just read. However, there is not such thing. 
Ex : Reading stuff about `Linear motor`, use a link in page to get to `Motor`, and I can't go back easily to `Linear motor` when I'm done reading article about `Motor`. (I need to find a link the `Linear motor`, which is not handy, or impossible if their is none. Or browse again the documentation)

**Solution**
I wish we could have something like in browser (go back to previous page, go forward in next page)

**Comment by omichel** [comment]
We plan to actually delete the offline documentation.
