### ISSUE TITLE
Stuck on "Loading World" - R2021a

### ISSUE THREAD

**Issue by UnleashedGH** [cyberbotics/webots#3091]
**Describe the Bug**
Webots gets stuck on "Loading World" after running the program.

**Steps to Reproduce**
1- Run Webots
2-Stuck on "Loading World", nothing is rendering

OR

1-Run Webots
2-Go to Wizard -> New Project Directory and create a new project
3-Stuck on "Loading World", nothing is rendering

**Expected behavior**
For the scene to render

**Screenshots**
![image](https://user-images.githubusercontent.com/47185022/119493018-66919f00-bd68-11eb-88dc-5b7258bb9d43.png)
(I get weird artifacts when I move windows around, seems that the viewport doesn't refresh correctly

**System**
 - Operating System: Windows 10 - 64 Bit
 - Graphics Card: Intel (R) HD Graphics

**Additional context**
It's worth noting that there is no CPU usage when "Loading World" appears, it doesn't seem that the program is actually loading anything but rather crashing, maybe not the entire program but at least the view port seems so.
objects also appear in the Scene Tree.

I followed the troubleshooting guide in regards to running in Safe Mode, with that I got the view port to render; I was able to add a background with a blue sky color , along with a table object; I was able to move, rotate, and zoom the camera with no issues

however, when I get to Wizard -> New Project Directory and create a new project, I get stuck on "Loading World" once again.
and also the objects appear in the Scene Tree.

**Comment by omichel** [comment]
This problem is likely due to your GPU which is below the recommended requirements for Webots. Can you try it on a computer with a NVIDIA GPU?

**Comment by UnleashedGH** [comment]
> This problem is likely due to your GPU which is below the recommended requirements for Webots. Can you try it on a computer

Only have access to this one.
I also have all OpenGL settings set to absolute lowest
![image](https://user-images.githubusercontent.com/47185022/119524461-55f02180-bd86-11eb-83a3-b0b25df97038.png)

I understand that its quite an extreme stress test, but I'm just confused on why the scene would render and function correctly when I'm on safe mode and no project opened
no lag or framerate issues either

**Comment by ShuffleWire** [comment]
I'm taking the opportunity to link this https://github.com/cyberbotics/webots/issues/3065 issue, don't know if it's related in anyway, but still.

**Comment by UnleashedGH** [comment]
> This problem is likely due to your GPU which is below the recommended requirements for Webots. Can you try it on a computer with a NVIDIA GPU?

I was able to narrow down the issue, it's because of the **TexturedBackground (Background)** Node
once I add it in a scene, even if its completely empty, the render crashes (white screen and other graphical artifacts)
![image](https://user-images.githubusercontent.com/47185022/119587795-15b98f00-bdd8-11eb-9ec2-bd3657078354.png)

however, if i just add a **TexturedBackgroundLight (DirectionalLight)** instead, scene renders correctly with no issues
i can add objects, move the camera, etc
![image](https://user-images.githubusercontent.com/47185022/119588121-ccb60a80-bdd8-11eb-8064-e9f7be8370e6.png)

the problem is that Wizard -> New Project Directory adds the Node by default, is there a way I can workaround that to prevent it from being added?

**Comment by ShuffleWire** [comment]
You can untick it in the world creation window : 
![image](https://user-images.githubusercontent.com/83014015/119613323-2defd500-bdfd-11eb-84c0-13a6cfe197f6.png)

**Comment by lukicdarkoo** [comment]
> * Graphics Card: Intel (R) HD Graphics

What is the generation of the Intel CPU?

**Comment by ShuffleWire** [comment]
> > * Graphics Card: Intel (R) HD Graphics
> 
> What is the generation of the Intel CPU?

I wish to say that even on a very old CPU (on my laptop I've a Intel 2020M, with onboard graphic being very old), it work nicely (not saying it's fast by any mean, but stable and functional :) )
Thus, I'm not sure if the integrated graphic are to blame, here. But hardware 3D rendering could be a mess, still...

**Comment by UnleashedGH** [comment]
> You can untick it in the world creation window :
> ![image](https://user-images.githubusercontent.com/83014015/119613443-5677cf00-bdfd-11eb-9694-cb7d147d042e.png)

Wow, I completely missed those options
Thank you



> > * Graphics Card: Intel (R) HD Graphics
> 
> What is the generation of the Intel CPU?

Intel(R) Celeron(R) CPU N3060 @ 1.60Hz

**Comment by lukicdarkoo** [comment]
> I wish to say that even on a very old CPU (on my laptop I've a Intel 2020M, with onboard graphic being very old), it work nicely (not saying it's fast by any mean, but stable and functional :) )
> Thus, I'm not sure if the integrated graphic are to blame, here. But hardware 3D rendering could be a mess, still...

I suspected that some OpenGL features are not present in the old integrated GPUs, but this should not be the case for this given CPU:
https://en.wikichip.org/wiki/intel/celeron/n3060

**Comment by omichel** [comment]
In any case, these old integrated GPUs are known to have random OpenGL bugs and this is why they are not officially supported by Webots.

**Comment by ShuffleWire** [comment]
> In any case, these old integrated GPUs are known to have random OpenGL bugs and this is why they are not officially supported by Webots.

It make sense, as far as I've experienced, it work, but sometimes it get crazy

**Comment by ShuffleWire** [comment]
@UnleashedGH did unticking "textured background" fix your issue ?

**Comment by UnleashedGH** [comment]
> @UnleashedGH did unticking "textured background" fix your issue ?

yes

**Comment by ShuffleWire** [comment]
As the solution seems to be a sufficient workaround, and the question related to non--GPU usage, we might close this issue, @omichel ?
