### ISSUE TITLE
Mismatching tag in connector documentation

### ISSUE THREAD

**Issue by ShuffleWire** [cyberbotics/webots#3094]
**Documentation page(s) concerned**
https://www.cyberbotics.com/doc/reference/connector

**What is the problem with the current documentation?**
The link "this figure" in "Field Summary" don't actually link to the figure, because the tag of the figure is wrong
![image](https://user-images.githubusercontent.com/83014015/119619958-cdfd2c80-be04-11eb-95d4-eb3049a1eb1e.png)

**Describe how you would fix it**
It would just be necessary to change the tag of the image from `#example-of-rotational-alignment-numberofrotations4-and-rotationaltolerance22-5-deg` to `#example-of-rotational-alignment` , but I don't know how/where to do that, if anyone could drive me :)

**Comment by ShuffleWire** [comment]
Should I change 

`[this figure](#example-of-rotational-alignment)`
to 
`[this figure](#example-of-rotational-alignment-numberofrotations4-and-rotationaltolerance22-5-deg)`

or 

`%figure "Example of rotational alignment (numberOfRotations=4 and rotationalTolerance=22.5 deg)"`
to
`%figure "Example of rotational alignment"`

Changing the first force to make a strange looking tag, but changing the second will remove interesting information for the reader.

**Comment by ShuffleWire** [comment]
BTW, what the difference between `released` and `master` ?

**Comment by stefaniapedrazzi** [comment]
`released` is only used for documentation fixes.

**Comment by stefaniapedrazzi** [comment]
Thank you!

I will now check and fix the test error.

**Comment by stefaniapedrazzi** [comment]
Fixed in #3095
