### ISSUE TITLE
Bluetooth remot control failed between webot and epuck

### ISSUE THREAD

**Issue by younesJR** [cyberbotics/webots#3107]
i'm trying to control epuck2 robot with webot using matlab code , the simulation in webot worked successfully but when it comes to real implementation i get the "bluetooth connexion failed ", eventhough when i run the botstudio example, it worked perfectly with the real epuck2.

for the system , i use webot 2021a and matlab 2018a 64bit

**Comment by BenjaminDeleze** [comment]
I'm closing this for now, feel free to reopen it if you have additional issues.
