### ISSUE TITLE
how to get a device when I use supervisor?

### ISSUE THREAD

**Issue by hanm2019** [cyberbotics/webots#3111]
**Describe the Bug**
There are a conveyor_belt and a ur10e robot in my webots env, I set ur10e's controller as extern, and I want to get the kinect image which is a children on the conveyor_belt.

**Steps to Reproduce**
code:
```
from controller import Camera
from controller import PositionSensor
from controller import Supervisor

robot = Supervisor()

# Get the time step of the current world.
timestep = int(robot.getBasicTimeStep())

conveyor_belt = robot.getFromDef("CONVEYOR_BELT")
assert(conveyor_belt != None)
conveyor_kinectcolor = conveyor_belt.getDevice("kinect color")
conveyor_kinectcolor.enable(int(1000/24))
conveyor_kinectcolor.getImage()
```
get the error:

```
   conveyor_kinectcolor = conveyor_belt.getDevice("kinect color")
  File "/usr/local/webots/lib/controller/python27/controller.py", line 1756, in <lambda>
    __getattr__ = lambda self, name: _swig_getattr(self, Node, name)
  File "/usr/local/webots/lib/controller/python27/controller.py", line 96, in _swig_getattr
    raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))
AttributeError: 'Node' object has no attribute 'getDevice'
```

**Expected behavior**

get the kinect and enable it

**Screenshots**
![图片](https://user-images.githubusercontent.com/56673361/120179409-1f5e4f00-c23d-11eb-9428-9bc8e744b5a4.png)

**System**
 - Operating System:  Linux Ubuntu 18.04
 - Graphics Card:  NVIDIA GeForce RTX 1080 11 GB]

**Comment by stefaniapedrazzi** [comment]
Please use the discord channel for questions and asking for help.
