### ISSUE TITLE
outdated robot tooltip

### ISSUE THREAD

**Issue by Thomas-Feldmeier** [cyberbotics/webots#3115]
resources/nodes/Robot.wrl:

```
The Robot node is a generic type of robot.
If you would like to build a two-wheeled robot you may prefer using a DifferentialWheels node.
If you would like to build a robot with supervisor capabilities use the Supervisor node instead (Webots PRO license required).
```

This text is displayed if a user is hovering the mouse over an robot node in the scene tree.
DifferentialWheels node is deprecated, there is no supervisor node any more(supervisor is a boolean flag of robot node), webots is free so no PRO license required.

Delete the last 2 lines.
Maybe add some other info.

**Comment by mael25** [comment]
Thank you @Thomas-Feldmeier for raising the issue, it has been fixed in #3117.
