### ISSUE TITLE
node.js 15 deprecation notice

### ISSUE THREAD

**Issue by ad-daniel** [cyberbotics/webots#3145]
**Description**
While compiling from source on a clean system I got this notice:

![Screenshot from 2021-06-08 14-54-17](https://user-images.githubusercontent.com/44834743/121188524-7e3d4d00-c869-11eb-82a2-69877fc7a794.png)

**Comment by omichel** [comment]
I believe nodejs is not needed any more (at least on the develop branch).
So, we can safely ignore this warning on the master branch and should get rid of it on the develop branch.
