### ISSUE TITLE
The Windows nightly build is broken

### ISSUE THREAD

**Issue by omichel** [cyberbotics/webots#3179]
I guess the problem was introduced in #3087:
```bash
Error on line 2301 in D:\a\webots\webots\scripts\packaging\webots.iss: Source file "D:\a\webots\webots\resources\javascript\modules" does not exist.
```

See full log [here](https://github.com/cyberbotics/webots/runs/2834339850?check_suite_focus=true).

**Comment by ad-daniel** [comment]
Appears to be working now, so I'm closing this issue.
