### ISSUE TITLE
Robot window layout in robotbenchmark simulations is broken

### ISSUE THREAD

**Issue by stefaniapedrazzi** [cyberbotics/webots#3182]
Info window layout in robotbenchmark simulation is broken and the tabs are no longer correctly displayed.
I would expect that after compiling webots from the main Makefile all the simulation works correctly including these ones.
![robotbechmark_info_window](https://user-images.githubusercontent.com/5910449/122199960-e0660580-ce9a-11eb-8ed4-2fe0e4fc2b8a.png)

**Comment by BenjaminDeleze** [comment]
It seems to be because we removed JQuery. I will replace the expressions with pure JS ones
