### ISSUE TITLE
Node deletion and reset behavior

### ISSUE THREAD

**Issue by ad-daniel** [cyberbotics/webots#3208]
**Describe the Bug**
To reproduce:

- open `stewart_platform.wbt` but don't run the world.
- delete the cardboard boxes
- reset. The boxes don't return.

Same thing happens if you run the world a few seconds after the deletion and then reset.

The behavior appears to be present both in master and 2021a, so it doesn't appear to be a regression, but I don't think it's supposed to behave like this.

**Comment by lukicdarkoo** [comment]
This expected behavior (see `Adds removed nodes`):
https://cyberbotics.com/doc/reference/supervisor?version=develop#resetreload-matrix

I am even using it as a feature :)

**Comment by ad-daniel** [comment]
You learn something new everyday, that table is quite useful actually. Should use the develop version of the docs more often, thanks!
