### ISSUE TITLE
Support in ROS2

### ISSUE THREAD

**Issue by talregev** [cyberbotics/webots#321]
The 4th ROS2 distribution is go out in May.   
Can you also support ROS2?

**Comment by DavidMansolino** [comment]
This is indeed on our roadmap, we are currently investigating the possibility to support ROS2 in Webots.
Of course, any help is welcome.

**Comment by DavidMansolino** [comment]
Just for the note, there are progresses with the support of ROS2 on universal robot side: https://github.com/ros-industrial/ur_modern_driver/issues/244#issuecomment-503068616
And people complaining that meshes are looking bad in gazebo: https://github.com/ros-industrial/universal_robot/issues/425
:wink:

**Comment by DavidMansolino** [comment]
Just for the note, we are progressing on this front on this repo: https://github.com/cyberbotics/webots_ros2

**Comment by DavidMansolino** [comment]
I believe we can close this issue as it is currently in active development in https://github.com/cyberbotics/webots_ros2
