### ISSUE TITLE
Issue with empty PROTO

### ISSUE THREAD

**Issue by ShuffleWire** [cyberbotics/webots#3217]
**Describe the Bug**
I can't load loading the following proto, Webots issue : "error: Bracket issue."
if I put anything inside (an empty group node, for instance), I get it working.

#VRML_SIM R2021a utf8

PROTO EmptyProto [
]
{
}

Not that painful, because empty proto are not that useful, but may hide something else.

**Comment by ad-daniel** [comment]
I wouldn't say it's a bug as a PROTO like this isn't a valid PROTO to begin with as it lacks the BaseNode (which is required). Hence why adding a `Group` in the body works just fine (Group being the BaseNode). As it lacks one, no corresponding node can be created.
