### ISSUE TITLE
Mavic propellers are broken in R2021b

### ISSUE THREAD

**Issue by lukicdarkoo** [cyberbotics/webots#3245]
![image](https://user-images.githubusercontent.com/2135826/123927204-e5dc4900-d98c-11eb-9737-2647fa504b7b.png)
(left R2021b, right R2021a)

**Comment by stefaniapedrazzi** [comment]
Just for note it seems to work correctly for me on my development system and with the latest nightly build of R2021b.

**Comment by stefaniapedrazzi** [comment]
But I can reproduce this in #2787.

**Comment by lukicdarkoo** [comment]
Testing it again appears to be only the case for #2787, thank you for the correction.

**Comment by omichel** [comment]
Can we close this issue?
