### ISSUE TITLE
Deprecated warning in highway_driving benchmark 

### ISSUE THREAD

**Issue by stefaniapedrazzi** [cyberbotics/webots#3248]
This warning is now displayed in the `highway_driving` benchmark:
```
Warning: wb_supervisor_node_get_number_of_contact_points() is deprecated, use wb_supervisor_node_get_contact_points() instead.
```

The controller should be updated to use the new methods.

**Comment by stefaniapedrazzi** [comment]
Other simulations also needs to be updated, for example the `obstacle_avoidance` benchmark.

**Comment by ad-daniel** [comment]
does it also need to be removed from the test suite or just when it is no longer supported? Currently the test checks both the old and new method

**Comment by stefaniapedrazzi** [comment]
> does it also need to be removed from the test suite or just when it is no longer supported? Currently the test checks both the old and new method

It is ok to keep both in the tests.
