### ISSUE TITLE
Improve information displayed in Preferences > Network > Cache dialog

### ISSUE THREAD

**Issue by stefaniapedrazzi** [cyberbotics/webots#3252]
Following #2787:
It would be more user-friendly to enhance the preferences dialog so that is doesn't display just the maximum size of the cache, but also the size currently in use.
Otherwise, even after pressing the button to clear the cache there is no real feedback (other than the automatic message) that shows that the cache has been really deleted.

**Comment by ad-daniel** [comment]
Implemented in https://github.com/cyberbotics/webots/pull/3342
