### ISSUE TITLE
icon_creator: controller is crashing

### ISSUE THREAD

**Issue by stefaniapedrazzi** [cyberbotics/webots#3268]
On my Ubuntu 18.04 system, the `icon_creator` controller is crashing when processing the image to auto-crop it and remove the background.

Error:
```
Traceback (most recent call last):
  File "icon_creator.py", line 324, in <module>
    background=background, colorThreshold=colorThreshold)
  File "icon_creator.py", line 225, in process_object
    colorThreshold, shadowColor, postfix)
  File "icon_creator.py", line 83, in take_screenshot
    pilImage = autocrop(pilImage)  # cropped at an early stage to save lot of CPU resources.
  File "icon_creator.py", line 74, in autocrop
    assert False, "Impossible to crop image"
AssertionError: Impossible to crop image
WARNING: 'icon_creator' controller exited with status: 1.
```

**Comment by mael25** [comment]
I tried on my virtual machine (Ubuntu 18.04.5 LTS) with R2021b-rev1 but I cannot reproduce the issue...

**Comment by stefaniapedrazzi** [comment]
I checked on a Ubuntu 20.04 VM and it is also working properly.

**Comment by stefaniapedrazzi** [comment]
It seems that the problem is the version of the `pillow` library:
* pillow 7.0.0 works correctly
* pillow 8.1.0 doesn't work (previously installed on my development system)

**Comment by stefaniapedrazzi** [comment]
In Pillow 7.1.0 the behavior of `Image.getbbox` changed:
https://pillow.readthedocs.io/en/stable/releasenotes/7.1.0.html#if-present-only-use-alpha-channel-for-bounding-box
