### ISSUE TITLE
radar.wbt not detecting any target

### ISSUE THREAD

**Issue by stefaniapedrazzi** [cyberbotics/webots#3270]
The `radar.wbt` simulation is expected to print in the console the detected targets.
But nothing is printed for R2021b.

**Comment by ad-daniel** [comment]
I can't reproduce it with ubuntu 20. Even with today's merges it still appears to be working. I'll test on windows soon.

**Comment by ad-daniel** [comment]
![radar](https://user-images.githubusercontent.com/44834743/124148677-283a7e80-da90-11eb-85fe-6173227b7a1d.PNG)

Appears to be working on windows too.

**Comment by stefaniapedrazzi** [comment]
You are right. It works correctly.
The problem was due to conflicts between version running world and Webots coming from different versions.
