### ISSUE TITLE
Controller crashes when deleting robot in display.wbt

### ISSUE THREAD

**Issue by stefaniapedrazzi** [cyberbotics/webots#3274]
The following error messages are printed in the console after deleting the robot in `display.wbt`:
```
WARNING: display_supervisor: The process crashed some time after starting successfully.
display_supervisor: request.c:181: request_is_over: Assertion `r->pointer <= request_get_size(r)' failed.
WARNING: 'display_supervisor' controller crashed.
```

It would be expected that the controller is terminated without errors.

**Comment by lukicdarkoo** [comment]
I am not getting that error but:
```
WARNING: SolidBox (PROTO) > DEF SQUARE_ARENA_APPEARANCE_A PBRAppearance > ImageTexture: 'webots://projects/default/worlds/textures/metal.jpg' not found.
A resource file can be defined relatively to the worlds directory of the current project, relatively to the worlds directory of the default project, relatively to its protos directory (if defined in a PROTO), or absolutely.
```

**Comment by stefaniapedrazzi** [comment]
Note that if you want to test in the same environment as in the release package you should first run `scripts/package/update_worlds_and_protos.py`.

Otherwise make sure that the world you are opening is located in the same folder as the Webots main application.

**Comment by ad-daniel** [comment]
I can't seem to reproduce it on ubuntu 20.

**Comment by BenjaminDeleze** [comment]
I can reproduce it on Ubuntu 20 (delete the robot named MYBOT, not the one named robot)
