### ISSUE TITLE
Guided Tour related bugs/improvements

### ISSUE THREAD

**Issue by ad-daniel** [cyberbotics/webots#3276]
**Describe the Bug**
This is to assemble issues related to the guided tour. Some might not be bugs or non-important, so can be skipped.

- [x] `khepera3gripper.wbt`: after doing the task, it goes to and gets stuck in a corner for a while before freeing itself. Might not be an issue, but could warrant changing the time spent on this world in the guided tour. (in auto)
- [x] `ure.wbt`: robot places can between two baskets and that ends up messing the scene later.
- [x] `naoroom.wbt`: `WARNING: Background: Texture dimension mismatch between leftUrl and rightUrl.` Fixed in #3323
- [x] `hoap2_walk.wbt`: falls off the table, simulating 20s for this is sufficient. (if auto)
- [ ] `brake.wbt`: bloom or blurriness between the spikes. EDIT: due to activating occlusion in the settings.
- [x] `sick_point_cloud.wbt`: good old lidar bug.

**Comment by BenjaminDeleze** [comment]
@ad-daniel can we close this?

**Comment by ad-daniel** [comment]
Yes.
