### ISSUE TITLE
Altimeter should included in the "Device tour"

### ISSUE THREAD

**Issue by omichel** [cyberbotics/webots#3278]
Ditto

**Comment by ad-daniel** [comment]
Do all worlds in the devices folder need to be included? If so `coupled_motors`, `hinge_joint_with_backlash` and ``hinge_2_joint_with_backlash` need to be added as well.

**Comment by omichel** [comment]
> Do all worlds in the devices folder need to be included? If so `coupled_motors`, `hinge_joint_with_backlash` and `hinge_2_joint_with_backlash` need to be added as well.

Yes, that would be nice.
