### ISSUE TITLE
Weird formatting of the `preferences > network tab`

### ISSUE THREAD

**Issue by ad-daniel** [cyberbotics/webots#3280]
**Describe the Bug**

![preferences](https://user-images.githubusercontent.com/44834743/124238348-c4a86380-db18-11eb-8412-d5a1d38eb608.PNG)

On windows. Resizing it has no effect on it.

**Comment by omichel** [comment]
With the default theme, it seems OK:
![image](https://user-images.githubusercontent.com/1264964/124239688-3f25b300-db1a-11eb-8eb5-b42849bfb43a.png)
