### ISSUE TITLE
The settings menu in the robot window shows warnings

### ISSUE THREAD

**Issue by lukicdarkoo** [cyberbotics/webots#3286]
**Steps to Reproduce**
1. Open the Spot example
2. Open the robot window
3. Click `Camera`
4. Click `Settings`
4. See `[javascript] Uncaught TypeError: Cannot convert undefined or null to object (window_manager.js?216_0:50)`

**System**
 - Operating System: macOS Big Sur

**Comment by mael25** [comment]
This has just been solved in #3272, but has been merged to master as the package was already crated

**Comment by omichel** [comment]
Fixed in #3272.
