### ISSUE TITLE
Autofocus doesn't work

### ISSUE THREAD

**Issue by lukicdarkoo** [cyberbotics/webots#3288]
**Steps to Reproduce**
1. Open the camera_auto_focus.wbt world
2. There are some attempts to autofocus, but it doesn't work properly

**System**
 - Operating System: macOS Big Sur

**Comment by stefaniapedrazzi** [comment]
This seems the same issue already reported here: #1976.
It doesn't seem a regression.

**Comment by omichel** [comment]
I closing this issue as it is better documented in #1976.
