### ISSUE TITLE
The HTML5 animation doesn't work with Safari

### ISSUE THREAD

**Issue by lukicdarkoo** [cyberbotics/webots#3289]
**Steps to Reproduce**
1. Record a HTML5 animation
2. Start a server `python3 -m http.server`
3. Open http://127.0.0.1:8000
4. The loader hangs indefinitely (the same page works fine with Chrome)

**System**
 - Operating System: macOS Big Sur

**Comment by omichel** [comment]
This is expected. Safari doesn't support webgl2. Maybe we should better document this or display a warning if Safari is detected, that invite users to use Firefox, Brave or Chrome.
