### ISSUE TITLE
Relocating the salamander example doesn't work

### ISSUE THREAD

**Issue by omichel** [cyberbotics/webots#3292]
This is because the skins folder is not copied.

**Comment by ad-daniel** [comment]
> We should make the comments clearer about these two methods (copyExternalProject and copyProject) which are quite hard to understand what they do and more importantly why.

Also, it should be checked if the conclusions drawn https://github.com/cyberbotics/webots/pull/3368 are indeed valid and if not, add the copying of the skins folder also to `copyExternalProject` as it was done for `copyProject`.

**Comment by stefaniapedrazzi** [comment]
Remaining issues addressed in #3398
