### ISSUE TITLE
Loading some old worlds (from R2021a) fails to load textures

### ISSUE THREAD

**Issue by lukicdarkoo** [cyberbotics/webots#3301]
Loading some old worlds fails to load certain resources and displays warnings.

**Steps to Reproduce**
1. Open `projects/vehicles/worlds/village.wbt` from R2021a
2. See the missing textures and warnings:
    ```
    WARNING: Floor (PROTO) > PBRAppearance > ImageTexture: 'textures/grass.jpg' not found.
    A resource file can be defined relatively to the worlds directory of the current project, relatively to the worlds directory of the default project, relatively to its protos directory (if defined in a PROTO), or absolutely.
    ```

**System**
 - Operating System: macOS Big Sur

**Comment by omichel** [comment]
One solution to fix this issue would be to create a dictionary of textures of R2021a that would point to the corresponding R2021a URLs and Webots would make the conversion when trying to open a texture or mesh that doesn't exist locally and the world/proto file is < R2021b.

However, I am not sure it is worth implementing this. Maybe we could simply document it in the change log and/or display a warning when opening an old world file or proto file that explains that texture paths should be replaced with URLs.
