### ISSUE TITLE
Using ROS instructions

### ISSUE THREAD

**Issue by mael25** [cyberbotics/webots#3304]
**Describe the Bug**
In the [Installing ROS and "webots_ros" Package](https://www.cyberbotics.com/doc/guide/tutorial-8-using-ros#installing-ros-and-webots_ros-package) instructions of the User Guide, at points 3, 5 and 6, the path given use `melodic`.

It might be good to highlight the fact that it has to be changed according to the ROS distribution installed and/or put `noetic` instead.

**Comment by lukicdarkoo** [comment]
We should also delete `kinetic` as it is not supported anymore.
