### ISSUE TITLE
Thinkerbots `vision_car.wbt` and Tinkerbots `braintenberg.wbt` controllers need adjusting.

### ISSUE THREAD

**Issue by ad-daniel** [cyberbotics/webots#3309]
**Describe the Bug**
They're supposed to stop before an obstacle or to avoid it but they don't.

**Comment by omichel** [comment]
Replacing the PbrAppearance of the SolidPipe with a standard Appearance seems to resolve the problem. That means that the infra-red factor of the distance sensor is probably wrongly computed with PbrAppearance.
