### ISSUE TITLE
Python example controllers crash

### ISSUE THREAD

**Issue by mael25** [cyberbotics/webots#3310]
**Describe the Bug**
The `slave` and `driver` controller crashes in `projects/languages/python/worlds/examples.wbt` with:

```
Traceback (most recent call last):
  File "slave.py", line 21, in <module>
    from controller import AnsiCodes
  File "/usr/local/webots/lib/controller/python27/controller.py", line 2330
    print("Error: `data_type` cannot be `{}`! Supported values are 'list' and 'buffer'.".format(data_type), file=sys.stderr)
                                                                                                                ^
SyntaxError: invalid syntax
WARNING: 'slave' controller exited with status: 1.
```

**System**
 - Ubuntu 20.04 (Webots Deb)

**Comment by lukicdarkoo** [comment]
This Python 2.7, I am not sure whether we want to support it anymore

**Comment by omichel** [comment]
No, we don't want to support Python 2.7 any more.

**Comment by omichel** [comment]
We should probably get rid of the python2.7 library.

**Comment by mael25** [comment]
It is weird because Python 3 was also installed on my machine...

**Comment by mael25** [comment]
When I tried with the Snap installation earlier it was using python3 automatically, but not with the Debian one
