### ISSUE TITLE
Name changed by path in proto

### ISSUE THREAD

**Issue by mael25** [cyberbotics/webots#3324]
**Describe the Bug**
The `name` field of two components has been changed as if it were a path to a resource in `Fabtino.proto`. This might have occured in other protos.
```

device [
          RotationalMotor {
            name "webots://projects/robots/rec/fabtino/protos/front_right_wheel_joint"
            maxVelocity 100
            maxTorque 100
          }
          PositionSensor {
            name "webots://projects/robots/rec/fabtino/protos/front_right_wheel_joint_sensor"
          }
        ]
```

**Comment by mael25** [comment]
Thus the controller does not work in `fabtino.wbt` #3321

**Comment by ad-daniel** [comment]
Yes, kinda surprising it didn't affect all other worlds as well. These fields were manually converted?

**Comment by BenjaminDeleze** [comment]
Yes, as the Fabtino was added after all the worlds/protos were already converted, I just changed its fields manually. It must be a ctrl-c, ctrl-v error.
