### ISSUE TITLE
Robot window javascript error

### ISSUE THREAD

**Issue by ad-daniel** [cyberbotics/webots#3326]
**Describe the Bug**
Getting `[javascript] TypeError: panel of panels is not a function. (In 'panel of panels', 'panel of panels' is undefined) (pick_and_place.html:85)` in both worlds `pick_and_place.wbt`, `wall_following.wbt`, `obstacle_avoidance.wbt`, `pit_escape.wbt` and `square_path.wbt`.

On Windows nightly.

**Comment by omichel** [comment]
Fixed in #3348.
