### ISSUE TITLE
Very noticeable floor texture distorsions in `inverted_pendulum.wbt`

### ISSUE THREAD

**Issue by ad-daniel** [cyberbotics/webots#3331]
**Describe the Bug**
Ditto.

https://user-images.githubusercontent.com/44834743/124439189-662df000-dd79-11eb-870c-c1ee331396e0.mp4

Tested on Windows Nightly

EDIT: Probably view-point related as changing the viewpoint swaps which side has the distortions.

**Comment by omichel** [comment]
I cannot reproduce this problem on my Windows machine in the development environment.

**Comment by ad-daniel** [comment]
Same distortion appears on ubuntu 20 development environment.

https://user-images.githubusercontent.com/44834743/124453801-07bc3e00-dd88-11eb-9c6d-ab731fe1506d.mp4

**Comment by BenjaminDeleze** [comment]
I cannot reproduce it on my ubuntu 20 on master. Do you make something special ?

**Comment by ad-daniel** [comment]
No, just pulled latest master. Could it be AMD GPU related?

**Comment by omichel** [comment]
> Could it be AMD GPU related?

Maybe.
