### ISSUE TITLE
Javascript error in `custom_robot_window_simple.wbt`

### ISSUE THREAD

**Issue by ad-daniel** [cyberbotics/webots#3332]
**Describe the Bug**
The message only appears when resetting.
`[javascript] ReferenceError: Can't find variable: QWebChannel (webots.js:65)`

on Windows nightly.

**Comment by omichel** [comment]
I cannot reproduce this error on my Windows machine with the latest nightly build.

**Comment by BenjaminDeleze** [comment]
I cannot reproduce it with the latest nightly build on Ubuntu 20

**Comment by ad-daniel** [comment]
I still have it on the latest Windows nightly.

**Comment by ad-daniel** [comment]
By manually copying the file `qwebchannel.js` from a linux build into `resources/web/local` and adding `<script src='resources/web/local/qwebchannel.js'></script>` to `custom_robot_window_simple.html` (and therefore bypassing [this instruction](https://github.com/cyberbotics/webots/blob/8e35fb8d7bc8217470a5e680b5b0d3108a56b739/src/webots/gui/WbRobotWindow.cpp#L121)) the warning disappears.

What I don't understand however is where it is supposed to find this resource in the first place, for linux and mac this is included in the package [here](https://github.com/cyberbotics/webots/blob/8e35fb8d7bc8217470a5e680b5b0d3108a56b739/scripts/packaging/files_core.txt#L333) here and copied from [here](https://github.com/cyberbotics/webots/blob/8e35fb8d7bc8217470a5e680b5b0d3108a56b739/scripts/install/qt_linux_installer.sh#L115-L116). Where it managed to find it for other Windows machines for it to affect only my machine I have no idea.
