### ISSUE TITLE
Missing textures in `texture_change.wbt`

### ISSUE THREAD

**Issue by ad-daniel** [cyberbotics/webots#3333]
**Describe the Bug**

`WARNING: DEF PANEL Transform > Shape > PBRAppearance > DEF TEXTURE ImageTexture: 'webots://projects/default/worlds/textures/lightwood.jpg' not found`

`WARNING: DEF PANEL Transform > Shape > PBRAppearance > DEF TEXTURE ImageTexture: 'webots://projects/default/worlds/textures/stone.jpg' not found.`

They appear to be hard-coded in the supervisor controller, might no longer be valid.

Tested on Windows Nightly

**Comment by omichel** [comment]
It seems it is properly changed in the source file, but this source file is not recompiled as it should. So there is a mismatch between the source and binary controller included in the release.
