### ISSUE TITLE
Called cancelGoal but the remaining trajectory still executed

### ISSUE THREAD

**Issue by sean85914** [cyberbotics/webots#3381]
**Describe the Bug**
I developed another node to control `ur5e` in Webots using `/follow_joint_trajectory` interface. I wrote a callback function to monitor the determinant of Jacobian matrix computed by Moveit. If the trajectory is executing and the determinant is less than a threshold value, I will call `cancelGoal()` to prevent infinity joint velocity (i.e., singularity). But I found that, after `cancelGoal()` is called, the remaining trajectory still executed. I checked the code in [trajectory_follower.py](https://github.com/cyberbotics/webots/blob/master/projects/robots/universal_robots/resources/ros_package/ur_e_webots/src/ur_e_webots/trajectory_follower.py) and I found that the `if ...` statement in Line  202 will not check if the goal is canceled.  Maybe `self.goal_handle is not None` should be added into the condition?

**Comment by omichel** [comment]
Yes, that seems a good idea. Can you please propose a patch for this in a Pull Request?
