### ISSUE TITLE
Pen drawing on Mac doesn't evaporates

### ISSUE THREAD

**Issue by BenjaminDeleze** [cyberbotics/webots#3411]
**Describe the Bug**
The first segment of line never evaporates in pen.wbt.

**Steps to Reproduce**
1. Go to 'devices/pen.wbt'
2. Run
3. See that the first segment (black) does not evaporate.

**Expected behavior**
The first segment should evaporate as the other ones

**Screenshots**
![pen](https://user-images.githubusercontent.com/25938827/125586365-6cff0a24-45a9-4b6d-84a8-556ccfae5acf.png)

**Additional context**
Tested on MacOs big sur
Could not reproduce on Ubuntu 20

**Comment by ad-daniel** [comment]
![pen](https://user-images.githubusercontent.com/44834743/125588247-0aa936ea-7177-48cf-bd68-719ff2acb110.png)

Same behavior on windows, it gets lighter at the beginning but never actually vanishes.

**Comment by BenjaminDeleze** [comment]
The issue is due to a too small ink_intensity (0.000008).
It is not reproducible on Ubuntu in pen.wbt as it does not return the same rand() suite, but if I force the ink_intensity to be that small I can reproduce the issue
