### ISSUE TITLE
Blocked assets download when copying a robot

### ISSUE THREAD

**Issue by stefaniapedrazzi** [cyberbotics/webots#3419]
Blocked assets download dialog is displayed on robot copy.

1. Open 'coupled_motors.wbt'
2. Copy the `GRIPPER` Robot
3. The loading world dialog opens saying it is downloading the assets, moreover it takes really long and don't even complete.

**Expected behavior**
If the robot is already loaded, there should not be any need to download again the assets on copy.
In any case, even if the copy should be necessary, the download should work and not be blocked.

**Comment by stefaniapedrazzi** [comment]
Other robot copy give the same issue, for example copying the helicopter robot in `propeller.wbt`.

**Comment by BenjaminDeleze** [comment]
I made some tests and it seems that not all robots suffer from this issues.
From what I tested it happens only to robots that are not defined in a PROTO.
However it doesn't seems limited to robots, some solid seems to have this issue too (if you convert RubberDuck to base node for example)
Moreover, talking a PROTO a trying to convert it to base node will also raise this issue.
