### ISSUE TITLE
Robot window doesn't update after restarting an external controller

### ISSUE THREAD

**Issue by lukicdarkoo** [cyberbotics/webots#3420]
**Steps to Reproduce**
1. Open `projects/languages/python/worlds/example.wbt`
2. Change controller to `<extern>`
3. Open the robot window
4. Run the `slave.py` extern controller (see the robot window getting the update)
5. Kill and start the extern controller (no update robot window updates)

**System**
 - Operating System: Linux Ubuntu 20.04

**Comment by stefaniapedrazzi** [comment]
This issue is still occurring in R2022b.
After killing and restarting the extern controller the robot window is not automatically updated.
The user has to reload the robot window page to make it work again.

**Comment by stefaniapedrazzi** [comment]
We discussed that the best solution is probably to close the robot window when the extern controller disconnects.
