### ISSUE TITLE
ROS test: compilation failure due to `moveit_ros_planning_interface`

### ISSUE THREAD

**Issue by stefaniapedrazzi** [cyberbotics/webots#3422]
`moveit_ros_planning_interface` is not automatically installed and `catkin_make` on Ubuntu 18.04 / melodic fails because of it.
I tested with a local copy of the `webots_ros` package, but the error is likely to occur also with the published package.

If this package cannot be installed automatically and needs to be installed manually, then we have to update the ROS tutorial accordingly:
https://cyberbotics.com/doc/guide/tutorial-8-using-ros?version=R2021b

**Comment by lukicdarkoo** [comment]
Did you run `rosdep install --from-paths src --ignore-src -r -y`?

**Comment by stefaniapedrazzi** [comment]
This issue is solved in #3433 /  #3426.

As written in the description, the documentation should provide all the required instructions to compile and run the `webots_ros` package and it was not the case before.
