### ISSUE TITLE
Robotino: remove NUE restriction

### ISSUE THREAD

**Issue by Thomas-Feldmeier** [cyberbotics/webots#3423]
https://cyberbotics.com/doc/guide/robotino3:
remove this line:
`And in WorldInfo the coordinateSystem must be set to "NUE".`

background:
the robotino uses asymmetric friction between wheels and floor (cylinder/box), coulombFriction [ 0, 2, 0]. there was a bug, robotino needed worlds with NUE coordinate system. now it can drive in any coordinate system, thanks to following bugfix:
[#3150](https://github.com/cyberbotics/webots/pull/3150)

**Comment by omichel** [comment]
Can you please open a PR about it? It should as simple as changing this [file](https://github.com/cyberbotics/webots/edit/master/docs/guide/robotino3.md).
