### ISSUE TITLE
warning "Webots R2021b. You may need to adjust urls"

### ISSUE THREAD

**Issue by Thomas-Feldmeier** [cyberbotics/webots#3430]
webots R2021b nightly build 13/7/2021, ubuntu 20.04

WARNING: '....proto': This file was created with Webots R2020b while you are using Webots R2021b. You may need to adjust urls for textures and meshes, see details in the change log of Webots R2021b.

There is no detail in change log how to fix this warning. Probably webots only checks for the first line of proto/world file  `#VRML_SIM R2021a utf8`

To 'fix' the warning: change the version number with an text editor.

there should be more information and a way to get rid of that warning without to change every proto file.

**Comment by ad-daniel** [comment]
The latest changes to the documentation have not yet been pushed to the released branch. Until then you can view the new version of the documentation by adding `?version=master` to the url. You can find the changelog for 2021b [here](https://cyberbotics.com/doc/reference/changelog-r2021?version=master).

With regards to the warning, it is normal. Here's the relevant part of the changelog:

> Reduced installation package size by using online resources for images, meshes, etc. (#2787). **The local URLs to textures and meshes in previous worlds files should be updated to point to online resources, e.g., "textures/carpet.jpg" should be changed to "https://raw.githubusercontent.com/cyberbotics/webots/R2021b/projects/default/worlds/textures/carpet.jpg".**
