### ISSUE TITLE
links to PBRAppearance

### ISSUE THREAD

**Issue by Thomas-Feldmeier** [cyberbotics/webots#3445]
changes are **_highlighted_**

https://cyberbotics.com/doc/reference/shape

The appearance field contains an Appearance **_or PBRAppearance_**

https://cyberbotics.com/doc/reference/appearance

The Appearance node **_(like the PBRAppearance node)_** specifies the visual properties of a geometry node  that specifies the visual attributes (e.g., material and texture) to be applied to the geometry. **_These nodes are inside of an Shade node._**

**Comment by omichel** [comment]
I would be nice if you could open a Pull Request about it. Following this [link](https://github.com/cyberbotics/webots/edit/master/docs/reference/shape.md) and this [one](https://github.com/cyberbotics/webots/edit/master/docs/reference/appearance.md) should be super-easy.
