### ISSUE TITLE
Robot window doesn't work in a virtual machine

### ISSUE THREAD

**Issue by lukicdarkoo** [cyberbotics/webots#3447]
**Steps to Reproduce**
1. Open the Python example
2. Double click on the robot
3. Shows the error `[javascript] Uncaught Error: Unable to initialize WebGL. Your browser or machine may not support it. (canvas.js?305_0:26)` and the robot window also doesn't work

**System**
```
$ webots --sysinfo
System: Linux 5.4.0-77-generic x86_64
Processor: AMD Ryzen 7 1800X Eight-Core Processor
Number of cores: 8
OpenGL vendor: VMware, Inc.
OpenGL renderer: llvmpipe (LLVM 10.0.0, 128 bits)
OpenGL version: 4.0 (Compatibility Profile) Mesa 20.0.8
```

**Comment by ad-daniel** [comment]
I tried on a nightly build (snap) version on ubuntu 18 and it opens fine

```
System: Linux 5.4.0-42-generic x86_64
Processor: Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz
Number of cores: 4
OpenGL vendor: VMware, Inc.
OpenGL renderer: llvmpipe (LLVM 10.0.0, 256 bits)
OpenGL version: 3.1 Mesa 20.0.8
```

**Comment by omichel** [comment]
It works on my VM as well (running on a Windows 10 host):
```
System: Linux 5.8.0-59-generic x86_64
Processor: AMD Ryzen 7 4800HS with Radeon Graphics
Number of cores: 16
OpenGL vendor: VMware, Inc.
OpenGL renderer: SVGA3D; build: RELEASE;  LLVM;
OpenGL version: 4.1 (Compatibility Profile) Mesa 20.2.6
```

**Comment by lukicdarkoo** [comment]
> I tried on a nightly build (snap) version on ubuntu 18 virtual machine and it opened fine
> 
> ```
> System: Linux 5.4.0-42-generic x86_64
> Processor: Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz
> Number of cores: 4
> OpenGL vendor: VMware, Inc.
> OpenGL renderer: llvmpipe (LLVM 10.0.0, 256 bits)
> OpenGL version: 3.1 Mesa 20.0.8
> ```

I have the same configuration, Ubuntu 18.04, VirtualBox, and Webots snap. I have just checked again and I am getting the same problem. Does the image in the robot window gets updated?

**Comment by ad-daniel** [comment]
No you're right, the robot window does open and is populated but when you actually run the simulation I get the error you mentioned.

**Comment by omichel** [comment]
I am not getting the error, but I am running it from the development environment (not from the snap).

**Comment by BenjaminDeleze** [comment]
I can reproduce it with the tarball on a VM with Ubuntu 18.

I have this error in this terminal: `ERROR:context_group.cc(145) ContextResult::kFatalFailure: WebGL1 blacklisted`

same config as Daniel

**Comment by ad-daniel** [comment]
For me, even opening `Help > openGL information` makes webots crash. `webots --sysinfo` doesn't.

**Comment by BenjaminDeleze** [comment]
It is strange, because I could stream a simulation from inside the VM and play it in a browser in the VM as well. So it can create a WebGL context (at least in browsers).

**Comment by ad-daniel** [comment]
Tested the same setup with `R2021a` snap and it works. I don't know how much about it was changed this release, but it might be a regression.

**Comment by stefaniapedrazzi** [comment]
> Tested the same setup with R2021a snap and it works. I don't know how much about it was changed this release, but it might be a regression.

Robot windows in R2021a are not using WebGL.

The exact same code to get the WebGL context in Firefox works but not in if the robot window is started by Webots (on a Ubuntu 18.04 VM).

**Comment by stefaniapedrazzi** [comment]
It seems this is a Qt bug of the `QtWebEngine` module.
I tried to revert to Qt 5.15.0 (see #3089) and the robot windows work correctly in the VM.

**Comment by stefaniapedrazzi** [comment]
Robot windows in VM also work correctly with a standard installation of Qt 5.15.1 (for testing I didn't recompile libqjpeg and QWebSockets).
I will try to identify the changes and write a bug report.

**Comment by stefaniapedrazzi** [comment]
Here is the link to the bug report:
https://bugreports.qt.io/browse/QTBUG-95536

**Comment by omichel** [comment]
Since we moved the robot in windows to the web browser, this issue is not relevant any more.
