### ISSUE TITLE
Wrong urls in snap

### ISSUE THREAD

**Issue by BenjaminDeleze** [cyberbotics/webots#3448]
The urls should have the form "https://raw.githubusercontent.com/.../R2021b/..."
But the snap package have urls with the commit number: "https://raw.githubusercontent.com/.../a4ecb88/..."

All the other packages (.exe, .dmg, .deb, .tar.gz) are correct.

I think it is because of the order in which we created the packet today:

- First we pushed the snap tag
- Then we pushed the webots tag

So the head of webots when building the snap package was not on the R2021 Tag of webots.

**Comment by BenjaminDeleze** [comment]
It seems that I was right, because the snap of the nightly build has correct urls: "https://raw.githubusercontent.com/.../R2021b/..." 
It is correct since the HEAD is still on the R2021b tag.

**Comment by lukicdarkoo** [comment]
> I think it is because of the order in which we created the packet today:

Yesterday, I re-ran the snap package creation just after all packages got built (I had different problems because of the same reason)

**Comment by BenjaminDeleze** [comment]
Okay, that is strange. So I don't know why it is correct in the nightly but not in the release

**Comment by BenjaminDeleze** [comment]
I tested again and it is fixed. I think I tested yesterday with the first snap package (before it was recreated)
