### ISSUE TITLE
supervisor setSFInt32 crashes on own proto fields and lua regeneration

### ISSUE THREAD

**Issue by Thomas-Feldmeier** [cyberbotics/webots#3483]
webots R2021b, ubutun 20.04

Crash.proto:
```
#VRML_SIM R2021b utf8
PROTO Crash [
  field SFInt32 subdivision 1
]
{
DEF Crash Transform {
  children [
    Shape {
      geometry Sphere {
#        subdivision IS subdivision
        subdivision %{= fields.subdivision.value }%
      }
    }
    Robot {
     controller "Crash"
     supervisor TRUE
    }
  ]
}
}
```

Crash.cpp:
```
#include <webots/Supervisor.hpp>

int main(int argc, char **argv) {
  webots::Supervisor *robot = new webots::Supervisor();
  robot->getFromDef("Crash")->getField("subdivision")->setSFInt32(2);
  robot->step(32);   
}
```

add controller Crash, compile, add proto node Crash to an world, webots will crash
the controller writes field subdivision. this field is a parameter of lua -> lua regeneration (a change in parameter "subdivision" restarts the lua program generating a new proto file. the controller is part of this proto and would be restarted too. here the crash happens)
no crash if:
* subdivision IS subdivision   instead of   subdivision %{= fields.subdivision.value }%
* or no controller is inside of the node

%{ subdivision = fields.subdivision.value }% will crash too if there is a controller present

**Comment by ad-daniel** [comment]
This is an odd one, I've made a few tests and:
- replacing the template language from Lua to JavaScript  it doesn't crash
```
#VRML_SIM R2021b utf8
# template language: javascript

PROTO Crash [
  field SFInt32 subdivision 1
]
{
DEF Crash Transform {
  children [
    Shape {
      geometry Sphere {
#        subdivision IS subdivision
        subdivision %<= fields.subdivision.value >%
      }
    }
    Robot {
     controller "Crash"
     supervisor TRUE
    }
  ]
}
}

```
- When using Lua and triggering the regeneration manually from the interface, it doesn't crash

The second test suggests that the issue might be related to having the controller running while regenerating the Robot that is using said controller, but it that were the case, it shouldn't work even in JavaScript but it does
