### ISSUE TITLE
Windows: cannot launch Webots R2021b from CMD

### ISSUE THREAD

**Issue by stefaniapedrazzi** [cyberbotics/webots#3485]
A user reported on Discord that with R2021b it is no longer possible to start Webots from CMD and can't get any output with argument `--version` or `--help` either.

Double clicking on the executable `${WEBOTS_HOME}/msys64/mingw64/bin/webotsw.exe` works correctly.

I quickly checked and I get the same issue on my Windows (user without development system installed) after installing Webots R2021b for all the users.

Here is the related documentation:
https://www.cyberbotics.com/doc/guide/starting-webots#windows

**Comment by omichel** [comment]
This bug was introduced in #2750.
