### ISSUE TITLE
Remote resource cannot be downloaded

### ISSUE THREAD

**Issue by chenxin199305** [cyberbotics/webots#3498]
After installing the newest version of webots, I find that the texture of the scene cannot be downloaded. As I am in mainland China, I am not sure if it is VPN problem. But when I copy and paste the resource link and open my VPN to download it, it also shows 404 (for example, https://raw.githubusercontent.com/cyberbotics/webots/R2021b/projects/appearances/protos/textures/thread_metal_plate/oval_thread_metal_plate_base_color.jpg:%20Error%20opening%20https:/raw.githubusercontent.com/cyberbotics/webots/R2021b/projects/appearances/protos/textures/thread_metal_plate/oval_thread_metal_plate_base_color.jpg). So, I am here writing this issue to please request a re-check from you that all the resources in the remote repository are downloadable. Thanks.

**Comment by Thomas-Feldmeier** [comment]
the link you give does not work for me too (has nothing to do with VPN problem). try this one:

https://raw.githubusercontent.com/cyberbotics/webots/R2021b/projects/appearances/protos/textures/thread_metal_plate/oval_thread_metal_plate_base_color.jpg

https://raw.githubusercontent.com/cyberbotics/webots/R2021b/projects/appearances/protos/textures/thread_metal_plate/oval_thread_metal_plate_base_color.jpg

i got this link by adding shape, appearance > Proto nodes > appearance > ThreadMetalPlate, convert to base Nodes, baseColorMap url

**Comment by TaoYibo1866** [comment]
I tried to copy those textures from my older version webots to 2021b folder, but didn't help. Does anyone know where are those downloaded files located in 2021b?

**Comment by stefaniapedrazzi** [comment]
They are automatically downloaded and loaded by Webots.

If you want to download/copy them manually, then make sure to change the URL of the textures so that they point to your resources and not to the default URL. Because otherwise Webots will continue to try to download them from the web.

Note that Webots default URLs are correct and this seems a problem with your network connection.

**Comment by TaoYibo1866** [comment]
> They are automatically downloaded and loaded by Webots.
> 
> If you want to download/copy them manually, then make sure to change the URL of the textures so that they point to your resources and not to the default URL. Because otherwise Webots will continue to try to download them from the web.
> 
> Note that Webots default URLs are correct and this seems a problem with your network connection.

Thank you for your reply. As we are in mainland China, we cannot access githubusercontent. We hope webots can give us a link to download all downloadable resources so that we can manually place it in the right place. This will mean a lot to us!

**Comment by stefaniapedrazzi** [comment]
> Thank you for your reply. As we are in mainland China, we cannot access githubusercontent. We hope webots can give us a link to download all downloadable resources so that we can manually place it in the right place. This will mean a lot to us!

This is not possible with Webots R2021b.
We are discussing about possible solutions that could be included in the next version but for the moment there is nothing concrete yet.

**Comment by TaoYibo1866** [comment]
> > Thank you for your reply. As we are in mainland China, we cannot access githubusercontent. We hope webots can give us a link to download all downloadable resources so that we can manually place it in the right place. This will mean a lot to us!
> 
> This is not possible with Webots R2021b.
> We are discussing about possible solutions that could be included in the next version but for the moment there is nothing concrete yet.

Looking forward to it, thanks!

**Comment by Thomas-Feldmeier** [comment]
best thing is to use webots R2021a or wait until webots R2021b revision comes out (i hope this comes)

dirty hack to "download" resources:

webots 2021b, copy webots/project folder to folder B and C (C is backup if you mess up)
webots 2021a, copy webots/project folder to folder A
now copy folder A to B, but don't overwrite already existing files. this should add all missing .png .jpg etc to their old location

now write a little program or a script to find all .wbt or .proto (maybe more) files in folder B, replace like this:
    "https://raw.githubusercontent.com/cyberbotics/webots/R2021b/projects/objects/road/protos/textures/road_line_triangle.png"
    "textures/road_line_triangle.png"

"https://raw.githubusercontent.com/cyberbotics/webots/R2021b/projects/OOO/AAA/BBB"
-> "AAA/BBB"

where AAA and BBB does not contain / or "
OOO is the rest, does not contain ", but can contain /

copy folder B to webots/project folder of webots R2021b. maybe you have to give proper rights to that folder

this hack should theoretically work, but i have not used it myself except for mybots sample world where it worked, so maybe there are more problems.

**Comment by TaoYibo1866** [comment]
> best thing is to use webots R2021a or wait until webots R2021b revision comes out (i hope this comes)
> 
> dirty hack to "download" resources:
> 
> webots 2021b, copy webots/project folder to folder B and C (C is backup if you mess up)
> webots 2021a, copy webots/project folder to folder A
> now copy folder A to B, but don't overwrite already existing files. this should add all missing .png .jpg etc to their old location
> 
> now write a little program or a script to find all .wbt or .proto (maybe more) files in folder B, replace like this:
> "https://raw.githubusercontent.com/cyberbotics/webots/R2021b/projects/objects/road/protos/textures/road_line_triangle.png"
> "textures/road_line_triangle.png"
> 
> "https://raw.githubusercontent.com/cyberbotics/webots/R2021b/projects/OOO/AAA/BBB"
> -> "AAA/BBB"
> 
> where AAA and BBB does not contain / or "
> OOO is the rest, does not contain ", but can contain /
> 
> copy folder B to webots/project folder of webots R2021b. maybe you have to give proper rights to that folder
> 
> this hack should theoretically work, but i have not used it myself except for mybots sample world where it worked, so maybe there are more problems.

Thank you! I just tried your method and it worked. However, i decided to use webots 2021a at last.

**Comment by Thomas-Feldmeier** [comment]
> Thank you! I just tried your method and it worked. However, i decided to use webots 2021a at last.

Can you please share your script/program to find files and replace text? This could help others.

**Comment by TaoYibo1866** [comment]
> > Thank you! I just tried your method and it worked. However, i decided to use webots 2021a at last.
> 
> Can you please share your script/program to find files and replace text? This could help others.

I merely rename some of the links manually to get my simulation running, sorry for that.

**Comment by BenjaminDeleze** [comment]
I'm closing this for now, feel free to reopen it if you have additional issues.
