### ISSUE TITLE
darwin-op can't open robot window

### ISSUE THREAD

**Issue by Thomas-Feldmeier** [cyberbotics/webots#3503]
sample world darwin-op

double click on robot or right click robot > show robot window:
```
Error: libzip.so.4: cannot open shared object file: No such file or directory (dynamic library)
Error: robot window initialization failed
Error: Cannot load the "/usr/local/webots/projects/robots/robotis/darwin-op/plugins/robot_windows/robotis-op2_window/librobotis-op2_window.so" robot window library.
```

there is a file in that folder:

```
ls -al /usr/local/webots/projects/robots/robotis/darwin-op/plugins/robot_windows/robotis-op2_window/librobotis-op2_window.so

-rwxr-xr-x 1 root root 172496 Jul 16 14:28 /usr/local/webots/projects/robots/robotis/darwin-op/plugins/robot_windows/robotis-op2_window/librobotis-op2_window.so

```

webots R2021b; ubuntu 20.04; i don't have a real darwin-op-robot, so a remote control to a real one will fail and that's why there is no robot window?

**Comment by stefaniapedrazzi** [comment]
> webots R2021b; ubuntu 20.04; i don't have a real darwin-op-robot, so a remote control to a real one will fail and that's why there is no robot window?

No, it doesn't seem the error is related on the availability of a real robot.
It seems simply that the `libzip.so.4` library needed to run it is not available on the system.
Which package did you use to install Webots ? Snap, debian or tarball?

**Comment by stefaniapedrazzi** [comment]
I tested on a clean machine and it works fine if Webots is installed with the tarball or snap package but I can reproduce the issue with the debian package.

**Comment by stefaniapedrazzi** [comment]
On Ubuntu 20.04 the available version libzip is libzip5 and in Ubuntu 18.04 is libzip4.
This makes impossible to distribute a single Debian package fully working out of the box on both Ubuntu distribution.
But we could reintroduce the limitation of the support of the Debian package only for the latest Ubuntu LTS (currently Ubuntu 20.04) as it was the case a couple of years ago.
To run Webots on Ubuntu 18.04 users will have to use the snap or tarball package.

A workaround to use the robotis robot window on Ubuntu 20.04 is to recompile the library:
1) Open any C++ file of the robot window (for example `$WEBOTS/projects/robots/robotis/darwin-op/plugins/robot_windows/robotis-op2_window/entry_points.cpp`)
2) Press the clean button on the text editor toolbar
3) Accept the dialog about project relocation
4) Press the build button on the text editor toolbar
5) Reload the simulation -> the robot window library is now linked with the correct version of `libzip` and can be correctly opened

Note that this is not a regression of Webots R2021b and there was the exact same issue with the previous versions.

**Comment by omichel** [comment]
I would suggest to drop Ubuntu 18.04 support for the `.deb` package and support only 20.04. This might also fix the problem we have with ROS Noetic.

**Comment by Thomas-Feldmeier** [comment]
webots_2021b_amd64.deb
