### ISSUE TITLE
inability to get a frame from another robot from a supervisor

### ISSUE THREAD

**Issue by HiTF** [cyberbotics/webots#3524]
i want to get a third party robot camera object from the world using a supervisor. But when i try:
`second_robot = supervisor.getFromDef("another_robot")
camera = second_robot.getDevice("camera")`
i get:
`Traceback (most recent call last):
  File "webots_robot.py", line 450, in <module>
    camera = second_robot.getDevice("camera")
  File "/home/hitf/webots/lib/controller/python38/controller.py", line 1765, in <lambda>
    getattr = lambda self, name: _swig_getattr(self, Node, name)
  File "/home/hitf/webots/lib/controller/python38/controller.py", line 96, in _swig_getattr
    raise AttributeError("'%s' object has no attribute '%s'" % (class_type.name, name))
AttributeError: 'Node' object has no attribute 'getDevice'
WARNING: 'webots_robot' controller exited with status: 1.`

So calling function getBaseTypeName() on second_robot it outputs type Robot.
The object received from getFromDef is not a robot object  or is it a bug?
Anyway, is there a way to get image from other robots from the supervisor?

**Comment by lukicdarkoo** [comment]
The Webots API doesn't support accessing devices of other robots. You have to either use the Receiver/Emitter API (https://www.cyberbotics.com/doc/reference/emitter) to transfer the image data or to use some third-party communication.
