### ISSUE TITLE
`wb_supervisor_node_set_visibility` also hides sibling nodes

### ISSUE THREAD

**Issue by stefaniapedrazzi** [cyberbotics/webots#3529]
In case of such a structure:
```
Solid {
  children [
    Shape A {
      ..
    }
    Shape B {
      ..
    }
  ]
}
```

Hiding the node A from a camera will also hide node B.
But if I add a `Transform` parent to the `Shape` that should be hidden then works correctly.

I will inspect if this is a limitation of the functionality, but in this case it should be clearly specified in the documentation that currently simply says that children are recursively hiddden too:
https://www.cyberbotics.com/doc/reference/supervisor#wb_supervisor_node_set_visibility

**Comment by stefaniapedrazzi** [comment]
Only geometry and transform nodes have their own WREN node.
All the other nodes (for example the Shape node) inherit the parent node, and thus if you set the visibility of a node that is not a geometry or a transform the visibility is also applied to all the siblings nodes.

**Comment by omichel** [comment]
From a user's perspective it seems strange that it doesn't work for a shape, but works for a geometry. Usability should not be a consequence of the underlying implementation (here in WREN). Instead, I believe we could change this behavior so that when a Shape is provided, it works also (and internally, it will apply to its geometry).

**Comment by stefaniapedrazzi** [comment]
Yes, I agree.
The current behavior seems buggy from a user's perspective and it would better to fix it.
However, I would not add an exception just for the `Shape` node but fix it properly for all the nodes (`Group`, `Slot`, joints, etc.) applying it recursively only to the children nodes.
