### ISSUE TITLE
Rendering difference between WebotsJS/X3D and Webots

### ISSUE THREAD

**Issue by omichel** [cyberbotics/webots#3534]
The FESTO logo visible on the robot web component at https://cyberbotics.com/doc/guide/robotino3 looks bad where it looks good when running the robotino3.wbt simulation in Webots.

On the web (Firefox/Window):
![image](https://user-images.githubusercontent.com/1264964/128047357-00267a9c-aff4-47f6-b35a-a1fea3f36c54.png)

In Webots:
![image](https://user-images.githubusercontent.com/1264964/128047600-22fa825b-81cd-4535-968b-2b61c287dd80.png)

Where does this difference come from? Could it be the resolution of the depth buffer for depth test?

**Comment by BenjaminDeleze** [comment]
I investigated the following possibilities:

- Resolution of the depth buffer: both version are using the same shaders and I could not find a difference in the way the depth buffer are created.
- Problem in indexedFaceSet/Mesh: It is not the case because I was able to reproduce the issue with only a box and a cylinder

It seems like the issue appears when the position difference between two textures is less than 0.03mm.

**Comment by omichel** [comment]
> Resolution of the depth buffer: both version are using the same shaders and I could not find a difference in the way the depth buffer are created.

Is the depth buffer 32-bit or 24-bit on both implementations? Is it combined with the stencil buffer (8-bit) used for shadows?

**Comment by omichel** [comment]
See for example https://stackoverflow.com/questions/22398575/depth-stencil-framebuffer-concerns

**Comment by BenjaminDeleze** [comment]
> Is the depth buffer 32-bit or 24-bit on both implementations? Is it combined with the stencil buffer (8-bit) used for shadows?

Yes both use the `WR_TEXTURE_INTERNAL_FORMAT_DEPTH24_STENCIL8`

**Comment by omichel** [comment]
> Yes both use the `WR_TEXTURE_INTERNAL_FORMAT_DEPTH24_STENCIL8`

And is the depth test the same? Also the value of the near and the far for the depth buffer are the same?
This article may be inspiring: https://learnopengl.com/Advanced-OpenGL/Depth-testing

**Comment by BenjaminDeleze** [comment]
I found out that the view and projection matrix are not totally the same in Webots and WebotsJS. Seems like a precision difference of glm-js or of the x3d export. However, I could not prove yet that this is the cause of the problem. I will continue to investigate it.

**Comment by BenjaminDeleze** [comment]
The precision difference comes from the x3d export. In `src/webots/vrml/wbSFRotation.hpp` and `src/webots/vrml/wbSFVector3.hpp` the precision of the x3d export is `FLOAT_MAX`. But it does not impact the rendering so we should keep it like it is to keep the export light.

**Comment by BenjaminDeleze** [comment]
Half of the problem is solved:

The clipping difference between cube and cylinder is due to `glClipControl` (see #3101). If I disable glClipControl on Webots I get the same result.

However, it does not change anything for the robotino problem or for clipping edge cases between two IFS

**Comment by BenjaminDeleze** [comment]
Close because similar of #3101
