### ISSUE TITLE
Calculation of front_speed_sum is wrong for FOUR_BY_FOUR vehicles

### ISSUE THREAD

**Issue by KNTRL9** [cyberbotics/webots#3545]
In the vehicle/c/driver/src/driver.c file on line 286 it states

    double front_speed_sum = instance->car->speeds[0] + instance->car->speeds[0];

while it should be

    double front_speed_sum = instance->car->speeds[0] + instance->car->speeds[1];

**Comment by omichel** [comment]
Thank you for this precise bug report.
Can you please go ahead and propose this change in a new PR: https://github.com/cyberbotics/webots/edit/master/projects/default/libraries/vehicle/c/driver/src/driver.c#L286
I just invited you to become a member of the Webots committers group.

**Comment by KNTRL9** [comment]
Opened a PR [3546](https://github.com/cyberbotics/webots/pull/3546].
