### ISSUE TITLE
FLU: Error in camera recognition

### ISSUE THREAD

**Issue by BenjaminDeleze** [cyberbotics/webots#3571]
**Describe the Bug**
It seems (see pictures) that the objects (at least capsule and cylinder, but maybe also plane, elevation grid and cone) are not well recognized by the camera recognition since the changes of FLU.
I don't know if it is only a problem of display in the camera display or if it is deeper.

It seems to come from #3496 

**Steps to Reproduce**
1. Go to `feature-enu-plan`.
2. Open `tests/api/camera_recognition.wbt`.
3. Play one step and look at the camera display.
4. Remark that the red square around the capsule is not well placed.

**Screenshots**
on master
![camera_recognition](https://user-images.githubusercontent.com/25938827/129342103-9a4c4b7c-e386-4d48-9258-a57a7b699fea.png)

on feature-enu-plan (look at the capsule)
![camera_recognition_enu](https://user-images.githubusercontent.com/25938827/129342106-9e72a6de-251e-44a0-a93c-521d60a84f0b.png)

**Comment by lukicdarkoo** [comment]
Fixed in #3575
