### ISSUE TITLE
Simulation freezing

### ISSUE THREAD

**Issue by felsager** [cyberbotics/webots#3572]
**Describe the bug**
When running a simulation of the Tiago Base robot the simulation freezes - the simulation speed goes to 0.00x. But no crash messages. Resetting the simulation gives the warning "WARNING: participant_controller: Forced termination (because process didn't terminate itself after 1 second)."

**Steps to reproduce**
This occurs with a basic time step of 16. 
Reducing the basic time step to 8 resolves the issue, and the simulation does not freeze.

**Screenshots**
Screenshot of gui when simulation is frozen:
![frozen_simulation](https://user-images.githubusercontent.com/76905857/129349359-bf2f5ab8-b6b5-4c30-a212-a55d18491591.png)

**System**
 - Operating System: Linux Ubuntu 20.04.2

**Comment by omichel** [comment]
It looks like the freeze takes place in one of your controller programs, not in Webots. If you replace your controllers with the "void" controller, do you still get the freeze?

**Comment by felsager** [comment]
No using the "void" controller does not freeze the simulation. But if the problem has to do with the controller i wonder why it should be able to cause the simulation to freeze, and decreasing the basic time step size to 8 stops it from freezing

**Comment by ad-daniel** [comment]
I can happen if you have an infinite loop. Can you share the world/controller? Or create a minimal example that showcases the issue?

**Comment by lukicdarkoo** [comment]
Also, to confirm whether the controller is blocking the simulation you can turn off the synchronization (see the `synchronization` parameter [here](https://cyberbotics.com/doc/reference/robot))

**Comment by felsager** [comment]
Hi again
Turning off synchronization made me able to debug the controller and see what actually went wrong with it, and was able to resolve an infinite loop happening in the planner. Thanks a lot everybody
