### ISSUE TITLE
LiDAR points distribute as straight line along the coordinate axes

### ISSUE THREAD

**Issue by BruceXSK** [cyberbotics/webots#3594]
As shown in the picture
![Problem](https://drive.google.com/uc?export=view&id=1krlPmXDRwbEp9R9JkPu7UdN29H9bQYQx)
There are some problems with the LiDAR points.
It seems that they distribute along the x and z axes. For more far away points look more obvious.

This problem appears in the latest version of webots(2021b Release date: July 16, 2021)
But it's ok in the older version (2021b Release date: Apri 28, 2021l), as shown in the picture below:
![old version](https://drive.google.com/uc?export=view&id=1wkf0ODY1RKjZ56ApOXHb8L8GEoEAi2bb)

Versions:
Webots 2021b Date:July 16, 2021
Ubuntu 20.04

How to fix that? Thanks

**Comment by omichel** [comment]
I believe this is consequence of https://github.com/cyberbotics/webots/pull/3230

**Comment by BruceXSK** [comment]
> I believe this is consequence of #3230

Thanks

**Comment by pglira** [comment]
We are still observing the same issue using Ubuntu 20.04 and Webots 2022a.

![MicrosoftTeams-image](https://user-images.githubusercontent.com/14214284/170028708-55ecb303-6991-4f2d-8f98-210d57a4b5a9.png)

Shouldn't this be fixed? If not, how can we avoid this behaviour?

Thanks for your support.

**Comment by pglira** [comment]
We've tried different things in the meanwhile, unfortunately none of it solved the issue.

Currently we are using the Velodyne lidar sensor instead of the generic one, but as you can see here the point cloud is still not correct:

![image](https://user-images.githubusercontent.com/14214284/170263163-7b4c9157-fcd6-479c-94cb-62d63974b368.png)

**Comment by omichel** [comment]
This loss of precision was introduced in #3230 to fix a more annoying bug. Feel free to investigate #3230 and propose a patch.

**Comment by pglira** [comment]
Thanks for the response. Is there any workaround? E.g. by choosing different settings for the lidar sensor?
