### ISSUE TITLE
Referenced Collada files are not properly oriented

### ISSUE THREAD

**Issue by lukicdarkoo** [cyberbotics/webots#3603]
In the following model (from R2021b) it says that Z-axis up:
https://github.com/cyberbotics/webots/blob/507e8485d3edbd4b2463d832c22b849f4325bf24/projects/devices/sick/protos/meshes/sick_s300_black.dae#L11
However, the SickS300 PROTO actually has the Y-axis up.

This may be related to the following bug:
https://github.com/assimp/assimp/issues/849

**Comment by omichel** [comment]
That seems to be fixed in R2022b (current develop branch):
![sick_s300](https://user-images.githubusercontent.com/1264964/174254879-3364b2d1-dfdc-4b9c-9a6e-681d29185822.jpg)
