### ISSUE TITLE
Matlab (R2019a) does not work with Webots on Mac OS 10.14.6 (Mojave) 

### ISSUE THREAD

**Issue by lianne** [cyberbotics/webots#3728]
Hi guys, I still have such a problem on my Mac OS 10.14.6 (Mojave) with Matlab R2019a. I tested both Webots R2021b and R2021b Nigthly Build Rev 1 (version 27 Sep 2021). Matlab starts without problems from the terminal with the command Matlab -nosplash -nodesktop (I have a symbolic link in usr/locan/bin).
Thanks.
 Luigi

_Originally posted by @lianne in https://github.com/cyberbotics/webots/issues/2608#issuecomment-929075338_

**Comment by omichel** [comment]
Unfortunately, I don't have Matlab R2019a to test. Did you try to upgrade to a more recent version of MATLAB? Otherwise, I would recommend you to compile Webots from the source and try to debug the problem on your own.

**Comment by BenjaminDeleze** [comment]
I'm closing this for now, feel free to reopen it if you have additional issues.
