### ISSUE TITLE
can not display right on ubuntu20.04

### ISSUE THREAD

**Issue by codedetermination** [cyberbotics/webots#3822]
WARNING: WoodenPalletStack (PROTO) > WoodenPallet (PROTO) > Transform > Shape > RoughPine (PROTO) > ImageTexture: Cannot download https://raw.githubusercontent.com/cyberbotics/webots/R2021b/projects/appearances/protos/textures/rough_pine/rough_pine_base_color.jpg: 打开https://raw.githubusercontent.com/cyberbotics/webots/R2021b/projects/appearances/protos/textures/rough_pine/rough_pine_base_color.jpg发生错误

**Comment by BenjaminDeleze** [comment]
I'm closing this for now, feel free to reopen it if you have additional issues.
