### ISSUE TITLE
Improve `village_winter` crossroad textures

### ISSUE THREAD

**Issue by ad-daniel** [cyberbotics/webots#3873]
**Describe the Bug**

All the crossroads in `village_winter` have a different texture compared to the roads, which looks kinda odd. Would be nice to have something more consistent.

![aa](https://user-images.githubusercontent.com/44834743/140965492-a41f6b38-4ef7-4ae8-a09a-c6fb20e42b6c.png)

**Comment by BenjaminDeleze** [comment]
It would be quite easy to replace them with `roundabout` protos.
The problem is that the sumo exporter does not have support for `roundabout` right now.  So we would not be able to regenerate the Sumo network.

**Comment by Thomas-Feldmeier** [comment]
in village_winter.wbt, change Crossroad appearence to same as in Road
i changed the first Crossroad, it looks nice
![village_winter](https://user-images.githubusercontent.com/73528085/141085632-3ea29ed5-56c9-48b0-a7f2-06d0f5e8d021.png)
ad

**Comment by ad-daniel** [comment]
Whatever change ends up being picked, it should be done in `feature-enu-plan` branch to avoid conflicts when merging
