### ISSUE TITLE
Contradicting information in the Tutorial and in `Add a new object or import an object` dialog

### ISSUE THREAD

**Issue by filiparag** [cyberbotics/webots#3879]
**Describe the Bug**

Contradicting information in the introductory tutorial (guide) and in `Add a new object or import an object` dialog.

In [Tutorial 6](https://cyberbotics.com/doc/guide/tutorial-6-4-wheels-robot#separating-the-robot-in-solid-nodes) there is following text:

> The main structure of a Robot model is **a tree of Solid nodes** linked together. The root node of this tree should be a Robot node.
> [...]
> Having these rules in mind, we can start designing the node hierarchy used to model the robot. The first step is to determine which part of the robot should be modeled as a Solid node.

and in the [mentioned dialog](https://github.com/cyberbotics/webots/blob/master/resources/nodes/Solid.wrl#L1) it states:

> A Solid node can be used to represent objects of the simulated environment that **are not robots** (e.g. obstacles, walls, ground, etc.).

![image](https://user-images.githubusercontent.com/4471044/141207482-bb686f2f-4778-49b2-9147-eeddb402d88a.png)

While following the tutorial, I wasn't sure whether to use Solids or Shapes for Robot's `children` property because the guide says, and the other properties expect Solids, but the dialog says not to use them in Robots.

The dialog text should be changed, so it doesn't cause confusion.

**Comment by omichel** [comment]
Thank you for reporting this problem.
I would propose to change [this text](https://github.com/cyberbotics/webots/blob/master/resources/nodes/Solid.wrl#L1) to:
```
# A Solid node can be used to represent objects in the simulated environment (e.g. obstacles, walls, ground, robot parts, etc.).
```
Would that make it clearer for you?

**Comment by filiparag** [comment]
> Would that make it clearer for you?

Yeah, I think it would better reflect Solid's usage.
