### ISSUE TITLE
HingeJoint's minStop and maxStop attributes do not work correctly

### ISSUE THREAD

**Issue by VladimirVincan** [cyberbotics/webots#3947]
Hello, 

I was trying to implement a simple mechanism that requires the use of a joint. The cards, shown on the GIFs, are supposed to be pushed by a robot, and then fall and stay vertically downwards due to gravity. The problem is, that I cannot limit the cards to stay vertically downwards. If I say that the joint's maxStop attribute has a value of π (or a bit less, e.g. 3),  the cards won't stop rotating, as shown on the first GIF. If the maxStop attribute has a value of ~2.6 (the second GIF), the cards rotate once or twice before they get limited by minStop and maxStop. If the maxStop attribute has a value of ~2 or less (the third GIF), I have not encountered an error. 

I would like to be able to set maxStop to be around π, so that the cards can stay vertically downwards. I could not find a reason why my PROTO file creates this kind of problem, so I believe it is a bug. Please take a look at the world on [this link](https://github.com/VladimirVincan/mep3/tree/excavation_squares/mep3_simulation/webots_data/worlds), it is named eurobot_2022.wbt. Also, please take a look at the PROTO file on[ this link](https://github.com/VladimirVincan/mep3/tree/excavation_squares/mep3_simulation/webots_data/protos), it is named ExcavationSquare.proto. Everything is done on the **excavation_squares** branch.

Thank you beforehand!

![max_stop_3_3](https://user-images.githubusercontent.com/13640533/142895771-b6443eb6-f090-4fd2-8966-36b4d3622d59.gif)

![max_stop_2_6](https://user-images.githubusercontent.com/13640533/142895785-9a4baba2-4f70-4105-836e-bf9d6afea7c9.gif)

![max_stop_2](https://user-images.githubusercontent.com/13640533/142895795-9159c0bb-6677-4f71-865a-30c71191944a.gif)

**Comment by ad-daniel** [comment]
That's an odd behavior, to an extent is normal insofar as adding an excessive force will probably break the constraint, however curiously enough using this method I haven't been able to break the `minStop` limit,  meaning I can't get it to rotate by turning it counter clockwise. Turning clockwise however the `maxStop` is violated much more frequently and easily, so given the asymmetry of the behavior something fishy must be happening
