### ISSUE TITLE
Backward compatibility loader doesn't work for a simple robot

### ISSUE THREAD

**Issue by lukicdarkoo** [cyberbotics/webots#3963]
More details:
https://github.com/cyberbotics/webots/pull/3950#pullrequestreview-814595020

World file:
[my_world_copy.zip](https://github.com/cyberbotics/webots/files/7581784/my_world_copy.zip)

**Comment by joachimhgg** [comment]
FYI, I have noticed that `sick.wbt`, `CH_Vens.wbt`, and `complete_appartment.wbt` are crashing too. Also it crashes when opening a 2022a world with 2021b proto inside (at least when I replaced nao.proto by its 2021b version, the 2022a worlds containing this proto are crashing)

**Comment by BenjaminDeleze** [comment]
I think it is still making Webots crash. I have two webots installation on my computer. One is on master (R2021b) and one on develop (R2022a). When I tried to open some worlds (for example `nao_room.wbt`, `nao_demo.wbt` or `pr2.wbt`) from my master repository in Webots R2022a, it crashes.

However, if I take those worlds, without making any changes but I just move them to my develop folder, it works fine. So I guess this is maybe related to PROTOs.
