### ISSUE TITLE
segmentation fault when opening a 2021b world in feature-enu-plan branch

### ISSUE THREAD

**Issue by joachimhgg** [cyberbotics/webots#3964]
## Description
 When opening this simple world, we get an segmentation fault.

## To reproduce

1. save the world:

```
#VRML_SIM R2021b utf8
WorldInfo {
}
Viewpoint {
  orientation -0.06750834915738668 0.4204490417174527 0.9048012080633624 3.4301283492059724
  position -0.5330653428885737 1.6720406742243783 1.3428920098698358
}
Solid {
    children [
      DEF WHEEL Shape {
        geometry Cylinder {
          height 0.01
          radius 0.025
        }
      }
    ]
    boundingObject USE WHEEL
}
```
2. Open it in Webots 2022a (`feature-enu-plan` branch)
3.  `File/New world` or open another world to get the segmentation fault.

## Investigation
The issue is not happening anymore when:
- removing the `boundingObject `
- replacing `2021b` by `2022a`
- test it in the `develop` branch

**Comment by ad-daniel** [comment]
Likely related to this: https://github.com/cyberbotics/webots/pull/3950
Does it still crash in this branch?

**Comment by joachimhgg** [comment]
Indeed it is related, this branch fixed it thanks.
