### ISSUE TITLE
Nested PROTO translation/rotation propagation not functional in groups

### ISSUE THREAD

**Issue by ad-daniel** [cyberbotics/webots#3979]
**Describe the Bug**

For a fairly simple nested PROTO, like a `StraightRoadSegment` inside a `Group`, changing the translation/field has no effect until some other field is changed. The loading of non-default values of translation works fine, is just the changes from GUI that are "temporarely" broken.

```
#VRML_SIM R2021b utf8
# template language: javascript

PROTO Test [
  field   SFVec3f              translation               0 0 0
  field   SFRotation           rotation                  0 0 1 0
  field   SFFloat              width                     7                      
]{
  Group {
    children [
      StraightRoadSegment {
        translation IS translation
        rotation IS rotation
        width IS width
      }
    ]
  }
}
```

To reproduce:
   - load the world in [bug_translation_propagation.zip](https://github.com/cyberbotics/webots/files/7666520/bug_translation_propagation.zip)
   - change translation/rotation field, nothing happens.
   - change width, the road widens
   - change translation/rotation field, now it propagates.

EDIT:
it appears to affect `StraightRoadSegment` but not `Road`

**Comment by stefaniapedrazzi** [comment]
Fixed in  #5779.
