### ISSUE TITLE
Warning on snap

### ISSUE THREAD

**Issue by BenjaminDeleze** [cyberbotics/webots#3985]
**Describe the Bug**
When launching the snap version of Webots I got a lot of warning like 
```
Fontconfig warning: "/etc/fonts/conf.d/10-hinting-slight.conf", line 4: unknown element "its:rules"
Fontconfig warning: "/etc/fonts/conf.d/10-hinting-slight.conf", line 5: unknown element "its:translateRule"
Fontconfig error: "/etc/fonts/conf.d/10-hinting-slight.conf", line 5: invalid attribute 'translate'
Fontconfig error: "/etc/fonts/conf.d/10-hinting-slight.conf", line 5: invalid attribute 'selector'
Fontconfig error: "/etc/fonts/conf.d/10-hinting-slight.conf", line 6: invalid attribute 'xmlns:its'
Fontconfig error: "/etc/fonts/conf.d/10-hinting-slight.conf", line 6: invalid attribute 'version'
```
and so on.

Webots seems to launch normally after that but these warnings were not there before.

**Comment by omichel** [comment]
Did you try [this](https://github.com/cyberbotics/webots/issues/2435#issuecomment-725060754])?

**Comment by omichel** [comment]
Also, it seems we not the only ones experiencing this on snap: https://itectec.com/ubuntu/ubuntu-snap-issue-with-fontsconfig-on-ubuntu-20-04/

The problem is documented [here](https://cyberbotics.com/doc/guide/installation-procedure#troubleshooting). I am afraid we cannot do much in Webots about it, except improve the documentation if the workaround doesn't work and we have a better one.

**Comment by BenjaminDeleze** [comment]
> Did you try [this](https://github.com/cyberbotics/webots/issues/2435#issuecomment-725060754%5D)?

Yes it did not change anything

**Comment by omichel** [comment]
@BenjaminDeleze: May I ask you to test the solution proposed [here](https://itectec.com/ubuntu/ubuntu-snap-issue-with-fontsconfig-on-ubuntu-20-04/)? If that works, I will add it to the documentation.

**Comment by BenjaminDeleze** [comment]
It did not change anything

**Comment by omichel** [comment]
It seems that [updating the snap from core18 to core20 would fix the problem](https://github.com/octave-snap/octave-snap/issues/67#issuecomment-821853801). But if we do this, I fear it won't work any more on Ubuntu 18.04.
