### ISSUE TITLE
GL_INVALID_OPERATION in sumo_interface_example.wbt

### ISSUE THREAD

**Issue by BenjaminDeleze** [cyberbotics/webots#4008]
**Describe the Bug**
OpenGL error: GL_INVALID_OPERATION can be seen after some time in the terminal

Not a regression.

**Steps to Reproduce**
1. Open `sumo_interface_example.wbt`
2. Run
3. Wait some time (1-2 minutes)
4. There will be some errors in the terminal (not the webots one)

**System**
 - Operating System: Linux Ubuntu 20.04

**Comment by joachimhgg** [comment]
I am not able to reproduce the issue on version `R2022a`. Is it still occurring for you?

**Comment by BenjaminDeleze** [comment]
I am not able able to reproduce this issue anymore with the latest version of R2022b
