### ISSUE TITLE
robot endpoint: pen could not draw at web streaming mode

### ISSUE THREAD

**Issue by hanm2019** [cyberbotics/webots#4017]
**Describe the Bug**
pen could not draw at web streaming mode

**Steps to Reproduce**
1. run the `robot/abb/irb/inverse_kinematics.wbt` at web streaming mode

**Expected behavior**
A circle on the paper

**Screenshots**
Screenshots from web:
![image](https://user-images.githubusercontent.com/56673361/145528009-62f06fe7-2f1b-40a0-8344-e81fd5342696.png)

Screenshots from webots:
![image](https://user-images.githubusercontent.com/56673361/145528181-fd5214f8-f92f-4fe5-a99d-170971dd5e99.png)

**System**
 - Operating System: Linux Ubuntu 18.04
 - Graphics Card: NVIDIA GeForce RTX 1080 11 GB
 - Webots Version: 2021a

**Comment by hanm2019** [comment]
I did not install `opencv-python`, Did it matter?

**Comment by BenjaminDeleze** [comment]
Unfortunately, this feature is not yet supported in web streaming mode/ web animation

**Comment by hanm2019** [comment]
thanks~
