### ISSUE TITLE
There may exist a memory leakage issue

### ISSUE THREAD

**Issue by FreshNing** [cyberbotics/webots#4022]
**Describe the Bug**
When I run the example in "${WEBOTS_HOME}\projects\samples\howto\supervisor_draw_trail", the memory consumption continuously increase.  Gradually，the simulation becomes slow and jerky. This problem is even more pronounced when I try to draw more trails. Additionally, referring to the example,  I utilize 'EvaluationGrid' to create a height map. However, it rendered slowly.

**Steps to Reproduce**
1. 'Simulation Reset'  would not release the increased memory
2. A function 'importMFNodeFromString()' was adopted
3. Large amounts of 'Field' modifications, like 'translation' 'rotation' 'height' ...
4. Other 'Node' operations, get Node from DEF and create children Node ...
5. Emitter and Receiver Nodes were used to make comunications between robot and supervisor robot 

**Expected behavior**
Find out the reasons and solutions

**System**
 - Operating System: Windows 10
 - Graphics Card: NVIDIA GeForce GTX 960M 2 GB
 - Webots Version: 2021b

**Additional context**
Wish for replies, thanks!

**Comment by BenjaminDeleze** [comment]
I could reproduce the issue on ubuntu 20 with `supervisor_draw_trail.wbt`.
