### ISSUE TITLE
Simulation view cannot display correctly

### ISSUE THREAD

**Issue by chenlin41204050** [cyberbotics/webots#4080]
**Describe the Bug**

**Steps to Reproduce**
1. Create a new project from the Wizards menu by selecting the New Project Directory
2. Simulation view cannot display correctly.

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/28135110/147360190-14b06768-8d66-4ece-af96-230fe13788c1.png)

**System**
 - Operating System: Windows 10
 - Graphics Card: NVIDIA GeForce GTX 1660 6 GB

**Additional context**
WARNING: RectangleArena (PROTO) > Parquetry (PROTO) > ImageTexture: Cannot download https://raw.githubusercontent.com/cyberbotics/webots/R2022a/projects/appearances/protos/textures/parquetry/chequered_parquetry_base_color.jpg: Error opening https://raw.githubusercontent.com/cyberbotics/webots/R2022a/projects/appearances/protos/textures/parquetry/chequered_parquetry_base_color.jpg
WARNING: RectangleArena (PROTO) > Parquetry (PROTO) > ImageTexture: Cannot download https://raw.githubusercontent.com/cyberbotics/webots/R2022a/projects/appearances/protos/textures/parquetry/chequered_parquetry_roughness.jpg: Error opening https://raw.githubusercontent.com/cyberbotics/webots/R2022a/projects/appearances/protos/textures/parquetry/chequered_parquetry_roughness.jpg
WARNING: RectangleArena (PROTO) > Parquetry (PROTO) > ImageTexture: Cannot download https://raw.githubusercontent.com/cyberbotics/webots/R2022a/projects/appearances/protos/textures/parquetry/chequered_parquetry_normal.jpg: Error opening https://raw.githubusercontent.com/cyberbotics/webots/R2022a/projects/appearances/protos/textures/parquetry/chequered_parquetry_normal.jpg
WARNING: RectangleArena (PROTO) > Parquetry (PROTO) > ImageTexture: Cannot download https://raw.githubusercontent.com/cyberbotics/webots/R2022a/projects/appearances/protos/textures/parquetry/chequered_parquetry_occlusion.jpg: Error opening https://raw.githubusercontent.com/cyberbotics/webots/R2022a/projects/appearances/protos/textures/parquetry/chequered_parquetry_occlusion.jpg
WARNING: RectangleArena (PROTO) > BrushedAluminium (PROTO) > ImageTexture: Cannot download https://raw.githubusercontent.com/cyberbotics/webots/R2022a/projects/appearances/protos/textures/brushed_aluminium/brushed_aluminium_base_color.jpg: Error opening https://raw.githubusercontent.com/cyberbotics/webots/R2022a/projects/appearances/protos/textures/brushed_aluminium/brushed_aluminium_base_color.jpg
WARNING: RectangleArena (PROTO) > BrushedAluminium (PROTO) > ImageTexture: Cannot download https://raw.githubusercontent.com/cyberbotics/webots/R2022a/projects/appearances/protos/textures/brushed_aluminium/brushed_aluminium_roughness.jpg: Error opening https://raw.githubusercontent.com/cyberbotics/webots/R2022a/projects/appearances/protos/textures/brushed_aluminium/brushed_aluminium_roughness.jpg
WARNING: RectangleArena (PROTO) > BrushedAluminium (PROTO) > ImageTexture: Cannot download https://raw.githubusercontent.com/cyberbotics/webots/R2022a/projects/appearances/protos/textures/brushed_aluminium/brushed_aluminium_normal.jpg: Error opening https://raw.githubusercontent.com/cyberbotics/webots/R2022a/projects/appearances/protos/textures/brushed_aluminium/brushed_aluminium_normal.jpg
WARNING: TexturedBackground (PROTO): Cannot retrieve 'https://raw.githubusercontent.com/cyberbotics/webots/R2022a/projects/default/worlds/textures/cubic/mountains_back.png': Cannot download https://raw.githubusercontent.com/cyberbotics/webots/R2022a/projects/default/worlds/textures/cubic/mountains_back.png: Error opening https://raw.githubusercontent.com/cyberbotics/webots/R2022a/projects/default/worlds/textures/cubic/mountains_back.png
WARNING: TexturedBackground (PROTO): Cannot download leftIrradianceUrl: Cannot download https://raw.githubusercontent.com/cyberbotics/webots/R2022a/projects/default/worlds/textures/cubic/mountains_back.hdr: Error opening https://raw.githubusercontent.com/cyberbotics/webots/R2022a/projects/default/worlds/textures/cubic/mountains_back.hdr

**Comment by ad-daniel** [comment]
The links you provided appear to be working, is the issue still happening? Are you behind a firewall/VPN? Might have been a temporary problem on github side.

**Comment by TheChlio** [comment]
r2021a works

**Comment by campagnani** [comment]
I have the same problem in the computer of my university.

The crasy thig is: some user happens this problem, in the same computer, same system, some users don't have this problems.

Distribuition: Ubuntu 22.04

**Comment by oktaspc** [comment]
i have the same issue in my pc

i installed webot using terminal.

Distribuition: Ubuntu 22.04

**Comment by omichel** [comment]
Could you please with the latest [nightly build](https://github.com/cyberbotics/webots/releases) of Webots R2022b? It should work with this version.

**Comment by campagnani** [comment]
@oktaspc I tested the R2022b and this solved the bug.
