### ISSUE TITLE
Scaling of basic shapes is non-functional

### ISSUE THREAD

**Issue by ad-daniel** [cyberbotics/webots#4087]
**Describe the Bug**
In 2022a, scaling of basic shapes (using the resize manipulator) no longer works as intended 

**Steps to Reproduce**
1. Create a `Transform { Shape { Box {} } }` (or any other geometry)
2. Select the transform from the scene tree
3. Press CTRL and attempt to extend one of the 3 axis
4. Sometimes nothing happens, sometimes it extends the shape in the opposite direction (it has the tendency to flatten the shape). Likewise uniform resize (CTRL + SHIFT) only works sporadically or for certain axis.

It's a regression since it was working correctly in R2021b.

**Comment by BenjaminDeleze** [comment]
I have not tested it, but it may come from here: https://github.com/cyberbotics/webots/pull/3540
