### ISSUE TITLE
"Front View" should be "South View"

### ISSUE THREAD

**Issue by Thomas-Feldmeier** [cyberbotics/webots#4111]
Load sample world "pedestrian", select green pedestrian

 view > change view > front view (alt + 2)

The view is always from south to north. The view is not of the front side of the pedestrian.

![pedestrian](https://user-images.githubusercontent.com/73528085/149146690-6a2e6372-ece1-41b7-952b-ffc9e2e9ec42.png)

Rename
"Front View" -> "South View" (from -y to +y of world EastNorthUp (ENU) coordinate system)
"Back View" -> "North View"
"Left View" -> "West View"
"Right View" -> "East View"

Maybe add a true "Front View" (from +x to -x relative to selected object) etc.

**Comment by ad-daniel** [comment]
Additionally, I think the shortcuts should probably be re-set.

![aa](https://user-images.githubusercontent.com/44834743/149183035-3f6d8362-5f57-4e8b-ad40-bcee970354cc.png)

There isn't much logic behind it currently (to my knowledge), and considering things like ALT + 5 (move viewpoint to object) and ALT + 3 (does nothing) are scattered among them, the overall behavior seems a bit random.

A fix could be setting ALT + 1 to ALT + 6 just for views, or there might be a better mapping. We can perhaps check how it's done in other software.

**Comment by ShuffleWire** [comment]
I think you could use what Blender use, as long as I remember, it was very convenient

**Comment by stefaniapedrazzi** [comment]
I just checked what is done in Blender (I have version 3.0.1):
* Viewpoint standard views:
    `Top`/`Bottom`/`Front`/`Back`/`Front`/`Left views match exactly what we implemented in Webots -> same name and same behavior
* Additionally Blender has a menu item "Align View" > "Align View To Active" with again the 6 options (Top/Bottom/Front/Back/Right/Left)

**Comment by omichel** [comment]
Yes, but blender doesn't have the ENU concepts we have in Webots `WorldInfo.coordinateSystem`, so the cardinal directions seems to be a good alternative to the front/back, left/right terminology for Webots.
