### ISSUE TITLE
wb_robot_get_type supposedly returns an undocumented constant

### ISSUE THREAD

**Issue by Justin-Fisher** [cyberbotics/webots#4121]
Webots docs say that `wb_robot_get_type` will return either `WB_NODE_ROBOT` or `WB_NODE_SUPERVISOR`.  As far as I can tell, the latter of these isn't a real constant.  It doesn't occur in the docs for Supervisor > NodeType, and it is not defined in the MatLab constants, which aims to gather all the constants in one place.  Also, it seems unlikely that this would be a constant, since Supervisor isn't really a node type itself, and instead just is a flag that can be set in nodes of type Robot.

It may be that the fix here is to add documentation for a `WB_NODE_SUPERVISOR` constant, ensure that `wb_robot_get_type` will return this constant for supervisors, and ensure that this constant is available in all languages.

Or it may be that the fix is to say that `wb_robot_get_type` will always return `WB_NODE_ROBOT` since that's the nodetype that all robot nodes have, regardless of whether their supervisor flag is True or False.  

Of course, if this function always returns the same constant, then you've gotta ask whether it's even worth having this as a function, when people could just refer to that constant directly?  So I suspect the real fix is probably just to delete or at least deprecate `wb_robot_get_type`.  The main purpose that it was supposed to serve -- telling you whether your robot has permission to use supervisor powers -- is better served by `wb_robot_get_supervisor` anyway.

**Comment by omichel** [comment]
That's a good point. This function seems to be a legacy which dates back from the times where the `Supervisor` was a Webots node. I believe we can safely remove it.
