### ISSUE TITLE
Can't download picture from github.

### ISSUE THREAD

**Issue by SB-Moloo** [cyberbotics/webots#4122]
**Describe the Bug**
When I open WEBOTS, it show some WARNING. I have tried many kinds of method to fix it such as unload and load.

**Screenshots**
![1642307665(1)](https://user-images.githubusercontent.com/73786065/149647464-92bda577-e66d-4df6-9a12-04d56d77b147.jpg)

**Comment by ShuffleWire** [comment]
Maybe this could help you ? https://github.com/cyberbotics/webots/issues/3574

**Comment by SB-Moloo** [comment]
> Maybe this could help you ? #3574

thank you very much!!!
