### ISSUE TITLE
webots  web streaming_viewer  change  world file  path error

### ISSUE THREAD

**Issue by o0stinger0o** [cyberbotics/webots#4123]
when i use web streaming_viewer
I have several world files in the "world" folder

i run webots with:
webots --stream /path/world/xxxxx.wbt
chage the world file in web will see:
ERROR: Streaming server: world /path/worlds//xxxxx.wbt doesn't exist.
It has an unexpected slash

There is no error when switching world files after changing the folder "world" to "worlds"

**Comment by omichel** [comment]
It is a requirement that the folder containing a webots world is named "worlds". Hence it is not possible to rename this folder "world". See [documentation about it](https://cyberbotics.com/doc/guide/the-standard-file-hierarchy-of-a-project).
