### ISSUE TITLE
Python 3.10 support

### ISSUE THREAD

**Issue by SGSSGene** [cyberbotics/webots#4128]
Currently, webots only works with python 3.9 (or lower). It would be nice to have python 3.10 support.

**Comment by SGSSGene** [comment]
Very cool, thank you. For reference, I have patched a few things, so I can run the Robocup-HumanoidTC branch.
My changes are too chaotic for a PR, but maybe helpful for the next person working on it.
https://github.com/SGSSGene/webots/commit/dcee03c99bb785fa4cb961e0f738875c40fff91b

**Comment by omichel** [comment]
That looks like a very good start. Could you please go ahead and create a draft PR which we will review and possibly complete? I just sent you an invite to become a member of the Webots committers, this should facilitate your contribution.

**Comment by omichel** [comment]
Note: @Justin-Fisher is currently developing a new Python API which should be fully independent from the Python version (for Python >= 3.5). See details at #3801. So, it may not be necessary in the long term to maintain manual support for each version of python...
