### ISSUE TITLE
cannot import _controller.so webots 2022a

### ISSUE THREAD

**Issue by Jenifen** [cyberbotics/webots#4134]
Error occured when i run the Simulation :  
ImportError: /usr/local/webots/lib/controller/python38/_controller.so: undefined symbol: _ZNK6webots3GPS14getSpeedVectorEvpen  

![bug_controller](https://user-images.githubusercontent.com/46198024/150165888-55aeec7c-4b04-4b21-b5e7-1736e8e2dd86.png)

**System**
 - Operating System: Linux Ubuntu 20.04
 - Graphics Card: NVIDIA GeForce GTX 1650
 - webots 2022a
 - python38

Thanks !

**Comment by ad-daniel** [comment]
Can you post the values of:
```
echo $WEBOTS_HOME
echo $PYTHONPATH
```
They should reference the 2022a folder

**Comment by Jenifen** [comment]
thanks for your response : 

**$WEBOTS_HOME** : /usr/local/webots
**$PYTHONPATH** : /opt/ros/foxy/lib/python3.8/site-packages
