### ISSUE TITLE
Speaker test is currently broken

### ISSUE THREAD

**Issue by ad-daniel** [cyberbotics/webots#4144]
**Describe the Bug**

Test `speaker.wbt` currently fails even on a local machine (Ubuntu 20).

`FAILURE with speaker: wb_speaker_is_speaking should return true when TTS is running.`

Likely introduced here: https://github.com/cyberbotics/webots/pull/4047

**Comment by stefaniapedrazzi** [comment]
It seems this should already be fixed in https://github.com/cyberbotics/webots/pull/4067.
@ad-daniel can we close this issue?

**Comment by ad-daniel** [comment]
Yes indeed
