### ISSUE TITLE
M1 Chip issues with Python Library

### ISSUE THREAD

**Issue by Suke0811** [cyberbotics/webots#4160]
Is there official support for the Apple M1 chip? 
When we try to run through 'extern' controller, we got an error saying architecture is incompatible as shown below.
![image](https://user-images.githubusercontent.com/49264928/151463426-8e791f03-c27a-46d1-ba05-ab617de2e223.png)

This is with M1 Macbook air, using Python 39.

_Originally posted by @Suke0811 in https://github.com/cyberbotics/webots/discussions/2574#discussioncomment-2063011_

**Comment by omichel** [comment]
Please follow-up on this in https://github.com/cyberbotics/webots/discussions/2574#discussioncomment-2063011
