### ISSUE TITLE
Weird boundingobject(collision) on the ElevationGrid 

### ISSUE THREAD

**Issue by james-yoo** [cyberbotics/webots#4169]
**Describe the Bug**
BoundingObject is not aligned correctly when ElevationGrid is imported by 'osm_importer'.

**Steps to Reproduce**
1. Install Webots R2022a
2. Open world 'CH_Vens.wbt'
3. Add any object to the scene
4. Start simulation

**Expected behavior**
BoundingObject of the ElevationGrid should correctly matched to the Floor node(=appearance mesh).

**Screenshots**
BoundingObject of the ElevationGrid is not aligned as follow animation(you can see the contact point in the air):
![CH_Vens_collision](https://user-images.githubusercontent.com/23667624/151658826-733cb077-a87f-401e-a915-4bf8a113828f.gif)

**System**
 - Operating System:Windows 10,
 - Graphics Card: NVIDIA GeForce Titan 1080

**Comment by ad-daniel** [comment]
Part of the issue is related to this https://github.com/cyberbotics/webots/issues/3884, meaning the location where the `boundingObject` is rendered (drawn) for elevation grid doesn't coincide where it is physically. But from your animation it seems the location is also wrong, or something else is causing it

**Comment by james-yoo** [comment]
I would like to know how to fix this issue. Is it a problem of osm_importer?

**Comment by ShuffleWire** [comment]
I just took a look at this bug, and it's still present in 2023b.

Crafted a more minimal example : 
[CH_Vens_simplified.wbt.zip](https://github.com/cyberbotics/webots/files/12537205/CH_Vens_simplified.wbt.zip)

But I suspect something is wrong with those huge Grid...
