### ISSUE TITLE
Webots github wiki pages hard to find by search engines

### ISSUE THREAD

**Issue by Thomas-Feldmeier** [cyberbotics/webots#4170]
The information in https://github.com/cyberbotics/webots/wiki are not indexed by search engines like google. If that wiki would run on a server from webots, it would help to increase the visibility.

(webots wiki on github: `https://github.com/cyberbotics/webots/wiki`)

(see `https://github-wiki-see.page/` for more information)

**Comment by ad-daniel** [comment]
I suppose we could also add a more direct link in https://cyberbotics.com/doc/guide/installation-procedure to the wiki for people that might be interested in installing webots from source, since I don't think it's mentioned in the website.

**Comment by nelsonjchen** [comment]
Hi, I run https://github-wiki-see.page/. I keep a watch on any mention of the service on GitHub

It looks like the GitHub Wiki is now directly indexable. 

* Has more than 500 stars
* Unpublically editable.

**Comment by omichel** [comment]
Yes, as our repository has more than 1000 stars and is not publicly editable, it is properly indexed and listed [here](https://docs.google.com/spreadsheets/d/1y5V1xVtL-Z4w4yt9mVQuwGCP3s8TgNAS756IKStRUqs/edit?usp=sharing). So, I am closing this issue for now.
