### ISSUE TITLE
[SUMO Interface] SUMO does not recognize vehicle added in webots

### ISSUE THREAD

**Issue by tciuan** [cyberbotics/webots#4239]
**Describe the Bug**
I have connected SUMO and Webots using the SUMO interface. The SUMO generates serverals vehicles and it shows well in the webots. However, I add a vehicle in webots and I want the SUMO should also be able to detect the vehicle in generate the traffic flow.

**Expected behavior**
The SUMO should detect the vehicle added in webots and generate the trips which can avoid the vehicle. 

**Screenshots**
The red vehicle being crashed is added in webots directly. All the other vehicle are generated by SUMO. As shown in below figure, the SUMO does not recognize the red vehicle and crashed into the red one directly.

![Picture1](https://user-images.githubusercontent.com/55172725/154142557-4867f085-7f17-4b53-aaea-17673b69eeb7.png)

**System**
 - Operating System: [e.g., Windows 10]
 - Graphics Card: [e.g., NVIDIA GeForce  3070]

**Additional context**

**Comment by ad-daniel** [comment]
I believe you need to give a DEF name to the red vehicle in the form: `WEBOTS_VEHICLE0` for sumo to be aware of it and avoid it (or at least try to, depending on where you spawn the other vehicles it might be too late to avoid a crash)

**Comment by ad-daniel** [comment]
I will close this for now, feel free to re-open this if needed.

**Comment by Yashraj19032001** [comment]
Hi, I am facing this issue in SUMO![164303942-c827fa9d-0a1b-4847-8681-5f479fe86fa1.png](https://user-images.githubusercontent.com/104098645/164375793-579561d3-d915-4181-abc5-9fccae28ac73.png) ,![unknown.png](https://user-images.githubusercontent.com/104098645/164375826-5e191c7f-83e0-4433-8e76- [ ] -ef8885c26cbc.png) can u please guide me .
Traceback (most recent call last):
File "av_challenge_controller.py", line 3, in
from vehicle import Driver
File "D:\Pillai college\4th Year\Final Year Project\Webots\lib\controller\python37\vehicle.py", line 31, in
import _vehicle
ImportError: DLL load failed: The specified module could not be found.
WARNING: 'av_challenge_controller' controller exited with status: 1.
this is showing in my console.

**Comment by Yashraj19032001** [comment]
Hi, I am facing this issue in SUMO INTERFACE, can u please guide me .
Traceback (most recent call last):
File "av_challenge_controller.py", line 3, in
from vehicle import Driver
File "D:\Pillai college\4th Year\Final Year Project\Webots\lib\controller\python37\vehicle.py", line 31, in
import _vehicle
ImportError: DLL load failed: The specified module could not be found.
WARNING: 'av_challenge_controller' controller exited with status: 1.
this is showing in my console.
![unknown.png](https://user-images.githubusercontent.com/104098645/164376150-793a41fb-c8f1-4bd1-a5b1-f2dff58289fb.png)

**Comment by omichel** [comment]
Can you open and run the sumo_interface_example.wbt file provided with Webots?
It seems your problem is not related with SUMO, but with Python.
May I ask you to try with Python 3.8 or 3.9 instead of 3.7?

**Comment by omichel** [comment]
Can you try with Webots R2022a instead?

**Comment by Yashraj19032001** [comment]
> Can you try with Webots R2022a instead?

It worked in python 3.8
I have one more doubt 
https://github.com/athishr88/Autonomous_vehicle
in this project 
in prallel parking and other scenario I am getting this error 
![image](https://user-images.githubusercontent.com/104098645/164411495-c9e2c3e3-d7f3-4b43-8413-b37a754d50a5.png)

**Comment by omichel** [comment]
You should probably pip install opencv for python 3.8.

**Comment by Yashraj19032001** [comment]
It is showing like this 
![image](https://user-images.githubusercontent.com/104098645/164413290-903d4ea6-cd25-4b6a-9786-6b4c8866acb9.png)

**Comment by Yashraj19032001** [comment]
![image](https://user-images.githubusercontent.com/104098645/164418788-d3bf78de-7960-4132-b00c-708f84d61886.png)
I m facing this prolem 
![image](https://user-images.githubusercontent.com/104098645/164419011-1dc3f954-1a5d-4edc-a27d-3693ece656c7.png)

**Comment by omichel** [comment]
Did you managed to solve the problem?
