### ISSUE TITLE
Mesh appearance is broken on develop

### ISSUE THREAD

**Issue by BenjaminDeleze** [cyberbotics/webots#4287]
![spot](https://user-images.githubusercontent.com/25938827/155955957-7c3bdbac-3d90-4d07-b36b-b78cb88da2c4.png)

**Comment by BenjaminDeleze** [comment]
The shoulder of the Nao is strange too.

After some research it seems to come from this PR #4243

**Comment by BenjaminHug8** [comment]
Solved in #4302
