### ISSUE TITLE
Change ROS 1 tutorial commands with the release of Webots R2022b

### ISSUE THREAD

**Issue by BenjaminHug8** [cyberbotics/webots#4291]
**Describe the Task**
The PR https://github.com/cyberbotics/webots/pull/4103# added namespace for topics, services, actions and nodes. Thus some commands to run the examples of `webots_ros` have changed in https://github.com/cyberbotics/webots_ros/pull/102.

The tutorials on this [page](http://wiki.ros.org/webots_ros/Tutorials/Sample%20Simulations) have to include the new commands when `Webots R2022b` and the corresponding ROS packages are released.

**Comment by ygoumaz** [comment]
The page is now up-to-date and all tutorials work fine on R2022b.
