### ISSUE TITLE
SUMO vehicle did not follow the presetting route and float everywhere

### ISSUE THREAD

**Issue by zhangcong0315** [cyberbotics/webots#4315]
After building a vehicle in Webots, some vehicles generated in sumo cannot follow their original route to move.
I used the following steps and saw the error:
1. generate a webot vehicle
2. use controller "sumo_supervisor" to reflect this vehicle into sumo
3. reset controller to "my*controller"--I want to control the webot vehicle by setting it speed to 80 mph
4. Run and See error: the other vehicles (generated in sumo) move out of the road (floating everywhere). I did not change any setting to control the sumo vehicles route. Why they cannot follow the original route? 
![image](https://user-images.githubusercontent.com/61287266/156686319-c2f7b111-8b30-4178-b210-d1e02cc79a10.png)

**Comment by BenjaminDeleze** [comment]
I'm closing this for now, feel free to reopen it if you have additional issues.
