### ISSUE TITLE
Open port warning

### ISSUE THREAD

**Issue by BenjaminDeleze** [cyberbotics/webots#4322]
These warnings are displayed when opening two instances of Webots.
It is not clear in the message why Webots try to open a streaming server (it is to be able to display robot windows).

```
ERROR: Error when creating the TCP streaming server on port 1234: Cannot set the server in listen mode: The bound address is already in use
WARNING: Trying again with port 1235
```

We should improve the message and also refactor the code to open a streaming server only when the user open the first robot window or launch Webots with `--stream`

**Comment by omichel** [comment]
The web server is needed even if we don't open stream the simulation: it is used by the robot window and the remote extern controllers. So, we shall keep the code like this. I will try to improve a little bit the message so that it shows:

```
WARNING: Cannot listen to port 1234 because it already in use, using port 1235 instead.
```
