### ISSUE TITLE
Progress bars difference between themes

### ISSUE THREAD

**Issue by ad-daniel** [cyberbotics/webots#4342]
**Describe the Bug**

It seems the progress bars for dark and classic themes differ

![a](https://user-images.githubusercontent.com/44834743/158327503-0e93b061-972e-4d37-96dc-7e19ef15c189.png)
![b](https://user-images.githubusercontent.com/44834743/158327512-47fb8717-9d4c-47a3-9db1-30fd679d33fb.png)

Both should show the progress percentage.

**Comment by BenjaminDeleze** [comment]
I now have the text not at the right place on develop if I use the dark or dusk theme
![Screenshot from 2022-03-21 14-02-48](https://user-images.githubusercontent.com/25938827/159267318-03140b5b-9889-4fe7-a947-abc389d19a81.png)

**Comment by ad-daniel** [comment]
I can reproduce it, but only on develop. I suspect it might be something that is no longer the default in Qt6
