### ISSUE TITLE
Broken robot window on develop

### ISSUE THREAD

**Issue by omichel** [cyberbotics/webots#4345]
When opening the e-puck robot window in Firefox on Windows on the develop branch, the layout is completely messed up (see below) and I am getting this error in the console:
```js
The stylesheet http://localhost:1234/robot_windows/e-puck/e-puck.css was not loaded because its MIME type, “text/html”, is not “text/css”.
```
In Chrome, it works fine.
Here is what I get in Firefox:
![image](https://user-images.githubusercontent.com/1264964/158566006-0ef16927-79b8-40a5-b0e6-ccb0912f3f44.png)

**Comment by BenjaminDeleze** [comment]
I cannot reproduce it on Ubuntu 20

**Comment by omichel** [comment]
I cannot reproduce it any more either. It was probably a problem with my local browser cache.
