### ISSUE TITLE
ROS Contact Point interface doesn't follow documentation; docs also not very descriptive

### ISSUE THREAD

**Issue by nathanieltagg** [cyberbotics/webots#4362]
**Describe the Bug**
ROS controller does not present contact points as documentation lists

**Steps to Reproduce**
Start webots with a ROS-controlled robot.
$ rosservice list | grep contact
yields these services:
/MyRobot/supervisor/node/disable_contact_points_tracking
/MyRobot/supervisor/node/enable_contact_point_tracking
/MyRobot/supervisor/node/get_contact_point
/MyRobot/supervisor/node/get_contact_point_node
/MyRobot/supervisor/node/get_number_of_contact_points

**Expected behavior**
The documentation says there should be a service /get_contact_points
 https://cyberbotics.com/doc/reference/supervisor?tab-language=ros#wb_supervisor_node_get_contact_points
The currently advertised service "get_contact_point" seems to be able to access only a single point at a time.

It's not obvious how to use contact points.  For instance, asking for get_number_of_contact_points on my robot node, with recusion on, seems to crash the ros controller.

**System**
R2022a

**Comment by ad-daniel** [comment]
You're right, in theory those API functions have been deprecated [here](https://github.com/cyberbotics/webots/pull/3162) and the change to `get_contact_pointS` introduced with `R2021b`. Not sure why they're still mentioned, either way the documented services are the correct one. I'll look into it.
