### ISSUE TITLE
No Stdout output when no webots console is open

### ISSUE THREAD

**Issue by SGSSGene** [cyberbotics/webots#4368]
**Describe the Bug**
If I run webots with `--stdout --stderr` I only receive output in bash if I have a console open in webots (which shows nothing).
If I start webots with any console open, I also don't receive anyoutput in bash. It starts outputting as soon I open a console in webots.

**Context**
This was actually run in the RoboCup version of webots, but I am strongly assuming that the same issue exists in webots.

**Comment by whtqh** [comment]
***@***.***谢谢！王海涛
