### ISSUE TITLE
Lack libb2-1.dll

### ISSUE THREAD

**Issue by FreshNing** [cyberbotics/webots#4379]
1. open webots
2. See error

**System**
 - Operating System:   Windows 10
 - Graphics Card:  NVIDIA GeForce GTX960M 2GB
 - webots version: 2022-3-22 released webots2022b-windows-setup.exe

**Comment by omichel** [comment]
Thank you for this bug report. I believe I fixed it in #4384. The fix should in the next nightly builds.
