### ISSUE TITLE
Some asset sizes are excessive for what they bring

### ISSUE THREAD

**Issue by ad-daniel** [cyberbotics/webots#4397]
**Describe the Bug**

Among the webots assets, there's a number of textures which are fairly big (both in terms of resolution and file size, some being several MB). As such it should be evaluated if keeping them in their current state is justified of if instead they can and should be compressed/adjusted. Some degree of performance improvement should be possible.

**Comment by omichel** [comment]
I suggest that we don't invest more time in this issue for R2022b.
