### ISSUE TITLE
POV and axises values in joystick is not appropriate when using ros

### ISSUE THREAD

**Issue by FreshNing** [cyberbotics/webots#4399]
**Describe the Bug**
The pov value type in ros topic is Int8Stamped, so when using ros to get the joystick pov value, I can only read up(1) and down(16) buttons. While using normal cpp API, I can read left(4096),  right(256) buttons and their combinations.
Additionally, the joystick button released status will not be detected

**System**
 - Operating System: [Linux Ubuntu 20.04]
 - ROS Version: noetic
 - Joystick: Logitech F710
 - Webots Version: 2022b

**Comment by omichel** [comment]
We should probably replace `Int8Stamped` with `Int16Stamped` in [RosJoystick.cpp](https://github.com/cyberbotics/webots/edit/master/projects/default/controllers/ros/RosJoystick.cpp). May I ask you to do it and propose your changes in a new Pull Request?

**Comment by FreshNing** [comment]
> We should probably replace `Int8Stamped` with `Int16Stamped` in [RosJoystick.cpp](https://github.com/cyberbotics/webots/edit/master/projects/default/controllers/ros/RosJoystick.cpp). May I ask you to do it and propose your changes in a new Pull Request?

I only made some Subtle changes and tested it on ubuntu. Now it works. thanks for replies.

**Comment by FreshNing** [comment]
> We should probably replace `Int8Stamped` with `Int16Stamped` in [RosJoystick.cpp](https://github.com/cyberbotics/webots/edit/master/projects/default/controllers/ros/RosJoystick.cpp). May I ask you to do it and propose your changes in a new Pull Request?

I make a new change in [RosJoystick.cpp](https://github.com/cyberbotics/webots/blob/master/projects/default/controllers/ros/RosJoystick.hpp), which fix the situation that joystick button released status can not be detected when using ros. And I have updated the changelog and documentation about joystick.

**Comment by omichel** [comment]
Could you please add your changes on #4401?

**Comment by FreshNing** [comment]
> Could you please add your changes on #4401?

Changed already.
