### ISSUE TITLE
no color

### ISSUE THREAD

**Issue by OZZHaoO** [cyberbotics/webots#4420]
WARNING: Floor (PROTO) > SandyGround (PROTO) > ImageTexture: Cannot download https://raw.githubusercontent.com/cyberbotics/webots/R2022a/projects/appearances/protos/textures/sandy_ground/sandy_ground_base_color.jpg: 打开https://raw.githubusercontent.com/cyberbotics/webots/R2022a/projects/appearances/protos/textures/sandy_ground/sandy_ground_base_color.jpg发生错误
WARNING: Floor (PROTO) > SandyGround (PROTO) > ImageTexture: Cannot download https://raw.githubusercontent.com/cyberbotics/webots/R2022a/projects/appearances/protos/textures/sandy_ground/sandy_ground_roughness.jpg: 打开https://raw.githubusercontent.com/cyberbotics/webots/R2022a/projects/appearances/protos/textures/sandy_ground/sandy_ground_roughness.jpg发生错误
WARNING: Floor (PROTO) > SandyGround (PROTO) > ImageTexture: Cannot download https://raw.githubusercontent.com/cyberbotics/webots/R2022a/projects/appearances/protos/textures/sandy_ground/sandy_ground_normal.jpg: 打开https://raw.githubusercontent.com/cyberbotics/webots/R2022a/projects/appearances/protos/textures/sandy_ground/sandy_ground_normal.jpg发生错误
WARNING: Floor (PROTO) > SandyGround (PROTO) > ImageTexture: Cannot download https://raw.githubusercontent.com/cyberbotics/webots/R2022a/projects/appearances/protos/textures/sandy_ground/sandy_ground_occlusion.jpg: 打开https://raw.githubusercontent.com/cyberbotics/webots/R2022a/projects/appearances/protos/textures/sandy_ground/sandy_ground_occlusion.jpg发生错误
WARNING: Road (PROTO) > Pavement (PROTO) > ImageTexture: Cannot download https://raw.githubusercontent.com/cyberbotics/webots/R2022a/projects/appearances/protos/textures/pavement/black_stone_pavement_base_color.jpg: 打开https://raw.githubusercontent.com/cyberbotics/webots/R2022a/projects/appearances/protos/textures/pavement/black_stone_pavement_base_color.jpg发生错误
WARNING: Road (PROTO) > Pavement (PROTO) > ImageTexture: Cannot download https://raw.githubusercontent.com/cyberbotics/webots/R2022a/projects/appearances/protos/textures/pavement/black_stone_pavement_roughness.jpg: 打开https://raw.githubusercontent.com/cyberbotics/webots/R2022a/projects/appearances/protos/textures/pavement/black_stone_pavement_roughness.jpg发生错误
WARNING: Road (PROTO) > Pavement (PROTO) > ImageTexture: Cannot download https://raw.githubusercontent.com/cyberbotics/webots/R2022a/projects/appearances/protos/textures/pavement/black_stone_pavement_normal.jpg: 打开https://raw.githubusercontent.com/cyberbotics/webots/R2022a/projects/appearances/protos/textures/pavement/black_stone_pavement_normal.jpg发生错误
WARNING: Road (PROTO) > Pavement (PROTO) > ImageTexture: Cannot download https://raw.githubusercontent.com/cyberbotics/webots/R2022a/projects/appearances/protos/textures/pavement/black_stone_pavement_occlusion.jpg: 打开https://raw.githubusercontent.com/cyberbotics/webots/R2022a/projects/appearances/protos/textures/pavement/black_stone_pavement_occlusion.jpg发生错误
WARNING: Windmill (PROTO) > Shape > PBRAppearance > ImageTexture: Cannot download https://raw.githubusercontent.com/cyberbotics/webots/R2022a/projects/objects/buildings/protos/textures/windmill_base_color.jpg: 打开https://raw.githubusercontent.com/cyberbotics/webots/R2022a/projects/objects/buildings/protos/textures/windmill_base_color.jpg发生错误
WARNING: Windmill (PROTO) > Shape > PBRAppearance > ImageTexture: Cannot download https://raw.githubusercontent.com/cyberbotics/webots/R2022a/projects/objects/buildings/protos/textures/windmill_roughness.jpg: 打开https://raw.githubusercontent.com/cyberbotics/webots/R2022a/projects/objects/buildings/protos/textures/windmill_roughness.jpg发生错误
WARNING: Windmill (PROTO) > Shape > PBRAppearance > ImageTexture: Cannot download https://raw.githubusercontent.com/cyberbotics/webots/R2022a/projects/objects/buildings/protos/textures/windmill_metalness.jpg: 打开https://raw.githubusercontent.com/cyberbotics/webots/R2022a/projects/objects/buildings/protos/textures/windmill_metalness.jpg发生错误
WARNING: Windmill (PROTO) > Shape > PBRAppearance > ImageTexture: Cannot download https://raw.githubusercontent.com/cyberbotics/webots/R2022a/projects/objects/buildings/protos/textures/windmill_normal.jpg: 打开https://raw.githubusercontent.com/cyberbotics/webots/R2022a/projects/objects/buildings/protos/textures/windmill_normal.jpg发生错误
WARNING: Windmill (PROTO) > Shape > PBRAppearance > ImageTexture: Cannot download https://raw.githubusercontent.com/cyberbotics/webots/R2022a/projects/objects/buildings/protos/textures/windmill_occlusion.jpg: 打开https://raw.githubusercontent.com/cyberbotics/webots/R2022a/projects/objects/buildings/protos/textures/windmill_occlusion.jpg发生错误
WARNING: SmallManor (PROTO) > Shape > PBRAppearance > ImageTexture: Cannot download https://raw.githubusercontent.com/cyberbotics/webots/R2022a/projects/objects/buildings/protos/textures/small_manor_roof_base_color.jpg: 打开https://raw.githubusercontent.com/cyberbotics/webots/R2022a/projects/objects/buildings/protos/textures/small_manor_roof_base_color.jpg发生错误
WARNING: SmallManor (PROTO) > Shape > PBRAppearance > ImageTexture: Cannot download https://raw.githubusercontent.com/cyberbotics/webots/R2022a/projects/objects/buildings/protos/textures/small_manor_roof_roughness.jpg: 打开https://raw.githubusercontent.com/cyberbotics/webots/R2022a/projects/objects/buildings/protos/textures/small_manor_roof_roughness.jpg发生错误
WARNING: SmallManor (PROTO) > Shape > PBRAppearance > ImageTexture: Cannot download https://raw.githubusercontent.com/cyberbotics/webots/R2022a/projects/objects/buildings/protos/textures/small_manor_roof_metalness.jpg: 打开https://raw.githubusercontent.com/cyberbotics/webots/R2022a/projects/objects/buildings/protos/textures/small_manor_roof_metalness.jpg发生错误
WARNING: SmallManor (PROTO) > Shape > PBRAppearance > ImageTexture: Cannot download https://raw.githubusercontent.com/cyberbotics/webots/R2022a/projects/objects/buildings/protos/textures/small_manor_roof_normal.jpg: 打开https://raw.githubusercontent.com/cyberbotics/webots/R2022a/projects/objects/buildings/protos/textures/small_manor_roof_normal.jpg发生错误
WARNING: SmallManor (PROTO) > Shape > PBRAppearance > ImageTexture: Cannot download https://raw.githubusercontent.com/cyberbotics/webots/R2022a/projects/objects/buildings/protos/textures/small_manor_roof_occlusion.jpg: 打开https://raw.githubusercontent.com/cyberbotics/webots/R2022a/projects/objects/buildings/protos/textures/small_manor_roof_occlusion.jpg发生错误
WARNING: SmallManor (PROTO) > Shape > PBRAppearance > ImageTexture: Cannot download https://raw.githubusercontent.com/cyberbotics/webots/R2022a/projects/objects/buildings/protos/textures/small_manor_walls_base_color.jpg: 打开https://raw.githubusercontent.com/cyberbotics/webots/R2022a/projects/objects/buildings/protos/textures/small_manor_walls_base_color.jpg发生错误
WARNING: SmallManor (PROTO) > Shape > PBRAppearance > ImageTexture: Cannot download https://raw.githubusercontent.com/cyberbotics/webots/R2022a/projects/objects/buildings/protos/textures/small_manor_walls_roughness.jpg: 打开https://raw.githubusercontent.com/cyberbotics/webots/R2022a/projects/objects/buildings/protos/textures/small_manor_walls_roughness.jpg发生错误
WARNING: SmallManor (PROTO) > Shape > PBRAppearance > ImageTexture: Cannot download https://raw.githubusercontent.com/cyberbotics/webots/R2022a/projects/objects/buildings/protos/textures/small_manor_walls_metalness.jpg: 打开https://raw.githubusercontent.com/cyberbotics/webots/R2022a/projects/objects/buildings/protos/textures/small_manor_walls_metalness.jpg发生错误
WARNING: SmallManor (PROTO) > Shape > PBRAppearance > ImageTexture: Cannot download https://raw.githubusercontent.com/cyberbotics/webots/R2022a/projects/objects/buildings/protos/textures/small_manor_walls_normal.jpg: 打开https://raw.githubusercontent.com/cyberbotics/webots/R2022a/projects/objects/buildings/protos/textures/small_manor_walls_normal.jpg发生错误
WARNING: SmallManor (PROTO) > Shape > PBRAppearance > ImageTexture: Cannot download https://raw.githubusercontent.com/cyberbotics/webots/R2022a/projects/objects/buildings/protos/textures/small_manor_walls_occlusion.jpg: 打开https://raw.githubusercontent.com/cyberbotics/webots/R2022a/projects/objects/buildings/protos/textures/small_manor_walls_occlusion.jpg发生错误
WARNING: SmallManor (PROTO) > Shape > PBRAppearance > ImageTexture: Cannot download https://raw.githubusercontent.com/cyberbotics/webots/R2022a/projects/objects/buildings/protos/textures/small_manor_frame_base_color.jpg: 打开https://raw.githubusercontent.com/cyberbotics/webots/R2022a/projects/objects/buildings/protos/textures/small_manor_frame_base_color.jpg发生错误
WARNING: SmallManor (PROTO) > Shape > PBRAppearance > ImageTexture: Cannot download https://raw.githubusercontent.com/cyberbotics/webots/R2022a/projects/objects/buildings/protos/textures/small_manor_frame_roughness.jpg: 打开https://raw.githubusercontent.com/cyberbotics/webots/R2022a/projects/objects/buildings/protos/textures/small_manor_frame_roughness.jpg发生错误
WARNING: SmallManor (PROTO) > Shape > PBRAppearance > ImageTexture: Cannot download https://raw.githubusercontent.com/cyberbotics/webots/R2022a/projects/objects/buildings/protos/textures/small_manor_frame_metalness.jpg: 打开https://raw.githubusercontent.com/cyberbotics/webots/R2022a/projects/objects/buildings/protos/textures/small_manor_frame_metalness.jpg发生错误
WARNING: SmallManor (PROTO) > Shape > PBRAppearance > ImageTexture: Cannot download https://raw.githubusercontent.com/cyberbotics/webots/R2022a/projects/objects/buildings/protos/textures/small_manor_frame_normal.jpg: 打开https://raw.githubusercontent.com/cyberbotics/webots/R2022a/projects/objects/buildings/protos/textures/small_manor_frame_normal.jpg发生错误
WARNING: SmallManor (PROTO) > Shape > PBRAppearance > ImageTexture: Cannot download https://raw.githubusercontent.com/cyberbotics/webots/R2022a/projects/objects/buildings/protos/textures/small_manor_frame_occlusion.jpg: 打开https://raw.githubusercontent.com/cyberbotics/webots/R2022a/projects/objects/buildings/protos/textures/small_manor_frame_occlusion.jpg发生错误
WARNING: SmallManor (PROTO) > Shape > PBRAppearance > ImageTexture: Cannot download https://raw.githubusercontent.com/cyberbotics/webots/R2022a/projects/objects/buildings/protos/textures/small_manor_windows_base_color.jpg: 打开https://raw.githubusercontent.com/cyberbotics/webots/R2022a/projects/objects/buildings/protos/textures/small_manor_windows_base_color.jpg发生错误
WARNING: SmallManor (PROTO) > Shape > PBRAppearance > ImageTexture: Cannot download https://raw.githubusercontent.com/cyberbotics/webots/R2022a/projects/objects/buildings/protos/textures/small_manor_windows_roughness.jpg: 打开https://raw.githubusercontent.com/cyberbotics/webots/R2022a/projects/objects/buildings/protos/textures/small_manor_windows_roughness.jpg发生错误
WARNING: SmallManor (PROTO) > Shape > PBRAppearance > ImageTexture: Cannot download https://raw.githubusercontent.com/cyberbotics/webots/R2022a/projects/objects/buildings/protos/textures/small_manor_windows_metalness.jpg: 打开https://raw.githubusercontent.com/cyberbotics/webots/R2022a/projects/objects/buildings/protos/textures/small_manor_windows_metalness.jpg发生错误
WARNING: SmallManor (PROTO) > Shape > PBRAppearance > ImageTexture: Cannot download https://raw.githubusercontent.com/cyberbotics/webots/R2022a/projects/objects/buildings/protos/textures/small_manor_windows_normal.jpg: 打开https://raw.githubusercontent.com/cyberbotics/webots/R2022a/projects/objects/buildings/protos/textures/small_manor_windows_normal.jpg发生错误
WARNING: SmallManor (PROTO) > Shape > PBRAppearance > ImageTexture: Cannot download https://raw.githubusercontent.com/cyberbotics/webots/R2022a/projects/objects/buildings/protos/textures/small_manor_windows_occlusion.jpg: 打开https://raw.githubusercontent.com/cyberbotics/webots/R2022a/projects/objects/buildings/protos/textures/small_manor_windows_occlusion.jpg发生错误
WARNING: SquareManhole (PROTO) > Transform > Shape > PBRAppearance > ImageTexture: Cannot download https://raw.githubusercontent.com/cyberbotics/webots/R2022a/projects/objects/factory/manhole/protos/textures/manhole_base_color.jpg: 打开https://raw.githubusercontent.com/cyberbotics/webots/R2022a/projects/objects/factory/manhole/protos/textures/manhole_base_color.jpg发生错误
WARNING: SquareManhole (PROTO) > Transform > Shape > PBRAppearance > ImageTexture: Cannot download https://raw.githubusercontent.com/cyberbotics/webots/R2022a/projects/objects/factory/manhole/protos/textures/manhole_roughness.jpg: 打开https://raw.githubusercontent.com/cyberbotics/webots/R2022a/projects/objects/factory/manhole/protos/textures/manhole_roughness.jpg发生错误
WARNING: SquareManhole (PROTO) > Transform > Shape > PBRAppearance > ImageTexture: Cannot download https://raw.githubusercontent.com/cyberbotics/webots/R2022a/projects/objects/factory/manhole/protos/textures/manhole_metalness.jpg: 打开https://raw.githubusercontent.com/cyberbotics/webots/R2022a/projects/objects/factory/manhole/protos/textures/manhole_metalness.jpg发生错误
WARNING: SquareManhole (PROTO) > Transform > Shape > PBRAppearance > ImageTexture: Cannot download https://raw.githubusercontent.com/cyberbotics/webots/R2022a/projects/objects/factory/manhole/protos/textures/manhole_normal.jpg: 打开https://raw.githubusercontent.com/cyberbotics/webots/R2022a/projects/objects/factory/manhole/protos/textures/manhole_normal.jpg发生错误
WARNING: SquareManhole (PROTO) > Transform > Shape > PBRAppearance > ImageTexture: Cannot download https://raw.githubusercontent.com/cyberbotics/webots/R2022a/projects/objects/factory/manhole/protos/textures/manhole_occlusion.jpg: 打开https://raw.githubusercontent.com/cyberbotics/webots/R2022a/projects/objects/factory/manhole/protos/textures/manhole_occlusion.jpg发生错误
WARNING: CardboardBox (PROTO) > Transform > Shape > PBRAppearance > ImageTexture: Cannot download https://raw.githubusercontent.com/cyberbotics/webots/R2022a/projects/objects/factory/containers/protos/textures/cardboard_box_base_color.jpg: 打开https://raw.githubusercontent.com/cyberbotics/webots/R2022a/projects/objects/factory/containers/protos/textures/cardboard_box_base_color.jpg发生错误
WARNING: CardboardBox (PROTO) > Transform > Shape > PBRAppearance > ImageTexture: Cannot download https://raw.githubusercontent.com/cyberbotics/webots/R2022a/projects/objects/factory/containers/protos/textures/cardboard_box_roughness.jpg: 打开https://raw.githubusercontent.com/cyberbotics/webots/R2022a/projects/objects/factory/containers/protos/textures/cardboard_box_roughness.jpg发生错误
WARNING: CardboardBox (PROTO) > Transform > Shape > PBRAppearance > ImageTexture: Cannot download https://raw.githubusercontent.com/cyberbotics/webots/R2022a/projects/objects/factory/containers/protos/textures/cardboard_box_normal.jpg: 打开https://raw.githubusercontent.com/cyberbotics/webots/R2022a/projects/objects/factory/containers/protos/textures/cardboard_box_normal.jpg发生错误
WARNING: CardboardBox (PROTO) > Transform > Shape > PBRAppearance > ImageTexture: Cannot download https://raw.githubusercontent.com/cyberbotics/webots/R2022a/projects/objects/factory/containers/protos/textures/cardboard_box_occlusion.jpg: 打开https://raw.githubusercontent.com/cyberbotics/webots/R2022a/projects/objects/factory/containers/protos/textures/cardboard_box_occlusion.jpg发生错误
WARNING: TeslaModel3Simple (PROTO) > DEF FRONT_RIGHT_WHEEL Slot > TeslaModel3Wheel (PROTO) > Solid > DEF WHEEL_SHAPE Shape > PBRAppearance > ImageTexture: Cannot download https://raw.githubusercontent.com/cyberbotics/webots/R2022a/projects/vehicles/protos/tesla/textures/tesla_model3_wheels_base_color.png: 打开https://raw.githubusercontent.com/cyberbotics/webots/R2022a/projects/vehicles/protos/tesla/textures/tesla_model3_wheels_base_color.png发生错误
WARNING: TeslaModel3Simple (PROTO) > DEF FRONT_RIGHT_WHEEL Slot > TeslaModel3Wheel (PROTO) > Solid > DEF WHEEL_SHAPE Shape > PBRAppearance > ImageTexture: Cannot download https://raw.githubusercontent.com/cyberbotics/webots/R2022a/projects/vehicles/protos/tesla/textures/tesla_model3_wheels_roughness.jpg: 打开https://raw.githubusercontent.com/cyberbotics/webots/R2022a/projects/vehicles/protos/tesla/textures/tesla_model3_wheels_roughness.jpg发生错误
WARNING: TeslaModel3Simple (PROTO) > DEF FRONT_RIGHT_WHEEL Slot > TeslaModel3Wheel (PROTO) > Solid > DEF WHEEL_SHAPE Shape > PBRAppearance > ImageTexture: Cannot download https://raw.githubusercontent.com/cyberbotics/webots/R2022a/projects/vehicles/protos/tesla/textures/tesla_model3_wheels_metallic.png: 打开https://raw.githubusercontent.com/cyberbotics/webots/R2022a/projects/vehicles/protos/tesla/textures/tesla_model3_wheels_metallic.png发生错误
WARNING: TeslaModel3Simple (PROTO) > DEF FRONT_RIGHT_WHEEL Slot > TeslaModel3Wheel (PROTO) > Solid > DEF WHEEL_SHAPE Shape > PBRAppearance > ImageTexture: Cannot download https://raw.githubusercontent.com/cyberbotics/webots/R2022a/projects/vehicles/protos/tesla/textures/tesla_model3_wheels_normal.jpg: 打开https://raw.githubusercontent.com/cyberbotics/webots/R2022a/projects/vehicles/protos/tesla/textures/tesla_model3_wheels_normal.jpg发生错误
WARNING: TeslaModel3Simple (PROTO) > DEF FRONT_RIGHT_WHEEL Slot > TeslaModel3Wheel (PROTO) > Solid > DEF WHEEL_SHAPE Shape > PBRAppearance > ImageTexture: Cannot download https://raw.githubusercontent.com/cyberbotics/webots/R2022a/projects/vehicles/protos/tesla/textures/tesla_model3_wheels_occlusion.jpg: 打开https://raw.githubusercontent.com/cyberbotics/webots/R2022a/projects/vehicles/protos/tesla/textures/tesla_model3_wheels_occlusion.jpg发生错误
WARNING: TeslaModel3Simple (PROTO) > Transform > TeslaModel3Coachwork (PROTO) > PBRAppearance > ImageTexture: Cannot download https://raw.githubusercontent.com/cyberbotics/webots/R2022a/projects/vehicles/protos/tesla/textures/tesla_model3_bodywork_base_color.png: 打开https://raw.githubusercontent.com/cyberbotics/webots/R2022a/projects/vehicles/protos/tesla/textures/tesla_model3_bodywork_base_color.png发生错误
WARNING: TeslaModel3Simple (PROTO) > Transform > TeslaModel3Coachwork (PROTO) > PBRAppearance > ImageTexture: Cannot download https://raw.githubusercontent.com/cyberbotics/webots/R2022a/projects/vehicles/protos/tesla/textures/tesla_model3_bodywork_roughness.jpg: 打开https://raw.githubusercontent.com/cyberbotics/webots/R2022a/projects/vehicles/protos/tesla/textures/tesla_model3_bodywork_roughness.jpg发生错误
WARNING: TeslaModel3Simple (PROTO) > Transform > TeslaModel3Coachwork (PROTO) > PBRAppearance > ImageTexture: Cannot download https://raw.githubusercontent.com/cyberbotics/webots/R2022a/projects/vehicles/protos/tesla/textures/tesla_model3_bodywork_metallic.jpg: 打开https://raw.githubusercontent.com/cyberbotics/webots/R2022a/projects/vehicles/protos/tesla/textures/tesla_model3_bodywork_metallic.jpg发生错误
WARNING: TeslaModel3Simple (PROTO) > Transform > TeslaModel3Coachwork (PROTO) > PBRAppearance > ImageTexture: Cannot download https://raw.githubusercontent.com/cyberbotics/webots/R2022a/projects/vehicles/protos/tesla/textures/tesla_model3_bodywork_normal.jpg: 打开https://raw.githubusercontent.com/cyberbotics/webots/R2022a/projects/vehicles/protos/tesla/textures/tesla_model3_bodywork_normal.jpg发生错误
WARNING: TeslaModel3Simple (PROTO) > Transform > TeslaModel3Coachwork (PROTO) > PBRAppearance > ImageTexture: Cannot download https://raw.githubusercontent.com/cyberbotics/webots/R2022a/projects/vehicles/protos/tesla/textures/tesla_model3_bodywork_occlusion.jpg: 打开https://raw.githubusercontent.com/cyberbotics/webots/R2022a/projects/vehicles/protos/tesla/textures/tesla_model3_bodywork_occlusion.jpg发生错误
WARNING: TeslaModel3Simple (PROTO) > Transform > TeslaModel3Windows (PROTO) > PBRAppearance > ImageTexture: Cannot download https://raw.githubusercontent.com/cyberbotics/webots/R2022a/projects/vehicles/protos/tesla/textures/tesla_model3_glass_normal.jpg: 打开https://raw.githubusercontent.com/cyberbotics/webots/R2022a/projects/vehicles/protos/tesla/textures/tesla_model3_glass_normal.jpg发生错误
WARNING: TeslaModel3Simple (PROTO) > Transform > TeslaModel3Windows (PROTO) > PBRAppearance > ImageTexture: Cannot download https://raw.githubusercontent.com/cyberbotics/webots/R2022a/projects/vehicles/protos/tesla/textures/tesla_model3_glass_occlusion.jpg: 打开https://raw.githubusercontent.com/cyberbotics/webots/R2022a/projects/vehicles/protos/tesla/textures/tesla_model3_glass_occlusion.jpg发生错误
WARNING: TeslaModel3Simple (PROTO) > Transform > TeslaModel3Details (PROTO) > PBRAppearance > ImageTexture: Cannot download https://raw.githubusercontent.com/cyberbotics/webots/R2022a/projects/vehicles/protos/tesla/textures/tesla_model3_details_base_color.jpg: 打开https://raw.githubusercontent.com/cyberbotics/webots/R2022a/projects/vehicles/protos/tesla/textures/tesla_model3_details_base_color.jpg发生错误
WARNING: TeslaModel3Simple (PROTO) > Transform > TeslaModel3Details (PROTO) > PBRAppearance > ImageTexture: Cannot download https://raw.githubusercontent.com/cyberbotics/webots/R2022a/projects/vehicles/protos/tesla/textures/tesla_model3_details_roughness.png: 打开https://raw.githubusercontent.com/cyberbotics/webots/R2022a/projects/vehicles/protos/tesla/textures/tesla_model3_details_roughness.png发生错误
WARNING: TeslaModel3Simple (PROTO) > Transform > TeslaModel3Details (PROTO) > PBRAppearance > ImageTexture: Cannot download https://raw.githubusercontent.com/cyberbotics/webots/R2022a/projects/vehicles/protos/tesla/textures/tesla_model3_details_metallic.jpg: 打开https://raw.githubusercontent.com/cyberbotics/webots/R2022a/projects/vehicles/protos/tesla/textures/tesla_model3_details_metallic.jpg发生错误
WARNING: TeslaModel3Simple (PROTO) > Transform > TeslaModel3Details (PROTO) > PBRAppearance > ImageTexture: Cannot download https://raw.githubusercontent.com/cyberbotics/webots/R2022a/projects/vehicles/protos/tesla/textures/tesla_model3_details_normal.jpg: 打开https://raw.githubusercontent.com/cyberbotics/webots/R2022a/projects/vehicles/protos/tesla/textures/tesla_model3_details_normal.jpg发生错误
WARNING: TeslaModel3Simple (PROTO) > Transform > TeslaModel3Details (PROTO) > PBRAppearance > ImageTexture: Cannot download https://raw.githubusercontent.com/cyberbotics/webots/R2022a/projects/vehicles/protos/tesla/textures/tesla_model3_details_occlusion.jpg: 打开https://raw.githubusercontent.com/cyberbotics/webots/R2022a/projects/vehicles/protos/tesla/textures/tesla_model3_details_occlusion.jpg发生错误
WARNING: TeslaModel3Simple (PROTO) > Transform > DEF FRONT_PLATE Transform > DEF PLATES Shape > PBRAppearance > ImageTexture: Cannot download https://raw.githubusercontent.com/cyberbotics/webots/R2022a/projects/vehicles/protos/textures/plate.jpg: 打开https://raw.githubusercontent.com/cyberbotics/webots/R2022a/projects/vehicles/protos/textures/plate.jpg发生错误
WARNING: Pine (PROTO) > Shape > PBRAppearance > ImageTexture: Cannot download https://raw.githubusercontent.com/cyberbotics/webots/R2022a/projects/objects/trees/protos/textures/pine_leaves.png: 打开https://raw.githubusercontent.com/cyberbotics/webots/R2022a/projects/objects/trees/protos/textures/pine_leaves.png发生错误
WARNING: Pine (PROTO) > Shape > PBRAppearance > ImageTexture: Cannot download https://raw.githubusercontent.com/cyberbotics/webots/R2022a/projects/objects/trees/protos/textures/pine_leaves_normal.jpg: 打开https://raw.githubusercontent.com/cyberbotics/webots/R2022a/projects/objects/trees/protos/textures/pine_leaves_normal.jpg发生错误
WARNING: Pine (PROTO) > Shape > PBRAppearance > ImageTexture: Cannot download https://raw.githubusercontent.com/cyberbotics/webots/R2022a/projects/objects/trees/protos/textures/pine_trunk.jpg: 打开https://raw.githubusercontent.com/cyberbotics/webots/R2022a/projects/objects/trees/protos/textures/pine_trunk.jpg发生错误
WARNING: Forest (PROTO) > Shape > PBRAppearance > ImageTexture: Cannot download https://raw.githubusercontent.com/cyberbotics/webots/R2022a/projects/objects/trees/protos/textures/trees.png: 打开https://raw.githubusercontent.com/cyberbotics/webots/R2022a/projects/objects/trees/protos/textures/trees.png发生错误
WARNING: Forest (PROTO) > DEF GROUND Shape > PBRAppearance > ImageTexture: Cannot download https://raw.githubusercontent.com/cyberbotics/webots/R2022a/projects/objects/trees/protos/textures/dry_leaf.jpg: 打开https://raw.githubusercontent.com/cyberbotics/webots/R2022a/projects/objects/trees/protos/textures/dry_leaf.jpg发生错误
WARNING: Mavic2Pro (PROTO) > DEF REAR_LEFT_HP_HELIX Propeller > Solid > Shape > GlossyPaint (PROTO) > ImageTexture: Cannot download https://raw.githubusercontent.com/cyberbotics/webots/R2022a/projects/appearances/protos/textures/matte_car_paint/matte_car_paint_base_color.jpg: 打开https://raw.githubusercontent.com/cyberbotics/webots/R2022a/projects/appearances/protos/textures/matte_car_paint/matte_car_paint_base_color.jpg发生错误
WARNING: Mavic2Pro (PROTO) > DEF REAR_LEFT_HP_HELIX Propeller > Solid > Shape > GlossyPaint (PROTO) > ImageTexture: Cannot download https://raw.githubusercontent.com/cyberbotics/webots/R2022a/projects/appearances/protos/textures/glossy_car_paint/glossy_car_paint_roughness.jpg: 打开https://raw.githubusercontent.com/cyberbotics/webots/R2022a/projects/appearances/protos/textures/glossy_car_paint/glossy_car_paint_roughness.jpg发生错误
WARNING: Mavic2Pro (PROTO) > DEF REAR_LEFT_HP_HELIX Propeller > Solid > Shape > GlossyPaint (PROTO) > ImageTexture: Cannot download https://raw.githubusercontent.com/cyberbotics/webots/R2022a/projects/appearances/protos/textures/glossy_car_paint/glossy_car_paint_normal.jpg: 打开https://raw.githubusercontent.com/cyberbotics/webots/R2022a/projects/appearances/protos/textures/glossy_car_paint/glossy_car_paint_normal.jpg发生错误
WARNING: Mavic2Pro (PROTO) > DEF REAR_LEFT_HP_HELIX Propeller > Solid > Transform > Shape > PBRAppearance > ImageTexture: Cannot download https://raw.githubusercontent.com/cyberbotics/webots/R2022a/projects/robots/dji/mavic/protos/textures/mavic_fast_helix.png: 打开https://raw.githubusercontent.com/cyberbotics/webots/R2022a/projects/robots/dji/mavic/protos/textures/mavic_fast_helix.png发生错误
WARNING: Mavic2Pro (PROTO) > DEF REAR_RIGHT_HP_HELIX Propeller > Solid > Shape > MattePaint (PROTO) > ImageTexture: Cannot download https://raw.githubusercontent.com/cyberbotics/webots/R2022a/projects/appearances/protos/textures/matte_car_paint/matte_car_paint_roughness.jpg: 打开https://raw.githubusercontent.com/cyberbotics/webots/R2022a/projects/appearances/protos/textures/matte_car_paint/matte_car_paint_roughness.jpg发生错误
WARNING: TexturedBackground (PROTO): Cannot retrieve 'https://raw.githubusercontent.com/cyberbotics/webots/R2022a/projects/default/worlds/textures/cubic/mountains_back.png': Cannot download https://raw.githubusercontent.com/cyberbotics/webots/R2022a/projects/default/worlds/textures/cubic/mountains_back.png: 打开https://raw.githubusercontent.com/cyberbotics/webots/R2022a/projects/default/worlds/textures/cubic/mountains_back.png发生错误
WARNING: TexturedBackground (PROTO): Cannot download leftIrradianceUrl: Cannot download https://raw.githubusercontent.com/cyberbotics/webots/R2022a/projects/default/worlds/textures/cubic/mountains_back.hdr: 打开https://raw.githubusercontent.com/cyberbotics/webots/R2022a/projects/default/worlds/textures/cubic/mountains_back.hdr发生错误

**Comment by ShuffleWire** [comment]
Maybe this could help you ? https://github.com/cyberbotics/webots/issues/3574

PS: "Hello", "Please" and a useful description might be appreciated next time ;)

**Comment by stefaniapedrazzi** [comment]
I will close this issue.
If it should occur again, please first check the URLs are not blocked by your network.
If it is not the case, then reopen the issue and provide a useful description of the issue with additional details.

**Comment by omichel** [comment]
This problem and solution are described [here](https://answers.ros.org/question/403290/warning-texturedbackground-proto-cannot-download/)
