### ISSUE TITLE
Redesign Robot window and controller specification

### ISSUE THREAD

**Issue by omichel** [cyberbotics/webots#4429]
Since we want to be able to specify that a robot has no robot window, we should change the specification of the robot `window` in the `Robot` node. To make it more consistent with other parameters, we should also change the `controller` field, as follows:

`Robot.controller "void"` &rarr; `"<generic>"` (default value: run the legacy "void" controller, to be renamed to "generic") 
`Robot.controller ""` &rarr; `"<none>"` (run no controller)
`Robot.controller "<extern>"` &rarr; unchanged (run an extern controller)

`Robot.window ""` &rarr; `"<generic>"` (default value: use the generic robot window)
`Robot.window "<none>"` (no robot window)

`Robot.remote_control ""` &rarr; `"<none>"` (default value: no remote control library)

For consistency reasons we should also change the `WorldInfo` node:

`WorldInfo.physics ""` &rarr; `"<none>"` (default value: no physics plugin).

`WorldInfo.window ""` &rarr; `"<none>"` (default value: no world info window).

**Comment by ThomasOliverKimble** [comment]
This has been addressed in PR #4501.
