### ISSUE TITLE
install webots in openSuse leaps and xcb error

### ISSUE THREAD

**Issue by unloadble** [cyberbotics/webots#4440]
### Discussed in https://github.com/cyberbotics/webots/discussions/4433

<div type='discussions-op-text'>

<sup>Originally posted by **unloadble** April  6, 2022</sup>
Hi guys
I've installed webots from snap store in suse 
but after i run them i encountered these errors

> 
> Invalid MIT-MAGIC-COOKIE-1 keyWarning: could not connect to display :0
> Info: Could not load the Qt platform plugin "xcb" in "/snap/webots/20/usr/share/webots/lib/webots/qt/plugin
> s" even though it was found.
> Fatal: This application failed to start because no Qt platform plugin could be initialized. Reinstalling th
> e application may fix this problem.
> 
> Available platform plugins are: xcb.
> 
> /snap/webots/20/usr/share/webots/webots: line 90: 3776 Aborted (core dumped) "$webots_home
> /bin/webots-bin" "$@"

how can i fix it ? </div>

**Comment by BenjaminDeleze** [comment]
I'm closing this for now, feel free to reopen it if you have additional issues.
