### ISSUE TITLE
Bug during sharing to webots.cloud

### ISSUE THREAD

**Issue by ThomasOliverKimble** [cyberbotics/webots#4442]
**Describe the Bug**
Uploading to webots.cloud from webots not working

**Steps to Reproduce**
1. Open Webots (built from develop branch)
2. Click in the share button
3. Click on either `Upload your scene` or `Record and upload animation` and we get the following error message: 
![errorMsg](https://user-images.githubusercontent.com/100125668/162229075-e3929f94-64b8-4fcd-a4f0-01b0c4f751c9.png)

**Expected behavior**
The scene or animation should be uploaded to webots.cloud

**System**
 - Operating System: Linux Ubuntu 20.04
 - Graphics Card: NVIDIA GeForce GTX 1060 6GB

**Comment by omichel** [comment]
@ThomasOliverKimble: Did you fix it in https://github.com/cyberbotics/webots-cloud/pull/7? If so, can we close this issue?

**Comment by ThomasOliverKimble** [comment]
> @ThomasOliverKimble: Did you fix it in [cyberbotics/webots-cloud#7](https://github.com/cyberbotics/webots-cloud/pull/7)? If so, can we close this issue?

Still not working, I will look into this today.

**Comment by ThomasOliverKimble** [comment]
Yes, was fixed with #4544.
