### ISSUE TITLE
Web component broken in develop

### ISSUE THREAD

**Issue by ad-daniel** [cyberbotics/webots#4483]
**Describe the Bug**
As emerged here https://github.com/cyberbotics/webots/pull/4192#pullrequestreview-887300963, for the Scara robot (among others) the web component doesn't appear to be placing the sphere denoting the joint anchor at the correct spot, hence it ends up looking as if the point of rotation is incorrect. 

Since then, it seems that other issues have emerged:

develop branch:
- some textures no longer show, for instance: https://cyberbotics.com/doc/guide/bb8?version=develop
- boundingObjects and joint representation no longer showing https://cyberbotics.com/doc/guide/scara-epson-t6?version=develop

released branch, on firefox:
- for example: https://cyberbotics.com/doc/guide/khepera4
`Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://googleads.g.doubleclick.net/pagead/id. (Reason: CORS request did not succeed). Status code: (null).`
or sometimes:
`Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://play.google.com/log?format=json&hasfast=true&authuser=0. (Reason: CORS request did not succeed). Status code: (null).`

**Comment by BenjaminDeleze** [comment]
> * some textures no longer show, for instance: https://cyberbotics.com/doc/guide/bb8?version=develop
> * boundingObjects and joint representation no longer showing https://cyberbotics.com/doc/guide/scara-epson-t6?version=develop

This is certainly, at least for the bounding objects, because the `.x3d` were not regenerated since the last changes in WebotsJS
I will handle that.

> * for example: https://cyberbotics.com/doc/guide/khepera4

I did not manage to get an error (either Firefox or Chrome)

**Comment by ad-daniel** [comment]
> I did not manage to get an error (either Firefox or Chrome)

We've looked into it yesterday and it doesn't appear to be related to the web component but rather to the google search bar at the very bottom of some pages, which I (we) didn't even know existed
