### ISSUE TITLE
Webots cannot start simulation when using Matlab 2017b

### ISSUE THREAD

**Issue by sxbug** [cyberbotics/webots#4494]
**Describe the Bug**
Webots cannot start simulation when using Matlab , can not execute: loadlibrary(libname,protofile,'alias','libController'); in launcher.m . 
Previous versions did not have this problem. If  change the E-puck controller to < extern >, then start MATLAB and open launcher.m. Click run  to simulate , it is OK.
I think whether there is a problem with the compatibility of MATLAB 2017b?

**Steps to Reproduce**
1. Open e-puck_matlab.wbt
2. Click on 'run to simulation'
3. matlab open and halt(matlab is black)
4. no any error msg

**Expected behavior**
Matlab can only be shut down by force.

**System**
 - webots 2022b nightly build 
-matlab 2017b 64bit
-win 10  64bit

**Comment by omichel** [comment]
Does it work with Webots R2022a?

**Comment by BenjaminDeleze** [comment]
I'm closing this for now, feel free to reopen it if you have additional issues.
