### ISSUE TITLE
failure to download texture

### ISSUE THREAD

**Issue by xlla** [cyberbotics/webots#4528]
**Describe the Bug**
While follow the instruction on wiki Tutorial-Create-Webots-Robot, after choose TextureBackground, it is failure to download resource.
<pre>
WARNING: TexturedBackground (PROTO): Cannot retrieve 'https://raw.githubusercontent.com/cyberbotics/webots/R2022a/projects/default/worlds/textures/cubic/mountains_back.png': Cannot download https://raw.githubusercontent.com/cyberbotics/webots/R2022a/projects/default/worlds/textures/cubic/mountains_back.png: Error opening https://raw.githubusercontent.com/cyberbotics/webots/R2022a/projects/default/worlds/textures/cubic/mountains_back.png
</pre>

I notice there is a commit #4182 says the png was replaced by jpg, so how to amend it? 

**Steps to Reproduce**
1. just following wiki Tutorial-Create-Webots-Robot

**Expected behavior**
A background texture being created.

**Screenshots**

**System**
 - Operating System: macOS High sierra
 - Graphics Card: [ NVIDIA GeForce GTX 1060 6 GB]

**Additional context**

**Comment by BarceloChristian** [comment]
I'll add some more information here.
The path to the texture shouldn't be broken because it points to the tag `R2022a` from Dec 2021. The problem is that right now, that tag is pointing to the branch `R2022a` which is in sync with master, instead of pointing to the commit used for that release.
![image](https://user-images.githubusercontent.com/21263985/167909648-d35be365-17d6-4ab6-abcf-c22e4dce798b.png)

**Comment by xlla** [comment]
Hi @BarceloChristian ,  I have checked the code in R2022a branch , it ought to use jpg resource.
[TexturedBackground.proto](https://github.com/cyberbotics/webots/blob/R2022a/projects/objects/backgrounds/protos/TexturedBackground.proto)

but my installed app of the Webots R2022a just request png resource.

I have checked the version , it shows
<pre>
slim:Webots.app xlla$ cat /Applications/Webots.app/resources/version.txt 
R2022a
</pre>

**Comment by xlla** [comment]
I have to installed [Webots Nightly Build (10-5-2022)](https://github.com/cyberbotics/webots/releases/tag/nightly_10_5_2022), it works!

**Comment by BenjaminDeleze** [comment]
Thank you for the report.
It was indeed a conflict between the branch `R2022a` and the tag `R2022a`.
It has now been fixed.
