### ISSUE TITLE
Broken robot geometry and broken background texture in "summit_xl_steel.wbt" Sample World.

### ISSUE THREAD

**Issue by koteth** [cyberbotics/webots#4529]
**Describe the Bug**
Broken robot geometry and broken background texture in "summit_xl_steel.wbt" Sample World. 
Webots R2022A

**Steps to Reproduce**
Open Sample World...
Select: summit_xl_steel.wbt

**Screenshots**
![summit_xl_steel_1](https://user-images.githubusercontent.com/3996021/167942663-7d80dbe8-a1bf-4c2d-b3d7-53c38945f2e0.png)

**System**
 - Operating System: [Windows 10, Linux Ubuntu 20.04]
 - Graphics Card: [NVIDIA GeForce MX 150]

**Comment by ad-daniel** [comment]
Hi, the issue with the background was temporary and should be gone now and concerning the summit it was indeed broken, and the patch is included in the latest nightly build: https://github.com/cyberbotics/webots/releases/
