### ISSUE TITLE
Fix QT6 plugins location in Windows package

### ISSUE THREAD

**Issue by stefaniapedrazzi** [cyberbotics/webots#4574]
The Windows package doesn't run (at least on my local system) because the Qt `platforms` and `tls` plugins are not found.
Previously with Qt5 there was a patch in `scripts/packaging/copy_msys64_files.py` but it was removed in #4189.

The patch still works fine and the plugins are found.
However, there are additional issues with assets that are not downloaded correctly but no errors and warnings are printed in the console.

**Comment by omichel** [comment]
I cannot reproduce this problem on my Windows 10 machine...

**Comment by omichel** [comment]
Interesting post: https://forum.qt.io/topic/110914/qt-5-14-0-plugins-path/4

**Comment by stefaniapedrazzi** [comment]
I tested again the latest nightly build on a different account on the same Windows machine and it seems that everything works fine this time.
Maybe I still had some environmental variables set that where pointing to the wrong folders.
