### ISSUE TITLE
Suggestions to improve UI for exporting animations and scenes locally

### ISSUE THREAD

**Issue by stefaniapedrazzi** [cyberbotics/webots#4602]
In the develop branch, it is very difficult to find how to save a scene or animation locally.
It is OK to try to promote as much as possible the upload on webots.cloud.
But at the moment it is not at all self-explanatory what will be done when pressing the "upload" buttons when the "Save as local files" option is checked.

I think that we could apply some minor improvements to make it more user friendly.

Here are some suggestions for discussion:
1. I think that if the naming the menu item simply "Share" instead of "Share on webots.cloud" would be less confusing in case a user wants to save locally only. Otherwise she might never open the dialog to search for the option.
2. Similarly, I personally would change the dialog title from "Share your simulation online" to "Share your simulation"
3. The word "upload" in the button text is misleading when the "save as local files" option is checked.
   What about using radio buttons and change, something like the one in the picture?
    ![Screenshot from 2022-06-07 10-48-12](https://user-images.githubusercontent.com/5910449/172338192-1683a843-6171-4abb-abf7-dbd6cbae51f0.png)
4. Otherwise if we should decide to keep the save as local file as an exceptional behavior enabled by a checkbox, I think we should at least change the label from "Save as local files" to "Save as local files only"

----
Additionally, the documentation has not been updated accordingly to the changes to the UI and still refers to the old menu items.
These are at least three pages that should be updated:
* https://www.cyberbotics.com/doc/guide/web-scene?version=develop#how-to-export-a-web-scene
* https://www.cyberbotics.com/doc/guide/web-animation?version=develop#how-to-export-a-web-animation
* https://www.cyberbotics.com/doc/guide/the-user-interface?version=develop#file-menu

**Comment by BenjaminDeleze** [comment]
I will implement these changes
