### ISSUE TITLE
Warning: Cannot allocate memory mapped file for camera image. 

### ISSUE THREAD

**Issue by BenjaminDeleze** [cyberbotics/webots#4607]
**Describe the Bug**

**Steps to Reproduce**
1. Go on `develop`
2. Open `nao_demo.wbt` in pause mode
3. Open the preferences
4. Click `OK`
5. Warnings appears in the Webots terminal.
```
WARNING: Nao (PROTO) > DEF HeadYaw Hinge2Joint > Solid > Camera: Cannot allocate memory mapped file for camera image
WARNING: Nao (PROTO) > DEF HeadYaw Hinge2Joint > Solid > Camera: Cannot allocate memory mapped file for camera image
```

Note that everything seems to work correctly after that

**Comment by omichel** [comment]
On windows, it crashes after displaying the warnings... 😒
