### ISSUE TITLE
CI test suite failure due to robot window test

### ISSUE THREAD

**Issue by stefaniapedrazzi** [cyberbotics/webots#4632]
Very often the CI test suite on Linux is failing due to errors when running the robot window test:
 ```
FAILURE with /home/runner/work/webots/webots/tests/api/worlds/robot_window_html.wbt: Timeout the results file has not been written quickly enough
```

**Comment by omichel** [comment]
I am closing the issue for now. Feel free to re-open if the failure strikes back.
