### ISSUE TITLE
Emitter-receiver sample is broken

### ISSUE THREAD

**Issue by ad-daniel** [cyberbotics/webots#4655]
**Describe the Bug**

The sphere appears black, instead of being transparent:
![emitter_receiver](https://user-images.githubusercontent.com/44834743/173823566-e2bdb5ec-bfbe-4ab7-bd29-1eb8f4278b2a.png)

**Comment by ad-daniel** [comment]
The issue is with the transparency, changing it has no effect other if setting a value of 1, in which case it disappears

**Comment by omichel** [comment]
Changing the `Sphere.subdivsion` from 2 to 1 or to 3 fixes the problem...

**Comment by BenjaminDeleze** [comment]
It seems that it was broken here in #4457
