### ISSUE TITLE
Conflict between cyberbotics.com and webots-js CSS

### ISSUE THREAD

**Issue by ThomasOliverKimble** [cyberbotics/webots#4665]
Conflict between cyberbotics.com `CSS` and progress bar `CSS` causing bug in appearance (can be seen [here](https://cyberbotics.com/doc/guide/aibo-ers7?version=develop) for example):

![ProgressBarWebotsDoc](https://user-images.githubusercontent.com/100125668/174047572-20945f4d-bf71-4395-8b4e-65eb154892e2.png)

**Comment by BenjaminDeleze** [comment]
The main issue seems to come from the `text-align: justify;` property

**Comment by ThomasOliverKimble** [comment]
> The main issue seems to come from the `text-align: justify;` property

Indeed, however I found an easier solution by switching the `<p>` elements to `<div>`, I am finishing up this in #4666.

**Comment by BenjaminDeleze** [comment]
Fine, but what if on a user's website there is rule with `div { text-align: justify/left/right/...;}`, will it work?

**Comment by ThomasOliverKimble** [comment]
> Fine, but what if on a user's website there is rule with `div { text-align: justify/left/right/...;}`, will it work?

I just tested this by implementing this rule in the streaming viewer (in `style.css`) and it does not affect the progress bars properties. If they are a `div`, I believe the class name or id is enough to set new properties for the element. Let me know if you find anything different.
