### ISSUE TITLE
Improve Bitcraze Crazyflie

### ISSUE THREAD

**Issue by omichel** [cyberbotics/webots#4711]
Here are some ideas to improve the Bitcraze Crazyflie simulation:

- [ ] Implement the fastHelix / slowHelix as in the [Mavic2Pro model](https://github.com/cyberbotics/webots/blob/master/projects/robots/dji/mavic/protos/Mavic2Pro.proto) for a [better rendering the helices](https://www.youtube.com/watch?v=-hJssj_Vcw8).
- [ ] Add altitude control to the keyboard controller.
- [ ] Improve the world file with obstacles and a more real world appearance, it could for example implement a simple [apartment](https://cyberbotics.com/doc/guide/samples-environments#apartment-wbt).

**Update by @knmcguire** :
- [ ] Replace the simple PID controller by bindings from the actual firmware (so hybrid SITL), see https://github.com/bitcraze/crazyflie-firmware/issues/1067
- [ ] Add the wall following controller example like in this branch:  https://github.com/bitcraze/crazyflie-simulation/tree/wallfollowing2.
- [ ] Add expansion decks protos, just like the add-on decks of the crazyflie itself. 
- [ ] Add transformation to boundingbox so that the origin can be 0.0.0

**Comment by knmcguire** [comment]
Thanks! This is a nice list of to-dos. I've added some additional items that we are planning to do as well.

**Comment by Klark007** [comment]
Looking at the sensor list it seems that the accelerometer, which is part of the crazyflie's real sensors, is not in the Proto. This could also be added to the above list

**Comment by knmcguire** [comment]
Good point! Currently we haven't included that since it is mostly used for state estimate filter and that is currently replaced by the 'gps', 

So many things to fix... I'm hoping that I'll be able to do this before the 2023b release but not sure when that is planned

**Comment by omichel** [comment]
We plan to release Webots R2023b on June 1st 2023.

**Comment by ShuffleWire** [comment]
Could we close this issue, the PR being merged ?

**Comment by omichel** [comment]
Sure.

**Comment by knmcguire** [comment]
Hi! technically there were some more improvements in the pipeline, but the current state of the crazyflie is pretty stable at the moment. so I'm okay with closing this. At least all the improvements that @omichel had proposed initially are taken care off 😄
