### ISSUE TITLE
Broken PROTO Wizard on nightly snap package

### ISSUE THREAD

**Issue by ThomasOliverKimble** [cyberbotics/webots#4729]
**Describe the Bug**
Creating a new PROTO with the PROTO Wizard does not work and gives the error: "Some directories or files could not be created."

**Steps to Reproduce**
Install 20-06-2022 nightly .snap file, start webots, create new Proto via the Proto Wizard, configure, finish

**Webots Version**
Snap package nightly build 20-06-2022

**Comment by ygoumaz** [comment]
This is not only related to the snap. I can also reproduce it with the Debian package. In fact, I believe the problem comes up after a re-localization of the project.
