### ISSUE TITLE
Automobile robot window in highway_driving benchmark is broken on Linux

### ISSUE THREAD

**Issue by omichel** [cyberbotics/webots#4735]
On Linux, when opening the projects/samples/robotbenchmark/highway_driving/worlds/highway_driving.wbt example, if I click on the scene tree to select the vehicle and open the robot window I am getting this error:
WARNING: Cannot read '/home/olivier/webots/projects/samples/robotbenchmark/highway_driving/plugins/robot_windows/automobile/automobile.html', sending "404 Not Found".

**Comment by stefaniapedrazzi** [comment]
Related to #4719
