### ISSUE TITLE
SUMO interface not working on Windows

### ISSUE THREAD

**Issue by carikaser** [cyberbotics/webots#4759]
The SUMO interface is not working on Windows 11. No errors are printed, but the simulation does not start. However, if Webots is restarted, it works. I installed Webots locally (not for all users).

**Comment by omichel** [comment]
This may be due to a firewall issue. Does it work now every time you start Webots?

**Comment by carikaser** [comment]
It works when I launch Webots or restart it, but not if I open a world involving SUMO once Webots is already running. The simulation cannot be started.

**Comment by omichel** [comment]
I believe this problem was caused by the sumo controller crashing for other reasons and it wasn't closing sumo properly, thus on reload, sumo was unable to start again because it didn't quit yet or didn't quit properly. This issue seems now resolved as we fixed the sumo controller crash.

**Comment by carikaser** [comment]
Yes, it seems to work fine now. Thank you!
