### ISSUE TITLE
Controller not found after relocation

### ISSUE THREAD

**Issue by ad-daniel** [cyberbotics/webots#4772]
**Describe the Bug**

In the latest nightly (tar), relocating the `highway_driving` sample prints an additional warning concerning the controller. Since this warning was not present in this issue: https://github.com/cyberbotics/webots/issues/4726, I suspect the issue was recently added.

```
ERROR: JavaScript error: could not open file: /home/daniel/Downloads/highway_driving/worlds/forest/highway_overtake/1.forest.
WARNING: DEF WEBOTS_VEHICLE0 LincolnMKZ (PROTO): The 'automobile' robot window library has not been found.
WARNING: DEF WEBOTS_VEHICLE0 LincolnMKZ (PROTO): The controller directory has not been found, searched the following locations:
/home/daniel/Downloads/highway_driving/controllers/highway_driving/
/home/daniel/Downloads/webots-R2022b-x86-64/webots/projects/vehicles/protos/lincoln/controllers/highway_driving/
/home/daniel/Downloads/webots-R2022b-x86-64/webots/projects/default/controllers/highway_driving/
/home/daniel/Downloads/webots-R2022b-x86-64/webots/resources/projects/controllers/highway_driving/
```

**Comment by omichel** [comment]
There is also a problem regarding the robot window:
```
WARNING: DEF WEBOTS_VEHICLE0 LincolnMKZ (PROTO): The 'automobile' robot window library has not been found.
```
Once a project is relocated, there is no way to find the robot window any more unless the plugin folder was copied as well. In which case, this warning don't show up and the robot window actually works.

To resolve this problem, I suggest that the relocation dialog will always copy the plugins files. Thus we should remove the checkbox about including the plugins files and perform this copy in any case.
