### ISSUE TITLE
Web Component script should reference meshes locally

### ISSUE THREAD

**Issue by ad-daniel** [cyberbotics/webots#4783]
**Describe the Bug**

As emerged in https://github.com/cyberbotics/webots/pull/4780, the web component script copies all the meshes and relatively references to them. Instead the meshes could be referenced using a `webots://` url to avoid duplication.

**Comment by BenjaminDeleze** [comment]
The problem comes from the fact that the `Crazyflie.proto` references its meshes with urls of the type: `meshes/*.dae`, if the urls where `webots://....../meshes/*.dae` as the other protos, it would solve the problem
