### ISSUE TITLE
Text of EPHERMAL PROTO not really readable

### ISSUE THREAD

**Issue by BenjaminDeleze** [cyberbotics/webots#4823]
As you can see on the picture, the description text before the `Insert new` button is cropped and the no slider is visible (even so we can scroll the text).

I have the same problem in both night and classic theme
![display_bug](https://user-images.githubusercontent.com/25938827/177123312-75c3cfac-ecea-4a2f-aa41-545531a32d7d.png)

**Comment by BenjaminDeleze** [comment]
The problem has been introduced in #4701 

Before:
![before](https://user-images.githubusercontent.com/25938827/177135258-a629e209-2d6d-4137-851b-392ade0c8b42.png)

After:
![after](https://user-images.githubusercontent.com/25938827/177135280-c3a20ed3-58ab-4d05-b66f-dc50a8da4420.png)

I can either try to restore the original look specifically for this text only or put the `Insert new` button lower to let the room to display the fulltext.

What do you think?

**Comment by ad-daniel** [comment]
I think it might also depend on how this https://github.com/cyberbotics/webots/pull/4826 is addressed, based on the available space and what not
