### ISSUE TITLE
The PBR appearance textures are duplicated many times in the documentation

### ISSUE THREAD

**Issue by omichel** [cyberbotics/webots#488]
Because robot models are using more and more the new PBR textures, the corresponding texture images (JPG) get copied many times in the documentation because they are used by the robot web component. Instead of duplicating these textures, we should refer to the original ones to avoid a huge redundancy in our repository.

**Comment by fabienrohrer** [comment]
I'm not sure to understand what PBR appearance images are. Do you speak about the textures of the robot component?

**Comment by omichel** [comment]
Yes.

**Comment by fabienrohrer** [comment]
The situation is still quite tolerable (only few textures are concerned) but it may indeed explode soon especially if we generalize the robot component to objects.

I can do this as I already implemented a similar mechanism to avoid the background textures to be duplicated:
https://github.com/omichel/webots/blob/develop/scripts/web_component_studio/controllers/web_component_studio_supervisor/web_component_studio_supervisor.py#L69
This has to be generalized.

**Comment by omichel** [comment]
#1638 should resolve this problem.

**Comment by BenjaminDeleze** [comment]
Will be fixed by #2787
