### ISSUE TITLE
EXTERNPROTO declaration is parsed even if added in comment

### ISSUE THREAD

**Issue by stefaniapedrazzi** [cyberbotics/webots#4952]
It seems that even if the EXTERNPROTO declaration is added in a comment, Webots parses and processes it.

Here is a sample world file:
```
#VRML_SIM R2022b utf8
# EXTERNPROTO "../protos/Ball.proto"

EXTERNPROTO "https://raw.githubusercontent.com/cyberbotics/webots/R2022b/projects/objects/floors/protos/RectangleArena.proto"

WorldInfo {
}
Viewpoint {
}
RectangleArena {
}
```

Error in the console:
```
ERROR: '/home/stefi/Desktop/test_project1/worlds/test2.wbt': Failed to load due to invalid token(s).
```

**Comment by ygoumaz** [comment]
I have investigated the problem and it seems that the EXTERNPROTOs in comments are not processed, which is correct. The error comes from the fact that there is a comment directly after the first line `#VRML_SIM R2022b utf8` without any space. I believe a space is required here for the header to be valid and the PROTO to be parsed correctly.

**Comment by stefaniapedrazzi** [comment]
I will check again.
Because Webots was crashing even if I was commenting the EXTERNPROTO causing the issue.

**Comment by stefaniapedrazzi** [comment]
I confirm the issue is just the space.

However, even in this case Webots should throw an error and load the default world instead of the current behavior:
on the VM it freezes, on my development system it seems to partially load something but crashes as soon as I click on the step button.

**Comment by stefaniapedrazzi** [comment]
Additionally there is no reason why a new line is needed between the header and the comment.
Also note that this is valid in VRML.

**Comment by omichel** [comment]
I assume we can now close this issue.
