### ISSUE TITLE
e-puck robot window warning when enabling all devices

### ISSUE THREAD

**Issue by stefaniapedrazzi** [cyberbotics/webots#4963]
Sometimes I get this warning in the Webots console when enabling all the devices from the e-puck robot window:
```
WARNING: Unsupported file type '/~WEBOTS_HOME/projects/robots/gctronic/e-puck/plugins/robot_windows/e-puck/undefined'
```

Steps to reproduce:
1. open `apartment.wbt`
2. run the simulation
3. show the e-puck robot window
4. in the robot window click on the "Enable all" button

**Comment by omichel** [comment]
I can reproduce it on Windows as well.
