### ISSUE TITLE
Confusion between PROTOs that should be distinguished

### ISSUE THREAD

**Issue by ygoumaz** [cyberbotics/webots#4964]
If 2 PROTOs (1 local and 1 remote) have the same name, adding one of them to the list of IMPORTABLE EXTERNPROTOs will always spawn the remote one.

**Steps to Reproduce**
1. Create a new PROTO with the PROTO wizard from any object (e.g. Cabinet). Give it the same name as an official Webots PROTO, but different than the PROTO you have created it from (e.g. Nao).
2. Open the IMPORTABLE EXTERNPROTO list editor.
3. Click on `Insert new`.
4. Select the local PROTO you have created in "current project".
5. Spawn this PROTO with a supervisor.
6. The official Nao will be imported, instead of the Cabinet named Nao.

Moreover, after step 4, if the world is saved, the Nao is declared in the world file as IMPORTABLE EXTERNPROTO but with the remote URL and not the local one.

This behavior is probably 'normal' right now, as we don't allow/handle multiple PROTOs with same names. But #4953 raises a similar problem and PROTOs should be stored according to their URL instead of their names to allow such behavior.

**Comment by omichel** [comment]
Can we close this one, as it seems it was fixed in #4967?

**Comment by ad-daniel** [comment]
Indeed
