### ISSUE TITLE
Scaling issue in simulation UI R2022b

### ISSUE THREAD

**Issue by TheMangalex** [cyberbotics/webots#5024]
**Describe the Bug**
I hope this isn't a duplication, but I didn't find a fix or something related. It might also be an issue with 4k displays.
Since the update to R2022b, the simulation window fills only a quarter of the given screen space. 

The mouse movements and clicks are measured at the whole screen though, making it additionally hard to click on objects.

**Steps to Reproduce**
1. Installing webots from source origin/master (make -j8)
2. Launching with ./webots

**Expected behavior**
Normal screen scaling as seen in 2nd Screenshot

**Screenshots**
R2022b
![webots r2022b](https://user-images.githubusercontent.com/26520790/183404487-50facc06-d5f4-4c3f-9cad-6c4115794dab.png)

R2022a
![webots](https://user-images.githubusercontent.com/26520790/183403796-62094790-b2ca-4978-a705-d321c1c03988.png)

**System**
 - Operating System: Ubuntu 20.04
 - Graphics Card: Intel HD Graphics & Rtx 3070 (only tested on intel currently though)
 - Display Settings: 4k (3840x2160)
 - Window-Manager: i3

**Additional context**

**Comment by omichel** [comment]
That's is strange... Can you try to to set `export QT_USE_PHYSICAL_DPI=1` and run Webots again?
Alternatively, can you also try `export QT_SCALE_FACTOR=2`?
Also can you try to remove `QT_ENABLE_HIGHDPI_SCALING` from https://github.com/cyberbotics/webots/blob/master/src/webots/launcher/webots-linux.sh#L74?

Let me know your findings.

**Comment by TheMangalex** [comment]
Okay so the 1st and 3rd option didn't change anything, but the 2nd option looked like that
![option2](https://user-images.githubusercontent.com/26520790/183430693-f8580ede-b352-4325-abfd-d06ac9fd9345.png)
.
Also it seems like this bug doesn't happen in Gnome for me and only i3, but i3 was working correctly with R2022a. Maybe some variable is incorrectly provided by the X-Server?

**Comment by omichel** [comment]
Maybe [this one](https://github.com/cyberbotics/webots/commit/88e8b517af05661aa55d7e7e2209ba12e04bb894) broke it? Can you try to revert it?

**Comment by TheMangalex** [comment]
Sadly this doesn't seem to change it.

**Comment by TheMangalex** [comment]
Sadly nothing as well.

**Comment by omichel** [comment]
Unfortunately, I am running out of ideas... That's strange the bug doesn't show up with R2022a...
A big change we did between R2022a and R2022b is the [upgrade to Qt6](https://github.com/cyberbotics/webots/pull/4189).
To find the problem, we could revert back in the github history to some commit before the upgrade to Qt6 and rebuild Webots to try to identify if problem was introduced here...

**Comment by TheMangalex** [comment]
Thank you very much for your help. Maybe there is a general change in how qt6 handles scaling and that makes problems with my display config. I'll check it and if I find a solution, I'll post an update.

**Comment by TheMangalex** [comment]
Interestingly using a QT_SCALE_FACTOR of 0.5 fixes the screen scaling, although the rest of the ui is pretty small.
Is there a way to increase the ui size (other than with QT_SCALE_FACTOR)?
![Screenshot_20220809_100026](https://user-images.githubusercontent.com/26520790/183597302-7daf0569-b434-4c3f-ba34-4944b72fd036.png)

**Comment by omichel** [comment]
We are progressing... Did you check all the different environment variables documented here: https://doc.qt.io/qt-6/highdpi.html#environment-variable-reference?

**Comment by omichel** [comment]
Alternatively, you may want to try to change the font sizes in the styling sheet: https://github.com/cyberbotics/webots/blob/master/resources/stylesheet.linux.qss

**Comment by TheMangalex** [comment]
Explicitely disabling the QT_ENABLE_HIGHDPI_SCALING with QT_ENABLE_HIGHDPI_SCALING=0 makes the Ui small, but working. I somehow forgot to check disabling it yesterday and tried just not to enable it.
In combination with a SCALE_FACTOR of 2 and a FONT_DPI of 80 it looks good again.

Thank you very much for your help!
![Screenshot_20220809_101423](https://user-images.githubusercontent.com/26520790/183599477-af1e65f5-fc38-4981-b28b-91d33029c928.png)

**Comment by omichel** [comment]
Could we integrate this in https://github.com/cyberbotics/webots/blob/master/src/webots/launcher/webots-linux.sh?
If we can detect that we are in a high DPI i3wm environment, the launcher script could set these environment variables automatically?

**Comment by TheMangalex** [comment]
That sounds like a good option.
I used the parameters

export QT_ENABLE_HIGHDPI_SCALING=0
export QT_SCALE_FACTOR=2
export QT_FONT_DPI=80

to fix my scaling. The Environment variable  $XDG_CURRENT_DESKTOP returns i3 for me.
I might be able to adapt the script later today and test it.

**Comment by omichel** [comment]
That would be great.
