### ISSUE TITLE
Remove WBO

### ISSUE THREAD

**Issue by omichel** [cyberbotics/webots#5056]
The WBO file format was implemented in Webots a long time ago, when there was probably no PROTO support in Webots.
Now, it is obsolete in the sense that everything that could be done with WBO can be done with PROTOs in a much cleaner way.
So, it is not good to keep this WBO feature in Webots because:
1. It makes the code of Webots more complex: it requires that we test it, maintain it and document it regularly.
2. It is confusing, useless and misleading for the users.

So, I would suggest to remove it.

**Comment by BenjaminDeleze** [comment]
I tought about one use case:

- Imagine you are running a competition with several predefined configurations (think the disposition of the walls of a maze for example).
- You could have only one world, several `.wbo` that contains the different configurations and a supervisor that would load the chosen `.wbo`

However it should be possible to achieve the same result by having several `.txt` files, reading them with the supervisor and using the `importFromString` method.

Even so the solution with the text files is a little bit more complicated I do not think it is worth keeping the `wbo` format if it is the only use case.
