### ISSUE TITLE
Remote PROTO without icon throw download warning

### ISSUE THREAD

**Issue by ad-daniel** [cyberbotics/webots#5066]
**Describe the Bug**

Take this example of world, the PROTO is downloaded from a remote url outside our own. When selecting this PROTO in the add-node window, a warning is shown saying that the icon could not be downloaded (none exists in the repo). By printing the error message we're essentially forcing people to define an icon for their PROTO which isn't ideal. If it couldn't be downloaded we should either show nothing (as we do for local proto) or show a default one, without printing any warning.

```
#VRML_SIM R2022b utf8

EXTERNPROTO "https://raw.githubusercontent.com/cyberbotics/webots-cloud-simulation-examples/main/7_local_assets/protos/MyProto.proto"

WorldInfo {
}
Viewpoint {
  orientation -0.0316302248353415 0.02843866445440257 0.9990949760863156 1.6779495280745207
  position -0.05753688709726134 2.5600691798403346 9.999992923742619
}
Background {
  skyColor 0.5 0.5 0.8
}
MyProto {
}
```

EDIT: if the link of the EXTERNPROTO does not work, use: 
```
EXTERNPROTO "https://raw.githubusercontent.com/cyberbotics/webots-cloud-simulation-examples/test-protos-download/7_local_assets/protos/MyProto.proto"
```

**Comment by BenjaminDeleze** [comment]
<p>
<img src=https://user-images.githubusercontent.com/25938827/184111522-1bc96395-9b72-4fd9-80b2-2d6106dfd55b.png width=400px/>
<img src=https://user-images.githubusercontent.com/25938827/184111529-45bd9ddd-bb4a-407d-a681-3529085d7df9.png width=400px/>
<img src=https://user-images.githubusercontent.com/25938827/184111525-198916d0-6926-4fb1-8e55-ba1c73fe731a.png width=400px/>
<img src=https://user-images.githubusercontent.com/25938827/184111533-a0e2afbe-97ac-4624-9666-efc1211cac14.png width=400px/>
</p>

What do you think of those default icons?

**Comment by omichel** [comment]
I prefer the "Missing PROTO icon" (more similar to "Missing texture"), but I would capitalize "PROTO".

**Comment by BenjaminDeleze** [comment]
After some discussion we decided to go with the following version to match the `MISSING TEXTURE` image:
<p>
<img src=https://user-images.githubusercontent.com/25938827/184115452-e4c867ce-2735-4b44-bf6f-c4c00435b612.png width=400/>
<img src=https://user-images.githubusercontent.com/25938827/184115455-6dc929c3-83aa-4bd5-9e6e-08b3ebb209bb.png width=400/>
</p>
