### ISSUE TITLE
URL relative to an unsaved world

### ISSUE THREAD

**Issue by ad-daniel** [cyberbotics/webots#5072]
**Describe the Bug**

Based on the visibility and/or while streaming, some URL may be expressed or searched for relative to the world file. This however presupposes that the world itself has a known location. If a user creates a world, adds stuff but never actually saves, the behavior is incorrect.

**Comment by omichel** [comment]
That is an edge use case. Possible solutions include:
1. Enforcing a world to be saved before streaming.
2. Enforce saving the world when creating it.

I believe solution 2 is the best as it seems needed to know the location of the world as soon as we want to modify it and add some objects with textures, meshes, etc.

**Comment by omichel** [comment]
To achieve this, I suggest to simply remove the "File / New World" which seems to be redundant and inconsistent with the Wizard menu.

**Comment by BenjaminDeleze** [comment]
> To achieve this, I suggest to simply remove the "File / New World" which seems to be redundant and inconsistent with the Wizard menu.

I am not sure to agree as sometime you just want to add a world to an existing project
