### ISSUE TITLE
Test suite broken in debug mode

### ISSUE THREAD

**Issue by ad-daniel** [cyberbotics/webots#5086]
**Describe the Bug**

When running the test suite in debug mode, the following assert is triggered for the `radar_relative_speed.wbt` world:

```
webots-bin: nodes/utils/WbSupervisorUtilities.cpp:1623: void WbSupervisorUtilities::handleMessage(QDataStream&): Assertion `0' failed.
./webots: line 102: 88196 Aborted                 (core dumped) "$webots_home/bin/webots-bin" "$@"
```

**Comment by ad-daniel** [comment]
Doesn't happen anymore for some reason

**Comment by omichel** [comment]
I had the feeling this was happening randomly... So it might strike back anytime soon...
