### ISSUE TITLE
EXTERNPROTO declaration not added correctly

### ISSUE THREAD

**Issue by BenjaminDeleze** [cyberbotics/webots#5096]
**Describe the Bug**
ditto

**Steps to Reproduce**
1. Open a world
2. Add a `TruckSimple`
3. Go to `TruckSimple` -> `trailer` -> `appearance`
4. Modify the `roughness` to 0.5
5. Save and reload
6. This error appear: 
```
ERROR: Missing declaration for 'TruckTrailerSimple', add: 'EXTERNPROTO "../../../webots/projects/vehicles/protos/generic/TruckTrailerSimple.proto"' to '/home/benjamin/Desktop/slot/worlds/empty.wbt'.
```

And the declaration is indeed missing

**Comment by stefaniapedrazzi** [comment]
This is a side effect coming from the wrong redirection of the `TruckTrailerSimple` fields:
changes to the `roughness` value (or texture image or any other field) are not propagated to the instantiated nodes (changes are not applied to the scene) and the `parameterChanged` signal is not emitted.
These changes can only be applied by saving and reverting the world.

The fix to this issue should consist in fixing the redirection of the parameters.

A workaround would be to add a validation pass just before saving the world to retrieve all the PROTO instances that changed but were not correctly notified.
