### ISSUE TITLE
Compilation slowed by WREN

### ISSUE THREAD

**Issue by ad-daniel** [cyberbotics/webots#5122]
**Describe the Bug**

In ubuntu, when compiling from WEBOTS_HOME, the process alts for ~15s at the step `# * wren *` every time, even when re-making without changing anything. Maybe there's a way to detect when nothing changes and skip doing so

**Comment by ygoumaz** [comment]
I can't reproduce this issue. Is it on the master branch?

**Comment by ad-daniel** [comment]
commenting: `source "/home/daniel/webots_master/dependencies/emsdk/emsdk_env.sh" >/dev/null 2>&1` in the .bashrc solved the issue
