### ISSUE TITLE
Double "Convert Root to Base Node(s)" makes Webots crash in Tiago++

### ISSUE THREAD

**Issue by BenjaminDeleze** [cyberbotics/webots#5141]
**Steps to Reproduce**
1. Open `Tiago++.wbt`
2. `Convert Root to Base Node(s)` one of the `TiagoGripper`
3. `Convert Root to Base Node(s)` one of the `CapScrew` inside of the `TiagoGripper`
4. Webots crash

**Additional context**
Bug present at least since R2022a.

**Comment by omichel** [comment]
After the first `Convert Root to Base Node(s)`, I am getting a warning in the console:
```
Warning: QObject::disconnect: Unexpected nullptr parameter
```

**Comment by ygoumaz** [comment]
#5467 is following-up on the warning issue.
