### ISSUE TITLE
Field editor area too big for content

### ISSUE THREAD

**Issue by stefaniapedrazzi** [cyberbotics/webots#5189]
On the master branch the field editor is too big and it is not resized to content.
This is really bad because lot of space is added between the elements and very often you also need to scroll to view and used all the fields when there will be enough space to display all the fields without the scrollbar.
I'm on Ubuntu 22.04.

![Screenshot from 2022-09-08 10-11-28](https://user-images.githubusercontent.com/5910449/189071302-bb6bd228-89ba-4a4e-ad67-092199223b5a.png)

**Comment by omichel** [comment]
This problem doesn't show-up on Windows.

**Comment by omichel** [comment]
I cannot reproduce it on my Ubuntu 22.04:
![Screenshot from 2022-09-08 12-29-59](https://user-images.githubusercontent.com/1264964/189100327-b07906df-861e-448b-85b0-432f9151899f.png)

Which world, node, field are you displaying?

**Comment by stefaniapedrazzi** [comment]
It still depends on the number of importable externproto.
If you have many of them the size of the field editor is big.

**Comment by stefaniapedrazzi** [comment]
Yes, I'm sure I'm using Webots compiled from the master branch.
I have this issue when working the robotti world.
However, it is not always reproducible and I'm now inspecting which actions are triggering it.
Once found I will fix it.

**Comment by stefaniapedrazzi** [comment]
Steps to reproduce:
1. open `sumo_interface_example.wbt`
2. Select `Floor.appearance` field, delete the node and add the `Soil` PROTO node
-> a scroll bar appears in the field editor

**Comment by ygoumaz** [comment]
I confirm I can reproduce the issue. This affects worlds with a large IMPORTABLE list. The issue can be reproduced by adding any PROTO node to this type of worlds. Best example is `icon_studio.wbt`.

**Comment by ad-daniel** [comment]
The previous issue similar to this was related to the fact that we populated the IMPORTABLE panel even when another panel was open. What I suspect is happening here is that by doing some actions (for example in yannick's case adding a PROTO with add-node), a call to `declareExternProto` occurs and in turn the signal `externProtoListChanged` is emitted. This signal causes the contents of the panel to be updated, or in this case, for it to be filled which messes up the panels yet again.

I suspect it might be sufficient to ensure that we trigger this signal only if the `importable` flag is active

**Comment by stefaniapedrazzi** [comment]
Yes, the `updateContents` is triggered by other actions when the WbExternProtoEditor is not active.
Thus, the newly added cleanup method is not called just after to fix the editor size.
However,  I think that we no longer need at all to updated the WbExternProtoEditor when the list of declaration changes: see https://github.com/cyberbotics/webots/pull/5193.
