### ISSUE TITLE
Field editor automatically displayed when selection changes

### ISSUE THREAD

**Issue by stefaniapedrazzi** [cyberbotics/webots#5209]
Steps to reproduce:
1. open any world
2. hide field editor by reducing its height with the mouse until it disappears
3. change selected object
-> the field editor appears again

I checked and it works correctly in R2022a: the field editor remains hidden after changing the selection.

**Comment by ad-daniel** [comment]
I think this was an intended behavior introduced here: https://github.com/cyberbotics/webots/pull/4826

**Comment by stefaniapedrazzi** [comment]
This behavior is quite bad and makes Webots difficult to use with small screens.

**Comment by omichel** [comment]
@stefaniapedrazzi: can you go ahead with the implementation of what you propose?
