### ISSUE TITLE
TexturedBox PROTO parameters changes not working

### ISSUE THREAD

**Issue by stefaniapedrazzi** [cyberbotics/webots#5214]
The changes to the `TexturedBox` PROTO `size` field are not applied in the scene until the world is saved and reverted.

**Comment by stefaniapedrazzi** [comment]
The issue is that `TexturedBox` PROTO is not flagged as "template" node.
`TexturedBox` itself doesn't contain any javascript code, but the base `TexturedParallelepiped` does.

**Comment by omichel** [comment]
I believe there are two ways to fix this:
1. Add the template language line in the `TexturedBox` PROTO and probably we should also add a test that checks if the template language is set properly in all the PROTO files depending on their dependencies.
2. Fix Webots to flag the PROTO as a template language PROTO if any of its dependency has this template language set.

I believe solution 2 is better in the long term as PROTO developers don't have to care about the dependencies of the PROTO they are creating. It is also cleaner that the template language line concerns only the current file and not its dependencies.

**Comment by stefaniapedrazzi** [comment]
Yes, I agree.
I'm inspecting how to implement solution 2.

**Comment by stefaniapedrazzi** [comment]
This is a regression. It was working properly in R2022a.
