### ISSUE TITLE
After error the controller does not start

### ISSUE THREAD

**Issue by laszlo-schaffer** [cyberbotics/webots#5324]
**Describe the Bug**
After an error occurs in the controller (python in this case), it does not start again. In the console it can be seen that the controller is going to be started with the corresponding command. But the simulation is not started, the runtime halts at 0:00:00.

**Steps to Reproduce**
1. Start the simulation, which produces an error in the controller.
2. Reset the simulation
3. Start the simulation again.
4. See that the simulation is halted, the controller wont start either.

**Expected behavior**
After the error is fixed and the simulation is started, it is expected that the simulation will run without the error.

**Screenshots**
In the screenshot it can be seen, that an error occured in the simulation. The error has been fixed, the simulation is started again after a reset, but the controller wont start, the simulation halts.

![webots_controller_error_simulation_not_starting](https://user-images.githubusercontent.com/73738851/195294826-52f282e6-888c-4abc-9903-d218c316fd4c.png)

**System**
 - Webots 2022b
 - Operating System: Windows 10, 10.0.19044 build 19044
 - CPU:  Intel(R) Core(TM) i7-4770K CPU @ 3.50GHz
 - Graphics Card: Nvidia Geforce GTX 770

**Additional context**
This error did not occur in earlier versions of Webots, like 2022a.

**Comment by omichel** [comment]
This bug was fixed in #5284.
Please download the latest [nightly build](https://github.com/cyberbotics/webots/releases) of Webots R2022b-rev1 which includes the patch.
Let me know if that resolves the problem.

**Comment by laszlo-schaffer** [comment]
Thank you. Indeed, it solves the problem.
