### ISSUE TITLE
Sumo crashing directly after startup

### ISSUE THREAD

**Issue by ygoumaz** [cyberbotics/webots#5481]
`Sumo-gui` crashes directly after the launch.

1. Open `vehicles/highway.wbt`
2. Run the simulation.
3. Sumo starts but crashes directly.

**Comment by stefaniapedrazzi** [comment]
I made some changes in https://github.com/cyberbotics/webots/pull/4936, maybe it is related.
I'm sure I tested the changes at some point and they were working properly but maybe some later changes could have broken something.
