### ISSUE TITLE
Motion blur not applied on pasted robot with camera (Windows)

### ISSUE THREAD

**Issue by stefaniapedrazzi** [cyberbotics/webots#5491]
Steps to reproduce:
1. Open `camera_motion_blur.wbt` and run the simulaton
2. Copy the MyBot robot and paste it in the world
-> in the camera overlay of the newly added Robot the motion blur effect is not visible

I get this behavior on Windows (with user name containing UTF-8 characters).
I tested on my development system on Ubuntu 22.04 and the motion blur is applied correctly to the pasted Camera image.

**Comment by omichel** [comment]
I am getting the same bug on macOS although my user name is fully ASCII.

**Comment by omichel** [comment]
I also noticed on macOS that if the ambient occlusion is disabled in the Webots/OpenGL preferences, the motion blur doesn't work at all even for the first robot.

**Comment by stefaniapedrazzi** [comment]
It is not reproducible, but sometimes also on my Windows machine it doesn't work even for the first robot.

**Comment by omichel** [comment]
Yes, it is the same also on macOS.

**Comment by stefaniapedrazzi** [comment]
I can reproduce this issue with the nightly built before changind the GTAO shader.
