### ISSUE TITLE
Test suite check still doesn't properly detect failures

### ISSUE THREAD

**Issue by stefaniapedrazzi** [cyberbotics/webots#5503]
The Ci test suite check is still reporting a success even if there are failures in one of the test:

For example this failure is not detected:
```
OK: gps_coordinates_north_direction
FAILURE with /home/runner/work/webots/webots/tests/api/worlds/gps_speed.wbt: Timeout the results file has not been written quickly enough
```
See:
[/cyberbotics/webots/actions/runs/3468695977/jobs/5795459649](https://github.com/cyberbotics/webots/actions/runs/3468695977/jobs/5795459649)

**Comment by ad-daniel** [comment]
I believe this issue can be close now
