### ISSUE TITLE
The simulation is slow.

### ISSUE THREAD

**Issue by vitormartins01** [cyberbotics/webots#5522]
My simulation has 1 dynamic robot and a camera. The problem with the simulation getting stuck is when I activate the camera controller...
I'm using the latest version of webots R2023A, I've tried everything to try to solve this problem but I couldn't find a solution.

System 
- System: Windows 11
 - Graphics Card:

**Comment by RugnirViking** [comment]
what graphics card do you have? and is the problem that the simulation is slow or that it gets "stuck"?

**Comment by vitormartins01** [comment]
Graphics Card: Nvidia Geforce gtx 1650 ti.

I didn't understand your question !

Without the camera controller activated my robot moves normally (at the speed I set) and the simulation is running at 0.9X. With the camera controller activated the robot appears stuck and the simulation is running at 0.01x.

**Comment by vitormartins01** [comment]
Could someone help me ?

**Comment by stefaniapedrazzi** [comment]
This issue seems to be duplicated in #5524.
