### ISSUE TITLE
Adding New Node and API Function wiki page is out of date

### ISSUE THREAD

**Issue by brettle** [cyberbotics/webots#5777]
**Describe the Bug**

The [Adding New Node and API Function wiki page](https://github.com/cyberbotics/webots/wiki/Adding-New-Node-and-API-Function) refers to the following things that I can't seem to find:

1.  `$WEBOTS_HOME/resources/web/wwi/protoVisualizer`
2.  `applyUpdateToObject function` in `$WEBOTS_HOME/resources/web/wwi/X3dScene.js`
3. Everything under the Webots-cloud section. I couldn't find any of it in the main webots repo or the webots-cloud repo.

**Comment by BenjaminDeleze** [comment]
As specified in the title of the sections, the WebotsJS and webots-cloud sections will only be needed after the corresponding PRs are merged.

**Comment by brettle** [comment]
Thanks @BenjaminDeleze and my apologies for not seeing that you made the changes after I mentioned the issue on discord.
