### ISSUE TITLE
Missing point on lidar

### ISSUE THREAD

**Issue by ShuffleWire** [cyberbotics/webots#5809]
**Describe the Bug**
When using high quality Lidar, I run into the issue that some points were not shown. i don't know if it a rendering issue of the Lidar by Wren, or a point cloud display issue, didn't tried to inspect that, but I'm confident about the display of the point cloud.

**Steps to Reproduce**
1. Open the world and run two steps
[lidar_cylinder_missing_points.zip](https://github.com/cyberbotics/webots/files/10547127/lidar_cylinder_missing_points.zip)

2. See missing point on the border
![lidar_6](https://user-images.githubusercontent.com/83014015/215783503-7c9e21f0-9a09-4c36-8883-9a25f2f97298.png)

Same with this world : 
[lidar_cylinder_missing_points_2.zip](https://github.com/cyberbotics/webots/files/10547140/lidar_cylinder_missing_points_2.zip)
![lidar_7](https://user-images.githubusercontent.com/83014015/215783593-ee522c03-a16d-458a-b52d-2783fe6f969f.png)

**Expected behavior**
All point should be displayed.

**System**
 - Operating System: Debian 11
 - Graphics Card: None, that could be a source of issue, please someone with one test for me :)  
 - Webots master 045000f6f723f93a57e34434dac05ff74a745013

**Comment by ShuffleWire** [comment]
Still present in R2023b

**Comment by omichel** [comment]
Fixed in #6417.
