### ISSUE TITLE
Multiple "identical" Lidar give differents results 

### ISSUE THREAD

**Issue by ShuffleWire** [cyberbotics/webots#5810]
**Describe the Bug**
I'm playing with Lidar, and encounters this weird behavior : when using two Lidar, they seems to pertubate each other.
I've two identical Llidar, placed at the same position. One "wide" has a fov of 180°, and 512 points. The second "narrow" as a fov 16 times smaller and 16 times as well less points. Hence, in the region in front of the lidar, I was expecting to have exactly the same result, i.e. points cloud generated by those two Lidar should overlap. (of course the larger one will generate additional points, but that not important here).

The thing is, they do not.

Open and run for two step this world : 
[lidar_bad_overlap.zip](https://github.com/cyberbotics/webots/files/10547298/lidar_bad_overlap.zip)

You get : 
![lidar_10](https://user-images.githubusercontent.com/83014015/215788375-60c9a015-382e-4d12-aca1-abcf39a48cad.png)

Clearly cloud don't overlap : the correct one is emitted by the "wide" Lidar, and the bad one is generated by the "narrow" Lidar
We could see, from the side, in orthographic view, that the bad point are in fact below the ground, as if they "gone trough" the ground, and eventually stopped. Alignment with the origin of the Lidar seems fine, thought.
![lidar_8](https://user-images.githubusercontent.com/83014015/215793664-d6103cc2-a19d-4c12-b90d-b7d50d1a8222.png)

I've circled in colors the points (broadly each line of the point cloud, but given the POV, they appear as one point each, approximately) : in green the good ones, in red the bad one, the white line is the floor (bold in order to be visible)

What is happening ? Why green and red points don't match ?

**System**
 - Operating System: Debian 11 master and develop 
 - Graphics Card: None, could someone with one could test for me ? EDIT : Tested with Webots 2023a-rev1 + GTX 1650 + Debian 11 on another machine, and same result

**Comment by Inngress** [comment]
I encounter the same problem with "narrow" lidars.

**The bug**
I just put two of them in the same world and activate them with a controller. While the lidar is facing a plane surface, the point cloud is perfect. But try and tilt it and it starts to have a weird behavior ;  the point cloud goes deeper into the ground the higher you position the lidar from it and the surface is also no longer parallel to the point cloud, it deviates. And the deviation depends on the tilt angle. See below
![two_lidars_tilted](https://github.com/cyberbotics/webots/assets/74958967/f086d055-7426-45b4-823d-d324291ea213)
![two_lidars_offset](https://github.com/cyberbotics/webots/assets/74958967/158e56e6-ee2c-460c-9f3c-d71e30dfb80d)



The lidar configuration is the following
```
tiltAngle 0
fieldOfView 1.0471975511965976 # 60°
verticalFieldOfView 0.8726646259971648 # 50°
horizontalResolution 65
numberOfLayers 40 # vertical resolution
maxRange 15
minRange 0.12
defaultFrequency 10
```
I checked and it is not just a display bug. I exported the data into ROS messages and visualizing it with Rviz gives the same offset between the two lidars.

**System**
- Operating System: Linux Ubuntu 22.04
- Graphics Card: NVIDIA GeForce RTX 3070 Ti laptop 8 GB
- Webots 2023b
