### ISSUE TITLE
Unwanted warnings or behavior in distributed simulations

### ISSUE THREAD

**Issue by stefaniapedrazzi** [cyberbotics/webots#5819]
Following the recent changes to the contact points detection these simulations are printing many warnings that should be solved (tested on develop branch):
* `animated_skin.wbt`: many warnings are printed
*  `sojourner.wbt`: cannot climb the rocks
* _continuing_

**Comment by ad-daniel** [comment]
Perhaps we can improve the test worlds script so that it runs the simulation for some time instead of just checking whether there are warnings on load. A possible approach could be to graft a custom supervisor into the world file prior to loading it that runs the simulation for X seconds and quits

**Comment by stefaniapedrazzi** [comment]
Yes, this would be good the detect the warnings.
However, we should always run the tests manually to check if the simulation behavior is still correct.
