### ISSUE TITLE
Wrong parent link for SliderJoint in generated URDF

### ISSUE THREAD

**Issue by IDavGal** [cyberbotics/webots#5866]
**Describe the Bug**
The generated URDF from a proto with a Transform->SliderJoint names the parent link of the joint after the Transform's node DEF statement (or the node type if no DEF statement is present), causing an unidentified link name error.

**Steps to Reproduce**
1. Create a robot with 2 Transforms each with a SliderJoint & HingeJoint child 
2. Define a DEF for each transform, and name the solid endPoint for each Joint
3. Export an URDF from the robot using the UI 
4. Check that the parent/children of both joints are properly named

**Screenshots**
An example output of the previous steps is shown next:
![protovsurdf](https://user-images.githubusercontent.com/99193391/217855112-0416d2f4-1768-445c-a8e9-cd75d762d0bf.jpeg)

**Additional context**
This behavior does not seem to happen when the joint node's parent is a solid/robot with a established `name` field

**Comment by ygoumaz** [comment]
I can reproduce this issue. It seems like only SlideJoint is not correctly linking with the parent node. It should indeed ignore the Transform node. I will investigate this and fix it.
