### ISSUE TITLE
webots can not use 3090 gpu in docker container through X11 forwarding

### ISSUE THREAD

**Issue by HaoLiuHust** [cyberbotics/webots#5873]
**Describe the Bug**

I am use X11 forwarding to start webots on a remote server with 3090 GPU, I have installed Nvidia GPU driver on that server, however, when I start webots, it saids the GPU is not meet the requirements because  opengl use Mesa/X.org.  How to solve this?

```
 > glxinfo | grep OpenGL
OpenGL vendor string: Mesa/X.org
OpenGL renderer string: llvmpipe (LLVM 15.0.6, 256 bits)
OpenGL core profile version string: 4.5 (Core Profile) Mesa 22.2.5
OpenGL core profile shading language version string: 4.50
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL core profile extensions:
OpenGL version string: 4.5 (Compatibility Profile) Mesa 22.2.5
OpenGL shading language version string: 4.50
OpenGL context flags: (none)
OpenGL profile mask: compatibility profile
OpenGL extensions:
OpenGL ES profile version string: OpenGL ES 3.2 Mesa 22.2.5
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20
OpenGL ES profile extensions:

```

**Steps to Reproduce**

**Expected behavior**

**Screenshots**

**System**
 - Operating System: [e.g., Windows 10, Linux Ubuntu 18.04, macOS Mojave]
 - Graphics Card: [e.g., NVIDIA GeForce RTX 2080 11 GB, AMD Radeon RX 580 8GB, etc.]

**Additional context**

**Comment by omichel** [comment]
This is not a bug, but a question. Please ask it on https://robotics.stackexchange.com with the `webots` tag.
