### ISSUE TITLE
Supervisor crash/hang after `enablePoseTracking()`

### ISSUE THREAD

**Issue by jaagut** [cyberbotics/webots#5882]
**Describe the Bug**
The supervisor controller (Python API) seems to crash/hang when using `enablePoseTracking()`.
Running `node1.getPose()` and `node2.getPose()` works just fine.
But running `node2.getPose()` after `node1.enablePoseTracking(<int>)` was called does not work, and the supervisor controller seems to hang forever.

**Steps to Reproduce**
1. Use one of these Webots versions: 
    - R2022b
    - R2023a
    - R2023b Nightly Build 10/2/2023
3. Open [this world](https://gist.github.com/jaagut/2b758d40b7e13b2dcc9020f079295032)
4. Run [this Python minimal example script](https://gist.github.com/jaagut/ae3eeb50650b5d2bd703ab789e7c07c6) `python3 minimal_example_supervisior_controller.py`
5. Examine the output of the script. Probably you will get the following output: _"IMPORTANT!!! Now the supervisor controller will hang forever..."_
6. Just in case the simulator stepping has an impact, the script can be run without stepping by setting `do_step = False` in line 5. Run the script again, results should be the same.
7. Also try `do_pose_tracking_node2 = False` (line 6) to check, whether it helps to enable pose tracking for all nodes we want to get the pose from.

<details><summary>Example output:</summary>
<p>
Getting the poses of both Nodes works:
Pose of Node1 [0.00037402848288182794, 0.1255107792045821, 0.9920921854374989, 0.030007285217697743, 0.9999804787604403, 0.006140897717199582, -0.0011538948251857391, 0.0014632167783275303, -0.006237162875434007, 0.9920732501578126, -0.12550603220793732, 0.23337273269731101, 0.0, 0.0, 0.0, 1.0]
Pose of Node2 [0.00037402848288182794, 0.1255107792045821, 0.9920921854374989, 0.030007285217697743, 0.9999804787604403, 0.006140897717199582, -0.0011538948251857391, 0.0014632167783275303, -0.006237162875434007, 0.9920732501578126, -0.12550603220793732, 0.23337273269731101, 0.0, 0.0, 0.0, 1.0]

Stepping the simulation...

Getting the poses of both Nodes works:
Pose of Node1 [0.00037402848288182794, 0.1255107792045821, 0.9920921854374989, 0.030007285217697743, 0.9999804787604403, 0.006140897717199582, -0.0011538948251857391, 0.0014632167783275303, -0.006237162875434007, 0.9920732501578126, -0.12550603220793732, 0.23337273269731101, 0.0, 0.0, 0.0, 1.0]
Pose of Node2 [0.00037402848288182794, 0.1255107792045821, 0.9920921854374989, 0.030007285217697743, 0.9999804787604403, 0.006140897717199582, -0.0011538948251857391, 0.0014632167783275303, -0.006237162875434007, 0.9920732501578126, -0.12550603220793732, 0.23337273269731101, 0.0, 0.0, 0.0, 1.0]

Stepping the simulation...

Getting the poses of both Nodes works:
Pose of Node1 [0.00037402848288182794, 0.1255107792045821, 0.9920921854374989, 0.030007285217697743, 0.9999804787604403, 0.006140897717199582, -0.0011538948251857391, 0.0014632167783275303, -0.006237162875434007, 0.9920732501578126, -0.12550603220793732, 0.23337273269731101, 0.0, 0.0, 0.0, 1.0]
Pose of Node2 [0.00037402848288182794, 0.1255107792045821, 0.9920921854374989, 0.030007285217697743, 0.9999804787604403, 0.006140897717199582, -0.0011538948251857391, 0.0014632167783275303, -0.006237162875434007, 0.9920732501578126, -0.12550603220793732, 0.23337273269731101, 0.0, 0.0, 0.0, 1.0]

Enabling pose tracking on Node1...

Enabling pose tracking on Node2...

Stepping the simulation...

Getting the pose of Node1 works:
Pose of Node1 [0.00037402848288182794, 0.1255107792045821, 0.9920921854374989, 0.030007285217697743, 0.9999804787604403, 0.006140897717199582, -0.0011538948251857391, 0.0014632167783275303, -0.006237162875434007, 0.9920732501578126, -0.12550603220793732, 0.23337273269731101, 0.0, 0.0, 0.0, 1.0]

IMPORTANT!!! Now the supervisor controller will hang forever...
</p>
</details>

**Expected behavior**
My understanding is, that pose tracking can be enabled for every node object we want (for performance reasons).
The supervisor controller should not hang, when using this feature.

Either I am doing something wrong and not as it is supposed to be (please direct me to the comprehensive documentation or create missing documentation), OR this behavior is not intended and probably a bug (please fix it or print warnings for the user).

**Screenshots**
No screenshots, but please have a look at the example output above.

**System**
 - Operating System: Linux Ubuntu 22.04 LTS (64 Bit)
 - Graphics Card: Nvidia Titan X GP102 (reva1)

**Additional context**
I have read this documentation: https://cyberbotics.com/doc/reference/supervisor?tab-language=python#wb_supervisor_node_enable_pose_tracking

**Comment by ad-daniel** [comment]
Thank you for the very detailed bug report and minimal example! I can confirm that even on the latest master and develop branches the problem persists. It doesn't appear to be language specific, I have the same issue with the C API. 
Concerning the conditions, it's very odd.
Sometimes I need to have 2 nodes being tracked and requesting 2 poses. Sometimes (less often), it's sufficient to request the pose of 1 while tracking 2 nodes.
