### ISSUE TITLE
Changing a proto parameter stops the motion

### ISSUE THREAD

**Issue by omichel** [cyberbotics/webots#5951]
While playing with [friction_gears.zip](https://github.com/cyberbotics/webots/files/10846672/friction_gears.zip), I found that if I change the number of teeth of the `Robot / children / DEF PASSIVE HingeJoint / endPoint Gear / teeth` from 20 to 19, the motion of this wheel stops. If I reset the simulation, it doesn't start again. If I save as and reload the simulation, it works.

I can reproduce the problem both on the master and develop branches.

**Comment by stefaniapedrazzi** [comment]
It seems that after the PROTO node is regenerated, the parent `WbSolid::mSolidChildren list is not correctly updated and it no longer contains the regenerated PROTO node.
