### ISSUE TITLE
When I installed webots using source compilation, I couldn't start webots

### ISSUE THREAD

**Issue by SenHe524** [cyberbotics/webots#6004]
**Describe the Bug**
When I installed webots using source compilation, I couldn't start webots.

**Steps to Reproduce**
Here is a record of the terminal output when the source code is compiled
//******
root@25cec3013669:/usr/local/webots# make -j8
 * dependencies *
 PROTO files unchanged, no need to rebuild proto-list.xml
 * ode *
 * glad *
 * wren *
 * webots (core) *
 * controller library *
 C controller library (release)
 C++ controller library (release)
 Java controller library (release)
e # Java not installed or 'JAVA_HOME' not set, skipping Java API
 Matlab controller library (release)
 generating matlab
 * resources *
 *** translations ***
 *** projects ***
 make release libraries/qt_utils
 make release plugins/physics
 make release libraries/generic_robot_window
 make release controllers/generic
 make release plugins/robot_windows/generic_window
 copying to /usr/local/webots/lib/controller/libgeneric_robot_window.so
 make release plugins/robot_windows/generic
 * projects *
 !!! languages !!!
 *** controllers ***
 make release driver
 make release slave
 make_java release Driver
 make_java release Slave
e # Java not installed or 'JAVA_HOME' not set, skipping Java API
e # Java not installed or 'JAVA_HOME' not set, skipping Java API
 make release e-puck_position_supervisor

 !!! default !!!

 *** resources ***
 make release controllers/braitenberg
 make release libraries/vehicle
 make release controllers/ros
 make release c/car
e # ROS_DISTRO should not be a ROS2 distribution
 copying to /usr/local/webots/lib/controller/libcar.so
 make release c/driver
 linking libdriver.so
 copying to /usr/local/webots/lib/controller/libdriver.so
 make release cpp/driver
 linking libCppDriver.so
 copying to /usr/local/webots/lib/controller/libCppDriver.so
 make release cpp/car
 linking libCppCar.so
 copying to /usr/local/webots/lib/controller/libCppCar.so
 make release java
e # Java not installed or 'JAVA_HOME' not set, skipping Java API

 !!! objects !!!
 make release factory/conveyors/controllers
 make release create_wall/controllers
 make release computers/controllers
 make release television/controllers
 make release mirror/controllers
 make release traffic/controllers
 make release keyboard_conveyor_platform
 make release conveyor_belt
 make release create_wall_emit_signal
 make release laptop_switch_on
 make release mirror
 make release crossroads_traffic_lights
 make release defective_street_light
 make release television_switch_on
 make release generic_traffic_light

 !!! robots !!!
 make release robotis/darwin-op/libraries
 make release kuka/youbot/libraries
 make release neuronics/ipr/libraries
 make release epfl/lis/controllers
 make release sony/aibo/controllers
 make release a4/portal/controllers
 make release adept/pioneer3/controllers
 make release bitcraze/crazyflie/controllers
 make release youbot_control
 make release blimp
 make release ers7_mimic
 make release ipr
 make release ers7
 make release pioneer3at_obstacle_avoidance_with_lidar
 make release crazyflie
 make release robotis-op2
 make release pioneer3dx_obstacle_avoidance_with_kinect
 make release bluebotics/shrimp/controllers
 make release pioneer3dx_collision_avoidance
 make release pioneer3dx_gripper
 make release shrimp
 make release boston_dynamics/atlas/controllers
 make release hello_world_demo
 make release boston_dynamics/spot/controllers
 make release spot_moving_demo
 make release clearpath/moose/controllers
 make release clearpath/pr2/controllers
 make release moose_path_following
 make release pr2_demo
 make release managers
 make release dji/mavic/controllers
 make release epfl/biorob/controllers
 make release mavic2pro
 make release ghostdog
 make release salamander
 make release festo/robotino3/controllers
 make release robotino3
 make release yamor
 make release fp_robotics/p-rob3/controllers/p-rob3
 make release franka_emika/panda/controllers
 make release panda_arm_demo
 make release fujitsu/hoap2/controllers
 make release gctronic/e-puck/controllers
 make release e-puck
 make release hoap2
 make release e-puck_avoid_obstacles
 make release e-puck_cross-compilation
 make release e-puck_line
 make release gctronic/elisa/controllers
 make release husarion/rosbot/controllers
 make release elisa3
 make release rosbot
 make release irobot/create/controllers
 make release create_avoid_obstacles
 make release ground
 make release kinematics/tinkerbots/controllers
 make release grabber_base
 make release e-puck_line_demo
 make release e-puck2_server
 make release k-team/hemisson/controllers
 make release hemisson
 make release crane
 make release four_wheels_vehicle
 make release k-team/khepera1/controllers
 make release khepera_bus
 make release tinkerbots_demo
 make release vehicle
 make release k-team/khepera3/controllers
 make release khepera3_gripper
 make release k-team/khepera4/controllers
 make release khepera4
 make release kondo/khr-2hv/controllers
 make release khr-2hv_demo
 make release kuka/youbot/controllers
 make release youbot
 make release khepera_gripper
 make release khepera_k213
 make release pipe
 make release tcpip
 make release lego/mindstorms/controllers
 make release Rover
 make_java release Rover
 make release micromagic/mantis/controllers
 make release mantis
e # Java not installed or 'JAVA_HOME' not set, skipping Java API
 make release micromagic/scout/controllers
 make release scout
 make release mir/mir100/controllers
 make release mobsya/thymio/controllers
 make release keyboard_control
 make release nasa/controllers
 make release thymio2_demo
 make release sojourner
 make release neuronics/ipr/controllers
 make release conveyor_belt
 make release nex/controllers
 make release fire_bird_6_obstacle_avoidance
 make release target_coordinates
 make release niryo/ned/controllers
 make release ned
 make release nvidia/jetbot/controllers
 make release jetbot_basic_motion
 make release ipr1_collaboration
 make release ipr2_collaboration
 make release pal_robotics/tiago_base/controllers/tiago_base
 make release fire_bird_6_sensor_acquisition
 make release pal_robotics/tiago_iron/controllers/tiago_iron
 make release pal_robotics/tiago_steel/controllers/tiago_steel
 make release ipr_cube
 make release pal_robotics/tiago_titanium/controllers/tiago_titanium
 make release ipr_factory
 make release pal_robotics/tiago++/controllers/tiago++
 make release parallax/boebot/controllers
 make release boebot
 make release picaxe/microbot/controllers
 make release rec/fabtino/controllers
 make release robotis/bioloid/controllers
 make release bioloid_dog
 make release keyboard_control
 make release robotis/darwin-op/controllers
 make release op3_motion_player
 make release motion_player
 make release soccer
 make release symmetry
 make release robotis/turtlebot/controllers
 make release turtlebot3_ostacle_avoidance
 make release robotnik/summit_xl_steel/controllers
 make release visual_tracking
 make release keyboard_control
 make release walk
 make release softbank/nao/controllers
 make release sony/qrio/controllers
 make release sphero/bb8/controllers
 make release distributor
 make release qrio
 make release bb-8
 make release nao_demo
 make release surveyor/controllers
 make release unimation/puma/controllers
 make release surveyor
 make release puma560
 make release universal_robots/controllers
 make release ure_can_grasper
 make release nao_soccer_player
 make release gctronic/e-puck/plugins/robot_windows
 make release e-puck
 make release robotis/darwin-op/plugins/robot_windows
 make release botstudio
 make release gctronic/e-puck/plugins/remote_controls
 make release e-puck_bluetooth
 make release e-puck_wifi
 make release robotis/darwin-op/plugins/remote_controls
 make release robotis-op2_tcpip
 make release robotis-op2_window
 make release epfl/lis/plugins/physics
 make release blimp_physics
 make release gctronic/e-puck/transfer
 make release nao_soccer_supervisor
 make release nao_wave_hand

 !!! samples !!!
 make release curriculum/controllers
 make release demos/controllers
 make release devices/controllers
 make release geometries/controllers
 make release howto
 make release mybot/controllers
 make release rendering/controllers
 make release tutorials/controllers
 make release advanced_odometry
 make release binocular/controllers/binocular
 make release muscle
 make release mybot_camera
 make release anaglyph
 make release accelerometer
 make release salamander
 make release epuck_avoid_collision
 make release advanced_particle_swarm_optimization
 make release gantry
 make release advanced_particle_swarm_optimization_supervisor
 make release mybot_simple
 make release biped/controllers/biped
 make release water_flow_animation
 make release epuck_go_forward
 make release altimeter
 make release advanced_genetic_algorithm
 make release hexapod
 make release advanced_genetic_algorithm_supervisor
 make release advanced_path_planning_NF1
 make release center_of_mass/controllers/center_of_mass
 make release axial_and_tail_rotors
 make release four_wheels_collision_avoidance
 make release contests
 make release advanced_path_planning_potential_field
 make release ratslife

 *** controllers ***
 make release contest_manager
 make_java release Rat0
 make release moon
 make release tower_of_hanoi

 *** controllers ***
 make release advanced_pattern_recognition
 make release hanoi
 make_java release Rat1
e # Java not installed or 'JAVA_HOME' not set, skipping Java API
 make release advanced_pattern_recognition_supervisor
 make release advanced_slam_1
e # Java not installed or 'JAVA_HOME' not set, skipping Java API
 make release center_of_mass/controllers/rotation
 make release axial_rotor
 make release advanced_slam_2
 make release battery
 make release ball
 make release beginner_robot_controller
 make release soccer_player
 make release intermediate_behavior_based
 make release intermediate_finite_state_machine
 make release soccer_referee_supervisor
 make release console/controllers/console
 make release brake
 make release intermediate_lawn_mower
 make release stewart_platform
 make release custom_robot_window/plugins/robot_windows/custom_robot_window
 make release intermediate_lfm
 make release robotbenchmark
 make release humanoid_sprint/controllers
 make release race_stopwatch
 make release intermediate_oam
 make release cylinder_stack/controllers/contact_points_supervisor
 make release bumper
 make release novice_accelerometer
 make release novice_camera
 make release docker/controllers/camera
 make release novice_ir_sensors
 make release inverted_pendulum/plugins
 make release physics/inverted_pendulum_perturbation
 make release novice_k2000
 make release camera
 make release novice_linear_camera
 make release force_control/controllers/force_control
 make release camera_auto_focus
 make release novice_motors
 make release camera_recognition
 make release humanoid_marathon/controllers
 make release marathon_supervisor
 make release pit_escape/controllers/pit_escape_supervisor
 make release square_path
 make release real_robot
 make release wall_following
 make release controllers/wall_following_supervisor
 make release marathon
 make release four_wheels/controllers/four_wheels
 make release gears/controllers/gears
 make release inverted_pendulum/controllers/inverted_pendulum
 make release camera_segmentation
 make release mouse_events/controllers/mouse_events
 make release mouse_events/controllers/mouse_events_non_blocking
 make release omni_wheels/controllers/omni_wheels
 make release coaxial_rotors
 make release compass
 make release parallel_robot_step/controllers/parallel_robot_step
 make release connector
 make release coupled_motors
 make release display
 make release physics/plugins/physics/flying_mybot
 make release physics/controllers/physics
 make release rolling_friction/controllers/rolling_friction_supervisor
 make release display_supervisor
 make release distance_sensor
 make release emitter_receiver
 make release encoders
 make release sick_terrain_scanning/controllers/sick_terrain_scanning
 make release sick_terrain_scanning/controllers/sick_terrain_scanning_supervisor
 make release supervisor_draw_trail/controllers/supervisor_draw_trail
 make release force3d_sensor
 make release force_sensor
 make release gps
 make release gps_lat_long
 make release gps_supervisor
 make release texture_change/controllers/texture_change
 make release gyro
 make release texture_change/controllers/texture_robot
 make release hinge_joint_with_backlash
 make release hokuyo
 make release imu
 make release inertial_unit
 make release url/controllers/url
 make release laser_pointer
 make release led
 make release vision/controllers/vision
 make release lidar
 make release light_sensor
 make release linear_motor
 OPENCV_DIR not set, skipping vision controller.
 make release motor
 make release ziegler_nichols/controllers/ziegler_nichols
 make release motor2
 make release motor3
 make release pen
 make release position_sensor
 make release radar
 make release range_finder
 make release receiver_noise
 make release sample_supervisor
 make release sick
 make release sick_point_cloud
 make release skin
 make release speaker
 make release speaker_text_to_speech
 make release spherical_camera
 make release track
 make release track_conveyor_belt
 make_java release EmitterReceiver
e # Java not installed or 'JAVA_HOME' not set, skipping Java API

 !!! vehicles !!!

 *** controllers ***

 *** robot windows ***
 make release automobile
 make release automobile_window
 make release autonomous_vehicle
 make release boomer
 make release radar_target_tracker
 make release racing_wheel
 make release VehicleDriver
 make release ros_automobile
e # ROS_DISTRO should not be a ROS2 distribution
e # Java not installed or 'JAVA_HOME' not set, skipping Java API

 !!! humans !!!

 *** libraries ***
 make release skin_animated_humans/libraries/bvh_util

 *** controllers ***
 make release skin_animated_humans/controllers/bvh_animation
 *******////

**System**
 - Operating System: ubuntu 20.04 in docker environment，ros2 version is foxy.
 
 This is the error I got when I tried to run webots using the linux installation guide
![image](https://user-images.githubusercontent.com/99389099/226268943-d96204a4-c3d9-4ef5-a2ed-fef5d8ec9e30.png)

**Comment by SenHe524** [comment]
Can someone help me point out my problem? What can I do to make webots work?

**Comment by omichel** [comment]
Did you managed to fix the problem?

**Comment by SenHe524** [comment]
> Did you manage to fix the problem?

Yes, that was solved yesterday. The reason for the above error is that I downloaded the webots source code under windows environment, so the wrong file format (CR LF under windows, LF under linux) caused the executable file inside the source code to perform strange errors
