### ISSUE TITLE
Crash when wb_robot_wtep caused by setMFVec3f for point Field of IndexedLineSet Node

### ISSUE THREAD

**Issue by dooxu9527** [cyberbotics/webots#6058]
I'm trying to draw the swing trajectories of quad robot's four feet, like what supervisor_draw_trail does.

**What I do:**
1. Create Shape Node by string like this in world
![图片](https://user-images.githubusercontent.com/86762913/230575398-1b0a9758-db29-4441-8d82-25df612c9689.png)
2. Get position from my controller & draw it by pointField->setMFVec3f([positions]) and coordField->setMFInt32([coords])

**My problem:**
It goes well when I just draw one line, but when I draw more lines it only works well in the beginning and will **crash after some time**,  by which the software closes directly. 
If I draw **two lines** it will **crash after about 1min** in simulation, and it will **crash after about 30s** if I draw **four lines**. 

**My test：**
1. If I only comment out the call of **setMFVec3f**, it won't crash, so I guess there are something wrong with it.
![图片](https://user-images.githubusercontent.com/86762913/230580063-2e3eb624-6c6b-49b2-9d85-1869e97a34ad.png)
2. When I run the simulation using gdb, it shows that the iteration that the code stoped at wb_robot_step(TIME_STEP), see this pictures:
![图片](https://user-images.githubusercontent.com/86762913/230579413-6366bf27-b403-43a0-a70f-3a1e70e59b36.png)
![图片](https://user-images.githubusercontent.com/86762913/230578152-96cdc5f2-599b-43fc-ad7a-054b37617831.png)

**Comment by stefaniapedrazzi** [comment]
Could you please submit your world and controller file?
I tried to reproduce it starting from the `supervisor_draw_trail` example using a C and C++ controller but everything works fine for me.

Which version of Webots are you using?
Could you please try the latest R2023 revision 1 available from the nightly builds?
https://github.com/cyberbotics/webots/releases/tag/nightly_10_4_2023

**Comment by dooxu9527** [comment]
> > Could you please submit your world and controller file? I tried to reproduce it starting from the `supervisor_draw_trail` example using a C and C++ controller but everything works fine for me.
> > Which version of Webots are you using? Could you please try the latest R2023 revision 1 available from the nightly builds? https://github.com/cyberbotics/webots/releases/tag/nightly_10_4_2023
> 
> Thank you for reply! I have tried the R2023a-rev1 and it works well! The version I used was R2023a_amd64, and I found that my system is x86 not amd64, so this may be the reason.

I have tried the stable version webots-R2023a-x86-64 back, but it doesn't work again. So only the pre-release R2023a-rev1 version doesn't have this problem.

**Comment by stefaniapedrazzi** [comment]
Thank you for the feedback!
We already applied many bug fixed to R2023a and included in R2023 version1.
So it seems that also this bug has already been fixed.
