### ISSUE TITLE
Python Function `getRangeImageArray` on Lidar is missing, possibly misspelled. 

### ISSUE THREAD

**Issue by Nelson-iitp** [cyberbotics/webots#6074]
https://github.com/cyberbotics/webots/blob/360298d4bf98a762dfcedb4ef011ca35cd1ce14d/lib/controller/python/controller/lidar.py#L76

This is where `getRangeImageArray` should be I guess.

**Comment by omichel** [comment]
I believe I fixed the problem in #6080. Can you confirm that with this patch, it works for you?

**Comment by Nelson-iitp** [comment]
yes it does.
