### ISSUE TITLE
Weird incompatibility with macOS 10.14.6

### ISSUE THREAD

**Issue by conorheins** [cyberbotics/webots#6092]
**Describe the Bug**

I'm encountering a weird installation issue when trying to install Webots R2022b on MacOS 10.14.6, which if I understand correctly, is a compatible OS. 

After going through the usual installation instructions (using `curl` to avoid the Mac security preferences), I see that the installed Webots Icon in my Applications folder has a white cross over it (the typical "incompatible software" symbol) and when I double click on it to open Webots, I get a pop-up window that says "This software requires macOS 10.14 or later, but you are using 10.14.6". 

I also get the consistent `LSOpenURLsWithRole() failed with error -10825 for the file ...Applications/Webots.app.`when I try to open the software using `open Webots.app` in the terminal. 

Anyone else encounter this issue, or know how to work around it?

**System**
 - Operating System: macOS Mojave 10.14.6

**Comment by omichel** [comment]
Webots R2022b requires at least macOS 11 (e.g., Big Sur), see https://cyberbotics.com/doc/guide/system-requirements?version=R2022b
You will need to downgrade to Webots R2022a for use with macOS 10.14 (e.g., Mojave), see https://cyberbotics.com/doc/guide/system-requirements?version=R2022a
