### ISSUE TITLE
Windows: TLS initialization failed

### ISSUE THREAD

**Issue by stefaniapedrazzi** [cyberbotics/webots#6129]
When installing and running a package created from the master branch (Qt6) I get this error in the console that prevents downloading the PROTO files:
``Cannot download XXX, error code: 99: TLS initialization failed``

I have a couple of different Webots installations on the system (package, development) that might be causing some conficts.
But it is strange that the in the Webots package installation there is an empty `qt6\plugins\tls` folder.

So maybe it is just a local problem.
But then we should remove the empty `tls` plugins folder from the Windows package.

**Comment by omichel** [comment]
No problem for me either in Windows 11.
