### ISSUE TITLE
Issues with classic theme

### ISSUE THREAD

**Issue by stefaniapedrazzi** [cyberbotics/webots#6179]
The arrows for increasing/decreasing the double value are no longer visible (same reproducible in both Ubuntu 22.04 and Windows).

Here is a screenshot of the Field Editor:
![Screenshot from 2023-06-07 11-13-27](https://github.com/cyberbotics/webots/assets/5910449/b208fbf1-9314-4430-8a72-ef78d3d14f6a)

Then, the field editor has no border.
Personally I think that it was good to use the border to separate it from the console widget.
It doesn't change anything when a node is selected because the node editor has his own border, but this is not the case when selecting for example a double value.

For comparison here is the previous appearance:
![Screenshot from 2023-06-07 11-30-05](https://github.com/cyberbotics/webots/assets/5910449/0b675b25-8a60-48b4-96f1-634b1252f3ef)

**Comment by omichel** [comment]
Also this one doesn't look nice:
![image](https://github.com/cyberbotics/webots/assets/1264964/c649866c-21d0-4b6c-9cd0-c438a081e2ea)
