### ISSUE TITLE
3D view bug, i can't choose the model correctly!

### ISSUE THREAD

**Issue by iWFEI** [cyberbotics/webots#6186]
**Describe the Bug**
After I finished installing webots, the 3D view display was incomplete. I clicked on the model with the mouse and couldn't select it correctly. Then I found out that when I clicked on an area that was not a model, the model was selected, and the displayed screen and the position of the model were not in the same place!!! May I know how to modify it? Thank you!

**Screenshots**
![选区_041](https://github.com/cyberbotics/webots/assets/43775329/f85d8900-0715-4a68-970b-4a90eca725cb)
**System**
 - Operating System: Ubuntu 20.04
 - Graphics Card: [e.g., NVIDIA GeForce RTX 3060 6 GB

**Comment by stefaniapedrazzi** [comment]
Same issue as  #6055.
