### ISSUE TITLE
Bug with size of khr-3hv

### ISSUE THREAD

**Issue by naos080415** [cyberbotics/webots#6207]
The position of the torso of khr-3hv.wbt on webots is set as follows. 

![Screenshot from 2023-06-15 12-03-24](https://github.com/cyberbotics/webots/assets/73214238/e98e8855-b7b8-4e41-937e-5f7797998d23)

However, the size of khr-3hv on the real robot is 401.05mm high (=0.40105m),  so the robot on webots is about twice the size of the real robot. Is it possible to change it to the same scale?

Ref:
- khr-3hv real robot document : [https://kondo-robot.com/d/product/03110e](url)

**Comment by omichel** [comment]
True.

To fix it, please modify the [khr-3hv proto](https://github.com/cyberbotics/webots/blob/master/projects/robots/kondo/khr-3hv/protos/Khr3hv.proto) and open a new pull request that we will review and merge in Webots.
I believe it is a matter of dividing by 2 the values of all the indexed face sets coordinates, like [here](https://github.com/cyberbotics/webots/blob/master/projects/robots/kondo/khr-3hv/protos/Khr3hv.proto#L49), [there](https://github.com/cyberbotics/webots/blob/master/projects/robots/kondo/khr-3hv/protos/Khr3hv.proto#L102), etc. Then, you will have to divide by two also the values in the translation fields, like [here](https://github.com/cyberbotics/webots/blob/master/projects/robots/kondo/khr-3hv/protos/Khr3hv.proto#L67), etc.

Please ask for a review of your pull request after you tested it in Webots and are satisfied with the result.

Let me know if you have any question.
