### ISSUE TITLE
animated_skin.wbt crashes on Windows

### ISSUE THREAD

**Issue by omichel** [cyberbotics/webots#6210]
**Steps to Reproduce**
1. Open Webots R2023b (release candidate) with the spot demo, run it.
2. Open the animated_skin.wbt world.
3. During the "post-finalizing node", Webots quits without reporting any error.

**System**
 - Operating System: Windows 11
 - Graphics Card: NVIDIA GeForce GTX 760 3GB

**Notes**
The crash is not 100% reproducible, but I can reproduce it in about 80% of my tests.

**Comment by BenjaminDeleze** [comment]
I could not reproduce that on ubuntu 20.
