### ISSUE TITLE
Classic theme issues 

### ISSUE THREAD

**Issue by stefaniapedrazzi** [cyberbotics/webots#6211]
I'm testing the snap package on Ubuntu 22.04
* ~~the dialog to choose the editor  font from the Preferences dialog is broken.
    When clicking on the button to open it, the UI becomes gray (because it is a modal dialog that should block the rest of the application) but nothing is displayed. (you can exit clicking ESC)~~ _edit: tested on a clean VM and works correctly_
* video caption in checkbox in video recording "Choose video parameter" doesn't work:
    when clicking on it nothing happens

**Comment by BenjaminDeleze** [comment]
This one?
![font](https://github.com/cyberbotics/webots/assets/25938827/e60780ab-362f-4553-9ebb-553c84eff1e8)

Strange, it works well on snap ubuntu 20.04

**Comment by stefaniapedrazzi** [comment]
Yes. It doesn't show up for me.

**Comment by stefaniapedrazzi** [comment]
I also checked on my development environment (same system) and works fine.
The issues seems only with the snap installation.

**Comment by BenjaminDeleze** [comment]
Very strange as it is working for snap on ubuntu 22.
Does it happens only for the classic theme?

**Comment by stefaniapedrazzi** [comment]
After i opened it on the development environment it works also from the snap.
I will check on a clean VM to see if I can reproduce it.

The second issue is with the video parameter checkbox is reproducible consistently.

**Comment by BenjaminDeleze** [comment]
Yes I have it too
