### ISSUE TITLE
Backward mechanism

### ISSUE THREAD

**Issue by BenjaminDeleze** [cyberbotics/webots#6215]
**Describe the Bug**
The backward mechanism is working quite well for `Pose`/`Transform`.
However there is some cases where some objects are not displayed correctly:
![complete_apartment](https://github.com/cyberbotics/webots/assets/25938827/de6ccbd7-16e2-47ee-b356-7ac322d5d4fe)

Is it an acceptable degree of backward compatibility?

**Comment by omichel** [comment]
That's odd. Why are we getting this?

**Comment by BenjaminDeleze** [comment]
I still need to investigate

**Comment by BenjaminDeleze** [comment]
It happens because, as I am loading a world from R2023a, it loads the `Toilet.proto` from R2023a that is something like:
```
Solid {
    translation IS translation
    rotation IS rotation
    scale 0.2 0.2 0.2
    name IS name
    children [
       ...
    ]
  ...
```

So when loading it in R2023b, we skip the scale field of the Solid and so the toilets are huge.

I don't think we can really do something about it.
