### ISSUE TITLE
Issue on virtual machine

### ISSUE THREAD

**Issue by BenjaminDeleze** [cyberbotics/webots#6236]
**Describe the Bug**
I am testing R2023b on a vmware ubuntu 22.04.

I saw several bugs that I could consistently reproduce on the VM but not on my desktop.

1. Bad layout rendering

The first time I load webots everytime I restart the VM, the graphical layout is partially dark. However, if I close and open it again, everything is fine. (theme independant)

2. The rotation of the 3D view does not take the picking of the mouse in account.

**Comment by stefaniapedrazzi** [comment]
I can only reproduce issue 2 on my VMs and this issue was already reported in #4717.

**Comment by BenjaminDeleze** [comment]
I cannot reproduce 1. either this morning. So this is a duplicate.
