### ISSUE TITLE
[ 2023b & 2023a & 2022b - Linux ] : Rendering view has black borders

### ISSUE THREAD

**Issue by SuperUserNameMan** [cyberbotics/webots#6256]
**Describe the Bug**
The rendering view has top and right black borders. (see screenshot)

**Steps to Reproduce**
Install 2023b or 2023a or 2022b `.deb` or `.tar.bz2`

Open any sample demo/example.

**Expected behavior**
No useless black borders.

**Screenshots**
![Capture du 2023-06-27 10-27-29](https://github.com/cyberbotics/webots/assets/9801802/36f84efe-0322-4d7b-95e5-c96bcb80f7a6)

**System**
 - Operating System: LinuxMint 21.1 Vera (based upon Ubuntu Jammy) + MATE 1.26.0
 - Graphics Card: integrated Radeon GPU that comes with the Amd Ryzen 5 5500u APU.
``` glxinfo :
    Vendor: AMD (0x1002)
    Device: RENOIR (renoir, LLVM 15.0.3, DRM 3.48, 5.15.0-75-generic) (0x164c)
    Version: 22.3.0
```

**Additional context**

**PS :** Last known version that does not show this bug is 2022a.

**Comment by SuperUserNameMan** [comment]
PS : last known version to not exhibit this black border is 2022a

**Comment by omichel** [comment]
It seems to be the same issue as #6055.
Maybe reverting [this patch](https://github.com/cyberbotics/webots/pull/5043/files) may help. Can you confirm?

**Comment by SuperUserNameMan** [comment]
Thanks for pointing me.

Alas, reverting was not enough. 

I had to force `QT_ENABLE_HIGHDPI_SCALING` to 0.

**Comment by omichel** [comment]
That probably means we need to handle your specific case for the setting `QT_ENABLE_HIGHDPI_SCALING` to 0.
Can you tell us with is the value of `XDG_CURRENT_DESKTOP` and `DPI` in your case?
Ideally, we should improve this script to take into account your specific case, as we cannot fully remove this code that would likely break other systems.

**Comment by SuperUserNameMan** [comment]
According to what I read, the MATE desktop handles HiDPI displays in a specific manner that might differs from other linux desktops.

I plugged my laptop to my 4k TV and tested with HiDPI enabled and disabled in MATE display settings.

According to my tests the patch should be :

```bash
# Fix for i3 window manager not working with Qt6
if [ "$XDG_CURRENT_DESKTOP" == "i3" ]; then
  DPI=`xrdb -query -all | grep Xft.dpi | awk '{print $2}'`
  if [[ "$DPI" -gt 96 ]]; then
    export QT_ENABLE_HIGHDPI_SCALING=0
    export QT_SCALE_FACTOR=2
    export QT_FONT_DPI=80
  fi
# Fix for MATE desktop
elif [ "$XDG_CURRENT_DESKTOP" == "MATE" ]; then
  export QT_ENABLE_HIGHDPI_SCALING=0
else
  export QT_ENABLE_HIGHDPI_SCALING=1
fi
```

Note : if a user toggles the MATE's HiDPI setting during a session, it is required to disconnect from the session and login again (else, Qt6 or webot will not take the new setting into account).
