### ISSUE TITLE
What is the difference between WbAxisAngle and WbRotation?

### ISSUE THREAD

**Issue by stefaniapedrazzi** [cyberbotics/webots#6298]
Both classes seem to represent a rotation in axis-angle format.
`WbAxisAngle` class has been introduced in Webots R2021a and it is used only by the `WbInertialUnit` class.
Why do we need two classes for this?

Note also that the code for converting a matrix to axis-angle seems to be duplicated in `WbRotation::fromMatrix3` and `WbMatrix3::toAxisAngle`.

**Comment by omichel** [comment]
Yes, some clean-up is probably needed here.

**Comment by stefaniapedrazzi** [comment]
I checked just to make sure that both the methods to compute the axis-angle give the same result and they are equivalent.
