### ISSUE TITLE
 'Virtual Reality Headset' failed to work

### ISSUE THREAD

**Issue by Shane-l-z** [cyberbotics/webots#6306]
**Describe the Bug**
When the 'Virtual Reality Headset' was enabled, VR equipment didn't display the scene of Webots.
Besides, the steamVR showed high latency: about 30.0 of 11.1ms(90Hz)

**Steps to Reproduce**
1. Open the file 'Boomer.wbt'
2. Click on 'View'
3. Scroll down to 'Virtual Reality Headset'
4. Click on 'enable'

**Screenshots**
![image](https://github.com/cyberbotics/webots/assets/109288485/921b7ecb-2bbe-4b7b-80b3-20cdc8b331ac)

**System**
VR：VIVE Pro2
plugin: steamVR
Webots version: R2022b

**Comment by ygoumaz** [comment]
Duplicate with https://github.com/cyberbotics/webots/issues/747 and #5690.
