### ISSUE TITLE
When I use the animationStartRecordingAPI, webots view cannot be used

### ISSUE THREAD

**Issue by HEFUHUI** [cyberbotics/webots#6336]
**Describe the Bug**
I use WebotsView to view the robot's motion. When I start animationStartRecording from Python, the webots-view cannot view the animation, but the simulation time continues. Sometimes, a time style of **0-1:59:56:672** may appear, which is normal in the webotsGUI

**Steps to Reproduce**
1. Start webots stream batch normally
2. Open the Streaming Viewer
3. Using Python controllers
4. `from controller import Robot, supervisor
robot = supervisor.Supervisor()

motor = robot.getDevice("wheel0_motor")
motor1 = robot.getDevice("wheel1_motor")
motor.setPosition(float('inf'))
motor1.setPosition(float('inf'))

robot.exportImage("/home/hg/test/1.jpg", 100)
robot.animationStartRecording("/home/hg/test/index.html")
i = 0
while robot.step() != -1:
    i += 1
    if i > 100:
        break
    motor.setVelocity(-100)
    motor1.setVelocity(-100)

robot.animationStopRecording()
`
5. See Error

**System**
 - Operating System: ubuntu 22.04
 - Graphics Card: GTX 2660Spuer

**Comment by BenjaminDeleze** [comment]
Currently you cannot export an animation and stream the world at the same time.

So to record an animation you need to launch Webots without the `--stream` option (you do not need the streaming viewer as well)

Also you shoud use the `robot.animationStopRecording` function to cleanly end the recording of the animation.
