### ISSUE TITLE
Webots can not import vehicles which are generated by SUMO

### ISSUE THREAD

**Issue by Growing1000** [cyberbotics/webots#6340]
**When I opened my wbt document, the SUMO started to run, but Webots can not import vehicles. Here are error reports.**

`ERROR: In order to import the PROTO 'CitroenCZeroSimple', first it must be declared in the IMPORTABLE EXTERNPROTO list.
ERROR: In order to import the PROTO 'TeslaModel3Simple', first it must be declared in the IMPORTABLE EXTERNPROTO list.
ERROR: In order to import the PROTO 'TeslaModel3Simple', first it must be declared in the IMPORTABLE EXTERNPROTO list.
...`

 **However, those examples like sumo_interface_example.wbt and highway_overtake.wbt can add vehicles automatically on my computer.**

**Comment by omichel** [comment]
You should simply add [these lines](https://github.com/cyberbotics/webots/blob/c3e94a811430bd4f70ec694efe5e37f50c7fdeee/projects/vehicles/worlds/sumo_interface_example.wbt#L12C1-L26) at the beginning of your `.wbt` world file.

**Comment by Growing1000** [comment]
Thanks for your reply. With your suggestion, the problem has been solved.
