### ISSUE TITLE
Bad version number

### ISSUE THREAD

**Issue by ShuffleWire** [cyberbotics/webots#6341]
I've notice two things about version number : 

Many are not accurate : in R2023b, there are still many reference to R2023a, and even in translation there are wrong link pointing to the upgrade path from R2022a to R2022b
`<source>Please adapt your project to R2023a following these instructions: https://cyberbotics.com/doc/guide/from-2022a-to-2022b</source>`

I think we should update those, but I don't know on which version to start doing so, and ensuring that next version will still follows the right pattern.

**Comment by omichel** [comment]
Thank you for reporting this.
You should fix it on the master branch and it will be back-ported to the develop branch afterwards.
