### ISSUE TITLE
Strange jump in value outputed by Lidar

### ISSUE THREAD

**Issue by ShuffleWire** [cyberbotics/webots#6344]
**Describe the Bug**
Using this world,
[lidar_jump_in_values.zip](https://github.com/cyberbotics/webots/files/12170331/lidar_jump_in_values.zip)

I get that : 
![lidar](https://github.com/cyberbotics/webots/assets/83014015/73e406f1-e18a-42d6-90c9-3954c13c410f)
with those weird jumps.
Displaying the raw depth values show the same issue : 
![image](https://github.com/cyberbotics/webots/assets/83014015/cdea7a3a-7c01-479b-b5df-e3d0dfc89fdf)

Moreover, looking closely, the points are not on the plane... 
![image](https://github.com/cyberbotics/webots/assets/83014015/ff0ed3d8-e293-4c91-9353-63c8413d4069)
in fact, probing computed values from inside Webots show that they are between 2 and 5cm bellow the plane, which is a lot.

I initially thought that the depth buffer was missing resolution, and truncating value, but the outputted value are far from that, and reading the code i understand that the z-buffer is in float, so that should be ok

**Expected behavior**
I would expect to get a smooth curve.

**System**
 - Operating System: Debian 11
 - Graphics Card: GTX 1650
 - Webots 2023b

**Comment by omichel** [comment]
Fixed in #6417.
