### ISSUE TITLE
how to add DEF to the world

### ISSUE THREAD

**Issue by GerardHarkemaAvans** [cyberbotics/webots#6372]
how to add DEF to the world

_Originally posted by @kadirou31 in https://github.com/cyberbotics/webots/issues/6174#issuecomment-1580210590_

**Comment by GerardHarkemaAvans** [comment]
Top Thanks

**Comment by GerardHarkemaAvans** [comment]
Closed

**Comment by ShuffleWire** [comment]
Think to use the 
![image](https://github.com/cyberbotics/webots/assets/83014015/037dce81-d194-43bc-a5db-b1f55bede02f)
button next time :)
