### ISSUE TITLE
getEmitterDirection returns weird data

### ISSUE THREAD

**Issue by Adman** [cyberbotics/webots#6392]
**Describe the Bug**
`Receiver.getEmitterDirection()` returns different data than previously, `controller.field.LP_c_double object`

**Steps to Reproduce**
1. Add Emitter
2. Add Receiver
3. Send data from emitter to receiver
4. Call `getEmitterDirection` from receiver device

**Expected behavior**
A list of three doubles (floats) should be returned, but `controller.field.LP_c_double object` is returned instead. (Should I extract the list of values from that object somehow?)

**System**
 - Operating System: Linux Ubuntu 20.04
 - Webots: R2023b. (On R2022a it worked fine)

**Additional context**

**Comment by omichel** [comment]
[Here](https://github.com/cyberbotics/webots/blob/0e1ab73a2806067c621946cf45964f4a1ad9c17d/lib/controller/python/controller/receiver.py#L26) is the source code where this is computed. Can you try to find a fix for this?
