### ISSUE TITLE
Wrong relative Position of objects in recognition by spherical cameras with pi/2 < fov < pi .

### ISSUE THREAD

**Issue by TheMangalex** [cyberbotics/webots#6395]
**Describe the Bug**
Hello everyone, I have noticed some problems with recognition objects in spherical cameras:

The position of an object in a recognition with a spherical camera becomes wrong if the center of the object/or a bigger part of it isn't  in the camera frustum anymore. This happens for fovs < pi. For fov > pi this seems to be fine. (Tested with fov of 2.14 and 3.0)
The wrong object positions during this projection force wrong bounding boxes and a wrong position in the webots_ros/RecognitionObjects Message.

Potential reason might be the mIsOmniDirectional bool in WbObjectDetection. 
The header has the annotation
`bool mIsOmniDirectional;  // is sensor omnidirectional (horizontal FOV < PI/2)`    (https://github.com/cyberbotics/webots/blob/master/src/webots/nodes/utils/WbObjectDetection.hpp#L101 )
The cpp file implements it with
`mIsOmniDirectional(mHorizontalFieldOfView > M_PI),`   (https://github.com/cyberbotics/webots/blob/master/src/webots/nodes/utils/WbObjectDetection.cpp#L40).

Changing this line to 
`mIsOmniDirectional(mHorizontalFieldOfView > M_PI / 2.0),`
lets it look correct for me, but I'm unsure if it is correct in all cases or just the two I tested.

I have some screenshots showing the problem and how it looks fixed attached below:

**Steps to Reproduce**
1. Use a spherical camera with fov between pi/2.0 and pi
2. Put an object close to the view frustum corner so that parts of it are outside it and parts are inside (as seen in the screenshots)
3. Use a recognition image/ros message
4. You can see the bounding box corners being wrong/the object position and other values being wrong

**Expected behavior**
The bounding box should match the recognition and the recognized object position should be correct. See screenshots below

**Screenshots**
Fov 2.14 before
<img width="374" alt="fov2 14-wrong" src="https://github.com/cyberbotics/webots/assets/26520790/c5196c52-31d6-4d6c-aed7-82e114db4034">

Fov 3.0 before
<img width="374" alt="webots-fov-3-wrong" src="https://github.com/cyberbotics/webots/assets/26520790/b69da7f9-80af-4a41-b93e-9aa7110699b8">

Fov 2.14 after adjustments
<img width="374" alt="webots-fov-2 14-adjusted" src="https://github.com/cyberbotics/webots/assets/26520790/9d8af0be-0c96-4156-9473-2a663b484fd1">

Fov 3.0 after adjustments
<img width="374" alt="webots-fov-3-adjusted" src="https://github.com/cyberbotics/webots/assets/26520790/29f7593b-720c-4253-aa38-127a20f77697">

**System**
 - Operating System: [Ubuntu 20.04 (Ros Noetic for Ros Messages)]

**Comment by omichel** [comment]
Your patch seems good to me. Please open new Pull Request to propose your fix for this problem.

**Comment by TheMangalex** [comment]
I opened PR #6396 for you.
