### ISSUE TITLE
The maximum distance that proximity sensor IR can calculate

### ISSUE THREAD

**Issue by ali1hammoud** [cyberbotics/webots#6410]
### Discussed in https://github.com/cyberbotics/webots/discussions/6409

<div type='discussions-op-text'>

<sup>Originally posted by **ali1hammoud** October  9, 2023</sup>
What is the maximum distance that proximity sensor IR can calculate?
according to the doc, we can change the distance in Lookup Table, I used E-puck robot, converted it to base node, and changed the values in lookup table as:
[[0.0e+00 3.0e+03 0.0e+00]
 [1.0e-01 2.0e+03 0.0e+00]
 [2.5e-01 1.0e+03 0.0e+00]
 [1.0e+00 0.0e+00 0.0e+00]]
So, the sensor will return 0 for 1 m and 3000 for 0 m.
I changed the redColorSensitivity to zero.

Then I started the simulation and got the values and found that the sensor will give me 0.0 from distance 0.417 m to 1 m, and 772 in 0.416.
The distance 0.416 is the maximum distance that the sensor can reach and sense, I searched to find the function in code that responsible to calculate the distance in simulation, but I couldn't find it, I searched in doc about the equation that represents the value of sensor reading, I couldn't find it either, the only thing I found the reflection factor as follows: f = 0.2 + 0.8 * red_level * (1 - 0.5 * roughness) * (1 - 0.5 * occlusion).

My question is 0.416 is the maximum distance can IR sensor sense? if not, what is the maximum distance, and what is the equation or function in code that return the reading value?
</div>

**Comment by omichel** [comment]
Please don't cross-post in both discussions and issues.
