### ISSUE TITLE
symbol lookup error: ./bin/webots-bin: undefined symbol: dFluidSetViscosity

### ISSUE THREAD

**Issue by sangshuduo** [cyberbotics/webots#6439]
**Describe the Bug**
# ./bin/webots-bin
./bin/webots-bin: symbol lookup error: ./bin/webots-bin: undefined symbol: dFluidSetViscosity

**Steps to Reproduce**
1. git clone webots
2. git submodule update --init --recursive
3. ./scripts/install/linux_compilation_dependencies.sh
4. make -j
5. ./bin/webots-bin

**System**
 - Operating System: Ubuntu 20.04 running in Docker
 - Graphics Card: 3050Ti

**Additional context**
# ldd bin/webots-bin
	linux-vdso.so.1 (0x00007ffeaa1bb000)
	libQt6Core.so.6 => /root/webots/lib/webots/libQt6Core.so.6 (0x00007fc1e512e000)
	libQt6Network.so.6 => /root/webots/lib/webots/libQt6Network.so.6 (0x00007fc1e4f85000)
	libQt6Gui.so.6 => /root/webots/lib/webots/libQt6Gui.so.6 (0x00007fc1e45dc000)
	libQt6OpenGL.so.6 => /root/webots/lib/webots/libQt6OpenGL.so.6 (0x00007fc1e453d000)
	libQt6OpenGLWidgets.so.6 => /root/webots/lib/webots/libQt6OpenGLWidgets.so.6 (0x00007fc1e4530000)
	libQt6WebSockets.so.6 => /root/webots/lib/webots/libQt6WebSockets.so.6 (0x00007fc1e44fd000)
	libQt6Widgets.so.6 => /root/webots/lib/webots/libQt6Widgets.so.6 (0x00007fc1e3dcb000)
	libQt6PrintSupport.so.6 => /root/webots/lib/webots/libQt6PrintSupport.so.6 (0x00007fc1e3d4f000)
	libQt6Qml.so.6 => /root/webots/lib/webots/libQt6Qml.so.6 (0x00007fc1e37e1000)
	libQt6Xml.so.6 => /root/webots/lib/webots/libQt6Xml.so.6 (0x00007fc1e37ba000)
	libopenal.so.1 => /usr/lib/x86_64-linux-gnu/libopenal.so.1 (0x00007fc1e36d2000)
	libGL.so.1 => /usr/lib/x86_64-linux-gnu/libGL.so.1 (0x00007fc1e3648000)
	libGLU.so.1 => /usr/lib/x86_64-linux-gnu/libGLU.so.1 (0x00007fc1e35d6000)
	libdl.so.2 => /usr/lib/x86_64-linux-gnu/libdl.so.2 (0x00007fc1e35d0000)
	libOIS-1.4.0.so => /root/webots/lib/webots/libOIS-1.4.0.so (0x00007fc1e33af000)
	libpico.so => /root/webots/lib/webots/libpico.so (0x00007fc1e313e000)
	libfreetype.so.6 => /usr/lib/x86_64-linux-gnu/libfreetype.so.6 (0x00007fc1e307f000)
	libassimp.so.5 => /usr/lib/x86_64-linux-gnu/libassimp.so.5 (0x00007fc1e2430000)
	libode.so => /usr/lib/x86_64-linux-gnu/libode.so (0x00007fc1e230c000)
	libpthread.so.0 => /usr/lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fc1e22e9000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007fc1e2107000)
	libm.so.6 => /usr/lib/x86_64-linux-gnu/libm.so.6 (0x00007fc1e1fb8000)
	libgcc_s.so.1 => /usr/lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fc1e1f9d000)
	libc.so.6 => /usr/lib/x86_64-linux-gnu/libc.so.6 (0x00007fc1e1da9000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fc1e6026000)
	libicui18n.so.56 => /root/webots/lib/webots/libicui18n.so.56 (0x00007fc1e1910000)
	libicuuc.so.56 => /root/webots/lib/webots/libicuuc.so.56 (0x00007fc1e1558000)
	libicudata.so.56 => /root/webots/lib/webots/libicudata.so.56 (0x00007fc1dfb75000)
	libglib-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0 (0x00007fc1dfa4b000)
	libz.so.1 => /usr/lib/x86_64-linux-gnu/libz.so.1 (0x00007fc1dfa2f000)
	libgthread-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libgthread-2.0.so.0 (0x00007fc1dfa28000)
	librt.so.1 => /usr/lib/x86_64-linux-gnu/librt.so.1 (0x00007fc1dfa1e000)
	libgssapi_krb5.so.2 => /usr/lib/x86_64-linux-gnu/libgssapi_krb5.so.2 (0x00007fc1df9d1000)
	libEGL.so.1 => /usr/lib/x86_64-linux-gnu/libEGL.so.1 (0x00007fc1df9bc000)
	libfontconfig.so.1 => /usr/lib/x86_64-linux-gnu/libfontconfig.so.1 (0x00007fc1df975000)
	libX11.so.6 => /usr/lib/x86_64-linux-gnu/libX11.so.6 (0x00007fc1df836000)
	libQt6DBus.so.6 => /root/webots/lib/webots/libQt6DBus.so.6 (0x00007fc1df772000)
	libxkbcommon.so.0 => /usr/lib/x86_64-linux-gnu/libxkbcommon.so.0 (0x00007fc1df730000)
	libsndio.so.7.0 => /usr/lib/x86_64-linux-gnu/libsndio.so.7.0 (0x00007fc1df71f000)
	libGLdispatch.so.0 => /usr/lib/x86_64-linux-gnu/libGLdispatch.so.0 (0x00007fc1df667000)
	libGLX.so.0 => /usr/lib/x86_64-linux-gnu/libGLX.so.0 (0x00007fc1df631000)
	libpng16.so.16 => /usr/lib/x86_64-linux-gnu/libpng16.so.16 (0x00007fc1df5f9000)
	libminizip.so.1 => /usr/lib/x86_64-linux-gnu/libminizip.so.1 (0x00007fc1df3ee000)
	libccd.so.2 => /usr/lib/x86_64-linux-gnu/libccd.so.2 (0x00007fc1df3e2000)
	libpcre.so.3 => /usr/lib/x86_64-linux-gnu/libpcre.so.3 (0x00007fc1df36f000)
	libkrb5.so.3 => /usr/lib/x86_64-linux-gnu/libkrb5.so.3 (0x00007fc1df292000)
	libk5crypto.so.3 => /usr/lib/x86_64-linux-gnu/libk5crypto.so.3 (0x00007fc1df25f000)
	libcom_err.so.2 => /usr/lib/x86_64-linux-gnu/libcom_err.so.2 (0x00007fc1df258000)
	libkrb5support.so.0 => /usr/lib/x86_64-linux-gnu/libkrb5support.so.0 (0x00007fc1df249000)
	libexpat.so.1 => /usr/lib/x86_64-linux-gnu/libexpat.so.1 (0x00007fc1df21b000)
	libuuid.so.1 => /usr/lib/x86_64-linux-gnu/libuuid.so.1 (0x00007fc1df212000)
	libxcb.so.1 => /usr/lib/x86_64-linux-gnu/libxcb.so.1 (0x00007fc1df1e8000)
	libdbus-1.so.3 => /usr/lib/x86_64-linux-gnu/libdbus-1.so.3 (0x00007fc1df195000)
	libasound.so.2 => /usr/lib/x86_64-linux-gnu/libasound.so.2 (0x00007fc1df09a000)
	libbsd.so.0 => /usr/lib/x86_64-linux-gnu/libbsd.so.0 (0x00007fc1df080000)
	libkeyutils.so.1 => /usr/lib/x86_64-linux-gnu/libkeyutils.so.1 (0x00007fc1df079000)
	libresolv.so.2 => /usr/lib/x86_64-linux-gnu/libresolv.so.2 (0x00007fc1df05d000)
	libXau.so.6 => /usr/lib/x86_64-linux-gnu/libXau.so.6 (0x00007fc1df055000)
	libXdmcp.so.6 => /usr/lib/x86_64-linux-gnu/libXdmcp.so.6 (0x00007fc1df04d000)
	libsystemd.so.0 => /usr/lib/x86_64-linux-gnu/libsystemd.so.0 (0x00007fc1def9e000)
	liblzma.so.5 => /usr/lib/x86_64-linux-gnu/liblzma.so.5 (0x00007fc1def75000)
	liblz4.so.1 => /usr/lib/x86_64-linux-gnu/liblz4.so.1 (0x00007fc1def54000)
	libgcrypt.so.20 => /usr/lib/x86_64-linux-gnu/libgcrypt.so.20 (0x00007fc1dee34000)
	libgpg-error.so.0 => /usr/lib/x86_64-linux-gnu/libgpg-error.so.0 (0x00007fc1dee11000)

**Comment by omichel** [comment]
You shouldn't start Webots by launching the binary directly, instead, you should start Webots using the launcher by typing: `./webots` instead of `./bin/webots-bin`. Make should copy the [Webots launcher](https://github.com/cyberbotics/webots/blob/master/src/webots/launcher/webots-linux.sh) to `./webots` and this launcher should be used to start Webots, as it takes care of many settings necessary for Webots to run properly.
