### ISSUE TITLE
E-Puck Documentation Issue

### ISSUE THREAD

**Issue by anirjoshi** [cyberbotics/webots#6451]
**Describe the Bug**
There seems to be an issue in the E-Puck characteristics table [here](https://www.cyberbotics.com/doc/guide/epuck?version=R2021a#e-puck-characteristics). Also, the report issue link from the documentation which is [link](https://github.com/cyberbotics/webots/edit/master/docs/guide/epuck.md) is not working. 

**Steps to Reproduce**
The issue is with the inconsistency with the speed of the E-Puck robot as mentioned in the table  [here](https://www.cyberbotics.com/doc/guide/epuck?version=R2021a#e-puck-characteristics). The speed is given as 6.28 rad/s which should be same as 6.28*radius m/s, that evaluates to 6.28*0.0205 m/s = 0.12874 m/s, but the max speed is reported as 0.25m/s there. Is there an issue with the documentation or is there any issue with the calculation of the speed?

**Expected behavior**
Either the speed or the radius should change appropriately.

**Screenshots**
<img width="896" alt="image" src="https://github.com/cyberbotics/webots/assets/45450979/3444f6d0-be39-4674-b2e2-bbcedd58ffcc">

**Comment by omichel** [comment]
I believe this was fixed, see #6444 and #6447.
