### ISSUE TITLE
Windows: Webots crashes if installed in user folder with non-ASCII characters

### ISSUE THREAD

**Issue by omichel** [cyberbotics/webots#649]
If Webots is installed locally (not as administrator) on Windows and the user home path contains non-ASCII characters (Chinese characters for example), then Webots crashes at start-up. However, this is not a regression and I believe many applications have the same problem. Nevertheless, we are probably not far away from a working solution because Webots is actually started, displays the splash screen, main window, then crashes...

**Comment by DavidMansolino** [comment]
> Nevertheless, we are probably not far away from a working solution because Webots is actually started, displays the splash screen, main window, then crashes...

This sentence is contradictory with the `wontfix` tag.
In any case, I believe we should either fix it either document it in the known bugs and/or installation instructions and close this isue.

**Comment by fabienrohrer** [comment]
By the way, would it be possible to test this in innosetup and do not propose this path in case of problems?

**Comment by DavidMansolino** [comment]
That's indeed an interesting solution to investigate.

**Comment by BenjaminDeleze** [comment]
@omichel did #5103 fix this?

**Comment by omichel** [comment]
Yes, it actually fixed it.
