### ISSUE TITLE
When i open empty.wbt it did not open blockly when i have it insalled.

### ISSUE THREAD

**Issue by FireCreator418** [cyberbotics/webots#6532]

**Comment by ShuffleWire** [comment]
Please provide more detailed info on your setup (OS, webots...) The step you took and what is the result you expect to get.

And first, what is blockly ?

**Comment by FireCreator418** [comment]
> Please provide more detailed info on your setup (OS, webots...) The step you took and what is the result you expect to get.
> 
> And first, what is blockly ?

Blockly is block base and it’s for making webots easy.
And i just want to ask do you use a progaming language?
If you do just tell me.

**Comment by ShuffleWire** [comment]
Yes I'm using C/C++/Python

I'm not familiar with Blockly, nor how it's supposed to work, but please share a world that should work but don't.

**Comment by ShuffleWire** [comment]
Ok I got the same issue : So for a repeatable path : 
1) git clone https://github.com/anadiedrichs/drone-deep-rl.git
2) Open the world empty.wbt in webots
3) We should get the same windows as https://youtu.be/bWE3aRRMNLY?t=356
![image](https://github.com/cyberbotics/webots/assets/83014015/7b07c960-e918-4c0d-afda-faa9eb9102a6)
But we are not.
I'm running Webots 2024a Build 15/2/2024, on Debian 12

Thing to note : AFAIK this plugins is made for Webots R2021a, so It might be expected to not work anymore.

**Solution :** 
On the tree, Find the Robot "robot" node, right click, and Select "Show robot windows"
Say me if it work for you

**Comment by FireCreator418** [comment]
Thanx!
