### ISSUE TITLE
ImportError: cannot import name 'Robot' from 'controller' 

### ISSUE THREAD

**Issue by AlanMelgarF** [cyberbotics/webots#6545]
**Describe the Bug**
I have a problem when I want to run the executable .py on the launch. I'm currently working on ROS and when I try to run the launch it says that the library Robot cannot be imported

Traceback (most recent call last):
  File "/home/user/catkin_ws/src/webots_ros/controllers/drive_1/drive_1.py", line 4, in <module>
    from controller import Robot
ImportError: cannot import name 'Robot' from 'controller' (/home/user/.local/lib/python3.8/site-packages/controller/__init__.py)
[webots_ros_python-3] process has died [pid 9285, exit code 1, cmd /home/user/catkin_ws/src/webots_ros/controllers/drive_1/drive_1.py __name:=webots_ros_python __log:=/home/user/.ros/log/00039720-08e7-11ef-9ebc-8dc438824077/webots_ros_python-3.log].
log file: /home/user/.ros/log/00039720-08e7-11ef-9ebc-8dc438824077/webots_ros_python-3*.log

**Comment by lukicdarkoo** [comment]
It looks like it loads the wrong controller library (`/home/user/.local/lib/python3.8/site-packages/controller/init.py`). There are two possible causes:
- Your `controller` Python library has been found first by Python. You will need to delete the `controller` package.
- Webots client library is not sourced. Check here: https://github.com/cyberbotics/webots_ros/blob/a4c93300e1528ac4f8fbf5cb7c3ecee63ff69784/launch/webots_ros_python.launch#L12-L14
