### ISSUE TITLE
webots.min.js: frameBuffers does not goes beyond 1.0

### ISSUE THREAD

**Issue by fabienrohrer** [cyberbotics/webots#657]
In the contrary of the Webots rendering pipeline, the frame buffers cannot exceed 1.0 rendering useless the use of HDR backgrounds and over-saturated lights.

For sure the format is currently Uint8 RGB(A?), but this is certainly not only a matter to use floats.

One should investigate more in this direction to be able to replicate nice sparkling we can do in Webots.

**Comment by omichel** [comment]
We are going to drop the three.js implementation of webots.js to replace with with wren.js which should resolve this problem.
