### ISSUE TITLE
Omni wheels rollers rotating direction

### ISSUE THREAD

**Issue by holmesvinn** [cyberbotics/webots#6616]
**Describe the Bug**
Omni wheeled robot in webots sample project is having issue with the rollers rotation. its rotating along wrong axis

**Steps to Reproduce**
1. Go to File -> Open Sample World
2. search for Omni
3. select the omni_wheels.wbt

**Screenshots**
![image](https://github.com/user-attachments/assets/57d21668-d8b9-4248-ac8e-e877cb2f96cb)

can someone pls help how to fix this?

**Comment by lukicdarkoo** [comment]
@MNikoliCC Can you take a look? I have just tested and the bug is also present in R2024a

**Comment by MNikoliCC** [comment]
The referenced PR should resolve the issue.
