### ISSUE TITLE
Transform and revolute the bounding object in Webots

### ISSUE THREAD

**Issue by OTT123** [cyberbotics/webots#6669]
**Describe the Bug**
[A clear and concise description of what the bug is.](https://stackoverflow.com/questions/79023007/transform-and-revolute-the-bounding-object-in-webots)

**System**
 - Operating System: ubuntu20.04, webots 2023b

**Comment by lukicdarkoo** [comment]
This issue should go to the urdf2webots. Please open a new issue there with the URDF sample (as stated on StackOverflow) so we can debug.
