### ISSUE TITLE
The arena is not shown in when a new project was opened

### ISSUE THREAD

**Issue by ImeshTibbotuwawa** [cyberbotics/webots#6674]
When a new project is opened, the arean will no be appear . and following error will shown.
My system is,
windows 11
i9 processor
64gb ram 
rtx4090
<img width="1280" alt="Screenshot 2024-10-11 111518" src="https://github.com/user-attachments/assets/ed395259-e683-4ef9-8747-2448aefcc777">

**Comment by ShuffleWire** [comment]
99 is UnknownNetworkError, that is not saying much...
could you download it manually from your browser, by visiting those URL ?
