### ISSUE TITLE
Simulation is not showing

### ISSUE THREAD

**Issue by SuperPogo2000** [cyberbotics/webots#6700]
**Describe the Bug**

**Steps to Reproduce**

**Expected behavior**

**Screenshots**

**System**
 - Operating System: [e.g., Windows 10, Linux Ubuntu 18.04, macOS Mojave]
 - Graphics Card: [e.g., NVIDIA GeForce RTX 2080 11 GB, AMD Radeon RX 580 8GB, etc.]

**Additional context**

**Comment by lukicdarkoo** [comment]
We are missing a lot of context here. Please fill out the issue template.

I will reopen the issue once more info is provided
