### ISSUE TITLE
Mac Senoqia  15.1 Python not support 

### ISSUE THREAD

**Issue by harunkurtdev** [cyberbotics/webots#6703]
**Describe the Bug**

WARNING: Python was not found.
To fix the problem, you should set the full path of your python command in Webots->preferences->python command.
INFO: ardupilot_vehicle_controller: Starting controller: 
WARNING: ardupilot_vehicle_controller: failed to start: 
WARNING: Unable to find the 'python' executable in the current PATH. Please check your python installation. It should be possible to launch python from a terminal by typing 'python'. It may be necessary to add the python bin directory to your PATH environment variable. More information about the python installation is available in Webots' User guide.

I downloaded ROS2 jazzy for macOS but not working with python3 support

**Screenshots**
![Ekran Resmi 2024-11-17 18 39 04](https://github.com/user-attachments/assets/db5fcaca-c1e1-4056-8a46-32620d2a4c97)

**System**
 - Operating System: macOS senoqia M3

**Comment by harunkurtdev** [comment]
here a another example

![Ekran Resmi 2024-11-17 18 42 28](https://github.com/user-attachments/assets/d858ced0-341a-4fb6-b11d-466c6b635623)

**Comment by lukicdarkoo** [comment]
@harunkurtdev What do you get when you run `/Users/harunkurtdev/.pyenv/shims/python3 --version`?

**Comment by harunkurtdev** [comment]
Mr. @lukicdarkoo, it is showing  `Python 3.10.12`.

**Comment by harunkurtdev** [comment]
okey sir I solve, I mistake a little.
