### ISSUE TITLE
Bug in webots/projects/languages/python/worlds/example.wbt world

### ISSUE THREAD

**Issue by MNikoliCC** [cyberbotics/webots#6707]
**Describe the Bug**
When running the simulation the error message appears: _Error: wb_supervisor_field_get_type() called with invalid 'field' argument._

**Steps to Reproduce**
1. Open the webots/projects/languages/python/worlds/example.wbt world
2. Run the simulation
3. In the console see the error: _Error: wb_supervisor_field_get_type() called with invalid 'field' argument._

**Expected behavior**
No error messages.

**System**
 - Operating System:  Linux Ubuntu 22.04, Webots installed from debian package directly
 - Graphics Card: [RENOIR (renoir, LLVM 15.0.7, DRM 3.57, 6.8.0-49-generic)]

**Additional context**
The line at which the error appears:
https://github.com/cyberbotics/webots/blob/1ad0a694f6ab2bfabb7be1e0a0414b878bc4f51b/projects/languages/python/controllers/driver/driver.py#L35

**Comment by lukicdarkoo** [comment]
It seems the PR close hook didn't work.

The issue is solved in #6708
