### ISSUE TITLE
Qt 6 tooltip text is not visible

### ISSUE THREAD

**Issue by MNikoliCC** [cyberbotics/webots#6709]
**Describe the Bug**
When covering the buttons of the Webots GUI, the text that describes the functionality of the button is not visible.

**Steps to Reproduce**
1. Start a Webots simulation
2. Cover one of the buttons in the GUI with your cursor (for example the "Reload").

**Expected behavior**
Text should appear clearly and visible.

**Screenshots**
![GUI bug](https://github.com/user-attachments/assets/5325c8f9-cf00-43fb-b6d1-7b3d4f446bf3)

**System**
 - Operating System: Linux Ubuntu 22.04
 - Graphics Card: RENOIR (renoir, LLVM 15.0.7, DRM 3.57, 6.8.0-49-generic)

**Comment by lukicdarkoo** [comment]
Fixed in #6711
