### ISSUE TITLE
supervisor_start_stop_movie test and mirror_supervisor failures

### ISSUE THREAD

**Issue by DavidMansolino** [cyberbotics/webots#742]
The `supervisor_start_stop_movie` test is failing on the `revision` branch (both locally and on travis).

**System**
 - Operating System: Linux Ubuntu 16.04

**Comment by DavidMansolino** [comment]
I am now not able to reproduce it anymore, it fails only at the first run.

**Comment by DavidMansolino** [comment]
I can't reproduce this on Travis either (I restarted the test and it succeeded).
Let's see if it fails again during one of the nightly.

**Comment by DavidMansolino** [comment]
The following test is also sometime failing:
> FAILURE with mirror_supervisor: The white color of the mirror image in the 3D scene is wrong.

https://travis-ci.com/omichel/webots/builds/120988174

**Comment by fabienrohrer** [comment]
Until proven otherwise, `start_stop_movie` issues doesn't occur anymore, and `mirror_supervisor` has been fixed here #1083.
