### ISSUE TITLE
webots.min.js: roughness and metalness does not act the same in threejs and in wren

### ISSUE THREAD

**Issue by fabienrohrer** [cyberbotics/webots#743]
wren and threejs management of roughness and metalness differ:

| Parameter | wren | threejs |
| --- | --- | --- |
| When metalness is close to 0 | Reflects the environment map color | :heavy_exclamation_mark: Does not reflects the environment map color (colors fade to a grey scale rendering) |
| When metalness is close to 1 | *reference* | :white_check_mark: The rendering matches |
| When roughness is close to 0 | *reference* | :white_check_mark: The rendering matches |
| When roughness is close to 1 | *reference* | :heavy_exclamation_mark: Materials capture more environ map intensity |

Unfortunately 80% of our materials are close to the problematic parameters.
This is particularly visible on textured materials with a roughness of 0 (like grounds).

**Comment by BenjaminDeleze** [comment]
Fixed in #2769
