### ISSUE TITLE
webots.min.js: rendering issues on some systems

### ISSUE THREAD

**Issue by stefaniapedrazzi** [cyberbotics/webots#752]
On my Linux desktop I get some issues when rendering specific objects, for example:
* `TruckSimple` in the `highway_driving` benchmark
![Screenshot from 2019-07-25 11-20-03](https://user-images.githubusercontent.com/5910449/61863453-e9791280-aecf-11e9-9327-44d740b6010e.png)

* both `BungalowStyleHouse` objects in the `humanoid_marathon`
![Screenshot from 2019-07-25 11-10-13](https://user-images.githubusercontent.com/5910449/61863458-ed0c9980-aecf-11e9-8ddc-31d3f535471e.png)

I tested both on Chrome and Firefox and I get the same issue.
The black dots are visible both the in the robotbenchmark animation and simulation.

@fabienrohrer tested on his macOS Chrome/Firefox and works correctly.

 - Operating System: Linux Ubuntu 18.04
 - Graphics Card: NVIDIA GeForce RTX 2060 6 GB

**Comment by stefaniapedrazzi** [comment]
I tried to check if it was a Z-fighting issue and I enabled the logarithmic depth buffer, increased the camera near value and decreased the far value but none of these changes solved the issue.

**Comment by stefaniapedrazzi** [comment]
This issue is also visible with the Door object, so I could easily simplify the world:
this is related to IndexedFaceSet (TexturedBox or any simple cube) and the PBRAppearances.normalMap.

**Comment by stefaniapedrazzi** [comment]
This seems to be due to texture mapping.
Default IFS texture mapping shows the texture on "front"/"back" faces and the border value is copied along the whole side faces.
I get the issue on the side faces.
But if I set a custom texture mapping where an area (and not a line) of the texture is shown on each face then it works fine without black artifacts.

**Comment by DavidMansolino** [comment]
I can reproduce the exact same problem:
```
System: Linux 4.4.0-157-generic x86_64
Processor: Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz
Number of cores: 8
OpenGL vendor: NVIDIA Corporation (0x10de)
OpenGL renderer: GeForce GTX 970/PCIe/SSE2 (0x13c2)
OpenGL version: 4.5.0 NVIDIA 384.130
Firefox
```

**Comment by stefaniapedrazzi** [comment]
Just for note I reported the issue in the three.js GitHub (issue  #17559) but they are not interested in fixing it.
Here is the answer:
> Unfortunately seems to be a bug in the driver and/or device. You may want to report the issue to Nvidia instead.
