### ISSUE TITLE
animated_skin.wbt crashes on High Sierra 10.13.6

### ISSUE THREAD

**Issue by WolfgangFahl** [cyberbotics/webots#784]
**Describe the Bug**
Trying to run animated_skin.wbt (e.g. as part of guided tour) crashes Webot application.

**Steps to Reproduce**
1. Start Webots guided tour 
2. Click next until animated_skin.wbt appears and tries to run

Alternatively load the world directly and press run button.

**Expected behavior**
No Crash. More important: do not restart animation automatically on next start - the crash can only be prevented if clicking the pause button quickly enough ...
It can also be prevented by stepping manually thru the first second and then continuing to run the simulation.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/1336221/62547517-9acf5f00-b865-11e9-800a-3c02eca0a789.png)

**System**
 - Operating System: Mac OS 10.13.6
 - Graphics Card: [Radeon RX 560.]

**Additional context**
```
./webots --sysinfo
System: Darwin 17.7.0 x86_64
Processor: Intel(R) Xeon(R) CPU           X5690  @ 3.47GHz
Number of cores: 24
OpenGL vendor: ATI Technologies Inc.
OpenGL renderer: AMD Radeon RX 560 OpenGL Engine
OpenGL version: 2.1 ATI-1.68.22
```

Crash report was sent to support@cyberbotics.com

**Comment by fabienrohrer** [comment]
I just give a try: I downloaded a fresh R2019b release, and I can run animated_skin.wbt smoothly:

![salamander](https://user-images.githubusercontent.com/866788/62551150-c1909400-b86b-11e9-8e92-acfd0e5d1fa5.gif)

I unfortunately bet again on some weirdness with your GPU.
Changing a GPU on a mac is not recommended. Are you sure that your system recognize it correctly? Is there some manipulation to do in such case?

**Comment by WolfgangFahl** [comment]
The GPU is just fine `Radeon RX 560:

  Chipsatz-Modell:	Radeon RX 560
  Typ:	GPU
  Bus:	PCIe
  Steckplatz:	Slot-1
  PCIe-Lane-Breite:	x8
  VRAM (dynamisch, maximal):	4096 MB
  Hersteller:	AMD (0x1002)
  Geräte-ID:	0x67ff
  Versions-ID:	0x00cf
  Metal:	Unterstützt, Funktionsset macOS GPUFamily1 v3`

**Comment by WolfgangFahl** [comment]
Tried the safemode today. Still crashes.

**Comment by fabienrohrer** [comment]
Thank you for your tests. We actively test Webots on several Mac with different GPUs and we still cannot reproduce your issue.

The only option I see to further investigate, is to ask you to provide us a stack of the crash. The OS generally opens a dialog box after a crash, containing the stack.

**Comment by fabienrohrer** [comment]
I explain this bug by the GPU switch. Reinstalling cleanly the OS is certainly the solution.

**Comment by WolfgangFahl** [comment]
Please reopen the bug. Why wouldn't you want to support this environment?

**Comment by fabienrohrer** [comment]
Could you confirm you modified the hardware of your computer?
