### ISSUE TITLE
webrots crash in Windows7 

### ISSUE THREAD

**Issue by lj1065** [cyberbotics/webots#794]
Every time, i run it, when it in "Finalizing nodes", it will crash, and stop working. The environment is Windows7. I  have update the GPU Driver.

**Comment by lj1065** [comment]
The error report is "webots.exe 中的 0x0000000180037fa4 处有未经处理的异常: 0xC0000005: 读取位置 0x0000000000000000 时发生访问冲突", in English is, "An unhandled exception occurred at 0x0000000180037fa4 in webots.exe: 0xC0000005: Access violation occurred while reading location 0x0000000000000000"

**Comment by DavidMansolino** [comment]
Is this occurring with every world or just one in particular?

Can you please give us the output of the `webots --sysinfo` command?

Can you please try to launch Webots in safe mode: https://cyberbotics.com/doc/guide/starting-webots#safe-mode

**Comment by lj1065** [comment]
No, it crash in the first start and every time. 
I follow your suggestiones, i launch it in safe mod, it crashed and it tell me that "webots requires OpenGL3.3 while only OpenGL 1.1 can be initialized,. please check your CPU abilites and install the latest graphics drives ...."
When I quit the safe-mode, and set the WEBOTS_SAFE_MODE to TRUE in the Environment Variables.
It does not crash anymore.
My computer has the latest AMD drive, but i do not know why it crash and why it goes well.

Thanks for your reply.

**Comment by omichel** [comment]
It seems you are missing an appropriate driver for your AMD card. It should provide an OpenGL version much better than 1.1. Can you report your exact GPU hardware and OpenGL driver version?

**Comment by lj1065** [comment]
CPU Type : Intel(R) Core(TM) i5-4210U CPU @ 1.70GHz
Windows Version : Windows 7 (Service Pack 1) (64 bit)
System Memory : 12 GB
Radeon Software Version : 19.7.5
Radeon Software Edition : Adrenalin 2019

**Comment by lj1065** [comment]
AMD Radeon R9 M275X
The version of OpenGL : 3.3.13570 Core Profile Froward-Compatible Context 0

**Comment by omichel** [comment]
Sorry, I am running out of ideas about this problem. Maybe it's a driver bug... Can you try Webots on a different machine or on the same machine with Linux?

**Comment by lj1065** [comment]
Yeah, I do not know why and the problem is solved after I  set the WEBOTS_SAFE_MODE to TRUE in the Environment Variables. It does not crash anymore. It runs well in my computer now.
Thanks for your reply.

**Comment by omichel** [comment]
The safe mode is simply disabling all advanced 3D rendering techniques. Can you try to re-enable 3D features one-by-one (from the Webots / Tools / Preferences / OpenGL) to identify which one is causing the crash?

**Comment by lj1065** [comment]
Yes, I am glad to do that. But what should i do for testing it. Please tell me.
PS : My computer has two graphics cards. The reason for the problem may be that I have not switched the right graphics card.

**Comment by DavidMansolino** [comment]
You will find the procedure to start Webots in safe mode here: https://cyberbotics.com/doc/guide/starting-webots#safe-mode

**Comment by fabienrohrer** [comment]
No feedback from the user since 3 months, not seen in other systems.

**Comment by venkateshbotta** [comment]
same problem for me also. Eventhough i changed environmental variables it is not working.please someone help me.

**Comment by DavidMansolino** [comment]
@venkateshbotta which version of Webots are you using? What do you get when you start Webots with the `--sysinfo` argument?
