### ISSUE TITLE
Spinning beach ball of death on Macos when using robot.simulationReset()

### ISSUE THREAD

**Issue by WolfgangFahl** [cyberbotics/webots#832]
**Describe the Bug**
In the inverted_pendulum benchmark example on a Desktop Webots I set E-puck supervisor to TRUE and use robot.simulationReset() in my code

**Steps to Reproduce**
1. Use the example code
2. modify it 
```
@@ -1,10 +1,12 @@
 """Sample Webots controller for the inverted pendulum benchmark."""
 
 from controller import Robot
+from controller import Supervisor
 import math
 
 # Get pointer to the robot.
-robot = Robot()
+#robot = Robot()
+robot=Supervisor()

robot.simulationReset()
```

**Expected behavior**
No Mac OS beachball of death.

**Screenshots**

**System**
 - MacOS 10.3.6
 - Graphics Card: MSI Aero ITX Radeon RX 560

**Additional context**
```
diff --git a/worlds/inverted_pendulum.wbt b/worlds/inverted_pendulum.wbt
index 7e6626f..2822fca 100644
--- a/worlds/inverted_pendulum.wbt
+++ b/worlds/inverted_pendulum.wbt
@@ -41,6 +41,7 @@ E-puck {
   translation 0 0 -0.98
   rotation 0 1 0 1.5707963
   controller "inverted_pendulum"
+  supervisor TRUE
```

**Comment by WolfgangFahl** [comment]
Workaround: save things. Restart Webots. Be happy ...

**Comment by DavidMansolino** [comment]
Have you tried using ``worldReload`` instead of ``simulationReset``?

**Comment by DavidMansolino** [comment]
I have checked both with the `worldReload` and `simulationReset` functions and both seem to work fine (on Ubuntu).
@fabienrohrer can you try on mac?

**Comment by fabienrohrer** [comment]
Thank you for this bug report, I can indeed reproduce it.

A workaround is to save the simulation at step 0 after modifying the E-puck.supervisor field and reload the simulation. Probably the node is in a bad state when changing the field from the API.

**Comment by fabienrohrer** [comment]
The infinite loop is because of this test:
https://github.com/omichel/webots/blob/revision/src/webots/nodes/WbRobot.cpp#L742 :

`((WbRobot *) this)->mSupervisor.value()` is correctly equals to `true` at this stage.
The controller is started when expected. 
The `supervisor` flag is well sent to the libController.

**Comment by DavidMansolino** [comment]
I can't reproduce the problem in the future R2020b release (develop branch) on macOS.

**Comment by WolfgangFahl** [comment]
I am looking forward to the new release ...
