### ISSUE TITLE
Wheel-to-Terrain Contact Interaction at Low Speeds

### ISSUE THREAD

**Issue by Mark-sudo** [cyberbotics/webots#833]
**Description**
At low speeds (about 0.1 kph) the Boomer tractor wheels sink into the ground until the bottom of the kingpin hits the ground.  This has only been seen in non-flat terrains.

**Steps to Reproduce**
1. Use any sample non-flat terrain provided by Webots
2. Place the Boomer vehicle (Webots sample tractor) in this world, with the Boomer controller (also provided by Webots)
3. Driver the tractor at slow speeds (around 0.1 km/h)
4. As the tractor reaches the interface between 2 terrain tiles, the wheels will start to sink into the ground.

**Expected behavior**
Vehicle wheels should not sink into the ground, regardless of the terrain geometry.

**System**
 - Windows 10
 - Graphics Card: NVIDIA GeForce RTX 2070, Intel HD Graphics 620

**Screenshots or Videos**
Attached you will find a couple of short videos and pictures depicting the problem.

https://agjunction-my.sharepoint.com/:v:/p/mvillela/Ead4Z4TufSBDimFK2IWp-1QBQBMu6c6aIAGeGk50m0D2Ow?e=NEHP9K

https://agjunction-my.sharepoint.com/:v:/p/mvillela/ERrNVOxUCYZCoefixsjkuNsB-xHTrgI6GIytDkwspUlrhw?e=oDvXMO

![Tire_Sinks](https://user-images.githubusercontent.com/54549741/63721482-366d4300-c806-11e9-95eb-632d3c34bf5a.png)
![Left_Front_Tire_Sinks](https://user-images.githubusercontent.com/54549741/63721486-38cf9d00-c806-11e9-84d1-c5384abe6e0c.png)

![Tire_Sinks_Kingpin_Hits_Ground](https://user-images.githubusercontent.com/54549741/63721239-b0e99300-c805-11e9-82d1-91115286fe41.png)

**Comment by fabienrohrer** [comment]
The collision quality depends a lot on the global physics properties, and on the contact properties between the wheels and the ground:

- Reducing the `WorldInfo.basicTimeStep` will improve directly the contacts quality. I would say that 8ms is a good value for such kind of simulation.
- Adding a `ContactProperty` node in `WorldInfo.contactProperties`, and define a `ContactProperty.softCFM` between the wheel and the ground will reduce the shrink effect.

Please look at the boomer.wbt world physhics properties here:
https://github.com/omichel/webots/blob/master/projects/vehicles/worlds/boomer.wbt#L2-L15

**Comment by fabienrohrer** [comment]
I confirm the presence of this bug. It's due to ODE.

It seems to be dependent on tile size of the elevation grid. If the tiles are big enough to avoid the vehicle to be several tiles at a time, it seems to work much better. Could it be a workaround for you?

**Comment by Mark-sudo** [comment]
Thank you.  I'll check into our options.
Do the Webots and ODE development teams have a formal coordination agreement to address issues like this, or do I need to contact the ODE group directly?

**Comment by fabienrohrer** [comment]
We already fixed several times issues in ODE.

**Comment by fabienrohrer** [comment]
"Fixed" by added a FAQ entree: https://cyberbotics.com/doc/guide/modeling#my-robot-sinks-into-the-ground-how-to-remove-this-effect
