### ISSUE TITLE
SFString Field Starting with '*' Trigger Qt Warning

### ISSUE THREAD

**Issue by DavidMansolino** [cyberbotics/webots#841]
**Describe the Bug**
If a field start with a `*` the following warning is displayed in the MSYS console:
```
Warning: QRegularExpressionPrivate::doMatch(): called on an invalid QRegularExpression object
```

**Steps to Reproduce**
1. Open the ``khepera3_gripper.wbt`` world.
2. Select a box and add `*` at the beginning of the name field.
3. Save and quit Webots.
4. Re-open Webots => The warnign is displayed in the console

**Expected behavior**
Not sure if we want to deny the use of ``*`` at start, but probably it would be better to remove this warning.

**System**
 - Operating System: Windows 10

**Comment by omichel** [comment]
The problem is likely here: https://github.com/omichel/webots/blob/revision/src/webots/nodes/WbSolid.cpp#L517
