### ISSUE TITLE
make failed at the tag 'R2019b'

### ISSUE THREAD

**Issue by uniqueluo** [cyberbotics/webots#858]
**Description**
I'm getting the following linking error when building webots 'R2019b' on Ubuntu 16.04 

```
#
# * dependencies *
#
#
# * ode *
#
#
# * glad *
#
#
# * wren *
#
# compiling Renderable.cpp
Renderable.cpp: In member function ‘void wren::Renderable::recomputeBoundingSphereInViewSpace(const mat4&)’:
Renderable.cpp:96:42: error: no match for ‘operator=’ (operand types are ‘glm::vec3 {aka glm::tvec3<float, (glm::precision)0u>}’ and ‘glm::tmat4x4<float, (glm::precision)0u>::col_type {aka glm::tvec4<float, (glm::precision)0u>}’)
       mBoundingSphereInViewSpace.mCenter = viewMatrix * glm::vec4(mBoundingSphere.mCenter, 1.0f);
```

**Steps to Reproduce**
1. git colne https://github.com/cyberbotics/webots.git
2. cd webots
3. git checkout R2019b
4. make
5. sudo apt-get install libglm-dev 
6. make

**Expected behavior**
make sucessful

**System**
 - Operating System: Linux Ubuntu 16.04
 - Graphics Card: [ NVIDIA GeForce GTX 106 6 GB.]

**Comment by DavidMansolino** [comment]
It seems the ``glm`` submodule is not initialized.
Can you please run the following commands in your 'webots' directory:
```
git submodule init
git submodule update
```

and then re-run the make.

**Comment by uniqueluo** [comment]
Fellow your instruction, everything works fine,  thank you!

**Comment by DavidMansolino** [comment]
You're welcome
