### ISSUE TITLE
The buttons of the web interface look bad

### ISSUE THREAD

**Issue by omichel** [cyberbotics/webots#928]
The height of the fast button is not the same as the other run and step buttons.
The shape of the run button is different from the shape of the other buttons, etc.
![image](https://user-images.githubusercontent.com/1264964/65939827-3aa10780-e427-11e9-865f-70f18da0aef7.png)
We should reuse the icons of Webots which are better designed. That would provide also more consistency.
![image](https://user-images.githubusercontent.com/1264964/65940089-e5192a80-e427-11e9-9cf2-390b205f9f8e.png)

**Comment by stefaniapedrazzi** [comment]
When the fast button has been added it seems that has been copied directly from the Webots icons without taking into account the style used in the web interface.

**Comment by stefaniapedrazzi** [comment]
I also don't like very much the appearance of the new world selection drop-down list and I think it should be improved.
