### ISSUE TITLE
Pi HTML code not correctly interpreted in Propeller documentation page

### ISSUE THREAD

**Issue by stefaniapedrazzi** [cyberbotics/webots#930]
In the description of the new `fastHelixThreshold` field the pi HTML code is displayed as `&pi;` instead of π:

https://www.cyberbotics.com/doc/reference/propeller?version=R2019b-rev1#field-summary

**Comment by fabienrohrer** [comment]
I think it's the contrary, we need to use `&pi;` instead of the HTML code:

https://github.com/cyberbotics/webots/blob/revision/docs/tests/test_md_files.py#L51

Here it's not working, because it is defined in a code statement.

Is this correct?

**Comment by stefaniapedrazzi** [comment]
Yes, we don't have to use the symbol but in the documentation we want that the symbol appears and not the HTML code.
