### ISSUE TITLE
Cannot open a "Support ticket" on my MacBook Air

### ISSUE THREAD

**Issue by fabienrohrer** [cyberbotics/webots#943]
On my MacBook Air only, the "Help / Support Ticket (Premier Service)" item fails with this error dialog:

![Capture d’écran 2019-10-01 à 16 10 21](https://user-images.githubusercontent.com/866788/65970314-950d8880-e466-11e9-9fff-99560903550c.png)

.. while the other URLs seem to work well.

**Comment by fabienrohrer** [comment]
The URL is:

`https://cyberbotics.com/support_ticket.php?&os=Darwin 18.7.0 x86_64&graphics=Intel Inc. - Intel HD Graphics 4000 OpenGL Engine - 4.1 INTEL-12.10.12&version=R2019b revision 1&type=ticket`

.. and works when typed directly in a browser.

**Comment by omichel** [comment]
Maybe we should URLencode the string (e.g., the spaces should be `%20` instead of ` `).

**Comment by omichel** [comment]
I tested on Windows and it works.

**Comment by omichel** [comment]
Maybe you should try to remove the `StrictMode` from here: https://github.com/cyberbotics/webots/blob/revision/src/webots/core/WbDesktopServices.cpp#L31

**Comment by fabienrohrer** [comment]
Good point, it seems to solve my issue.
(I can reproduce the issue in my development environment by copying the string above.)

It seems that this URL contains something which is not liked by the strict mode.

**Comment by omichel** [comment]
Yes, but the problem is specific to macOS...

**Comment by fabienrohrer** [comment]
Ok, the issue appears when the strict mode is used and the url contains spaces instead of `%20`.

**Comment by fabienrohrer** [comment]
As this mechanism is used in different contexts, for example to open links from the documentation or from the robot window, I expect that some tolerance should be acceptable (for example is users change this). I think that removing the "strict" mode everywhere will be more robust.
