### ISSUE TITLE
Better dependency management

### ISSUE THREAD

**Issue by fabienrohrer** [cyberbotics/webots#965]
Modifying the dependencies on the FTP in a single directory is for sure a bad practice.
The side effects may be big, it bypasses the review process, and it has no versioning control. Updating the package can break the previous Webots versions.

Simply adding a supplementary directory specifying the Webots version would already help. Probably even better solutions may be found.

**Comment by omichel** [comment]
Another solution would be to add some MD5 check in the download scripts.

**Comment by DavidMansolino** [comment]
That would be indeed a good start.

**Comment by DavidMansolino** [comment]
I just realized that because of our bad management of the dependencies the master branch was broken for a while (it is now fixed because of the merge revision into master).
We should really improve this urgently, we may also investigate systems such as git-lfs to replace the ftp.
