### ISSUE TITLE
Update instructions to install on a Ubuntu server distribution

### ISSUE THREAD

**Issue by stefaniapedrazzi** [cyberbotics/webots#969]
It seems that Webots can run without any UI (see docker instructions https://github.com/cyberbotics/webots/wiki/Continuous-Integration#run-a-travis-like-environment) but this is not what is described in the Webots documentation:
https://www.cyberbotics.com/doc/guide/installation-procedure#server-edition

We should check and update the documentation.

**Comment by DavidMansolino** [comment]
At least `libxkbcommon-x11-dev` should be added to the list (see  #1774)

**Comment by DavidMansolino** [comment]
Replaced by #2008
