### ISSUE TITLE
Mandatory npm Dependency

### ISSUE THREAD

**Issue by DavidMansolino** [cyberbotics/webots#986]
**Describe the Bug**
The npm dependency is documented as optional: https://github.com/cyberbotics/webots/wiki/Linux-Optional-Dependencies#nodejs

However, the main compilation process fails if npm is not installed. It should just be skipped if npm is missing, as it is already the case for java and python for example.

**Comment by stefaniapedrazzi** [comment]
I just checked on Ubuntu 18.04 and it works correctly for me on revision even when building from the main `webots` folder: if `npm` is not found, the build of `webots.min.js` is skipped.

**Comment by DavidMansolino** [comment]
I just retried both on a clean VM and in a Docker (where I originally found the issue), but I can't reproduce this anymore, probably a wrong setup on my first trial.
