### ISSUE TITLE
Inconsistent Java version

### ISSUE THREAD

**Issue by DavidMansolino** [cyberbotics/webots#988]
The java version has been changed in the linux installation instructions: https://github.com/cyberbotics/webots/wiki/Linux-Optional-Dependencies/_compare/a787c2d67b0c01558001110859e086d9d7f650ca...b4cdb914519eb157e74eb2a0403ab0b0ad52a57f

But this has not been reflected in Travis, this is bad as it means that we are not using the same development environment locally than the one used for testing and releasing.

**Comment by DavidMansolino** [comment]
We also document that Java 1.8 should be used: https://www.cyberbotics.com/doc/guide/using-java#java-and-java-compiler-installation

**Comment by omichel** [comment]
Fixed in #990.
